# Importing libraries

In [3]:
# Basic libraries
import pandas as pd
import numpy as np
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.multioutput import MultiOutputClassifier

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, hamming_loss
from memory_profiler import memory_usage


# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [4]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [5]:
ds = load_dataset("higopires/RePro-categories-multilabel")

train = ds['train'].to_pandas()
val = ds['validation'].to_pandas()
test = ds['test'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8002 entries, 0 to 8001
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   review_text             8002 non-null   object
 1   ENTREGA                 8002 non-null   int64
 2   OUTROS                  8002 non-null   int64
 3   PRODUTO                 8002 non-null   int64
 4   CONDICOESDERECEBIMENTO  8002 non-null   int64
 5   INADEQUADA              8002 non-null   int64
 6   ANUNCIO                 8002 non-null   int64
dtypes: int64(6), object(1)
memory usage: 437.7+ KB

# Dataset preprocessing

In [6]:
train = train[train['INADEQUADA'] == 0].reset_index(drop=True)
val = val[val['INADEQUADA'] == 0].reset_index(drop=True)
test = test[test['INADEQUADA'] == 0].reset_index(drop=True)

train = train.drop(columns=['INADEQUADA'])
val = val.drop(columns=['INADEQUADA'])
test = test.drop(columns=['INADEQUADA'])

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 966 entries, 0 to 965
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   review_text             966 non-null    object
 1   ENTREGA                 966 non-null    int64
 2   OUTROS                  966 non-null    int64
 3   PRODUTO                 966 non-null    int64
 4   CONDICOESDERECEBIMENTO  966 non-null    int64
 5   ANUNCIO                 966 non-null    int64
dtypes: int64(5), object(1)
memory usage: 45.4+ KB

In [8]:
train.rename(columns={'review_text': 'text'}, inplace=True)
val.rename(columns={'review_text': 'text'}, inplace=True)
test.rename(columns={'review_text': 'text'}, inplace=True)

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7674 entries, 0 to 7673
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   text                    7674 non-null   object
 1   ENTREGA                 7674 non-null   int64
 2   OUTROS                  7674 non-null   int64
 3   PRODUTO                 7674 non-null   int64
 4   CONDICOESDERECEBIMENTO  7674 non-null   int64
 5   ANUNCIO                 7674 non-null   int64
dtypes: int64(5), object(1)
memory usage: 359.8+ KB

In [9]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [10]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': MultiOutputClassifier(SVC()),
        'params': {
            'estimator__C': [0.1, 1, 10],
            'estimator__kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultiOutputClassifier(MultinomialNB()),
        'params': {
            'estimator__alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': MultiOutputClassifier(LogisticRegression(max_iter=1000)),
        'params': {
            'estimator__C': [0.1, 1, 10],
            'estimator__penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': MultiOutputClassifier(GradientBoostingClassifier()),
        'params': {
            'estimator__n_estimators': [100, 150, 200],
            'estimator__criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': MultiOutputClassifier(AdaBoostClassifier()),
        'params': {
            'estimator__n_estimators': [50, 100, 150],
            'estimator__learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': MultiOutputClassifier(SGDClassifier()),
        'params': {
            'estimator__alpha': [0.0001, 0.001, 0.01],
            'estimator__penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [11]:
train

,text,ENTREGA,OUTROS,PRODUTO,CONDICOESDERECEBIMENTO,ANUNCIO
0,aparelho muito bom confiável e com valor aquis...,0,0,1,0,0
1,história é muito boa porém autor enrolou um po...,0,0,1,0,0
2,entrega rápida produto muito bom amei praticidade,1,0,1,0,0
3,produto otimo falta carregador da maquina pequena,0,0,1,1,0
4,proteção anti queda não é boa se cair de frent...,0,0,1,0,0
...,...,...,...,...,...,...
7669,amei produto chegou prazo e em perfeito estado...,1,0,1,1,0
7670,ótima embalagem produto entregue prazo recomen...,1,0,1,1,0
7671,ótimo produto super recomendo entrega bem rápida,1,0,1,0,0
7672,veio tudo certinho dentro prazo e produto é mu...,1,0,1,1,0
7673,produto é bom comprei de várias marcas porém c...,0,0,1,0,0

In [12]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'hamming_loss', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = list(train.columns[1:])
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [13]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train[classes])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                val_classes = val.drop(columns=['text'])

                accuracy = accuracy_score(val_classes, y_pred)
                
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val_classes.to_numpy(), y_pred, average=None, zero_division=0)

                hamm_loss = hamming_loss(val_classes.to_numpy(), y_pred)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'hamming_loss': hamm_loss,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_multilabel1.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 5.514278099988587
Peak memory usage during training: 422.42578125 MB
Prediction time: 1.0579653999884613
Peak memory usage during prediction: 422.546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_16340\3004956853.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 6.051981600001454
Peak memory usage during training: 427.14453125 MB
Prediction time: 1.9433777999947779
Peak memory usage during prediction: 422.203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 6.008134900010191
Peak memory usage during training: 427.484375 MB
Prediction time: 1.4801886000204831
Peak memory usage during prediction: 422.41015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 10.084336799976882
Peak memory usage during training: 467.2578125 MB
Prediction time: 1.045807899965439
Peak memory usage during prediction: 467.25 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 11.39257369999541
Peak memory usage during training: 476.8203125 MB
Prediction time: 1.070524499984458
Peak memory usage during prediction: 476.80859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 11.396929699985776
Peak memory usage during training: 478.8515625 MB
Prediction time: 1.0401535000419244
Peak memory usage during prediction: 477.10546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 14.733435900008772
Peak memory usage during training: 513.9609375 MB
Prediction time: 1.1167172000277787
Peak memory usage during prediction: 507.3359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 16.994329900015146
Peak memory usage during training: 527.09375 MB
Prediction time: 1.0549194000195712
Peak memory usage during prediction: 527.37109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 16.88574639998842
Peak memory usage during training: 526.83984375 MB
Prediction time: 1.1172763999784365
Peak memory usage during prediction: 526.89453125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 13.844011800014414
Peak memory usage during training: 650.34375 MB
Prediction time: 1.8533677000086755
Peak memory usage during prediction: 544.18359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 18.217946199991275
Peak memory usage during training: 696.32421875 MB
Prediction time: 2.7660271000349894
Peak memory usage during prediction: 547.55078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 13.77476260002004
Peak memory usage during training: 653.1875 MB
Prediction time: 1.8303258999949321
Peak memory usage during prediction: 545.734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 11.511392399959732
Peak memory usage during training: 645.09375 MB
Prediction time: 1.5776124999974854
Peak memory usage during prediction: 543.796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 18.6717877999763
Peak memory usage during training: 716.92578125 MB
Prediction time: 2.7870582999894395
Peak memory usage during prediction: 548.71875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 10.943368199979886
Peak memory usage during training: 633.49609375 MB
Prediction time: 1.473536100005731
Peak memory usage during prediction: 544.6328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 11.309831999999005
Peak memory usage during training: 636.515625 MB
Prediction time: 1.4938868000172079
Peak memory usage during prediction: 544.45703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 25.279210400010925
Peak memory usage during training: 739.890625 MB
Prediction time: 2.9093877999694087
Peak memory usage during prediction: 552.4140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 11.493236199952662
Peak memory usage during training: 610.9921875 MB
Prediction time: 1.185686600045301
Peak memory usage during prediction: 545.0390625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.1522142000030726
Peak memory usage during training: 539.80859375 MB
Prediction time: 1.8437183999922127
Peak memory usage during prediction: 530.796875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.1311549000092782
Peak memory usage during training: 538.734375 MB
Prediction time: 1.8365048000123352
Peak memory usage during prediction: 530.61328125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.1261001999955624
Peak memory usage during training: 539.07421875 MB
Prediction time: 1.840559700038284
Peak memory usage during prediction: 530.69921875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7263966000173241
Peak memory usage during training: 541.44921875 MB
Prediction time: 1.8316635999944992
Peak memory usage during prediction: 531.21875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.8420729999779724
Peak memory usage during training: 541.3359375 MB
Prediction time: 1.827192600001581
Peak memory usage during prediction: 531.29296875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9137031999998726
Peak memory usage during training: 540.671875 MB
Prediction time: 1.8340977000189014
Peak memory usage during prediction: 531.53125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.139551800035406
Peak memory usage during training: 539.6015625 MB
Prediction time: 1.294336299994029
Peak memory usage during prediction: 645.25 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1243161000311375
Peak memory usage during training: 539.82421875 MB
Prediction time: 1.28928620001534
Peak memory usage during prediction: 629.2734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1375868000322953
Peak memory usage during training: 540.26171875 MB
Prediction time: 1.2787923999712802
Peak memory usage during prediction: 625.4765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1398728999774903
Peak memory usage during training: 540.015625 MB
Prediction time: 1.2862152999732643
Peak memory usage during prediction: 637.92578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.11984170001233
Peak memory usage during training: 540.265625 MB
Prediction time: 1.2855138000450097
Peak memory usage during prediction: 646.12109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.118086399976164
Peak memory usage during training: 539.74609375 MB
Prediction time: 1.2819060999900103
Peak memory usage during prediction: 637.5625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1228770000161603
Peak memory usage during training: 540.42578125 MB
Prediction time: 1.3060423000133596
Peak memory usage during prediction: 641.67578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1289897999959067
Peak memory usage during training: 540.41015625 MB
Prediction time: 1.2819192999741063
Peak memory usage during prediction: 645.87890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1303094999748282
Peak memory usage during training: 540.41015625 MB
Prediction time: 1.286951099988073
Peak memory usage during prediction: 644.91015625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7082739999750629
Peak memory usage during training: 543.27734375 MB
Prediction time: 1.8286175999674015
Peak memory usage during prediction: 534.7734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7023569999728352
Peak memory usage during training: 542.4765625 MB
Prediction time: 1.8283348000259139
Peak memory usage during prediction: 535.15234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 4.022331899963319
Peak memory usage during training: 542.234375 MB
Prediction time: 1.844074000022374
Peak memory usage during prediction: 533.87890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.723860300029628
Peak memory usage during training: 543.484375 MB
Prediction time: 1.8394550000084564
Peak memory usage during prediction: 534.90625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7197938999743201
Peak memory usage during training: 542.71484375 MB
Prediction time: 1.8263824000023305
Peak memory usage during prediction: 535.1875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.8024833000381477
Peak memory usage during training: 542.34765625 MB
Prediction time: 1.856192600040231
Peak memory usage during prediction: 534.0234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7165618000435643
Peak memory usage during training: 543.015625 MB
Prediction time: 1.8406169000081718
Peak memory usage during prediction: 534.9140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7065146999666467
Peak memory usage during training: 543.06640625 MB
Prediction time: 1.825851599976886
Peak memory usage during prediction: 535.1953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.7925394999911077
Peak memory usage during training: 542.09765625 MB
Prediction time: 1.8222860000096262
Peak memory usage during prediction: 533.9453125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 20.981413700035773
Peak memory usage during training: 541.7421875 MB
Prediction time: 1.42114309995668
Peak memory usage during prediction: 535.57421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 20.6389781999751
Peak memory usage during training: 543.0546875 MB
Prediction time: 1.865010900015477
Peak memory usage during prediction: 536.62890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 30.599498499999754
Peak memory usage during training: 543.25 MB
Prediction time: 1.8647290999651887
Peak memory usage during prediction: 536.16796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 30.375312299991492
Peak memory usage during training: 544.203125 MB
Prediction time: 1.8877217000117525
Peak memory usage during prediction: 537.03125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 40.27292260003742
Peak memory usage during training: 543.74609375 MB
Prediction time: 1.859604199999012
Peak memory usage during prediction: 537.12890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 40.026249399990775
Peak memory usage during training: 544.63671875 MB
Prediction time: 1.8716185000375845
Peak memory usage during prediction: 537.3984375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.339250599965453
Peak memory usage during training: 544.171875 MB
Prediction time: 1.0458986000157893
Peak memory usage during prediction: 536.953125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.337901700055227
Peak memory usage during training: 544.35546875 MB
Prediction time: 1.0356413000263274
Peak memory usage during prediction: 537.25390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.326271300029475
Peak memory usage during training: 543.95703125 MB
Prediction time: 1.036097600008361
Peak memory usage during prediction: 537.37890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.073849399981555
Peak memory usage during training: 544.42578125 MB
Prediction time: 1.1379649000009522
Peak memory usage during prediction: 537.77734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.085547399998177
Peak memory usage during training: 544.09375 MB
Prediction time: 1.1307304000365548
Peak memory usage during prediction: 537.8125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.054507799970452
Peak memory usage during training: 544.609375 MB
Prediction time: 1.1281653000041842
Peak memory usage during prediction: 537.74609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 14.884905699989758
Peak memory usage during training: 544.5859375 MB
Prediction time: 1.222281700000167
Peak memory usage during prediction: 543.0703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 14.803814199985936
Peak memory usage during training: 544.796875 MB
Prediction time: 1.226121100015007
Peak memory usage during prediction: 543.1875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 14.802267500024755
Peak memory usage during training: 545.12109375 MB
Prediction time: 1.2273569999961182
Peak memory usage during prediction: 543.43359375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.2049391000182368
Peak memory usage during training: 544.0703125 MB
Prediction time: 1.817303100018762
Peak memory usage during prediction: 538.96484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2633494000183418
Peak memory usage during training: 545.41796875 MB
Prediction time: 1.8398378000129014
Peak memory usage during prediction: 539.23828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7036157000111416
Peak memory usage during training: 545.37890625 MB
Prediction time: 1.833291899994947
Peak memory usage during prediction: 539.1015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1818994000204839
Peak memory usage during training: 544.984375 MB
Prediction time: 1.8305592999677174
Peak memory usage during prediction: 538.98828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1855653999955393
Peak memory usage during training: 544.75390625 MB
Prediction time: 1.825509599992074
Peak memory usage during prediction: 538.953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.2371907000197098
Peak memory usage during training: 545.58984375 MB
Prediction time: 1.8235602999920957
Peak memory usage during prediction: 539.28515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1577088999911211
Peak memory usage during training: 545.796875 MB
Prediction time: 1.8410608999547549
Peak memory usage during prediction: 539.03515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1876893000444397
Peak memory usage during training: 545.48046875 MB
Prediction time: 1.8222186000202782
Peak memory usage during prediction: 538.73046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1978214000118896
Peak memory usage during training: 544.98828125 MB
Prediction time: 1.8307192000211217
Peak memory usage during prediction: 538.73046875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 5.594761400017887
Peak memory usage during training: 544.5234375 MB
Prediction time: 1.4801466999924742
Peak memory usage during prediction: 439.6484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 6.303144700010307
Peak memory usage during training: 448.9375 MB
Prediction time: 1.5303674000315368
Peak memory usage during prediction: 444.1015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 6.3994153999956325
Peak memory usage during training: 450.7734375 MB
Prediction time: 1.4711079999688081
Peak memory usage during prediction: 444.1484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 10.889833400025964
Peak memory usage during training: 495.88671875 MB
Prediction time: 1.0815148999681696
Peak memory usage during prediction: 490.34765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 12.491319699969608
Peak memory usage during training: 503.43359375 MB
Prediction time: 1.204002299986314
Peak memory usage during prediction: 498.21875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 12.222670499992091
Peak memory usage during training: 505.203125 MB
Prediction time: 1.067759900004603
Peak memory usage during prediction: 503.9765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 16.487351800024044
Peak memory usage during training: 546.0234375 MB
Prediction time: 1.216930599999614
Peak memory usage during prediction: 546.03515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 18.264688199968077
Peak memory usage during training: 557.9453125 MB
Prediction time: 1.114967500034254
Peak memory usage during prediction: 552.75 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 18.145860499993432
Peak memory usage during training: 559.4765625 MB
Prediction time: 1.1855743000051007
Peak memory usage during prediction: 552.72265625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.301485200005118
Peak memory usage during training: 655.21875 MB
Prediction time: 1.4261279999627732
Peak memory usage during prediction: 570.43359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 17.683820899983402
Peak memory usage during training: 704.28125 MB
Prediction time: 2.683435200015083
Peak memory usage during prediction: 575.40625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 12.581413100007921
Peak memory usage during training: 668.25 MB
Prediction time: 1.6624623999814503
Peak memory usage during prediction: 572.625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.648569200013299
Peak memory usage during training: 655.33203125 MB
Prediction time: 1.2859078000183217
Peak memory usage during prediction: 569.55078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 16.721666699973866
Peak memory usage during training: 714.2734375 MB
Prediction time: 2.5535566000035033
Peak memory usage during prediction: 574.2578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 8.507063500001095
Peak memory usage during training: 629.4296875 MB
Prediction time: 1.270548600004986
Peak memory usage during prediction: 569.734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.512296900036745
Peak memory usage during training: 645.6328125 MB
Prediction time: 1.2078747000196017
Peak memory usage during prediction: 570.77734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 20.131366699992213
Peak memory usage during training: 749.984375 MB
Prediction time: 2.621021600032691
Peak memory usage during prediction: 575.73046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 7.42628600000171
Peak memory usage during training: 620.640625 MB
Prediction time: 1.1516772999893874
Peak memory usage during prediction: 569.234375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.1431930999970064
Peak memory usage during training: 562.0078125 MB
Prediction time: 1.8224776000133716
Peak memory usage during prediction: 552.890625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.1322362999781035
Peak memory usage during training: 561.765625 MB
Prediction time: 1.8364299000240862
Peak memory usage during prediction: 552.6796875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.1354588000103831
Peak memory usage during training: 561.33203125 MB
Prediction time: 1.8305407000007108
Peak memory usage during prediction: 552.67578125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8342664999654517
Peak memory usage during training: 562.87109375 MB
Prediction time: 1.8393634000094607
Peak memory usage during prediction: 552.9140625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0376393000478856
Peak memory usage during training: 562.5546875 MB
Prediction time: 1.866240499948617
Peak memory usage during prediction: 552.44140625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1359291999833658
Peak memory usage during training: 562.60546875 MB
Prediction time: 1.8773702000034973
Peak memory usage during prediction: 552.94140625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1365861000376754
Peak memory usage during training: 560.9609375 MB
Prediction time: 0.7524924000026658
Peak memory usage during prediction: 617.25390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1362183000310324
Peak memory usage during training: 561.296875 MB
Prediction time: 0.7492900000070222
Peak memory usage during prediction: 634.6328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1242086999700405
Peak memory usage during training: 561.51953125 MB
Prediction time: 0.7446632000501268
Peak memory usage during prediction: 626.1796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1305986000224948
Peak memory usage during training: 561.30078125 MB
Prediction time: 0.7420285000116564
Peak memory usage during prediction: 655.98046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.128563700011
Peak memory usage during training: 561.63671875 MB
Prediction time: 0.7487688999972306
Peak memory usage during prediction: 660.7734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1272348000202328
Peak memory usage during training: 561.48046875 MB
Prediction time: 0.758889899996575
Peak memory usage during prediction: 658.2890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1335430000326596
Peak memory usage during training: 561.6484375 MB
Prediction time: 0.7470975000178441
Peak memory usage during prediction: 612.9140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1241355999954976
Peak memory usage during training: 561.22265625 MB
Prediction time: 0.7508113000076264
Peak memory usage during prediction: 620.76171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.121728899946902
Peak memory usage during training: 561.63671875 MB
Prediction time: 0.7433287999592721
Peak memory usage during prediction: 643.0078125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7240928999963216
Peak memory usage during training: 562.41796875 MB
Prediction time: 1.8424799999920651
Peak memory usage during prediction: 553.82421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7487777000060305
Peak memory usage during training: 563.65234375 MB
Prediction time: 1.8230823000194505
Peak memory usage during prediction: 554.09375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.1643399000167847
Peak memory usage during training: 562.84765625 MB
Prediction time: 1.8322292999946512
Peak memory usage during prediction: 552.88671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7407959999982268
Peak memory usage during training: 562.640625 MB
Prediction time: 1.8465962000191212
Peak memory usage during prediction: 553.9609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7582364000263624
Peak memory usage during training: 563.625 MB
Prediction time: 1.840655500011053
Peak memory usage during prediction: 554.0703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.8001027000136673
Peak memory usage during training: 563.07421875 MB
Prediction time: 1.8410184000385925
Peak memory usage during prediction: 552.83984375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.740120200032834
Peak memory usage during training: 562.296875 MB
Prediction time: 1.8301088000298478
Peak memory usage during prediction: 553.87890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.747710499970708
Peak memory usage during training: 563.58203125 MB
Prediction time: 1.8271276999730617
Peak memory usage during prediction: 554.02734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.805907899979502
Peak memory usage during training: 563.34765625 MB
Prediction time: 1.8469709999626502
Peak memory usage during prediction: 552.83203125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 10.386679999995977
Peak memory usage during training: 562.0390625 MB
Prediction time: 1.882909899984952
Peak memory usage during prediction: 553.328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 10.328677700017579
Peak memory usage during training: 561.77734375 MB
Prediction time: 2.1553682000376284
Peak memory usage during prediction: 552.9296875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 15.200093899969943
Peak memory usage during training: 561.515625 MB
Prediction time: 1.4545601000427268
Peak memory usage during prediction: 553.33984375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 14.89368189999368
Peak memory usage during training: 562.078125 MB
Prediction time: 1.8714499999769032
Peak memory usage during prediction: 553.61328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 19.243295799999032
Peak memory usage during training: 562.421875 MB
Prediction time: 0.9865194999729283
Peak memory usage during prediction: 558.34765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.993713700037915
Peak memory usage during training: 562.5078125 MB
Prediction time: 1.8708018000470474
Peak memory usage during prediction: 553.48046875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.159784400020726
Peak memory usage during training: 562.04296875 MB
Prediction time: 1.0296533000073396
Peak memory usage during prediction: 553.41796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.1442269000108354
Peak memory usage during training: 562.046875 MB
Prediction time: 1.0374410999938846
Peak memory usage during prediction: 552.921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.143397099978756
Peak memory usage during training: 561.6640625 MB
Prediction time: 1.0451087999972515
Peak memory usage during prediction: 552.796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.720082700019702
Peak memory usage during training: 561.13671875 MB
Prediction time: 1.1388985000085086
Peak memory usage during prediction: 557.20703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.724930399970617
Peak memory usage during training: 561.09375 MB
Prediction time: 1.14492320001591
Peak memory usage during prediction: 557.7265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.73260400001891
Peak memory usage during training: 561.14453125 MB
Prediction time: 1.1378104000468738
Peak memory usage during prediction: 557.7734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.306985699979123
Peak memory usage during training: 561.609375 MB
Prediction time: 1.2371503999456763
Peak memory usage during prediction: 553.4609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.301471999962814
Peak memory usage during training: 561.4375 MB
Prediction time: 1.2553973000030965
Peak memory usage during prediction: 553.60546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.656900400004815
Peak memory usage during training: 561.8515625 MB
Prediction time: 1.2303660999750718
Peak memory usage during prediction: 558.2265625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.294205599988345
Peak memory usage during training: 561.91015625 MB
Prediction time: 1.8574528999743052
Peak memory usage during prediction: 553.125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0862666000030003
Peak memory usage during training: 561.90625 MB
Prediction time: 1.8404326000018045
Peak memory usage during prediction: 553.01953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.8222081999992952
Peak memory usage during training: 561.66015625 MB
Prediction time: 1.838343999988865
Peak memory usage during prediction: 553.15625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2511795000173151
Peak memory usage during training: 561.89453125 MB
Prediction time: 1.829323399986606
Peak memory usage during prediction: 553.125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.7182995000039227
Peak memory usage during training: 561.88671875 MB
Prediction time: 1.8515220999834128
Peak memory usage during prediction: 553.125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7461315999971703
Peak memory usage during training: 561.88671875 MB
Prediction time: 1.9075573000009172
Peak memory usage during prediction: 553.25 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2993179999757558
Peak memory usage during training: 561.98828125 MB
Prediction time: 1.8630290000000969
Peak memory usage during prediction: 553.0859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2783484000246972
Peak memory usage during training: 562.01953125 MB
Prediction time: 1.846257400000468
Peak memory usage during prediction: 553.46484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.6819715999881737
Peak memory usage during training: 562.0625 MB
Prediction time: 1.8529682999942452
Peak memory usage during prediction: 553.28125 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 5.270025900041219
Peak memory usage during training: 553.28125 MB
Prediction time: 1.4458755999803543
Peak memory usage during prediction: 434.2421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 5.986295499955304
Peak memory usage during training: 444.46875 MB
Prediction time: 0.9878941000206396
Peak memory usage during prediction: 444.4765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 6.0084736999706365
Peak memory usage during training: 444.375 MB
Prediction time: 1.4564956999965943
Peak memory usage during prediction: 439.359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 10.013305399974342
Peak memory usage during training: 484.59765625 MB
Prediction time: 1.0291388999903575
Peak memory usage during prediction: 484.046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 11.469265300023835
Peak memory usage during training: 494.4765625 MB
Prediction time: 1.0121364999795333
Peak memory usage during prediction: 494.48046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 11.482820400036871
Peak memory usage during training: 496.53515625 MB
Prediction time: 1.0130538999801502
Peak memory usage during prediction: 494.4921875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 14.680986099992879
Peak memory usage during training: 529.17578125 MB
Prediction time: 1.0634150999831036
Peak memory usage during prediction: 529.28125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 16.887814399960916
Peak memory usage during training: 543.734375 MB
Prediction time: 1.0460879999445751
Peak memory usage during prediction: 544.09765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 16.7074852999649
Peak memory usage during training: 543.17578125 MB
Prediction time: 1.0450474999961443
Peak memory usage during prediction: 543.34765625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 13.87646300002234
Peak memory usage during training: 662.7421875 MB
Prediction time: 1.859932999999728
Peak memory usage during prediction: 557.65625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 18.598781200009398
Peak memory usage during training: 709.54296875 MB
Prediction time: 2.8110449999803677
Peak memory usage during prediction: 560.4375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.073593099950813
Peak memory usage during training: 663.23828125 MB
Prediction time: 1.8603803000296466
Peak memory usage during prediction: 557.3046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 11.748438799986616
Peak memory usage during training: 656.6484375 MB
Prediction time: 1.6216340999817476
Peak memory usage during prediction: 556.5234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 19.118763500009663
Peak memory usage during training: 729.15625 MB
Prediction time: 2.8134109000093304
Peak memory usage during prediction: 560.24609375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 11.151824300002772
Peak memory usage during training: 644.5625 MB
Prediction time: 1.5025147999986075
Peak memory usage during prediction: 556.29296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 11.525410900008865
Peak memory usage during training: 646.54296875 MB
Prediction time: 1.499653600039892
Peak memory usage during prediction: 556.234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 25.847833000007086
Peak memory usage during training: 750.77734375 MB
Prediction time: 2.968838299973868
Peak memory usage during prediction: 563.453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 11.740924099984113
Peak memory usage during training: 620.44140625 MB
Prediction time: 1.1874538999982178
Peak memory usage during prediction: 555.73046875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.1375739999930374
Peak memory usage during training: 549.7109375 MB
Prediction time: 1.8482666999916546
Peak memory usage during prediction: 539.44921875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.1391213999595493
Peak memory usage during training: 549.265625 MB
Prediction time: 1.8463110000011511
Peak memory usage during prediction: 539.14453125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.14179999998305
Peak memory usage during training: 547.921875 MB
Prediction time: 1.840544700040482
Peak memory usage during prediction: 539.12890625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7692905999720097
Peak memory usage during training: 550.87890625 MB
Prediction time: 1.840430499985814
Peak memory usage during prediction: 538.56640625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.8879669000161812
Peak memory usage during training: 550.1640625 MB
Prediction time: 1.8267665000166744
Peak memory usage during prediction: 538.85546875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9382318999851122
Peak memory usage during training: 550.39453125 MB
Prediction time: 1.8431543000042439
Peak memory usage during prediction: 538.62890625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1360669999849051
Peak memory usage during training: 547.79296875 MB
Prediction time: 1.2838619000394829
Peak memory usage during prediction: 636.5859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1215363999945112
Peak memory usage during training: 547.578125 MB
Prediction time: 1.2762189999921247
Peak memory usage during prediction: 650.609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1258777000475675
Peak memory usage during training: 547.21875 MB
Prediction time: 1.2877354000229388
Peak memory usage during prediction: 650.33203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.129806999990251
Peak memory usage during training: 547.23828125 MB
Prediction time: 1.2845063999993727
Peak memory usage during prediction: 643.19140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1344169999938458
Peak memory usage during training: 547.5546875 MB
Prediction time: 1.303499199973885
Peak memory usage during prediction: 647.29296875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1269758000271395
Peak memory usage during training: 547.91796875 MB
Prediction time: 1.2890630000038072
Peak memory usage during prediction: 640.04296875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1699478999944404
Peak memory usage during training: 547.9296875 MB
Prediction time: 1.2870535000110976
Peak memory usage during prediction: 651.703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.126905400014948
Peak memory usage during training: 547.44921875 MB
Prediction time: 1.2890215000370517
Peak memory usage during prediction: 649.1484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1324266999727115
Peak memory usage during training: 547.44140625 MB
Prediction time: 1.2837417999980971
Peak memory usage during prediction: 647.52734375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7084679999970831
Peak memory usage during training: 549.80078125 MB
Prediction time: 1.8461935999803245
Peak memory usage during prediction: 539.15625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7017123999539763
Peak memory usage during training: 549.5390625 MB
Prediction time: 1.8400084000313655
Peak memory usage during prediction: 539.5078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 4.122022399969865
Peak memory usage during training: 548.484375 MB
Prediction time: 1.8427478999947198
Peak memory usage during prediction: 538.30859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7319541999604553
Peak memory usage during training: 549.57421875 MB
Prediction time: 1.836311699997168
Peak memory usage during prediction: 539.31640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7150593000114895
Peak memory usage during training: 549.5546875 MB
Prediction time: 1.8275119999889284
Peak memory usage during prediction: 539.54296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.821380000037607
Peak memory usage during training: 548.50390625 MB
Prediction time: 1.8380485999514349
Peak memory usage during prediction: 538.5 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7356466000201181
Peak memory usage during training: 549.421875 MB
Prediction time: 1.8130015999777243
Peak memory usage during prediction: 539.38671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7473623999976553
Peak memory usage during training: 550.0546875 MB
Prediction time: 1.9086515000090003
Peak memory usage during prediction: 539.55078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.8526927000493743
Peak memory usage during training: 549.58203125 MB
Prediction time: 1.8528131999773905
Peak memory usage during prediction: 538.44140625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 21.26855910004815
Peak memory usage during training: 547.625 MB
Prediction time: 1.871298000041861
Peak memory usage during prediction: 539.09375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 21.16631200001575
Peak memory usage during training: 548.21875 MB
Prediction time: 1.8921342000248842
Peak memory usage during prediction: 524.78125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 31.39129860000685
Peak memory usage during training: 533.671875 MB
Prediction time: 1.866474799986463
Peak memory usage during prediction: 525.3515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 31.275949299975764
Peak memory usage during training: 534.28125 MB
Prediction time: 1.886258699989412
Peak memory usage during prediction: 525.5625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 41.41742220002925
Peak memory usage during training: 533.78125 MB
Prediction time: 1.8767033000476658
Peak memory usage during prediction: 525.75 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 41.205926799972076
Peak memory usage during training: 533.6015625 MB
Prediction time: 1.8849814999848604
Peak memory usage during prediction: 525.7578125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.481466099969111
Peak memory usage during training: 533.87109375 MB
Prediction time: 1.0844352000276558
Peak memory usage during prediction: 524.9375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.5860551000223495
Peak memory usage during training: 533.26953125 MB
Prediction time: 1.0420946999802254
Peak memory usage during prediction: 529.7578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.474984600034077
Peak memory usage during training: 533.5234375 MB
Prediction time: 1.048418699996546
Peak memory usage during prediction: 524.8203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.375594799988903
Peak memory usage during training: 533.62109375 MB
Prediction time: 1.1494441999820992
Peak memory usage during prediction: 524.88671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.368343300011475
Peak memory usage during training: 533.16796875 MB
Prediction time: 1.1353618999710307
Peak memory usage during prediction: 524.9375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.228319599991664
Peak memory usage during training: 533.42578125 MB
Prediction time: 1.1913069000001997
Peak memory usage during prediction: 524.9765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 15.154448199959006
Peak memory usage during training: 533.453125 MB
Prediction time: 1.2227383000426926
Peak memory usage during prediction: 525.265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 14.884233099990524
Peak memory usage during training: 533.5234375 MB
Prediction time: 1.2242025999585167
Peak memory usage during prediction: 530.34765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 14.805019700026605
Peak memory usage during training: 533.86328125 MB
Prediction time: 1.2119308999972418
Peak memory usage during prediction: 530.44140625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1902361999964342
Peak memory usage during training: 532.77734375 MB
Prediction time: 1.8267273000092246
Peak memory usage during prediction: 525.515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.271120699995663
Peak memory usage during training: 532.796875 MB
Prediction time: 1.8709704999928363
Peak memory usage during prediction: 486.265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.6987875000340864
Peak memory usage during training: 493.4375 MB
Prediction time: 1.819349700002931
Peak memory usage during prediction: 485.99609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1719253999763168
Peak memory usage during training: 492.91015625 MB
Prediction time: 1.8451736000133678
Peak memory usage during prediction: 486.015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1933525999775156
Peak memory usage during training: 493.03515625 MB
Prediction time: 1.8402206000173464
Peak memory usage during prediction: 485.9921875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.235220999980811
Peak memory usage during training: 493.0234375 MB
Prediction time: 1.828814100008458
Peak memory usage during prediction: 486.6015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1676347000175156
Peak memory usage during training: 492.99609375 MB
Prediction time: 1.8043599999509752
Peak memory usage during prediction: 486.3671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1932451000320725
Peak memory usage during training: 492.921875 MB
Prediction time: 1.8113256000215188
Peak memory usage during prediction: 486.05859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1719289000029676
Peak memory usage during training: 492.44140625 MB
Prediction time: 1.8487077000318095
Peak memory usage during prediction: 486.32421875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 5.580569599987939
Peak memory usage during training: 488.3828125 MB
Prediction time: 0.9785518999560736
Peak memory usage during prediction: 395.41015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 6.122834899986628
Peak memory usage during training: 403.94921875 MB
Prediction time: 1.446250700042583
Peak memory usage during prediction: 399.2734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 6.094894299982116
Peak memory usage during training: 404.05078125 MB
Prediction time: 1.436830899969209
Peak memory usage during prediction: 399.2890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 10.617347899999004
Peak memory usage during training: 450.3046875 MB
Prediction time: 1.0153298000223003
Peak memory usage during prediction: 450.32421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 11.57866619998822
Peak memory usage during training: 457.28515625 MB
Prediction time: 1.0114760000142269
Peak memory usage during prediction: 457.62109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 11.596772399963811
Peak memory usage during training: 458.21484375 MB
Prediction time: 1.004560399975162
Peak memory usage during prediction: 458.3125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 15.57438559998991
Peak memory usage during training: 500.9453125 MB
Prediction time: 1.0700051999883726
Peak memory usage during prediction: 495.47265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 17.005616899987217
Peak memory usage during training: 511.6796875 MB
Prediction time: 1.0395538000157103
Peak memory usage during prediction: 511.98046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 17.072992100031115
Peak memory usage during training: 511.1875 MB
Prediction time: 1.0424232999794185
Peak memory usage during prediction: 511.51171875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 9.772856299998239
Peak memory usage during training: 610.53515625 MB
Prediction time: 1.3411260999855585
Peak memory usage during prediction: 524.94921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 16.730928100005258
Peak memory usage during training: 658.6015625 MB
Prediction time: 2.5593593000085093
Peak memory usage during prediction: 529.60546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 12.282421199954115
Peak memory usage during training: 620.9296875 MB
Prediction time: 1.635425899992697
Peak memory usage during prediction: 527.203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.462390600005165
Peak memory usage during training: 609.1171875 MB
Prediction time: 1.2737296000123024
Peak memory usage during prediction: 524.484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 16.86468529998092
Peak memory usage during training: 671.0625 MB
Prediction time: 2.545073199959006
Peak memory usage during prediction: 528.19921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 8.46315190003952
Peak memory usage during training: 583.56640625 MB
Prediction time: 1.2590071000158787
Peak memory usage during prediction: 523.59765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.341304400004447
Peak memory usage during training: 599.26171875 MB
Prediction time: 1.1988461999571882
Peak memory usage during prediction: 524.109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 19.74086439999519
Peak memory usage during training: 703.2578125 MB
Prediction time: 2.5858906999928877
Peak memory usage during prediction: 528.66796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 7.320206500007771
Peak memory usage during training: 573.45703125 MB
Prediction time: 1.143546199949924
Peak memory usage during prediction: 523.20703125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.176659099990502
Peak memory usage during training: 515.91796875 MB
Prediction time: 1.8517986999941058
Peak memory usage during prediction: 506.91015625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.1478848000406288
Peak memory usage during training: 515.15234375 MB
Prediction time: 1.866718800039962
Peak memory usage during prediction: 506.73046875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.1557255000225268
Peak memory usage during training: 516.27734375 MB
Prediction time: 1.8657400000374764
Peak memory usage during prediction: 506.71484375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8882985000382178
Peak memory usage during training: 516.98046875 MB
Prediction time: 1.9620265000266954
Peak memory usage during prediction: 506.375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.054597299953457
Peak memory usage during training: 516.48046875 MB
Prediction time: 1.8745685999747366
Peak memory usage during prediction: 506.16015625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.116005200019572
Peak memory usage during training: 515.90234375 MB
Prediction time: 1.9512525999452919
Peak memory usage during prediction: 506.41015625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1523515000008047
Peak memory usage during training: 514.4765625 MB
Prediction time: 0.7449407000094652
Peak memory usage during prediction: 569.39453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.148514799948316
Peak memory usage during training: 513.91796875 MB
Prediction time: 0.7711466000182554
Peak memory usage during prediction: 576.70703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.2093574000173248
Peak memory usage during training: 514.015625 MB
Prediction time: 0.7752514000167139
Peak memory usage during prediction: 598.33203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.17789079999784
Peak memory usage during training: 514.0 MB
Prediction time: 0.7874051000108011
Peak memory usage during prediction: 572.6328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1412793000345118
Peak memory usage during training: 514.01953125 MB
Prediction time: 0.7638214000035077
Peak memory usage during prediction: 615.05859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1380545999854803
Peak memory usage during training: 513.9140625 MB
Prediction time: 0.7447425000136718
Peak memory usage during prediction: 626.15234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.159398499992676
Peak memory usage during training: 514.05859375 MB
Prediction time: 0.7549746999866329
Peak memory usage during prediction: 586.1875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1404520000214688
Peak memory usage during training: 513.96875 MB
Prediction time: 0.7612503000418656
Peak memory usage during prediction: 571.171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1313715999713168
Peak memory usage during training: 514.05859375 MB
Prediction time: 0.76925900002243
Peak memory usage during prediction: 615.78125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7504267999902368
Peak memory usage during training: 516.70703125 MB
Prediction time: 1.910640899965074
Peak memory usage during prediction: 507.44921875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7311469999840483
Peak memory usage during training: 516.9609375 MB
Prediction time: 1.8765869000344537
Peak memory usage during prediction: 410.94140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.1598253999836743
Peak memory usage during training: 420.11328125 MB
Prediction time: 1.8473434000043198
Peak memory usage during prediction: 409.71875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7335514000151306
Peak memory usage during training: 419.734375 MB
Prediction time: 1.8492143000476062
Peak memory usage during prediction: 410.71875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7305570999742486
Peak memory usage during training: 420.06640625 MB
Prediction time: 1.877180200011935
Peak memory usage during prediction: 410.90625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.8172728000208735
Peak memory usage during training: 420.1640625 MB
Prediction time: 1.9110203000018373
Peak memory usage during prediction: 409.71875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7432263999944553
Peak memory usage during training: 419.6640625 MB
Prediction time: 1.9150759999756701
Peak memory usage during prediction: 410.68359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7361766999820247
Peak memory usage during training: 420.125 MB
Prediction time: 1.8714790000231005
Peak memory usage during prediction: 410.8828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.758762699959334
Peak memory usage during training: 420.06640625 MB
Prediction time: 1.8626310999970883
Peak memory usage during prediction: 409.671875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 10.146660399972461
Peak memory usage during training: 418.06640625 MB
Prediction time: 1.8783811000175774
Peak memory usage during prediction: 409.96875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 10.00039190001553
Peak memory usage during training: 418.11328125 MB
Prediction time: 1.8619279999984428
Peak memory usage during prediction: 410.375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 14.448887199978344
Peak memory usage during training: 418.40625 MB
Prediction time: 1.8837035999749787
Peak memory usage during prediction: 410.36328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 14.325155299971811
Peak memory usage during training: 418.41015625 MB
Prediction time: 1.8893233999842778
Peak memory usage during prediction: 410.3046875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 18.61352130002342
Peak memory usage during training: 418.37109375 MB
Prediction time: 1.8943195000174455
Peak memory usage during prediction: 410.82421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.532780100009404
Peak memory usage during training: 418.546875 MB
Prediction time: 1.8919816999696195
Peak memory usage during prediction: 411.21484375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.1438159000244923
Peak memory usage during training: 418.81640625 MB
Prediction time: 1.0402582000242546
Peak memory usage during prediction: 410.71875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0748216999927536
Peak memory usage during training: 417.8984375 MB
Prediction time: 1.0438355000223964
Peak memory usage during prediction: 410.46875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.161082999955397
Peak memory usage during training: 417.87109375 MB
Prediction time: 1.0827624999801628
Peak memory usage during prediction: 410.125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.829153499973472
Peak memory usage during training: 417.87890625 MB
Prediction time: 1.1787513999734074
Peak memory usage during prediction: 415.4453125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.195275100006256
Peak memory usage during training: 417.9296875 MB
Prediction time: 1.2973805999499746
Peak memory usage during prediction: 410.4375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.442051299964078
Peak memory usage during training: 418.3046875 MB
Prediction time: 1.2947404999868013
Peak memory usage during prediction: 410.4140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.89328389998991
Peak memory usage during training: 417.86328125 MB
Prediction time: 1.3183513000258245
Peak memory usage during prediction: 415.69921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.924914599978365
Peak memory usage during training: 418.08984375 MB
Prediction time: 1.4493363999645226
Peak memory usage during prediction: 410.88671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.901356599992141
Peak memory usage during training: 418.59765625 MB
Prediction time: 1.2365605999948457
Peak memory usage during prediction: 416.2265625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3315306999720633
Peak memory usage during training: 418.21875 MB
Prediction time: 1.9328232000116259
Peak memory usage during prediction: 411.22265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.099746000021696
Peak memory usage during training: 417.48046875 MB
Prediction time: 1.8798189999652095
Peak memory usage during prediction: 410.80078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.8432058000471443
Peak memory usage during training: 417.96484375 MB
Prediction time: 1.8470802999800071
Peak memory usage during prediction: 410.80859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2602796999854036
Peak memory usage during training: 418.109375 MB
Prediction time: 1.8606204999960028
Peak memory usage during prediction: 410.95703125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.7217347000259906
Peak memory usage during training: 417.5625 MB
Prediction time: 1.8670905000180937
Peak memory usage during prediction: 410.83203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7576918000122532
Peak memory usage during training: 417.98046875 MB
Prediction time: 1.8486542999744415
Peak memory usage during prediction: 410.96875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2303525999886915
Peak memory usage during training: 418.2109375 MB
Prediction time: 1.8612376000382937
Peak memory usage during prediction: 410.79296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.275661299994681
Peak memory usage during training: 418.09765625 MB
Prediction time: 1.8443511000368744
Peak memory usage during prediction: 410.81640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.708588499983307
Peak memory usage during training: 417.42578125 MB
Prediction time: 1.974641699984204
Peak memory usage during prediction: 410.828125 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 5.290536099986639
Peak memory usage during training: 417.99609375 MB
Prediction time: 1.552908200013917
Peak memory usage during prediction: 292.6796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 5.883670600014739
Peak memory usage during training: 303.0859375 MB
Prediction time: 1.5073372999904677
Peak memory usage during prediction: 298.25 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 5.909013800031971
Peak memory usage during training: 303.19921875 MB
Prediction time: 1.5252089999848977
Peak memory usage during prediction: 298.140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 9.824316599988379
Peak memory usage during training: 343.63671875 MB
Prediction time: 1.0528532000025734
Peak memory usage during prediction: 338.2265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 11.129323000030126
Peak memory usage during training: 353.2734375 MB
Prediction time: 1.0144830999779515
Peak memory usage during prediction: 348.05078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 11.10810410004342
Peak memory usage during training: 353.30859375 MB
Prediction time: 1.0285448000067845
Peak memory usage during prediction: 347.98046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 14.235347100009676
Peak memory usage during training: 388.8203125 MB
Prediction time: 1.0985156000242569
Peak memory usage during prediction: 383.1640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 16.450705599971116
Peak memory usage during training: 403.27734375 MB
Prediction time: 1.0940108000067994
Peak memory usage during prediction: 292.44140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 16.58516720001353
Peak memory usage during training: 298.10546875 MB
Prediction time: 1.0909326000255533
Peak memory usage during prediction: 292.43359375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 13.900354299985338
Peak memory usage during training: 419.91015625 MB
Prediction time: 1.9245161000289954
Peak memory usage during prediction: 311.4375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 18.429610299994238
Peak memory usage during training: 462.51953125 MB
Prediction time: 2.788806599972304
Peak memory usage during prediction: 313.62109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.085266300011426
Peak memory usage during training: 420.81640625 MB
Prediction time: 1.9843882000423037
Peak memory usage during prediction: 311.11328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 11.968513400002848
Peak memory usage during training: 410.46875 MB
Prediction time: 1.6127486000186764
Peak memory usage during prediction: 310.265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 19.21251390001271
Peak memory usage during training: 483.76171875 MB
Prediction time: 2.794757999945432
Peak memory usage during prediction: 314.1015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 11.138961000018753
Peak memory usage during training: 396.5625 MB
Prediction time: 1.5199242000235245
Peak memory usage during prediction: 309.95703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 11.509313000016846
Peak memory usage during training: 400.4375 MB
Prediction time: 1.516479799989611
Peak memory usage during prediction: 310.125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 25.70432969997637
Peak memory usage during training: 504.3984375 MB
Prediction time: 3.004413700022269
Peak memory usage during prediction: 316.1484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 11.75300630001584
Peak memory usage during training: 373.9921875 MB
Prediction time: 1.1753162000095472
Peak memory usage during prediction: 309.1953125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.1770034999935888
Peak memory usage during training: 303.19140625 MB
Prediction time: 1.8711808000225574
Peak memory usage during prediction: 293.03515625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.1522616000147536
Peak memory usage during training: 301.4296875 MB
Prediction time: 1.8641718000289984
Peak memory usage during prediction: 292.8046875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.1671364000067115
Peak memory usage during training: 301.48046875 MB
Prediction time: 1.9256210000021383
Peak memory usage during prediction: 292.765625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7291166999493726
Peak memory usage during training: 303.515625 MB
Prediction time: 1.8704307000152767
Peak memory usage during prediction: 293.19921875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.8557762999553233
Peak memory usage during training: 302.83203125 MB
Prediction time: 1.854773600003682
Peak memory usage during prediction: 292.98828125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9427513999980874
Peak memory usage during training: 303.3515625 MB
Prediction time: 1.85382820002269
Peak memory usage during prediction: 292.7265625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.14611720002722
Peak memory usage during training: 301.30859375 MB
Prediction time: 1.3218271000077948
Peak memory usage during prediction: 405.828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1351219999487512
Peak memory usage during training: 300.421875 MB
Prediction time: 1.328238699992653
Peak memory usage during prediction: 390.8046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1402685000211932
Peak memory usage during training: 300.421875 MB
Prediction time: 1.3369595999829471
Peak memory usage during prediction: 401.87109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1601056000217795
Peak memory usage during training: 300.40625 MB
Prediction time: 1.3105896999477409
Peak memory usage during prediction: 399.03515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1400741999968886
Peak memory usage during training: 300.421875 MB
Prediction time: 1.309654499986209
Peak memory usage during prediction: 402.5 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.177432399999816
Peak memory usage during training: 300.375 MB
Prediction time: 1.4661487999837846
Peak memory usage during prediction: 406.6171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2242739000357687
Peak memory usage during training: 300.359375 MB
Prediction time: 1.4588865999830887
Peak memory usage during prediction: 405.4609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.3323353999876417
Peak memory usage during training: 300.4375 MB
Prediction time: 0.8150560999638401
Peak memory usage during prediction: 392.37890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.238953699998092
Peak memory usage during training: 300.3984375 MB
Prediction time: 0.7970070000155829
Peak memory usage during prediction: 407.96484375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8310153000056744
Peak memory usage during training: 302.63671875 MB
Prediction time: 2.103772400005255
Peak memory usage during prediction: 293.42578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7734643000294454
Peak memory usage during training: 302.75390625 MB
Prediction time: 2.0918333999579772
Peak memory usage during prediction: 293.56640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 4.272255900024902
Peak memory usage during training: 302.2421875 MB
Prediction time: 1.895811699971091
Peak memory usage during prediction: 292.3046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7439540000050329
Peak memory usage during training: 302.87109375 MB
Prediction time: 1.9542290000244975
Peak memory usage during prediction: 293.33984375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7321572999935597
Peak memory usage during training: 302.05859375 MB
Prediction time: 1.905265600013081
Peak memory usage during prediction: 293.5859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.8668184999842197
Peak memory usage during training: 301.58984375 MB
Prediction time: 1.924398300005123
Peak memory usage during prediction: 292.58203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7944199999910779
Peak memory usage during training: 302.45703125 MB
Prediction time: 1.9142189000267535
Peak memory usage during prediction: 293.35546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7342244000174105
Peak memory usage during training: 302.7890625 MB
Prediction time: 1.9202645999612287
Peak memory usage during prediction: 293.59375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.8335611000075005
Peak memory usage during training: 302.2578125 MB
Prediction time: 1.9561220000032336
Peak memory usage during prediction: 292.4140625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 21.51297079998767
Peak memory usage during training: 301.00390625 MB
Prediction time: 1.6344017999945208
Peak memory usage during prediction: 292.74609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 22.306819799996447
Peak memory usage during training: 300.140625 MB
Prediction time: 1.9820016999728978
Peak memory usage during prediction: 292.6640625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 32.14176279999083
Peak memory usage during training: 299.984375 MB
Prediction time: 1.896491400024388
Peak memory usage during prediction: 275.7265625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 30.881365200039
Peak memory usage during training: 282.9140625 MB
Prediction time: 1.8935259999707341
Peak memory usage during prediction: 275.41796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 40.568162699986715
Peak memory usage during training: 282.6015625 MB
Prediction time: 1.8925151000148617
Peak memory usage during prediction: 275.9765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 40.51382069999818
Peak memory usage during training: 462.69921875 MB
Prediction time: 1.4708229000098072
Peak memory usage during prediction: 455.96484375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.395036600006279
Peak memory usage during training: 462.67578125 MB
Prediction time: 1.057993600028567
Peak memory usage during prediction: 455.6484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.4432941999984905
Peak memory usage during training: 463.171875 MB
Prediction time: 1.0419842000119388
Peak memory usage during prediction: 454.94140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.382255100004841
Peak memory usage during training: 462.54296875 MB
Prediction time: 1.059594999998808
Peak memory usage during prediction: 455.0546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.221603499958292
Peak memory usage during training: 462.59375 MB
Prediction time: 1.154360499989707
Peak memory usage during prediction: 455.32421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.221393399988301
Peak memory usage during training: 462.8984375 MB
Prediction time: 1.1474802999873646
Peak memory usage during prediction: 455.375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 10.255242499988526
Peak memory usage during training: 462.94140625 MB
Prediction time: 1.141037299996242
Peak memory usage during prediction: 455.41796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 15.148239800008014
Peak memory usage during training: 462.95703125 MB
Prediction time: 1.239091900002677
Peak memory usage during prediction: 455.6796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 16.140196899999864
Peak memory usage during training: 463.0 MB
Prediction time: 1.4717281999764964
Peak memory usage during prediction: 455.90234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 15.988301400037017
Peak memory usage during training: 462.94140625 MB
Prediction time: 1.2615482999826781
Peak memory usage during prediction: 460.91015625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.2225759999710135
Peak memory usage during training: 462.66015625 MB
Prediction time: 1.8783513000234962
Peak memory usage during prediction: 455.67578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2756218999857083
Peak memory usage during training: 462.9921875 MB
Prediction time: 1.9129607999930158
Peak memory usage during prediction: 455.6953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.6978775999741629
Peak memory usage during training: 462.46875 MB
Prediction time: 1.8608627000357956
Peak memory usage during prediction: 456.0546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1987213999964297
Peak memory usage during training: 463.00390625 MB
Prediction time: 1.8616890999837779
Peak memory usage during prediction: 456.08984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2318045000429265
Peak memory usage during training: 462.9765625 MB
Prediction time: 1.9007192999706604
Peak memory usage during prediction: 456.1015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.2795753000536934
Peak memory usage during training: 462.74609375 MB
Prediction time: 1.8704035999835469
Peak memory usage during prediction: 456.00390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1854361000005156
Peak memory usage during training: 463.01953125 MB
Prediction time: 1.8550425000139512
Peak memory usage during prediction: 456.02734375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2087321999715641
Peak memory usage during training: 462.6640625 MB
Prediction time: 1.8645758000202477
Peak memory usage during prediction: 456.03125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.2217989999917336
Peak memory usage during training: 462.63671875 MB
Prediction time: 1.896435200003907
Peak memory usage during prediction: 456.0390625 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 5.604609900037758
Peak memory usage during training: 462.97265625 MB
Prediction time: 1.0058995999861509
Peak memory usage during prediction: 356.1171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 6.209999999962747
Peak memory usage during training: 365.875 MB
Prediction time: 1.0215325999888591
Peak memory usage during prediction: 360.2734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 6.171166700019967
Peak memory usage during training: 365.5078125 MB
Prediction time: 1.4717004999984056
Peak memory usage during prediction: 360.25 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 10.70824220002396
Peak memory usage during training: 412.40234375 MB
Prediction time: 1.0450620999909006
Peak memory usage during prediction: 406.5390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 11.835984000004828
Peak memory usage during training: 420.265625 MB
Prediction time: 1.0257605999941006
Peak memory usage during prediction: 415.0859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 11.7653818000108
Peak memory usage during training: 420.2734375 MB
Prediction time: 1.0142300999723375
Peak memory usage during prediction: 420.2734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 15.524429800047074
Peak memory usage during training: 463.265625 MB
Prediction time: 1.060049700026866
Peak memory usage during prediction: 456.421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 17.393264399957843
Peak memory usage during training: 474.7109375 MB
Prediction time: 1.057843899994623
Peak memory usage during prediction: 469.1484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 17.303773900028318
Peak memory usage during training: 476.87890625 MB
Prediction time: 1.0670676999725401
Peak memory usage during prediction: 468.984375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 9.866692499956116
Peak memory usage during training: 570.00390625 MB
Prediction time: 1.3432186000281945
Peak memory usage during prediction: 486.9375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 16.814710400009062
Peak memory usage during training: 620.296875 MB
Prediction time: 2.5681713999947533
Peak memory usage during prediction: 490.89453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 12.32638980000047
Peak memory usage during training: 584.3984375 MB
Prediction time: 1.6396859000087716
Peak memory usage during prediction: 488.32421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.456327499996405
Peak memory usage during training: 571.3828125 MB
Prediction time: 1.2713726999936625
Peak memory usage during prediction: 486.23828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 16.439830999996047
Peak memory usage during training: 630.65625 MB
Prediction time: 2.5517190999817103
Peak memory usage during prediction: 490.30078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 8.454448299948126
Peak memory usage during training: 545.7109375 MB
Prediction time: 1.288558500004001
Peak memory usage during prediction: 486.015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.4842789999675
Peak memory usage during training: 561.42578125 MB
Prediction time: 1.3117544000269845
Peak memory usage during prediction: 487.0390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 20.28939099999843
Peak memory usage during training: 665.97265625 MB
Prediction time: 2.6246359999640845
Peak memory usage during prediction: 491.25390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 7.296565100026783
Peak memory usage during training: 535.99609375 MB
Prediction time: 1.145210400049109
Peak memory usage during prediction: 486.4140625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.1574737000046298
Peak memory usage during training: 477.78125 MB
Prediction time: 1.8473333999863826
Peak memory usage during prediction: 469.7734375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.1367145999683999
Peak memory usage during training: 477.69921875 MB
Prediction time: 1.8612413000082597
Peak memory usage during prediction: 469.37109375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.2117716000066139
Peak memory usage during training: 477.91015625 MB
Prediction time: 1.935038199997507
Peak memory usage during prediction: 469.375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9186194999492727
Peak memory usage during training: 480.36328125 MB
Prediction time: 1.9610390999587253
Peak memory usage during prediction: 468.99609375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1331952000036836
Peak memory usage during training: 479.60546875 MB
Prediction time: 1.898664899985306
Peak memory usage during prediction: 468.77734375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2707674999837764
Peak memory usage during training: 480.19140625 MB
Prediction time: 1.907596500008367
Peak memory usage during prediction: 468.7734375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.173393999983091
Peak memory usage during training: 477.91015625 MB
Prediction time: 0.7579783999826759
Peak memory usage during prediction: 540.82421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1311265000258572
Peak memory usage during training: 477.23046875 MB
Prediction time: 0.7539799000369385
Peak memory usage during prediction: 575.40234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1468015999998897
Peak memory usage during training: 477.6328125 MB
Prediction time: 0.7538817999884486
Peak memory usage during prediction: 537.43359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.166179199994076
Peak memory usage during training: 477.2109375 MB
Prediction time: 0.7516356999985874
Peak memory usage during prediction: 548.171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1586080000270158
Peak memory usage during training: 477.6171875 MB
Prediction time: 0.7892460000002757
Peak memory usage during prediction: 574.75 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.204997299995739
Peak memory usage during training: 477.234375 MB
Prediction time: 0.7904379999963567
Peak memory usage during prediction: 581.38671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2790914999786764
Peak memory usage during training: 477.6328125 MB
Prediction time: 0.8058813000097871
Peak memory usage during prediction: 532.0390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1996972000342794
Peak memory usage during training: 477.14453125 MB
Prediction time: 0.7863362999632955
Peak memory usage during prediction: 557.50390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1647560999845155
Peak memory usage during training: 477.66796875 MB
Prediction time: 0.7680697999894619
Peak memory usage during prediction: 573.38671875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7271063000080176
Peak memory usage during training: 479.08984375 MB
Prediction time: 1.8671258999966085
Peak memory usage during prediction: 469.6328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7337217000313103
Peak memory usage during training: 479.9921875 MB
Prediction time: 1.925333499966655
Peak memory usage during prediction: 470.10546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.2117998999892734
Peak memory usage during training: 479.98046875 MB
Prediction time: 1.9019553000107408
Peak memory usage during prediction: 468.875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7377489999635145
Peak memory usage during training: 479.640625 MB
Prediction time: 1.882005500025116
Peak memory usage during prediction: 469.90625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7631110000074841
Peak memory usage during training: 480.06640625 MB
Prediction time: 1.8810837999917567
Peak memory usage during prediction: 470.05859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.7526180999702774
Peak memory usage during training: 479.48046875 MB
Prediction time: 1.855189000023529
Peak memory usage during prediction: 468.7890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7425675000413321
Peak memory usage during training: 479.0 MB
Prediction time: 1.8695899999584071
Peak memory usage during prediction: 469.80859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.7536099000135437
Peak memory usage during training: 480.75390625 MB
Prediction time: 1.9294369000126608
Peak memory usage during prediction: 470.1015625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.7572934000054374
Peak memory usage during training: 479.10546875 MB
Prediction time: 1.88851269998122
Peak memory usage during prediction: 468.83984375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 10.35338149999734
Peak memory usage during training: 478.40234375 MB
Prediction time: 1.8973525000037625
Peak memory usage during prediction: 468.96875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 10.30285640002694
Peak memory usage during training: 477.7578125 MB
Prediction time: 1.8841543000307865
Peak memory usage during prediction: 468.875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 14.790402900020126
Peak memory usage during training: 478.16015625 MB
Prediction time: 1.901882000034675
Peak memory usage during prediction: 469.33203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 14.718629500013776
Peak memory usage during training: 477.83203125 MB
Prediction time: 1.877538700005971
Peak memory usage during prediction: 469.01953125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 19.032409899984486
Peak memory usage during training: 478.2890625 MB
Prediction time: 1.919907300034538
Peak memory usage during prediction: 469.58203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 19.111349900020286
Peak memory usage during training: 477.828125 MB
Prediction time: 2.0424298000289127
Peak memory usage during prediction: 469.390625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.3605854000197724
Peak memory usage during training: 478.37890625 MB
Prediction time: 1.327324400015641
Peak memory usage during prediction: 469.5703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.3630008999607526
Peak memory usage during training: 477.6484375 MB
Prediction time: 1.1561107000452466
Peak memory usage during prediction: 469.23828125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.239286499971058
Peak memory usage during training: 477.9609375 MB
Prediction time: 1.109890500025358
Peak memory usage during prediction: 469.25 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.96100040001329
Peak memory usage during training: 477.26171875 MB
Prediction time: 1.2042962000123225
Peak memory usage during prediction: 469.1875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.864945399982389
Peak memory usage during training: 477.9296875 MB
Prediction time: 1.2056015999987721
Peak memory usage during prediction: 473.8125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.860752000007778
Peak memory usage during training: 477.3046875 MB
Prediction time: 1.1774470999953337
Peak memory usage during prediction: 473.8359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.3894108000095
Peak memory usage during training: 478.30078125 MB
Prediction time: 1.2426844000001438
Peak memory usage during prediction: 469.4765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.37211410002783
Peak memory usage during training: 477.53125 MB
Prediction time: 1.2959291999577545
Peak memory usage during prediction: 469.671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.551284099987242
Peak memory usage during training: 478.41015625 MB
Prediction time: 1.3618023000308312
Peak memory usage during prediction: 469.76953125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.4561576000414789
Peak memory usage during training: 477.44140625 MB
Prediction time: 1.905766899988521
Peak memory usage during prediction: 469.51953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0627722999779508
Peak memory usage during training: 476.7890625 MB
Prediction time: 1.91933100001188
Peak memory usage during prediction: 469.26953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.8848641999647953
Peak memory usage during training: 477.25390625 MB
Prediction time: 1.9300934000057168
Peak memory usage during prediction: 469.515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.308570699999109
Peak memory usage during training: 477.453125 MB
Prediction time: 1.8620558999828063
Peak memory usage during prediction: 469.5234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.727258900005836
Peak memory usage during training: 477.00390625 MB
Prediction time: 1.893030599982012
Peak memory usage during prediction: 469.48046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7699206999968737
Peak memory usage during training: 477.453125 MB
Prediction time: 1.899698699999135
Peak memory usage during prediction: 469.62109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.280572600022424
Peak memory usage during training: 477.4609375 MB
Prediction time: 1.9263440999784507
Peak memory usage during prediction: 469.59375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.3284200000343844
Peak memory usage during training: 477.58984375 MB
Prediction time: 1.95144800003618
Peak memory usage during prediction: 469.52734375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7112268999917433
Peak memory usage during training: 476.71484375 MB
Prediction time: 1.9354282999993302
Peak memory usage during prediction: 469.5234375 MB
----------------------------------------------------------------------------------------------------

# Process results

In [14]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 25 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   seed                                    396 non-null    object
 1   vectorizer                              396 non-null    object
 2   model                                   396 non-null    object
 3   params                                  396 non-null    object
 4   accuracy                                396 non-null    float64
 5   hamming_loss                            396 non-null    float64
 6   training_time                           396 non-null    float64
 7   prediction_time                         396 non-null    float64
 8   peak_memory_train                       396 non-null    float64
 9   peak_memory_prediction                  396 non-null    float64
 10  precision_class_ENTREGA                 396 non-null    float64
 11  recall_class_ENTREGA                    396 non-null    float64
 12  f1_class_ENTREGA                        396 non-null    float64
 13  precision_class_OUTROS                  396 non-null    float64
 14  recall_class_OUTROS                     396 non-null    float64
 15  f1_class_OUTROS                         396 non-null    float64
 16  precision_class_PRODUTO                 396 non-null    float64
 17  recall_class_PRODUTO                    396 non-null    float64
 18  f1_class_PRODUTO                        396 non-null    float64
 19  precision_class_CONDICOESDERECEBIMENTO  396 non-null    float64
 20  recall_class_CONDICOESDERECEBIMENTO     396 non-null    float64
 21  f1_class_CONDICOESDERECEBIMENTO         396 non-null    float64
 22  precision_class_ANUNCIO                 396 non-null    float64
 23  recall_class_ANUNCIO                    396 non-null    float64
 24  f1_class_ANUNCIO                        396 non-null    float64
dtypes: float64(21), object(4)
memory usage: 77.5+ KB

In [15]:
results.head()

,seed,vectorizer,model,params,accuracy,hamming_loss,training_time,prediction_time,peak_memory_train,peak_memory_prediction,...,f1_class_OUTROS,precision_class_PRODUTO,recall_class_PRODUTO,f1_class_PRODUTO,precision_class_CONDICOESDERECEBIMENTO,recall_class_CONDICOESDERECEBIMENTO,f1_class_CONDICOESDERECEBIMENTO,precision_class_ANUNCIO,recall_class_ANUNCIO,f1_class_ANUNCIO
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.642857,0.106933,5.514278,1.057965,422.425781,422.546875,...,0.488136,0.872390,0.986877,0.926108,0.919355,0.360759,0.518182,1.0,0.156627,0.270833
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.626050,0.116807,6.051982,1.943378,427.144531,422.203125,...,0.443662,0.870670,0.989501,0.926290,0.914894,0.272152,0.419512,1.0,0.072289,0.134831
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.626050,0.116807,6.008135,1.480189,427.484375,422.410156,...,0.443662,0.870670,0.989501,0.926290,0.914894,0.272152,0.419512,1.0,0.072289,0.134831
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.656513,0.103782,10.084337,1.045808,467.257812,467.250000,...,0.510067,0.873843,0.990814,0.928659,0.903226,0.354430,0.509091,1.0,0.192771,0.323232
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.628151,0.113445,11.392574,1.070524,476.820312,476.808594,...,0.477509,0.872390,0.986877,0.926108,0.893617,0.265823,0.409756,1.0,0.048193,0.091954

In [16]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,hamming_loss,training_time,prediction_time,peak_memory_train,peak_memory_prediction,...,precision_class_PRODUTO,recall_class_PRODUTO,f1_class_PRODUTO,precision_class_CONDICOESDERECEBIMENTO,recall_class_CONDICOESDERECEBIMENTO,f1_class_CONDICOESDERECEBIMENTO,precision_class_ANUNCIO,recall_class_ANUNCIO,f1_class_ANUNCIO,f1_avg
0,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.577731,0.139076,5.836746,1.173982,485.425781,480.613281,...,0.834628,0.986877,0.904390,0.855072,0.373418,0.519824,1.000000,0.144578,0.252632,0.500622
1,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.637605,0.111555,5.928384,1.215968,485.651042,480.658854,...,0.839246,0.993438,0.909856,0.876404,0.493671,0.631579,1.000000,0.445783,0.616667,0.686748
2,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.692227,0.084034,6.011802,1.203333,485.584635,480.674479,...,0.906748,0.969816,0.937223,0.796610,0.594937,0.681159,0.878788,0.698795,0.778523,0.789880
3,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 150, 'estimator__l...",3.333333,0.579832,0.136975,8.529893,1.266062,485.924479,479.545573,...,0.834071,0.989501,0.905162,0.855072,0.373418,0.519824,1.000000,0.180723,0.306122,0.516954
4,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 150, 'estimator__l...",3.333333,0.654412,0.103151,8.532834,1.333554,485.686198,478.054688,...,0.843159,0.994751,0.912703,0.863158,0.518987,0.648221,1.000000,0.542169,0.703125,0.725466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'estimator__C': 1, 'estimator__kernel': 'rbf'}",3.333333,0.704832,0.083824,19.001022,2.798409,643.281250,474.355469,...,0.901324,0.982940,0.940364,0.891304,0.518987,0.656000,1.000000,0.361446,0.530973,0.738595
128,SVC,TfidfVectorizer,"{'estimator__C': 1, 'estimator__kernel': 'sigm...",3.333333,0.732143,0.069748,11.078051,1.498658,558.207031,470.294271,...,0.931250,0.977690,0.953905,0.858491,0.575949,0.689394,0.979592,0.578313,0.727273,0.803399
129,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'lin...",3.333333,0.716387,0.073739,11.448185,1.503340,561.165365,470.272135,...,0.938303,0.958005,0.948052,0.782946,0.639241,0.703833,0.846154,0.662651,0.743243,0.810494
130,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'rbf'}",3.333333,0.723739,0.074160,25.610458,2.960880,665.022135,477.338542,...,0.924224,0.976378,0.949585,0.880000,0.556962,0.682171,0.975610,0.481928,0.645161,0.781463
131,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'sig...",3.333333,0.678571,0.081723,11.662389,1.182819,535.141927,469.988281,...,0.936774,0.952756,0.944697,0.737931,0.677215,0.706271,0.716049,0.698795,0.707317,0.798550

In [17]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train[classes])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test[classes], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test[classes], y_pred, average=None, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: LogisticRegression
Best model params: {'estimator__C': 10, 'estimator__penalty': 'l2'}
Best vectorizer: CountVectorizer
Best accuracy: 0.7028985507246377

Class ENTREGA
Precision: 0.9377162629757786
Recall: 0.9093959731543624
F1: 0.9233390119250426
Support: 298

Class OUTROS
Precision: 0.8159509202453987
Recall: 0.6073059360730594
F1: 0.6963350785340314
Support: 219

Class PRODUTO
Precision: 0.9291237113402062
Recall: 0.9474375821287779
F1: 0.9381912817176318
Support: 761

Class CONDICOESDERECEBIMENTO
Precision: 0.76
Recall: 0.6951219512195121
F1: 0.7261146496815286
Support: 164

Class ANUNCIO
Precision: 0.8309859154929577
Recall: 0.7023809523809523
F1: 0.7612903225806451
Support: 84

In [18]:
with open('models/best_model_sklearn_multilabel1.pkl', 'wb') as f:
    pickle.dump(pipeline, f)