# Importing libraries

In [4]:
# Basic libraries
import pandas as pd
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from memory_profiler import memory_usage

# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [5]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [6]:
ds = load_dataset("dair-ai/emotion", "split")

train = ds['train'].to_pandas()
val = ds['validation'].to_pandas()
test = ds['test'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    16000 non-null  object
 1   label   16000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 250.1+ KB

# Dataset preprocessing

In [7]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [8]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': SVC(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': LogisticRegression(max_iter=1000),
        'params': {
            'C': [0.1, 1, 10],
            'penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': GradientBoostingClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': SGDClassifier(),
        'params': {
            'alpha': [0.0001, 0.001, 0.01],
            'penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [9]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = sorted(train['label'].unique())
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [10]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train['label'])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                accuracy = accuracy_score(val['label'], y_pred)
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val['label'], y_pred, average=None, labels=classes, zero_division=0)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_multiclass3.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 8.392934100000275
Peak memory usage during training: 423.02734375 MB
Prediction time: 1.0655908999997337
Peak memory usage during prediction: 415.86328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_8692\4276233647.py:66: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 9.704741199999717
Peak memory usage during training: 425.37109375 MB
Prediction time: 1.0338348000000224
Peak memory usage during prediction: 425.49609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 9.689865800000007
Peak memory usage during training: 425.5078125 MB
Prediction time: 1.0339995999997882
Peak memory usage during prediction: 425.6484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 15.988385800000287
Peak memory usage during training: 475.71875 MB
Prediction time: 1.1388790000000881
Peak memory usage during prediction: 469.41015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 18.7348221000002
Peak memory usage during training: 483.5703125 MB
Prediction time: 1.136784499999976
Peak memory usage during prediction: 476.86328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 18.756881899999826
Peak memory usage during training: 484.26953125 MB
Prediction time: 1.1273316000001614
Peak memory usage during prediction: 477.2734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 23.71421220000002
Peak memory usage during training: 529.33203125 MB
Prediction time: 1.235481499999878
Peak memory usage during prediction: 522.4375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 28.188649499999883
Peak memory usage during training: 539.328125 MB
Prediction time: 1.23594920000005
Peak memory usage during prediction: 538.7265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 27.830251499999576
Peak memory usage during training: 540.37109375 MB
Prediction time: 1.2273751000002449
Peak memory usage during prediction: 533.5859375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 20.142752100000052
Peak memory usage during training: 749.26953125 MB
Prediction time: 1.8089412999997876
Peak memory usage during prediction: 557.4609375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 25.943327099999806
Peak memory usage during training: 753.0 MB
Prediction time: 2.257346499999585
Peak memory usage during prediction: 559.453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 20.863960900000166
Peak memory usage during training: 756.453125 MB
Prediction time: 1.940649300000132
Peak memory usage during prediction: 560.52734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 14.82474000000002
Peak memory usage during training: 750.875 MB
Prediction time: 1.5398499999996602
Peak memory usage during prediction: 558.41796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 31.548072100000354
Peak memory usage during training: 783.60546875 MB
Prediction time: 2.109173499999997
Peak memory usage during prediction: 560.21484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.580382699999973
Peak memory usage during training: 724.12890625 MB
Prediction time: 1.5414983000000575
Peak memory usage during prediction: 559.6171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 12.531189499999982
Peak memory usage during training: 700.57421875 MB
Prediction time: 1.4739520999996785
Peak memory usage during prediction: 560.3203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 33.435417099999995
Peak memory usage during training: 781.79296875 MB
Prediction time: 2.1019680999997945
Peak memory usage during prediction: 560.71875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.420067300000028
Peak memory usage during training: 643.5625 MB
Prediction time: 1.2990741000003254
Peak memory usage during prediction: 560.87109375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.1046566999998504
Peak memory usage during training: 555.96484375 MB
Prediction time: 1.8045525999996244
Peak memory usage during prediction: 545.2265625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.1082596000001104
Peak memory usage during training: 552.57421875 MB
Prediction time: 1.8080307000000175
Peak memory usage during prediction: 543.60546875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.1052561000001333
Peak memory usage during training: 552.98046875 MB
Prediction time: 1.7967659000000822
Peak memory usage during prediction: 542.69921875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1612686999997095
Peak memory usage during training: 576.26171875 MB
Prediction time: 1.8317164999998568
Peak memory usage during prediction: 543.27734375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.6010283000000527
Peak memory usage during training: 576.046875 MB
Prediction time: 1.8815590999997767
Peak memory usage during prediction: 543.08203125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 2.1797332000001006
Peak memory usage during training: 576.28515625 MB
Prediction time: 1.8201732999996239
Peak memory usage during prediction: 542.9921875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.113829700000224
Peak memory usage during training: 552.30078125 MB
Prediction time: 1.038736500000141
Peak memory usage during prediction: 1009.9921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1110650000000533
Peak memory usage during training: 550.96875 MB
Prediction time: 1.01901399999997
Peak memory usage during prediction: 1030.2578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.091548800000055
Peak memory usage during training: 552.171875 MB
Prediction time: 1.0280823999996755
Peak memory usage during prediction: 998.62890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1053077000001394
Peak memory usage during training: 550.87890625 MB
Prediction time: 1.0150045000000318
Peak memory usage during prediction: 1027.34765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.095763799999986
Peak memory usage during training: 552.109375 MB
Prediction time: 1.0315034999998716
Peak memory usage during prediction: 1032.57421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0996828000002097
Peak memory usage during training: 550.75390625 MB
Prediction time: 1.0270147999999608
Peak memory usage during prediction: 1027.01171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1011373999999705
Peak memory usage during training: 552.00390625 MB
Prediction time: 1.0336879999999837
Peak memory usage during prediction: 1014.9921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1052881999999045
Peak memory usage during training: 551.03515625 MB
Prediction time: 1.022660299999643
Peak memory usage during prediction: 1033.109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1044546999996783
Peak memory usage during training: 551.10546875 MB
Prediction time: 1.0255555999997341
Peak memory usage during prediction: 991.38671875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7898944000003212
Peak memory usage during training: 553.30859375 MB
Prediction time: 1.8613052999999127
Peak memory usage during prediction: 545.58984375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9251801000000341
Peak memory usage during training: 556.6015625 MB
Prediction time: 1.8187861999999768
Peak memory usage during prediction: 546.40625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 3.499054299999898
Peak memory usage during training: 554.90234375 MB
Prediction time: 1.4059995000002345
Peak memory usage during prediction: 548.26171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8600781999998617
Peak memory usage during training: 554.4375 MB
Prediction time: 1.8986651000000165
Peak memory usage during prediction: 545.8203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9831607999999505
Peak memory usage during training: 557.0234375 MB
Prediction time: 1.8547546999998303
Peak memory usage during prediction: 546.68359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 5.217877400000361
Peak memory usage during training: 555.10546875 MB
Prediction time: 1.8262077999997928
Peak memory usage during prediction: 544.44140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8633546000000933
Peak memory usage during training: 554.5703125 MB
Prediction time: 1.8236731000001782
Peak memory usage during prediction: 545.8203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9788042999998652
Peak memory usage during training: 557.0078125 MB
Prediction time: 1.8332164999997076
Peak memory usage during prediction: 546.5625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 5.203631200000018
Peak memory usage during training: 554.9921875 MB
Prediction time: 1.3945024999998168
Peak memory usage during prediction: 548.33203125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 26.54516360000025
Peak memory usage during training: 554.37109375 MB
Prediction time: 1.8658189999996466
Peak memory usage during prediction: 545.9921875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 26.39764779999996
Peak memory usage during training: 555.18359375 MB
Prediction time: 1.444676299999628
Peak memory usage during prediction: 545.84765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 39.44335140000021
Peak memory usage during training: 555.6015625 MB
Prediction time: 1.425180199999886
Peak memory usage during prediction: 546.43359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 39.337732799999685
Peak memory usage during training: 556.1484375 MB
Prediction time: 1.4106873999999152
Peak memory usage during prediction: 546.3203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 52.05891619999966
Peak memory usage during training: 556.4140625 MB
Prediction time: 0.9803627000001143
Peak memory usage during prediction: 546.34765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 51.8611748000003
Peak memory usage during training: 556.26171875 MB
Prediction time: 0.982213899999806
Peak memory usage during prediction: 546.6328125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.8228119999998853
Peak memory usage during training: 556.16796875 MB
Prediction time: 1.4216169999999693
Peak memory usage during prediction: 546.62109375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7970304000000397
Peak memory usage during training: 556.12109375 MB
Prediction time: 1.4132856999999603
Peak memory usage during prediction: 546.7734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7869268999997985
Peak memory usage during training: 556.03515625 MB
Prediction time: 1.417995400000109
Peak memory usage during prediction: 546.58984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.061066100000062
Peak memory usage during training: 555.9375 MB
Prediction time: 0.9885233999998491
Peak memory usage during prediction: 546.859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.007090600000083
Peak memory usage during training: 556.21875 MB
Prediction time: 0.9856073000000833
Peak memory usage during prediction: 546.8125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0594535999998698
Peak memory usage during training: 556.12890625 MB
Prediction time: 0.992993800000022
Peak memory usage during prediction: 546.7265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.314519699999892
Peak memory usage during training: 556.08203125 MB
Prediction time: 1.0208020999998553
Peak memory usage during prediction: 547.08203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.227763400000185
Peak memory usage during training: 556.5703125 MB
Prediction time: 1.0328081000002385
Peak memory usage during prediction: 546.77734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.302961999999752
Peak memory usage during training: 556.29296875 MB
Prediction time: 1.0239034999999603
Peak memory usage during prediction: 546.85546875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.2219010999997408
Peak memory usage during training: 555.5546875 MB
Prediction time: 1.8372761000000537
Peak memory usage during prediction: 547.5 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2201202000001103
Peak memory usage during training: 555.48828125 MB
Prediction time: 1.3815094000001409
Peak memory usage during prediction: 547.421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.6717593999997007
Peak memory usage during training: 555.2265625 MB
Prediction time: 1.8272578000000976
Peak memory usage during prediction: 547.4296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1873952000000827
Peak memory usage during training: 555.4296875 MB
Prediction time: 1.8278387999998813
Peak memory usage during prediction: 547.37109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2584843999998157
Peak memory usage during training: 555.47265625 MB
Prediction time: 1.3889921999998478
Peak memory usage during prediction: 547.40625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.2236806000000797
Peak memory usage during training: 555.22265625 MB
Prediction time: 1.8271475999999893
Peak memory usage during prediction: 547.28125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.170792099999744
Peak memory usage during training: 555.44140625 MB
Prediction time: 1.8091392999999698
Peak memory usage during prediction: 547.36328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1917810999998437
Peak memory usage during training: 555.47265625 MB
Prediction time: 1.8338966999999684
Peak memory usage during prediction: 547.515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1934913000000051
Peak memory usage during training: 555.2265625 MB
Prediction time: 1.8352092999998604
Peak memory usage during prediction: 547.375 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 8.524862700000085
Peak memory usage during training: 547.375 MB
Prediction time: 1.03796229999989
Peak memory usage during prediction: 438.8125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 9.452343500000097
Peak memory usage during training: 441.86328125 MB
Prediction time: 1.037635500000306
Peak memory usage during prediction: 441.8828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 9.393490500000098
Peak memory usage during training: 442.0 MB
Prediction time: 1.0404829999997673
Peak memory usage during prediction: 442.03515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 16.62533590000021
Peak memory usage during training: 496.37890625 MB
Prediction time: 1.1297715999999127
Peak memory usage during prediction: 489.74609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 18.540967400000227
Peak memory usage during training: 503.0546875 MB
Prediction time: 1.1391582000001108
Peak memory usage during prediction: 496.1875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 18.506797600000027
Peak memory usage during training: 502.9375 MB
Prediction time: 1.1405558000001292
Peak memory usage during prediction: 495.95703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 24.56722239999999
Peak memory usage during training: 552.609375 MB
Prediction time: 1.2215360999998666
Peak memory usage during prediction: 545.6328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 27.350720899999942
Peak memory usage during training: 561.20703125 MB
Prediction time: 1.2180100000000493
Peak memory usage during prediction: 560.37109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 27.684349199999815
Peak memory usage during training: 561.39453125 MB
Prediction time: 1.210031799999797
Peak memory usage during prediction: 560.36328125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 16.223441699999967
Peak memory usage during training: 802.7109375 MB
Prediction time: 1.626883099999759
Peak memory usage during prediction: 575.39453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 26.173876500000006
Peak memory usage during training: 772.40234375 MB
Prediction time: 2.264317900000151
Peak memory usage during prediction: 577.73828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 20.343708600000355
Peak memory usage during training: 781.1328125 MB
Prediction time: 1.9821302000000287
Peak memory usage during prediction: 578.45703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.719762300000184
Peak memory usage during training: 695.109375 MB
Prediction time: 1.463639300000068
Peak memory usage during prediction: 576.0703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 32.247433
Peak memory usage during training: 797.15625 MB
Prediction time: 2.102693299999828
Peak memory usage during prediction: 576.671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.376248500000202
Peak memory usage during training: 734.640625 MB
Prediction time: 1.6276551999999356
Peak memory usage during prediction: 562.70703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 9.985946799999965
Peak memory usage during training: 677.8671875 MB
Prediction time: 1.36783000000014
Peak memory usage during prediction: 577.52734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 34.100644999999986
Peak memory usage during training: 797.0078125 MB
Prediction time: 2.1726512000000184
Peak memory usage during prediction: 577.23046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 7.726933899999949
Peak memory usage during training: 657.52734375 MB
Prediction time: 1.3015000999998847
Peak memory usage during prediction: 574.65625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.2172002000002067
Peak memory usage during training: 573.265625 MB
Prediction time: 1.9711900999996033
Peak memory usage during prediction: 559.4140625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.2338804000000891
Peak memory usage during training: 567.90625 MB
Prediction time: 2.001192600000195
Peak memory usage during prediction: 558.28125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.2218917999998666
Peak memory usage during training: 568.0859375 MB
Prediction time: 2.003805900000316
Peak memory usage during prediction: 557.58984375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2003347999998368
Peak memory usage during training: 592.14453125 MB
Prediction time: 2.0245765999998184
Peak memory usage during prediction: 557.26171875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3611910999998145
Peak memory usage during training: 591.84375 MB
Prediction time: 1.9172687999998743
Peak memory usage during prediction: 557.28515625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.5524055000000772
Peak memory usage during training: 591.57421875 MB
Prediction time: 1.8426639000003888
Peak memory usage during prediction: 556.8515625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1241006999998717
Peak memory usage during training: 566.640625 MB
Prediction time: 1.1476811000002272
Peak memory usage during prediction: 936.58203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.138102699999763
Peak memory usage during training: 564.3203125 MB
Prediction time: 1.1872902000000067
Peak memory usage during prediction: 983.24609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.3251233000000866
Peak memory usage during training: 564.5078125 MB
Prediction time: 1.2420191999999588
Peak memory usage during prediction: 976.296875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1857952000000296
Peak memory usage during training: 564.1796875 MB
Prediction time: 1.0741660999997293
Peak memory usage during prediction: 1032.14453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1398495999997067
Peak memory usage during training: 564.0 MB
Prediction time: 1.1000636999997369
Peak memory usage during prediction: 1019.77734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.2831210999997893
Peak memory usage during training: 563.98828125 MB
Prediction time: 1.2184384000001955
Peak memory usage during prediction: 977.03515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.352798200000052
Peak memory usage during training: 564.2734375 MB
Prediction time: 1.231789899999967
Peak memory usage during prediction: 922.85546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2938780999998016
Peak memory usage during training: 563.8203125 MB
Prediction time: 1.1750969999998233
Peak memory usage during prediction: 979.546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1970538999999008
Peak memory usage during training: 564.15625 MB
Prediction time: 1.1842385999998442
Peak memory usage during prediction: 999.76171875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8712304999999105
Peak memory usage during training: 564.3359375 MB
Prediction time: 1.9013426000001346
Peak memory usage during prediction: 557.25390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0202077999997528
Peak memory usage during training: 570.078125 MB
Prediction time: 1.894143399999848
Peak memory usage during prediction: 558.265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.1796038000002227
Peak memory usage during training: 566.28515625 MB
Prediction time: 1.8942320000001018
Peak memory usage during prediction: 556.078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8874877999996897
Peak memory usage during training: 564.56640625 MB
Prediction time: 1.0065047000002778
Peak memory usage during prediction: 564.57421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0682114999999612
Peak memory usage during training: 569.68359375 MB
Prediction time: 1.9017023999999765
Peak memory usage during prediction: 558.390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.4556781000001138
Peak memory usage during training: 565.796875 MB
Prediction time: 1.9383692000001247
Peak memory usage during prediction: 556.10546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8483963999997286
Peak memory usage during training: 564.61328125 MB
Prediction time: 1.8902827000001707
Peak memory usage during prediction: 557.578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0759204999999383
Peak memory usage during training: 569.73046875 MB
Prediction time: 1.8820941999997558
Peak memory usage during prediction: 558.328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.458866399999806
Peak memory usage during training: 566.421875 MB
Prediction time: 1.9200631999997313
Peak memory usage during prediction: 556.140625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 13.581945500000074
Peak memory usage during training: 565.328125 MB
Prediction time: 2.0065044999996644
Peak memory usage during prediction: 555.78515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 13.493756400000166
Peak memory usage during training: 564.87890625 MB
Prediction time: 1.4537101000000803
Peak memory usage during prediction: 555.6953125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 20.207748999999694
Peak memory usage during training: 564.578125 MB
Prediction time: 1.5634433999998691
Peak memory usage during prediction: 556.109375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 19.420759999999973
Peak memory usage during training: 565.11328125 MB
Prediction time: 1.4965281999998297
Peak memory usage during prediction: 556.0390625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 26.266358500000024
Peak memory usage during training: 564.9609375 MB
Prediction time: 1.152325000000019
Peak memory usage during prediction: 556.1328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 25.903094000000237
Peak memory usage during training: 565.359375 MB
Prediction time: 1.0154703000002883
Peak memory usage during prediction: 563.40625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3518855000002077
Peak memory usage during training: 563.33203125 MB
Prediction time: 1.4566442999998799
Peak memory usage during prediction: 556.47265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3316247000002477
Peak memory usage during training: 563.19921875 MB
Prediction time: 1.4599797999999282
Peak memory usage during prediction: 556.4375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3447010999998383
Peak memory usage during training: 563.28515625 MB
Prediction time: 1.4765339999999014
Peak memory usage during prediction: 556.41015625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.389888400000018
Peak memory usage during training: 563.21875 MB
Prediction time: 1.2429124999998749
Peak memory usage during prediction: 556.3359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.190084200000001
Peak memory usage during training: 563.3125 MB
Prediction time: 1.0690894999997909
Peak memory usage during prediction: 556.203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.110772900000029
Peak memory usage during training: 563.2265625 MB
Prediction time: 1.0238298999997824
Peak memory usage during prediction: 556.265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.9029050000003735
Peak memory usage during training: 563.109375 MB
Prediction time: 1.052433800000017
Peak memory usage during prediction: 561.74609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.834429
Peak memory usage during training: 563.1875 MB
Prediction time: 1.0496186000000307
Peak memory usage during prediction: 561.796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.875077799999872
Peak memory usage during training: 563.1171875 MB
Prediction time: 1.0435872000002746
Peak memory usage during prediction: 561.96875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3041800999999396
Peak memory usage during training: 563.12109375 MB
Prediction time: 1.8854393999999957
Peak memory usage during prediction: 556.47265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.8112599999999475
Peak memory usage during training: 563.0703125 MB
Prediction time: 1.88636919999999
Peak memory usage during prediction: 556.7421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7827376999998705
Peak memory usage during training: 563.18359375 MB
Prediction time: 1.8822884000001068
Peak memory usage during prediction: 556.60546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2625199999997676
Peak memory usage during training: 563.25390625 MB
Prediction time: 1.8960971000001337
Peak memory usage during prediction: 556.73828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.3346901999998408
Peak memory usage during training: 563.3125 MB
Prediction time: 1.8842061000000285
Peak memory usage during prediction: 556.734375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.3505941000003077
Peak memory usage during training: 563.27734375 MB
Prediction time: 1.878546400000232
Peak memory usage during prediction: 556.53125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2312113999996654
Peak memory usage during training: 563.1484375 MB
Prediction time: 1.891048999999839
Peak memory usage during prediction: 556.421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2575737000001936
Peak memory usage during training: 563.0859375 MB
Prediction time: 1.996706500000073
Peak memory usage during prediction: 556.484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.2823852000001352
Peak memory usage during training: 562.99609375 MB
Prediction time: 1.8539946000000782
Peak memory usage during prediction: 556.55078125 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 8.515710200000285
Peak memory usage during training: 556.55078125 MB
Prediction time: 1.0955246999997144
Peak memory usage during prediction: 435.02734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 10.22175950000019
Peak memory usage during training: 441.4609375 MB
Prediction time: 1.12270639999997
Peak memory usage during prediction: 434.6796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 10.36047009999993
Peak memory usage during training: 440.4609375 MB
Prediction time: 1.1061032999996314
Peak memory usage during prediction: 440.01953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 17.24385110000003
Peak memory usage during training: 487.89453125 MB
Prediction time: 1.1788586000002397
Peak memory usage during prediction: 487.90625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 19.503144799999973
Peak memory usage during training: 498.99609375 MB
Prediction time: 1.181607200000144
Peak memory usage during prediction: 491.96875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 19.22975859999997
Peak memory usage during training: 498.296875 MB
Prediction time: 1.1569832000000133
Peak memory usage during prediction: 497.7109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 24.454581299999973
Peak memory usage during training: 542.0546875 MB
Prediction time: 1.2101588000000447
Peak memory usage during prediction: 535.24609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 28.204920799999854
Peak memory usage during training: 556.140625 MB
Prediction time: 1.2076480999999148
Peak memory usage during prediction: 554.91796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 28.074359100000038
Peak memory usage during training: 556.00390625 MB
Prediction time: 1.2183336999996754
Peak memory usage during prediction: 554.8671875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 20.174782699999923
Peak memory usage during training: 772.61328125 MB
Prediction time: 1.8004358000002867
Peak memory usage during prediction: 568.83984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 25.945699500000046
Peak memory usage during training: 763.62890625 MB
Prediction time: 2.2512768999999935
Peak memory usage during prediction: 571.59375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 20.892045000000053
Peak memory usage during training: 775.94921875 MB
Prediction time: 1.9292983000000277
Peak memory usage during prediction: 571.77734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 14.76739570000018
Peak memory usage during training: 761.3125 MB
Prediction time: 1.5254609000003256
Peak memory usage during prediction: 570.02734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 31.50734919999968
Peak memory usage during training: 794.046875 MB
Prediction time: 2.0917592000000695
Peak memory usage during prediction: 571.54296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.529098599999998
Peak memory usage during training: 734.37109375 MB
Prediction time: 1.5252189999996517
Peak memory usage during prediction: 570.421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 12.491849300000013
Peak memory usage during training: 711.4140625 MB
Prediction time: 1.473454600000423
Peak memory usage during prediction: 571.6484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 33.432669799999985
Peak memory usage during training: 792.0 MB
Prediction time: 2.092258000000129
Peak memory usage during prediction: 571.66015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.355081500000324
Peak memory usage during training: 653.75 MB
Prediction time: 1.2954161000002387
Peak memory usage during prediction: 571.4296875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.0829358999999386
Peak memory usage during training: 565.47265625 MB
Prediction time: 1.8003395000000637
Peak memory usage during prediction: 554.984375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.0897958999998991
Peak memory usage during training: 562.37109375 MB
Prediction time: 1.795054700000037
Peak memory usage during prediction: 553.0546875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.0864877000003617
Peak memory usage during training: 561.7890625 MB
Prediction time: 1.8049832000001516
Peak memory usage during prediction: 551.94140625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.909243399999923
Peak memory usage during training: 583.87890625 MB
Prediction time: 1.7962004000000888
Peak memory usage during prediction: 551.6953125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.5081858999997166
Peak memory usage during training: 583.04296875 MB
Prediction time: 1.7964689999998882
Peak memory usage during prediction: 551.28125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 2.1431036000003587
Peak memory usage during training: 582.53515625 MB
Prediction time: 1.8125374999999622
Peak memory usage during prediction: 551.33203125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.079029300000002
Peak memory usage during training: 560.14453125 MB
Prediction time: 0.9806871000000683
Peak memory usage during prediction: 1008.84765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0914350999996714
Peak memory usage during training: 558.0234375 MB
Prediction time: 0.9677867000000333
Peak memory usage during prediction: 948.15234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.086759499999971
Peak memory usage during training: 558.98828125 MB
Prediction time: 0.9749662000003809
Peak memory usage during prediction: 933.90234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0956538999998884
Peak memory usage during training: 558.61328125 MB
Prediction time: 0.975098099999741
Peak memory usage during prediction: 1014.3671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0982148999996753
Peak memory usage during training: 559.375 MB
Prediction time: 0.9711817000002156
Peak memory usage during prediction: 937.34765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0912153000003855
Peak memory usage during training: 558.5 MB
Prediction time: 0.963117499999953
Peak memory usage during prediction: 942.78515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1011498999996547
Peak memory usage during training: 559.21875 MB
Prediction time: 1.0029976000000715
Peak memory usage during prediction: 932.13671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0948858000001565
Peak memory usage during training: 558.72265625 MB
Prediction time: 0.9946726000002855
Peak memory usage during prediction: 987.60546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1054830000002767
Peak memory usage during training: 546.265625 MB
Prediction time: 0.9641097999997328
Peak memory usage during prediction: 923.3671875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7806820000000698
Peak memory usage during training: 546.08984375 MB
Prediction time: 1.3528839000000517
Peak memory usage during prediction: 544.03125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9088451000002351
Peak memory usage during training: 549.98828125 MB
Prediction time: 1.3613436000000547
Peak memory usage during prediction: 539.9296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 3.4846611000002667
Peak memory usage during training: 548.6171875 MB
Prediction time: 1.8037638000000698
Peak memory usage during prediction: 537.9140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8296459000002869
Peak memory usage during training: 546.73046875 MB
Prediction time: 1.7959175000000869
Peak memory usage during prediction: 539.515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9694135999998252
Peak memory usage during training: 550.12890625 MB
Prediction time: 1.8227775000000292
Peak memory usage during prediction: 540.21484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 5.1938208999999915
Peak memory usage during training: 548.62890625 MB
Prediction time: 1.8041713999996318
Peak memory usage during prediction: 537.80859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8329721000000063
Peak memory usage during training: 546.6328125 MB
Prediction time: 1.8032020999999077
Peak memory usage during prediction: 539.1953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9810672000003251
Peak memory usage during training: 549.96875 MB
Prediction time: 1.800932499999817
Peak memory usage during prediction: 539.76953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 5.216552399999728
Peak memory usage during training: 548.515625 MB
Prediction time: 1.8115739999998368
Peak memory usage during prediction: 537.75 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 26.251573500000177
Peak memory usage during training: 547.21484375 MB
Prediction time: 1.3770903999998154
Peak memory usage during prediction: 538.03125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 26.118894100000034
Peak memory usage during training: 546.68359375 MB
Prediction time: 1.3934833999996954
Peak memory usage during prediction: 537.7265625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 39.42098639999995
Peak memory usage during training: 546.546875 MB
Prediction time: 1.5122737000001507
Peak memory usage during prediction: 538.3515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 39.42118459999983
Peak memory usage during training: 547.484375 MB
Prediction time: 1.4107523000002402
Peak memory usage during prediction: 538.140625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 52.5807648
Peak memory usage during training: 547.73828125 MB
Prediction time: 0.9750568999997995
Peak memory usage during prediction: 538.484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 52.41000389999954
Peak memory usage during training: 547.265625 MB
Prediction time: 0.961270599999807
Peak memory usage during prediction: 538.0546875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.807824299999993
Peak memory usage during training: 546.44140625 MB
Prediction time: 0.9436930000001666
Peak memory usage during prediction: 543.49609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.772795099999712
Peak memory usage during training: 546.4453125 MB
Prediction time: 1.3997990000007121
Peak memory usage during prediction: 538.0234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7829807999996774
Peak memory usage during training: 546.47265625 MB
Prediction time: 1.4074437000008402
Peak memory usage during prediction: 538.046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0341536999994787
Peak memory usage during training: 546.38671875 MB
Prediction time: 0.9824437999996007
Peak memory usage during prediction: 538.0703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.976900000000569
Peak memory usage during training: 546.546875 MB
Prediction time: 0.9639359000002514
Peak memory usage during prediction: 543.578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0081581000004007
Peak memory usage during training: 546.328125 MB
Prediction time: 0.9863433999998961
Peak memory usage during prediction: 537.96484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.289786300000742
Peak memory usage during training: 546.34375 MB
Prediction time: 1.0208692000005612
Peak memory usage during prediction: 538.25390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.207877499999995
Peak memory usage during training: 546.546875 MB
Prediction time: 0.9994625999997879
Peak memory usage during prediction: 538.25 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.244006500000069
Peak memory usage during training: 546.59765625 MB
Prediction time: 1.0039502999998149
Peak memory usage during prediction: 538.203125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1957286000006206
Peak memory usage during training: 547.02734375 MB
Prediction time: 1.357202099999995
Peak memory usage during prediction: 538.4296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1917707000002338
Peak memory usage during training: 546.06640625 MB
Prediction time: 1.8143122999999832
Peak memory usage during prediction: 538.4375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.6705424000001585
Peak memory usage during training: 545.8984375 MB
Prediction time: 1.7867095999999947
Peak memory usage during prediction: 538.5 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1745882000004713
Peak memory usage during training: 546.08984375 MB
Prediction time: 1.7939730999996755
Peak memory usage during prediction: 538.43359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2315840999999637
Peak memory usage during training: 546.1328125 MB
Prediction time: 1.7947423999994498
Peak memory usage during prediction: 538.63671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.2146591999999146
Peak memory usage during training: 546.0859375 MB
Prediction time: 1.787819899999704
Peak memory usage during prediction: 538.63671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.15755099999933
Peak memory usage during training: 546.125 MB
Prediction time: 1.7942678999997952
Peak memory usage during prediction: 538.56640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1685262999999395
Peak memory usage during training: 546.08203125 MB
Prediction time: 1.801243400000203
Peak memory usage during prediction: 538.6484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1845648000007714
Peak memory usage during training: 546.09375 MB
Prediction time: 1.7963575000003402
Peak memory usage during prediction: 538.64453125 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 8.543834199999765
Peak memory usage during training: 538.64453125 MB
Prediction time: 1.0227055000004839
Peak memory usage during prediction: 430.56640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 9.410773399999925
Peak memory usage during training: 440.015625 MB
Prediction time: 1.0111289999995279
Peak memory usage during prediction: 440.05078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 9.52324580000004
Peak memory usage during training: 439.60546875 MB
Prediction time: 1.0188925999991625
Peak memory usage during prediction: 439.71484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 16.854023299999426
Peak memory usage during training: 493.81640625 MB
Prediction time: 1.1168701000005967
Peak memory usage during prediction: 493.890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 18.44773239999995
Peak memory usage during training: 500.625 MB
Prediction time: 1.1106757999996262
Peak memory usage during prediction: 493.671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 18.536486199999672
Peak memory usage during training: 500.41796875 MB
Prediction time: 1.1434802000003401
Peak memory usage during prediction: 493.37109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 24.740859100000307
Peak memory usage during training: 550.78125 MB
Prediction time: 1.2203990999996677
Peak memory usage during prediction: 549.7578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 27.245034999999916
Peak memory usage during training: 560.23828125 MB
Prediction time: 1.2106854000003295
Peak memory usage during prediction: 553.5390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 27.288657799999783
Peak memory usage during training: 558.984375 MB
Prediction time: 1.2031819000003452
Peak memory usage during prediction: 557.48046875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 16.28256710000005
Peak memory usage during training: 800.7421875 MB
Prediction time: 1.621654800000215
Peak memory usage during prediction: 572.89453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 26.2150915000002
Peak memory usage during training: 769.9375 MB
Prediction time: 2.270104000000174
Peak memory usage during prediction: 574.73828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 20.42209660000026
Peak memory usage during training: 778.12109375 MB
Prediction time: 1.9775668000002042
Peak memory usage during prediction: 575.65625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.712771900000007
Peak memory usage during training: 692.50390625 MB
Prediction time: 1.4082860000007713
Peak memory usage during prediction: 573.25390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 32.25442320000002
Peak memory usage during training: 794.93359375 MB
Prediction time: 2.0984545000001162
Peak memory usage during prediction: 574.2109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.33983629999966
Peak memory usage during training: 732.41015625 MB
Prediction time: 1.575550800000201
Peak memory usage during prediction: 560.09765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 9.687054800000624
Peak memory usage during training: 674.765625 MB
Prediction time: 1.3405023000004803
Peak memory usage during prediction: 574.734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 33.3485955999995
Peak memory usage during training: 795.0859375 MB
Prediction time: 2.1006729000000632
Peak memory usage during prediction: 574.51171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 7.433666900000389
Peak memory usage during training: 653.9140625 MB
Prediction time: 1.2350759999999354
Peak memory usage during prediction: 573.8828125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.1248899999991409
Peak memory usage during training: 570.72265625 MB
Prediction time: 1.858015400000113
Peak memory usage during prediction: 556.8203125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.1131052999999156
Peak memory usage during training: 565.13671875 MB
Prediction time: 1.8145867999992333
Peak memory usage during prediction: 555.5546875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.1196270000000368
Peak memory usage during training: 565.38671875 MB
Prediction time: 1.806782600000588
Peak memory usage during prediction: 554.61328125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.109167300000081
Peak memory usage during training: 588.88671875 MB
Prediction time: 1.8320440999996208
Peak memory usage during prediction: 554.34765625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3699920000008206
Peak memory usage during training: 588.625 MB
Prediction time: 1.8272516999995787
Peak memory usage during prediction: 554.0625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.8294763999992938
Peak memory usage during training: 588.71484375 MB
Prediction time: 1.8100807000000714
Peak memory usage during prediction: 554.04296875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0937310000008438
Peak memory usage during training: 563.96875 MB
Prediction time: 1.0089460999997755
Peak memory usage during prediction: 945.66796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1013413000000583
Peak memory usage during training: 562.1640625 MB
Prediction time: 1.0192481000003681
Peak memory usage during prediction: 946.4453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0941766000005373
Peak memory usage during training: 562.1875 MB
Prediction time: 1.0330387000003611
Peak memory usage during prediction: 1014.6171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.101351600000271
Peak memory usage during training: 561.51953125 MB
Prediction time: 1.0258280999996714
Peak memory usage during prediction: 1010.2109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0940910999997868
Peak memory usage during training: 561.81640625 MB
Prediction time: 1.0147885999995196
Peak memory usage during prediction: 995.34765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1050125000001572
Peak memory usage during training: 561.515625 MB
Prediction time: 1.0218934000004083
Peak memory usage during prediction: 1007.21484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1082581999999093
Peak memory usage during training: 561.82421875 MB
Prediction time: 1.0176590000000942
Peak memory usage during prediction: 944.99609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1051467000006596
Peak memory usage during training: 561.5625 MB
Prediction time: 1.017738399999871
Peak memory usage during prediction: 940.671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1022775999999794
Peak memory usage during training: 561.89453125 MB
Prediction time: 1.0192964999996548
Peak memory usage during prediction: 934.5859375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7887602999999217
Peak memory usage during training: 561.67578125 MB
Prediction time: 1.3868225999995047
Peak memory usage during prediction: 559.6484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.9697630999999092
Peak memory usage during training: 564.82421875 MB
Prediction time: 1.8208912999998574
Peak memory usage during prediction: 555.76171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.0984466999998403
Peak memory usage during training: 564.67578125 MB
Prediction time: 1.8236538999999539
Peak memory usage during prediction: 553.51171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8154390999998213
Peak memory usage during training: 562.1328125 MB
Prediction time: 1.8149592999998276
Peak memory usage during prediction: 554.8203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0055600000005143
Peak memory usage during training: 564.9296875 MB
Prediction time: 1.830386599999656
Peak memory usage during prediction: 555.765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.433385399999679
Peak memory usage during training: 564.82421875 MB
Prediction time: 1.8087585000002946
Peak memory usage during prediction: 553.5546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8224979000005987
Peak memory usage during training: 562.21875 MB
Prediction time: 1.8141337999995812
Peak memory usage during prediction: 555.015625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.998473799999374
Peak memory usage during training: 564.98828125 MB
Prediction time: 1.8277391999999963
Peak memory usage during prediction: 555.640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.388480200000231
Peak memory usage during training: 564.69921875 MB
Prediction time: 1.815892800000256
Peak memory usage during prediction: 553.40625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 12.633443400000033
Peak memory usage during training: 563.5859375 MB
Prediction time: 1.8603620999992927
Peak memory usage during prediction: 553.40625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 12.604343500000141
Peak memory usage during training: 562.3046875 MB
Prediction time: 1.862058700000489
Peak memory usage during prediction: 553.45703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 18.646185499999774
Peak memory usage during training: 562.5390625 MB
Prediction time: 0.9591341999994256
Peak memory usage during prediction: 553.86328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.59932409999965
Peak memory usage during training: 562.828125 MB
Prediction time: 1.4200065999993967
Peak memory usage during prediction: 553.5546875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 24.557258900000306
Peak memory usage during training: 563.125 MB
Prediction time: 0.9852572999998301
Peak memory usage during prediction: 561.0390625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 24.532451299999593
Peak memory usage during training: 562.53125 MB
Prediction time: 0.9855389000003925
Peak memory usage during prediction: 560.3984375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3018817000001945
Peak memory usage during training: 560.62109375 MB
Prediction time: 0.9709931000006691
Peak memory usage during prediction: 553.9609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2827602999996088
Peak memory usage during training: 560.65625 MB
Prediction time: 1.4107248000000254
Peak memory usage during prediction: 554.12890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2935373000000254
Peak memory usage during training: 561.14453125 MB
Prediction time: 1.427093799999966
Peak memory usage during prediction: 553.85546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.048044899999695
Peak memory usage during training: 561.15625 MB
Prediction time: 0.9881913999997778
Peak memory usage during prediction: 553.6953125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.9897290999997495
Peak memory usage during training: 561.03515625 MB
Prediction time: 1.0012268999998923
Peak memory usage during prediction: 553.3125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.0140809999993508
Peak memory usage during training: 560.99609375 MB
Prediction time: 1.0230376000008619
Peak memory usage during prediction: 553.65234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.80750050000006
Peak memory usage during training: 555.046875 MB
Prediction time: 1.025462100000368
Peak memory usage during prediction: 549.9609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.6986056999994616
Peak memory usage during training: 551.99609375 MB
Prediction time: 1.020951100000275
Peak memory usage during prediction: 549.80859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.7504570000000967
Peak memory usage during training: 552.265625 MB
Prediction time: 1.0174997000003714
Peak memory usage during prediction: 549.8671875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2543280999998387
Peak memory usage during training: 552.09765625 MB
Prediction time: 1.8118796999997357
Peak memory usage during prediction: 545.3359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.770710799999506
Peak memory usage during training: 551.99609375 MB
Prediction time: 1.8254951999997502
Peak memory usage during prediction: 545.33203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.75081020000016
Peak memory usage during training: 552.00390625 MB
Prediction time: 1.817010100000516
Peak memory usage during prediction: 545.33203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2149981999991724
Peak memory usage during training: 552.10546875 MB
Prediction time: 1.8149992999997266
Peak memory usage during prediction: 545.34765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2645701000001281
Peak memory usage during training: 552.41796875 MB
Prediction time: 1.8147416000001613
Peak memory usage during prediction: 545.14453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.2956960000001345
Peak memory usage during training: 552.19921875 MB
Prediction time: 1.8252542000000176
Peak memory usage during prediction: 545.41796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2003641999999672
Peak memory usage during training: 552.3671875 MB
Prediction time: 1.8008103000001938
Peak memory usage during prediction: 545.34375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2130334000003131
Peak memory usage during training: 552.33203125 MB
Prediction time: 1.8082647000001089
Peak memory usage during prediction: 545.41015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.2441768999997294
Peak memory usage during training: 552.28125 MB
Prediction time: 1.8249266000002535
Peak memory usage during prediction: 545.20703125 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 8.343880499999614
Peak memory usage during training: 545.20703125 MB
Prediction time: 1.0416857000000164
Peak memory usage during prediction: 433.0078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 9.699054200000319
Peak memory usage during training: 437.50390625 MB
Prediction time: 1.0357087000002139
Peak memory usage during prediction: 430.92578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 9.628755900000215
Peak memory usage during training: 437.26953125 MB
Prediction time: 1.0350696000004973
Peak memory usage during prediction: 430.74609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 16.240213400000357
Peak memory usage during training: 486.19140625 MB
Prediction time: 1.124868900000365
Peak memory usage during prediction: 479.390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 18.70768170000065
Peak memory usage during training: 494.68359375 MB
Prediction time: 1.1284077999998772
Peak memory usage during prediction: 487.83984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 19.023321200000282
Peak memory usage during training: 494.81640625 MB
Prediction time: 1.1220745999999053
Peak memory usage during prediction: 487.75390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 23.81502950000049
Peak memory usage during training: 538.0859375 MB
Prediction time: 1.23412400000052
Peak memory usage during prediction: 531.5078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 28.047366100000545
Peak memory usage during training: 549.59375 MB
Prediction time: 1.2326331000003847
Peak memory usage during prediction: 549.67578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 28.037281500000063
Peak memory usage during training: 549.890625 MB
Prediction time: 1.2160971000002974
Peak memory usage during prediction: 549.9921875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 20.171351400000276
Peak memory usage during training: 767.1484375 MB
Prediction time: 1.810866900000292
Peak memory usage during prediction: 564.21875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 25.968915200000083
Peak memory usage during training: 758.59375 MB
Prediction time: 2.2503741999998965
Peak memory usage during prediction: 565.953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 20.84719419999965
Peak memory usage during training: 762.00390625 MB
Prediction time: 1.9294017000001986
Peak memory usage during prediction: 566.6875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 14.77285060000031
Peak memory usage during training: 756.2265625 MB
Prediction time: 1.5220755000000281
Peak memory usage during prediction: 564.6875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 31.52424189999965
Peak memory usage during training: 789.5859375 MB
Prediction time: 2.1009436000003916
Peak memory usage during prediction: 565.3203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.56118669999978
Peak memory usage during training: 729.13671875 MB
Prediction time: 1.533701999999721
Peak memory usage during prediction: 565.2265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 12.526816000000508
Peak memory usage during training: 705.4453125 MB
Prediction time: 1.4712687000001097
Peak memory usage during prediction: 566.203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 33.45455159999983
Peak memory usage during training: 787.31640625 MB
Prediction time: 2.1014753999997993
Peak memory usage during prediction: 566.62109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.398565599999529
Peak memory usage during training: 648.71875 MB
Prediction time: 1.2964279000007082
Peak memory usage during prediction: 566.33203125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.1019310000001497
Peak memory usage during training: 560.8984375 MB
Prediction time: 1.8137887000002593
Peak memory usage during prediction: 549.2578125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.0989097000001493
Peak memory usage during training: 558.125 MB
Prediction time: 1.3700016000002506
Peak memory usage during prediction: 547.4765625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.100760000000264
Peak memory usage during training: 558.6484375 MB
Prediction time: 1.8152952999998888
Peak memory usage during prediction: 546.87109375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9172768999997061
Peak memory usage during training: 579.984375 MB
Prediction time: 1.8257465999995475
Peak memory usage during prediction: 546.5234375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.4637026999998852
Peak memory usage during training: 581.06640625 MB
Prediction time: 1.8284455000002708
Peak memory usage during prediction: 546.34375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 2.1577123000006395
Peak memory usage during training: 579.9921875 MB
Prediction time: 1.8262004000007437
Peak memory usage during prediction: 546.6171875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.102094699999725
Peak memory usage during training: 556.84765625 MB
Prediction time: 0.9847396000004665
Peak memory usage during prediction: 1003.9765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1097841999999218
Peak memory usage during training: 554.90625 MB
Prediction time: 0.9979453999994803
Peak memory usage during prediction: 926.82421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1057424000000537
Peak memory usage during training: 555.14453125 MB
Prediction time: 1.0006622999999308
Peak memory usage during prediction: 1002.10546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1056319999997868
Peak memory usage during training: 554.91015625 MB
Prediction time: 0.991064799999549
Peak memory usage during prediction: 918.93359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1020085000000108
Peak memory usage during training: 555.1328125 MB
Prediction time: 0.981394100000216
Peak memory usage during prediction: 1005.5703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0993794000005437
Peak memory usage during training: 554.80859375 MB
Prediction time: 0.991181499999584
Peak memory usage during prediction: 1006.2734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1138934999999037
Peak memory usage during training: 555.140625 MB
Prediction time: 0.9902387000001909
Peak memory usage during prediction: 992.8203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1101137999994535
Peak memory usage during training: 554.8671875 MB
Prediction time: 0.9928656000001865
Peak memory usage during prediction: 958.82421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.1126462000001993
Peak memory usage during training: 555.05078125 MB
Prediction time: 0.9882519000002503
Peak memory usage during prediction: 997.78515625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8084986000003482
Peak memory usage during training: 554.78125 MB
Prediction time: 1.8213232999996762
Peak memory usage during prediction: 546.890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9177393999998458
Peak memory usage during training: 559.1796875 MB
Prediction time: 1.8170543000005637
Peak memory usage during prediction: 547.79296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 3.4883646999996927
Peak memory usage during training: 557.0234375 MB
Prediction time: 1.8143546999999671
Peak memory usage during prediction: 545.62890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8471838999994361
Peak memory usage during training: 554.765625 MB
Prediction time: 1.8144895999994333
Peak memory usage during prediction: 546.91015625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9785119999996823
Peak memory usage during training: 559.13671875 MB
Prediction time: 1.374028599999292
Peak memory usage during prediction: 547.7890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 5.226744800000233
Peak memory usage during training: 556.9609375 MB
Prediction time: 1.8138593999992736
Peak memory usage during prediction: 545.57421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.8512418000000253
Peak memory usage during training: 554.65625 MB
Prediction time: 1.8300325000000157
Peak memory usage during prediction: 547.12109375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9776870999994571
Peak memory usage during training: 559.33984375 MB
Prediction time: 1.822323200000028
Peak memory usage during prediction: 547.80859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 5.188083799999731
Peak memory usage during training: 557.1640625 MB
Prediction time: 1.8233309000006557
Peak memory usage during prediction: 545.76171875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 26.37069909999991
Peak memory usage during training: 556.48046875 MB
Prediction time: 1.4081621000004816
Peak memory usage during prediction: 552.546875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 26.318871200000103
Peak memory usage during training: 556.078125 MB
Prediction time: 1.8533899000003657
Peak memory usage during prediction: 545.75 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 39.42568469999969
Peak memory usage during training: 556.36328125 MB
Prediction time: 0.9633573999999498
Peak memory usage during prediction: 552.87109375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 39.13191029999962
Peak memory usage during training: 555.64453125 MB
Prediction time: 0.9674609000003329
Peak memory usage during prediction: 545.55078125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 52.364164900000105
Peak memory usage during training: 555.59375 MB
Prediction time: 0.976442500000303
Peak memory usage during prediction: 552.78515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 51.85175059999983
Peak memory usage during training: 555.96875 MB
Prediction time: 0.9879934000000503
Peak memory usage during prediction: 545.8203125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.8097747000001618
Peak memory usage during training: 554.76953125 MB
Prediction time: 1.4022952000004807
Peak memory usage during prediction: 545.55078125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7835068999993382
Peak memory usage during training: 554.6328125 MB
Prediction time: 1.4081952999995337
Peak memory usage during prediction: 545.8125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7834883999994418
Peak memory usage during training: 554.6640625 MB
Prediction time: 0.9713907000004838
Peak memory usage during prediction: 551.88671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0523809999995137
Peak memory usage during training: 554.63671875 MB
Prediction time: 0.9981838000003336
Peak memory usage during prediction: 545.9140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.002954500000669
Peak memory usage during training: 554.6796875 MB
Prediction time: 0.9916688000002978
Peak memory usage during prediction: 545.48046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0197587000002386
Peak memory usage during training: 554.45703125 MB
Prediction time: 0.9857491000002483
Peak memory usage during prediction: 545.58984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.316581199999746
Peak memory usage during training: 554.48828125 MB
Prediction time: 1.0196101999999883
Peak memory usage during prediction: 545.9140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.226830799999334
Peak memory usage during training: 554.50390625 MB
Prediction time: 1.0241975999997521
Peak memory usage during prediction: 546.0234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.2610508999996455
Peak memory usage during training: 554.83984375 MB
Prediction time: 1.02128730000004
Peak memory usage during prediction: 546.02734375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.203983899999912
Peak memory usage during training: 554.5390625 MB
Prediction time: 1.799453700000413
Peak memory usage during prediction: 545.90234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.208017099999779
Peak memory usage during training: 552.38671875 MB
Prediction time: 1.81190609999976
Peak memory usage during prediction: 545.8828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.3390982000000804
Peak memory usage during training: 552.390625 MB
Prediction time: 1.813514600000417
Peak memory usage during prediction: 545.9765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1748539999998684
Peak memory usage during training: 552.390625 MB
Prediction time: 1.81646499999988
Peak memory usage during prediction: 545.7578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2565483999997014
Peak memory usage during training: 552.37890625 MB
Prediction time: 1.810570600000574
Peak memory usage during prediction: 545.9765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.231221099999857
Peak memory usage during training: 552.390625 MB
Prediction time: 1.8060593000000154
Peak memory usage during prediction: 545.8828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.161506599999484
Peak memory usage during training: 552.390625 MB
Prediction time: 1.3904443999999785
Peak memory usage during prediction: 545.9765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.189812599999641
Peak memory usage during training: 552.390625 MB
Prediction time: 1.808513199999652
Peak memory usage during prediction: 545.6875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1919148000006317
Peak memory usage during training: 552.3203125 MB
Prediction time: 1.3742821999994703
Peak memory usage during prediction: 545.90625 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 8.500434800000221
Peak memory usage during training: 545.90625 MB
Prediction time: 1.0251664999996137
Peak memory usage during prediction: 436.0078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 9.596906099999615
Peak memory usage during training: 440.66015625 MB
Prediction time: 1.031699000000117
Peak memory usage during prediction: 434.08203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 9.617607099999987
Peak memory usage during training: 440.15234375 MB
Prediction time: 1.0329727999996976
Peak memory usage during prediction: 440.24609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 16.62180829999943
Peak memory usage during training: 493.3046875 MB
Prediction time: 1.123456399999668
Peak memory usage during prediction: 486.515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 18.609227999999348
Peak memory usage during training: 501.3984375 MB
Prediction time: 1.1216958000004524
Peak memory usage during prediction: 494.1171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 18.57019279999986
Peak memory usage during training: 501.29296875 MB
Prediction time: 1.1228640999997879
Peak memory usage during prediction: 494.02734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 24.514618899999732
Peak memory usage during training: 541.69140625 MB
Prediction time: 1.225248300000203
Peak memory usage during prediction: 534.81640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 27.495524299999488
Peak memory usage during training: 559.44140625 MB
Prediction time: 1.2091320000008636
Peak memory usage during prediction: 552.578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 27.27934229999937
Peak memory usage during training: 558.22265625 MB
Prediction time: 1.2153870000001916
Peak memory usage during prediction: 557.71484375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 16.231620900000053
Peak memory usage during training: 799.6015625 MB
Prediction time: 1.6224044999999023
Peak memory usage during prediction: 572.25 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 26.26045680000061
Peak memory usage during training: 769.1796875 MB
Prediction time: 2.263952999999674
Peak memory usage during prediction: 574.23828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 20.397563999999875
Peak memory usage during training: 768.453125 MB
Prediction time: 1.977137799999582
Peak memory usage during prediction: 574.77734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 10.721728200000143
Peak memory usage during training: 691.578125 MB
Prediction time: 1.4142457999996623
Peak memory usage during prediction: 573.2890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 32.21503510000002
Peak memory usage during training: 794.30078125 MB
Prediction time: 2.0917539000001852
Peak memory usage during prediction: 573.9921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.310132300000078
Peak memory usage during training: 732.109375 MB
Prediction time: 1.5717414999999164
Peak memory usage during prediction: 559.2890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 9.66399790000014
Peak memory usage during training: 674.8046875 MB
Prediction time: 1.3490065000005416
Peak memory usage during prediction: 574.04296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 33.30969279999954
Peak memory usage during training: 793.8359375 MB
Prediction time: 2.1017327999998088
Peak memory usage during prediction: 574.0625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 7.421661299999869
Peak memory usage during training: 653.43359375 MB
Prediction time: 1.2143643999997948
Peak memory usage during prediction: 571.8671875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.0957080999996833
Peak memory usage during training: 571.8125 MB
Prediction time: 1.8215831000006801
Peak memory usage during prediction: 556.93359375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.0983667999998943
Peak memory usage during training: 567.02734375 MB
Prediction time: 1.3766708000002836
Peak memory usage during prediction: 555.484375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.0981788999997661
Peak memory usage during training: 567.8828125 MB
Prediction time: 1.8227919999999358
Peak memory usage during prediction: 555.16015625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0704808999998932
Peak memory usage during training: 588.44140625 MB
Prediction time: 1.8228128000000652
Peak memory usage during prediction: 554.796875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.4545577999997477
Peak memory usage during training: 588.09375 MB
Prediction time: 1.8090806000000157
Peak memory usage during prediction: 553.84375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.5707122000003437
Peak memory usage during training: 587.05859375 MB
Prediction time: 1.8096365000001242
Peak memory usage during prediction: 553.8359375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0872671999995873
Peak memory usage during training: 564.8046875 MB
Prediction time: 1.0264188000001013
Peak memory usage during prediction: 1013.33203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0935343999999532
Peak memory usage during training: 562.48046875 MB
Prediction time: 1.0169452999998612
Peak memory usage during prediction: 937.50390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.1040524000000005
Peak memory usage during training: 563.2734375 MB
Prediction time: 1.0266123000001244
Peak memory usage during prediction: 1017.1796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1113954000002195
Peak memory usage during training: 562.59375 MB
Prediction time: 1.0158074000000852
Peak memory usage during prediction: 1015.13671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1032343999995646
Peak memory usage during training: 563.2109375 MB
Prediction time: 1.0151011999996626
Peak memory usage during prediction: 1004.73046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0898126000001866
Peak memory usage during training: 562.609375 MB
Prediction time: 1.0206226000000242
Peak memory usage during prediction: 1002.73828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1034450000006473
Peak memory usage during training: 563.2890625 MB
Prediction time: 1.018518399999266
Peak memory usage during prediction: 1014.8515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.1062817000001814
Peak memory usage during training: 562.54296875 MB
Prediction time: 1.0323508000001311
Peak memory usage during prediction: 1010.3125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0892490000005637
Peak memory usage during training: 563.41796875 MB
Prediction time: 1.030975199999375
Peak memory usage during prediction: 992.9765625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8057726999995793
Peak memory usage during training: 562.140625 MB
Prediction time: 1.830939500000568
Peak memory usage during prediction: 554.09375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0025487000002613
Peak memory usage during training: 567.0078125 MB
Prediction time: 1.8189994000003935
Peak memory usage during prediction: 555.2265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.1157204000001
Peak memory usage during training: 564.5078125 MB
Prediction time: 1.807915000000321
Peak memory usage during prediction: 553.0 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8125286000004053
Peak memory usage during training: 562.4296875 MB
Prediction time: 1.8065182000000277
Peak memory usage during prediction: 554.38671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0388589000003776
Peak memory usage during training: 567.43359375 MB
Prediction time: 1.8363525999993726
Peak memory usage during prediction: 555.55078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.371730600000774
Peak memory usage during training: 564.54296875 MB
Prediction time: 1.8264296000006652
Peak memory usage during prediction: 553.09375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8350431999997454
Peak memory usage during training: 562.33984375 MB
Prediction time: 1.8112281999992774
Peak memory usage during prediction: 554.484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0305055999997421
Peak memory usage during training: 567.02734375 MB
Prediction time: 1.8350542999996833
Peak memory usage during prediction: 555.1640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.3863054000003103
Peak memory usage during training: 564.99609375 MB
Prediction time: 1.826418399999966
Peak memory usage during prediction: 553.00390625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 12.529838100000234
Peak memory usage during training: 563.9140625 MB
Prediction time: 1.4066262000005736
Peak memory usage during prediction: 552.796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 12.586193999999523
Peak memory usage during training: 562.84375 MB
Prediction time: 1.4115643999994063
Peak memory usage during prediction: 552.7578125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 18.602502199999435
Peak memory usage during training: 562.8359375 MB
Prediction time: 1.4367761000003156
Peak memory usage during prediction: 552.98828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.519332799999574
Peak memory usage during training: 563.07421875 MB
Prediction time: 0.9665673999998035
Peak memory usage during prediction: 552.71484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 24.45634229999996
Peak memory usage during training: 562.95703125 MB
Prediction time: 0.9872322999999597
Peak memory usage during prediction: 560.11328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 24.481456600000456
Peak memory usage during training: 562.6953125 MB
Prediction time: 0.9862984000001234
Peak memory usage during prediction: 552.71484375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2946017000003849
Peak memory usage during training: 562.03125 MB
Prediction time: 0.965885900000103
Peak memory usage during prediction: 552.99609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2790800999991916
Peak memory usage during training: 562.2578125 MB
Prediction time: 1.409063199999764
Peak memory usage during prediction: 553.3671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2938544999997248
Peak memory usage during training: 562.171875 MB
Prediction time: 1.4150484000001597
Peak memory usage during prediction: 553.609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.045438000000104
Peak memory usage during training: 562.3671875 MB
Prediction time: 0.9933338000000731
Peak memory usage during prediction: 553.73828125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.9953353000000789
Peak memory usage during training: 562.3125 MB
Prediction time: 0.9971024000005855
Peak memory usage during prediction: 553.1484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.017056099999536
Peak memory usage during training: 562.31640625 MB
Prediction time: 0.992221999999856
Peak memory usage during prediction: 553.171875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.7897093000001405
Peak memory usage during training: 562.296875 MB
Prediction time: 1.0139784000002692
Peak memory usage during prediction: 559.16015625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.690187100000003
Peak memory usage during training: 561.9609375 MB
Prediction time: 1.011452200000349
Peak memory usage during prediction: 559.33984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.7604157000005216
Peak memory usage during training: 561.9921875 MB
Prediction time: 1.0172093000001041
Peak memory usage during prediction: 558.92578125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2712901999993846
Peak memory usage during training: 562.27734375 MB
Prediction time: 1.8133518000004187
Peak memory usage during prediction: 553.91796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.7642344000005323
Peak memory usage during training: 562.11328125 MB
Prediction time: 1.7975145000000339
Peak memory usage during prediction: 553.6640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.768912000000455
Peak memory usage during training: 561.734375 MB
Prediction time: 1.8172566000002917
Peak memory usage during prediction: 553.92578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2139536000004227
Peak memory usage during training: 562.2109375 MB
Prediction time: 1.8302284999999756
Peak memory usage during prediction: 553.8359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2501777000006769
Peak memory usage during training: 562.1875 MB
Prediction time: 1.815798700000414
Peak memory usage during prediction: 553.87109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.3101145000000542
Peak memory usage during training: 562.1953125 MB
Prediction time: 1.3849623999994947
Peak memory usage during prediction: 553.8203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1787839999997232
Peak memory usage during training: 562.15234375 MB
Prediction time: 1.818279000000075
Peak memory usage during prediction: 554.0390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2093780999994124
Peak memory usage during training: 562.30078125 MB
Prediction time: 1.8205261999992217
Peak memory usage during prediction: 553.8203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.2372015000000829
Peak memory usage during training: 562.140625 MB
Prediction time: 1.8128818000004685
Peak memory usage during prediction: 553.80078125 MB
----------------------------------------------------------------------------------------------------

# Process results

In [11]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seed                    396 non-null    object
 1   vectorizer              396 non-null    object
 2   model                   396 non-null    object
 3   params                  396 non-null    object
 4   accuracy                396 non-null    float64
 5   training_time           396 non-null    float64
 6   prediction_time         396 non-null    float64
 7   peak_memory_train       396 non-null    float64
 8   peak_memory_prediction  396 non-null    float64
 9   precision_class_0       396 non-null    float64
 10  recall_class_0          396 non-null    float64
 11  f1_class_0              396 non-null    float64
 12  precision_class_1       396 non-null    float64
 13  recall_class_1          396 non-null    float64
 14  f1_class_1              396 non-null    float64
 15  precision_class_2       396 non-null    float64
 16  recall_class_2          396 non-null    float64
 17  f1_class_2              396 non-null    float64
 18  precision_class_3       396 non-null    float64
 19  recall_class_3          396 non-null    float64
 20  f1_class_3              396 non-null    float64
 21  precision_class_4       396 non-null    float64
 22  recall_class_4          396 non-null    float64
 23  f1_class_4              396 non-null    float64
 24  precision_class_5       396 non-null    float64
 25  recall_class_5          396 non-null    float64
 26  f1_class_5              396 non-null    float64
dtypes: float64(23), object(4)
memory usage: 83.7+ KB

In [12]:
results.head()

,seed,vectorizer,model,params,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,...,f1_class_2,precision_class_3,recall_class_3,f1_class_3,precision_class_4,recall_class_4,f1_class_4,precision_class_5,recall_class_5,f1_class_5
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.890,8.392934,1.065591,423.027344,415.863281,0.908273,...,0.817647,0.896947,0.854545,0.875233,0.839450,0.863208,0.851163,0.911765,0.765432,0.832215
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.884,9.704741,1.033835,425.371094,425.496094,0.911602,...,0.814815,0.894737,0.865455,0.879852,0.823529,0.858491,0.840647,0.887324,0.777778,0.828947
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.884,9.689866,1.034000,425.507812,425.648438,0.911602,...,0.814815,0.894737,0.865455,0.879852,0.823529,0.858491,0.840647,0.887324,0.777778,0.828947
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.890,15.988386,1.138879,475.718750,469.410156,0.909747,...,0.810496,0.904580,0.861818,0.882682,0.836364,0.867925,0.851852,0.897059,0.753086,0.818792
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.886,18.734822,1.136784,483.570312,476.863281,0.918819,...,0.812680,0.890977,0.861818,0.876155,0.814159,0.867925,0.840183,0.910448,0.753086,0.824324

In [13]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,...,precision_class_3,recall_class_3,f1_class_3,precision_class_4,recall_class_4,f1_class_4,precision_class_5,recall_class_5,f1_class_5,f1_avg
0,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.01}",3.333333,0.3515,2.161124,1.074813,562.247396,554.589844,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.004717,0.009390,0.000000,0.000000,0.000000,0.089074
1,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.1}",3.333333,0.3600,2.058383,1.022473,562.220052,554.221354,0.000000,...,0.000000,0.000000,0.000000,0.439024,0.084906,0.142292,0.500000,0.012346,0.024096,0.116544
2,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 1.0}",3.333333,0.3685,2.047303,1.013030,562.179688,554.363281,0.000000,...,0.285714,0.007273,0.014184,0.483333,0.136792,0.213235,0.800000,0.197531,0.316832,0.220409
3,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.01}",3.333333,0.3515,2.833372,1.030625,560.151042,556.955729,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.004717,0.009390,0.000000,0.000000,0.000000,0.089074
4,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.1}",3.333333,0.3600,2.741074,1.027341,559.048177,556.981771,0.000000,...,0.000000,0.000000,0.000000,0.425000,0.080189,0.134921,0.500000,0.024691,0.047059,0.119177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'rbf'}",3.333333,0.8605,31.526554,2.100625,789.079427,565.692708,0.865772,...,0.915612,0.789091,0.847656,0.855615,0.754717,0.802005,0.944444,0.629630,0.755556,0.816410
128,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'sigmoid'}",3.333333,0.8895,14.556889,1.533473,729.212240,565.088542,0.895470,...,0.906716,0.883636,0.895028,0.815166,0.811321,0.813239,0.907692,0.728395,0.808219,0.857992
129,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'linear'}",3.333333,0.8710,12.516618,1.472892,705.811198,566.057292,0.871528,...,0.897727,0.861818,0.879406,0.831683,0.792453,0.811594,0.833333,0.802469,0.817610,0.843550
130,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'rbf'}",3.333333,0.8690,33.440879,2.098567,787.036458,566.333333,0.872881,...,0.917355,0.807273,0.858801,0.859296,0.806604,0.832117,0.894737,0.629630,0.739130,0.825004
131,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'sigmoid'}",3.333333,0.8520,14.391238,1.296973,648.677083,566.210938,0.832237,...,0.886719,0.825455,0.854991,0.824742,0.754717,0.788177,0.813333,0.753086,0.782051,0.821344

In [14]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train['label'])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test['label'], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test['label'], y_pred, average=None, labels=classes, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: SGD
Best model params: {'alpha': 0.0001, 'penalty': 'l1'}
Best vectorizer: TfidfVectorizer
Best accuracy: 0.9005

Class 0
Precision: 0.9426086956521739
Recall: 0.9328743545611016
F1: 0.9377162629757786
Support: 581

Class 1
Precision: 0.8955223880597015
Recall: 0.9496402877697842
F1: 0.9217877094972067
Support: 695

Class 2
Precision: 0.8394160583941606
Recall: 0.7232704402515723
F1: 0.777027027027027
Support: 159

Class 3
Precision: 0.8920863309352518
Recall: 0.9018181818181819
F1: 0.8969258589511754
Support: 275

Class 4
Precision: 0.8766519823788547
Recall: 0.8883928571428571
F1: 0.8824833702882483
Support: 224

Class 5
Precision: 0.8043478260869565
Recall: 0.5606060606060606
F1: 0.6607142857142857
Support: 66

In [15]:
with open('models/best_model_sklearn_multiclass3.pkl', 'wb') as f:
    pickle.dump(pipeline, f)