# Importing libraries

In [3]:
# Basic libraries
import pandas as pd
import numpy as np
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.multioutput import MultiOutputClassifier

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, hamming_loss
from memory_profiler import memory_usage


# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [4]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [5]:
ds = load_dataset("TimSchopf/arxiv_categories", "default")

train = ds['train'].to_pandas()
test = ds['test'].to_pandas() 
val = ds['validation'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163168 entries, 0 to 163167
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             163168 non-null  object
 1   title          163168 non-null  object
 2   abstract       163168 non-null  object
 3   categories     163168 non-null  object
 4   creation_date  163168 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), object(4)
memory usage: 6.2+ MB

# Dataset preprocessing

In [6]:
allowed_categories = ["cs.AI", "cs.CL", "stat.ML", "math.OC", "cs.LG"]

def clean_element(lst):
    final = []
    for elem in lst:
        clean = elem.split('->')[-1]
        final.append(clean)
    return final

train['categories'] = train['categories'].apply(clean_element)
test['categories'] = test['categories'].apply(clean_element)
val['categories'] = val['categories'].apply(clean_element)

In [7]:
train = train[train['categories'].apply(lambda cats: all(c in allowed_categories for c in cats))]
test = test[test['categories'].apply(lambda cats: all(c in allowed_categories for c in cats))]
val = val[val['categories'].apply(lambda cats: all(c in allowed_categories for c in cats))]

In [8]:
train.rename(columns={'categories': 'labels'}, inplace=True)
test.rename(columns={'categories': 'labels'}, inplace=True)
val.rename(columns={'categories': 'labels'}, inplace=True)

train.rename(columns={'title': 'text'}, inplace=True)
test.rename(columns={'title': 'text'}, inplace=True)
val.rename(columns={'title': 'text'}, inplace=True)

train.drop(columns=['id', 'abstract', 'creation_date'], inplace=True)
test.drop(columns=['id', 'abstract', 'creation_date'], inplace=True)
val.drop(columns=['id', 'abstract', 'creation_date'], inplace=True)

train.reset_index(drop=True, inplace=True)
test.reset_index(drop=True, inplace=True)
val.reset_index(drop=True, inplace=True)

train

,text,labels
0,Upper and Lower Bounds for Large Scale Multist...,[math.OC]
1,Binary Classification: Counterbalancing Class ...,[cs.LG]
2,Smooth Optimization with Approximate Gradient,[math.OC]
3,An AI-powered Smart Routing Solution for Payme...,[cs.AI]
4,A linearly convergent method for solving high-...,[math.OC]
...,...,...
10141,Simple Question Answering with Subgraph Rankin...,"[cs.CL, cs.LG, stat.ML]"
10142,"Fire Now, Fire Later: Alarm-Based Systems for ...","[cs.AI, cs.LG, stat.ML]"
10143,NSP-BERT: A Prompt-based Few-Shot Learner Thro...,"[cs.AI, cs.CL]"
10144,Near-optimal bounds for phase synchronization,[math.OC]
10145,Rapid Convergence of First-Order Numerical Alg...,[math.OC]

In [9]:
mlb = MultiLabelBinarizer()

train_labels_binarized = mlb.fit_transform(train['labels'])
val_labels_binarized = mlb.transform(val['labels'])
test_labels_binarized = mlb.transform(test['labels'])

train_labels_df = pd.DataFrame(train_labels_binarized, columns=mlb.classes_)
val_labels_df = pd.DataFrame(val_labels_binarized, columns=mlb.classes_)
test_labels_df = pd.DataFrame(test_labels_binarized, columns=mlb.classes_)

train = pd.concat([train, train_labels_df], axis=1)
val = pd.concat([val, val_labels_df], axis=1)
test = pd.concat([test, test_labels_df], axis=1)

train = train.drop(columns=['labels'])
val = val.drop(columns=['labels'])
test = test.drop(columns=['labels'])

train

,text,cs.AI,cs.CL,cs.LG,math.OC,stat.ML
0,Upper and Lower Bounds for Large Scale Multist...,0,0,0,1,0
1,Binary Classification: Counterbalancing Class ...,0,0,1,0,0
2,Smooth Optimization with Approximate Gradient,0,0,0,1,0
3,An AI-powered Smart Routing Solution for Payme...,1,0,0,0,0
4,A linearly convergent method for solving high-...,0,0,0,1,0
...,...,...,...,...,...,...
10141,Simple Question Answering with Subgraph Rankin...,0,1,1,0,1
10142,"Fire Now, Fire Later: Alarm-Based Systems for ...",1,0,1,0,1
10143,NSP-BERT: A Prompt-based Few-Shot Learner Thro...,1,1,0,0,0
10144,Near-optimal bounds for phase synchronization,0,0,0,1,0
10145,Rapid Convergence of First-Order Numerical Alg...,0,0,0,1,0

In [10]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [11]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': MultiOutputClassifier(SVC()),
        'params': {
            'estimator__C': [0.1, 1, 10],
            'estimator__kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultiOutputClassifier(MultinomialNB()),
        'params': {
            'estimator__alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': MultiOutputClassifier(LogisticRegression(max_iter=1000)),
        'params': {
            'estimator__C': [0.1, 1, 10],
            'estimator__penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': MultiOutputClassifier(GradientBoostingClassifier()),
        'params': {
            'estimator__n_estimators': [100, 150, 200],
            'estimator__criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': MultiOutputClassifier(AdaBoostClassifier()),
        'params': {
            'estimator__n_estimators': [50, 100, 150],
            'estimator__learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': MultiOutputClassifier(SGDClassifier()),
        'params': {
            'estimator__alpha': [0.0001, 0.001, 0.01],
            'estimator__penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [12]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'hamming_loss', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = list(train.columns[1:])
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [13]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train[classes])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                val_classes = val.drop(columns=['text'])

                accuracy = accuracy_score(val_classes, y_pred)
                
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val_classes.to_numpy(), y_pred, average=None, zero_division=0)

                hamm_loss = hamming_loss(val_classes.to_numpy(), y_pred)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'hamming_loss': hamm_loss,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_multilabel3.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 8.043998300003295
Peak memory usage during training: 760.36328125 MB
Prediction time: 1.023780200004694
Peak memory usage during prediction: 752.94140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_21216\2813873047.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 8.664699100001599
Peak memory usage during training: 759.37890625 MB
Prediction time: 0.9895920999988448
Peak memory usage during prediction: 752.8125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 8.462641300000541
Peak memory usage during training: 759.15234375 MB
Prediction time: 0.9926725999976043
Peak memory usage during prediction: 759.33984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 15.037505100000999
Peak memory usage during training: 839.24609375 MB
Prediction time: 1.0487372999996296
Peak memory usage during prediction: 831.6328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 16.582599599998503
Peak memory usage during training: 838.86328125 MB
Prediction time: 1.0448737999977311
Peak memory usage during prediction: 831.26171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 16.460802599998715
Peak memory usage during training: 837.8515625 MB
Prediction time: 1.0468576999992365
Peak memory usage during prediction: 831.328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 22.40077509999537
Peak memory usage during training: 917.03515625 MB
Prediction time: 1.1083480000015697
Peak memory usage during prediction: 909.83203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 24.98580289999518
Peak memory usage during training: 916.43359375 MB
Prediction time: 1.2281691999960458
Peak memory usage during prediction: 909.9296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 29.89202440000372
Peak memory usage during training: 916.5546875 MB
Prediction time: 4.107356399996206
Peak memory usage during prediction: 909.953125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 14.736490299997968
Peak memory usage during training: 1125.99609375 MB
Prediction time: 1.7073128999982146
Peak memory usage during prediction: 935.8671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 19.45556729999953
Peak memory usage during training: 1150.68359375 MB
Prediction time: 2.4964949000059278
Peak memory usage during prediction: 938.484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.63026230000105
Peak memory usage during training: 1132.94921875 MB
Prediction time: 1.7355785000036121
Peak memory usage during prediction: 925.96875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 13.356228600001486
Peak memory usage during training: 1138.64453125 MB
Prediction time: 1.5068077000032645
Peak memory usage during prediction: 926.12890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 21.908839999996417
Peak memory usage during training: 1159.87109375 MB
Prediction time: 2.3950549000001047
Peak memory usage during prediction: 928.6015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 12.971752899997227
Peak memory usage during training: 1124.0546875 MB
Prediction time: 1.5101390999989235
Peak memory usage during prediction: 926.921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 17.36695420000615
Peak memory usage during training: 1166.46484375 MB
Prediction time: 1.3838079999986803
Peak memory usage during prediction: 926.16015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 47.648407799999404
Peak memory usage during training: 1156.38671875 MB
Prediction time: 2.5404963999972097
Peak memory usage during prediction: 929.5 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 20.97910740000225
Peak memory usage during training: 1153.48046875 MB
Prediction time: 1.2411692000023322
Peak memory usage during prediction: 927.87890625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.0381435000017518
Peak memory usage during training: 915.35546875 MB
Prediction time: 1.8267906999972183
Peak memory usage during prediction: 907.25390625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.0419832999978098
Peak memory usage during training: 914.00390625 MB
Prediction time: 1.7991286999967997
Peak memory usage during prediction: 906.94140625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.0404280000002473
Peak memory usage during training: 913.421875 MB
Prediction time: 1.8071443000008003
Peak memory usage during prediction: 906.8671875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.279986800000188
Peak memory usage during training: 915.359375 MB
Prediction time: 1.7937144000025
Peak memory usage during prediction: 907.73046875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.793711300000723
Peak memory usage during training: 915.0625 MB
Prediction time: 1.7931689999968512
Peak memory usage during prediction: 907.71484375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9537053999956697
Peak memory usage during training: 915.19921875 MB
Prediction time: 1.805231600003026
Peak memory usage during prediction: 908.23828125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0406673000034061
Peak memory usage during training: 914.46484375 MB
Prediction time: 1.2382078000009642
Peak memory usage during prediction: 1110.98046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0230195999974967
Peak memory usage during training: 914.53515625 MB
Prediction time: 1.2322499000001699
Peak memory usage during prediction: 1100.68359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.02708249999705
Peak memory usage during training: 914.57421875 MB
Prediction time: 1.2316949000014574
Peak memory usage during prediction: 1101.73828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0308021000018925
Peak memory usage during training: 914.6015625 MB
Prediction time: 1.2440566000004765
Peak memory usage during prediction: 1090.8984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0395306999998866
Peak memory usage during training: 914.61328125 MB
Prediction time: 1.2304631000006339
Peak memory usage during prediction: 1106.8359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0267890999966767
Peak memory usage during training: 914.37109375 MB
Prediction time: 1.2345776000001933
Peak memory usage during prediction: 1100.58203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0290806999983033
Peak memory usage during training: 914.38671875 MB
Prediction time: 1.233646900000167
Peak memory usage during prediction: 1108.125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.026200100001006
Peak memory usage during training: 914.546875 MB
Prediction time: 1.2335872000039672
Peak memory usage during prediction: 1106.83984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0320587000023806
Peak memory usage during training: 914.484375 MB
Prediction time: 1.2409076999974786
Peak memory usage during prediction: 1111.5234375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7471224999972037
Peak memory usage during training: 921.84765625 MB
Prediction time: 1.785100399996736
Peak memory usage during prediction: 912.01171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7971773000026587
Peak memory usage during training: 921.859375 MB
Prediction time: 1.7842709999968065
Peak memory usage during prediction: 912.171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.9197513000035542
Peak memory usage during training: 917.93359375 MB
Prediction time: 1.7971881000048597
Peak memory usage during prediction: 911.0234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7654309999998077
Peak memory usage during training: 922.078125 MB
Prediction time: 1.809849800003576
Peak memory usage during prediction: 912.08203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.8031974999976228
Peak memory usage during training: 921.921875 MB
Prediction time: 1.7844116000051145
Peak memory usage during prediction: 912.16796875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.646727799998189
Peak memory usage during training: 917.078125 MB
Prediction time: 1.802669100005005
Peak memory usage during prediction: 910.97265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7661874999976135
Peak memory usage during training: 922.04296875 MB
Prediction time: 1.805154900001071
Peak memory usage during prediction: 912.03515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.8061379000064335
Peak memory usage during training: 921.85546875 MB
Prediction time: 1.8031437000026926
Peak memory usage during prediction: 912.16796875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.6299220000000787
Peak memory usage during training: 917.23046875 MB
Prediction time: 1.797922199999448
Peak memory usage during prediction: 910.9609375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 11.643333899999561
Peak memory usage during training: 916.30859375 MB
Prediction time: 1.8129165999998804
Peak memory usage during prediction: 912.3828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 11.636236699996516
Peak memory usage during training: 917.1953125 MB
Prediction time: 1.8422459000066738
Peak memory usage during prediction: 913.0234375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 17.137269600003492
Peak memory usage during training: 917.609375 MB
Prediction time: 1.822668499997235
Peak memory usage during prediction: 913.2734375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 17.081098399998154
Peak memory usage during training: 917.76171875 MB
Prediction time: 1.8324861000000965
Peak memory usage during prediction: 913.4453125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 22.686168799998995
Peak memory usage during training: 917.98046875 MB
Prediction time: 1.3979015000004438
Peak memory usage during prediction: 916.46484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 22.737143799997284
Peak memory usage during training: 918.20703125 MB
Prediction time: 1.8541694000014104
Peak memory usage during prediction: 913.87890625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.322620499995537
Peak memory usage during training: 918.69921875 MB
Prediction time: 1.0108441000047605
Peak memory usage during prediction: 916.93359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.279569400001492
Peak memory usage during training: 918.76171875 MB
Prediction time: 1.0038281000015559
Peak memory usage during prediction: 917.05859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.296344300004421
Peak memory usage during training: 918.828125 MB
Prediction time: 1.0276670000021113
Peak memory usage during prediction: 917.19921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.049081299999671
Peak memory usage during training: 918.9375 MB
Prediction time: 1.1072732000029646
Peak memory usage during prediction: 917.56640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.057404899998801
Peak memory usage during training: 919.1796875 MB
Prediction time: 1.1024296999967191
Peak memory usage during prediction: 917.640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.01215570000204
Peak memory usage during training: 919.09375 MB
Prediction time: 1.1004285000017262
Peak memory usage during prediction: 917.5625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.960134900000412
Peak memory usage during training: 919.38671875 MB
Prediction time: 1.254363200001535
Peak memory usage during prediction: 917.890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.067945400005556
Peak memory usage during training: 919.2578125 MB
Prediction time: 1.2410123000008753
Peak memory usage during prediction: 918.21484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.983789100006106
Peak memory usage during training: 919.1640625 MB
Prediction time: 1.190374099998735
Peak memory usage during prediction: 918.15234375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1546376999976928
Peak memory usage during training: 919.125 MB
Prediction time: 1.8317057000022032
Peak memory usage during prediction: 915.34765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1472334999998566
Peak memory usage during training: 919.28125 MB
Prediction time: 1.8211674999984098
Peak memory usage during prediction: 915.4140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.3129944000029354
Peak memory usage during training: 919.5078125 MB
Prediction time: 1.825940399998217
Peak memory usage during prediction: 915.48046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.093340299994452
Peak memory usage during training: 919.5546875 MB
Prediction time: 1.8391644000002998
Peak memory usage during prediction: 915.46484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1104759000008926
Peak memory usage during training: 919.5546875 MB
Prediction time: 1.8261091999956989
Peak memory usage during prediction: 915.46484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.148720699995465
Peak memory usage during training: 919.640625 MB
Prediction time: 1.8437827000016114
Peak memory usage during prediction: 915.453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0849992000003112
Peak memory usage during training: 919.54296875 MB
Prediction time: 1.8150490999978501
Peak memory usage during prediction: 915.4765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.0963541000019177
Peak memory usage during training: 919.5703125 MB
Prediction time: 1.836786799998663
Peak memory usage during prediction: 915.48046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.087452799998573
Peak memory usage during training: 919.69140625 MB
Prediction time: 1.8061311000055866
Peak memory usage during prediction: 915.5390625 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 8.807458000002953
Peak memory usage during training: 915.54296875 MB
Prediction time: 0.9986662000010256
Peak memory usage during prediction: 769.234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 9.105206300002465
Peak memory usage during training: 774.75390625 MB
Prediction time: 0.9878561999939848
Peak memory usage during prediction: 774.859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 9.17839219999587
Peak memory usage during training: 774.5625 MB
Prediction time: 0.9865349999963655
Peak memory usage during prediction: 774.7421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 16.997580800001742
Peak memory usage during training: 859.6171875 MB
Prediction time: 1.0545171000048867
Peak memory usage during prediction: 855.81640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 17.743434699994395
Peak memory usage during training: 857.66796875 MB
Prediction time: 1.0580622000052244
Peak memory usage during prediction: 856.91796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 17.807002100002137
Peak memory usage during training: 857.60546875 MB
Prediction time: 1.0479828000025009
Peak memory usage during prediction: 856.91796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 25.504259100001946
Peak memory usage during training: 941.09375 MB
Prediction time: 1.1110728000057861
Peak memory usage during prediction: 935.19921875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 26.534037099998386
Peak memory usage during training: 941.109375 MB
Prediction time: 1.0936607999974512
Peak memory usage during prediction: 941.2734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 27.01987899999949
Peak memory usage during training: 940.515625 MB
Prediction time: 1.103552900000068
Peak memory usage during prediction: 940.7109375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 12.324515100001008
Peak memory usage during training: 1157.2421875 MB
Prediction time: 1.4738670000006096
Peak memory usage during prediction: 959.09375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 17.450279199998477
Peak memory usage during training: 1166.72265625 MB
Prediction time: 2.3579163999966113
Peak memory usage during prediction: 960.5703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.63646819999849
Peak memory usage during training: 1155.578125 MB
Prediction time: 1.6234512999944855
Peak memory usage during prediction: 959.8359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 16.632466900002328
Peak memory usage during training: 1191.5546875 MB
Prediction time: 1.3690745000058087
Peak memory usage during prediction: 958.40234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 20.07024939999974
Peak memory usage during training: 1187.28515625 MB
Prediction time: 2.277165999999852
Peak memory usage during prediction: 960.57421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.16116730000067
Peak memory usage during training: 1160.9609375 MB
Prediction time: 1.4213216999996803
Peak memory usage during prediction: 959.8203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 28.84980440000072
Peak memory usage during training: 1174.5859375 MB
Prediction time: 1.2512323000046308
Peak memory usage during prediction: 958.1328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 44.640269499999704
Peak memory usage during training: 1178.5390625 MB
Prediction time: 2.4287657999957446
Peak memory usage during prediction: 960.6875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 14.287979699998687
Peak memory usage during training: 1163.18359375 MB
Prediction time: 1.1453210000036051
Peak memory usage during prediction: 959.71484375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.0253591000000597
Peak memory usage during training: 944.7109375 MB
Prediction time: 1.792615600003046
Peak memory usage during prediction: 936.4375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.0328095000004396
Peak memory usage during training: 942.9609375 MB
Prediction time: 1.7932966000007582
Peak memory usage during prediction: 936.45703125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.0322069000030751
Peak memory usage during training: 943.0234375 MB
Prediction time: 1.795193999998446
Peak memory usage during prediction: 935.921875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3847008000011556
Peak memory usage during training: 944.3515625 MB
Prediction time: 1.803271800003131
Peak memory usage during prediction: 936.05859375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8546623000002
Peak memory usage during training: 943.7109375 MB
Prediction time: 1.7878426000024774
Peak memory usage during prediction: 936.046875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0880353000029572
Peak memory usage during training: 943.69140625 MB
Prediction time: 1.786168999999063
Peak memory usage during prediction: 936.06640625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0232011000043713
Peak memory usage during training: 942.3046875 MB
Prediction time: 0.7522363000025507
Peak memory usage during prediction: 1049.2109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0230639000001247
Peak memory usage during training: 946.7265625 MB
Prediction time: 0.743512399996689
Peak memory usage during prediction: 1053.08984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0299882999970578
Peak memory usage during training: 941.65234375 MB
Prediction time: 0.7494999999980791
Peak memory usage during prediction: 1062.34375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0211703999957535
Peak memory usage during training: 946.890625 MB
Prediction time: 0.7505654999986291
Peak memory usage during prediction: 1044.890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.009236999998393
Peak memory usage during training: 942.01953125 MB
Prediction time: 0.7507011000052444
Peak memory usage during prediction: 1040.0234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0210103999997955
Peak memory usage during training: 946.85546875 MB
Prediction time: 0.7473708000034094
Peak memory usage during prediction: 1074.41015625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.025982400002249
Peak memory usage during training: 941.7890625 MB
Prediction time: 0.7581459000066388
Peak memory usage during prediction: 1058.76953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.027137799996126
Peak memory usage during training: 946.8671875 MB
Prediction time: 0.7514878000001772
Peak memory usage during prediction: 1050.453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.013960100004624
Peak memory usage during training: 941.796875 MB
Prediction time: 0.7434748000014224
Peak memory usage during prediction: 1043.45703125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7730987999966601
Peak memory usage during training: 949.61328125 MB
Prediction time: 1.7974214999994729
Peak memory usage during prediction: 937.1875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8515554999976302
Peak memory usage during training: 947.984375 MB
Prediction time: 1.7911583999957656
Peak memory usage during prediction: 937.4296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.799257899998338
Peak memory usage during training: 943.8671875 MB
Prediction time: 1.7936909999989439
Peak memory usage during prediction: 936.2421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7872149000031641
Peak memory usage during training: 948.0078125 MB
Prediction time: 1.7906942999979947
Peak memory usage during prediction: 937.3203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8452623999983189
Peak memory usage during training: 948.02734375 MB
Prediction time: 1.791107999997621
Peak memory usage during prediction: 937.46484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.0838761999984854
Peak memory usage during training: 943.9609375 MB
Prediction time: 1.7919793999972171
Peak memory usage during prediction: 936.3515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7887181999976747
Peak memory usage during training: 948.0390625 MB
Prediction time: 1.7921496999988449
Peak memory usage during prediction: 937.2265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8555503000025055
Peak memory usage during training: 947.9140625 MB
Prediction time: 1.7912035000044852
Peak memory usage during prediction: 937.3515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.082615100000112
Peak memory usage during training: 943.83203125 MB
Prediction time: 1.7971622999975807
Peak memory usage during prediction: 936.2265625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 6.973541799998202
Peak memory usage during training: 942.171875 MB
Prediction time: 1.8085770000034245
Peak memory usage during prediction: 935.859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 6.9352665999977035
Peak memory usage during training: 942.03515625 MB
Prediction time: 1.8229483000031905
Peak memory usage during prediction: 935.921875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 10.097587399999611
Peak memory usage during training: 941.78125 MB
Prediction time: 1.8184879000036744
Peak memory usage during prediction: 935.94140625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 10.09434269999474
Peak memory usage during training: 942.1328125 MB
Prediction time: 1.8214726000005612
Peak memory usage during prediction: 936.2109375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 13.189820999999938
Peak memory usage during training: 942.06640625 MB
Prediction time: 1.8429980000000796
Peak memory usage during prediction: 923.8828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 13.194294500004617
Peak memory usage during training: 929.71484375 MB
Prediction time: 1.3864984000028926
Peak memory usage during prediction: 927.0390625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.3011740000001737
Peak memory usage during training: 929.7109375 MB
Prediction time: 0.9940675000034389
Peak memory usage during prediction: 927.02734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2734299000003375
Peak memory usage during training: 928.96484375 MB
Prediction time: 0.997227899999416
Peak memory usage during prediction: 926.35546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2619858000034583
Peak memory usage during training: 928.7265625 MB
Prediction time: 0.9921198000010918
Peak memory usage during prediction: 926.25 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.066074099995603
Peak memory usage during training: 928.86328125 MB
Prediction time: 1.0913459000003058
Peak memory usage during prediction: 926.2578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.059437100004288
Peak memory usage during training: 928.80078125 MB
Prediction time: 1.0888163000054192
Peak memory usage during prediction: 926.3671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.027886399999261
Peak memory usage during training: 929.16796875 MB
Prediction time: 1.086601700000756
Peak memory usage during prediction: 926.32421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.818564699999115
Peak memory usage during training: 928.796875 MB
Prediction time: 1.1825332999942475
Peak memory usage during prediction: 926.55078125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.818102799996268
Peak memory usage during training: 929.4453125 MB
Prediction time: 1.1802601999952458
Peak memory usage during prediction: 926.703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.797990099999879
Peak memory usage during training: 929.13671875 MB
Prediction time: 1.1805483999996795
Peak memory usage during prediction: 927.01171875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2052810000022873
Peak memory usage during training: 928.484375 MB
Prediction time: 1.7917283999995561
Peak memory usage during prediction: 923.9375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.6963859000024968
Peak memory usage during training: 928.578125 MB
Prediction time: 1.7882823999971151
Peak memory usage during prediction: 924.03515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7086194000003161
Peak memory usage during training: 928.90625 MB
Prediction time: 1.7790303000001586
Peak memory usage during prediction: 923.95703125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1193710000006831
Peak memory usage during training: 928.94140625 MB
Prediction time: 1.784770500002196
Peak memory usage during prediction: 924.08984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.131012500001816
Peak memory usage during training: 928.98828125 MB
Prediction time: 1.8019585000001825
Peak memory usage during prediction: 924.01171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.1935680999959004
Peak memory usage during training: 928.6484375 MB
Prediction time: 1.797427699995751
Peak memory usage during prediction: 924.0234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0882149000026402
Peak memory usage during training: 928.94140625 MB
Prediction time: 1.8069384999980684
Peak memory usage during prediction: 923.96484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0840465000001132
Peak memory usage during training: 928.9375 MB
Prediction time: 1.794034599995939
Peak memory usage during prediction: 924.09375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.117503100002068
Peak memory usage during training: 929.015625 MB
Prediction time: 1.803804000002856
Peak memory usage during prediction: 924.0390625 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 7.874593599997752
Peak memory usage during training: 924.1484375 MB
Prediction time: 1.472688299996662
Peak memory usage during prediction: 764.66796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 8.562555399999837
Peak memory usage during training: 771.9296875 MB
Prediction time: 0.9862665999971796
Peak memory usage during prediction: 764.953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 8.45469160000357
Peak memory usage during training: 771.1484375 MB
Prediction time: 0.9835423999975319
Peak memory usage during prediction: 771.15625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 15.221522700005153
Peak memory usage during training: 850.890625 MB
Prediction time: 1.041254800002207
Peak memory usage during prediction: 842.875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 16.374237600000924
Peak memory usage during training: 849.1796875 MB
Prediction time: 1.0532584999964456
Peak memory usage during prediction: 843.1328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 16.444837900002312
Peak memory usage during training: 849.09375 MB
Prediction time: 1.0439770999946631
Peak memory usage during prediction: 842.94140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 22.609513600000355
Peak memory usage during training: 927.34375 MB
Prediction time: 1.1013663999983692
Peak memory usage during prediction: 920.89453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 24.39362930000061
Peak memory usage during training: 927.58984375 MB
Prediction time: 1.103397999999288
Peak memory usage during prediction: 921.08203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 24.20948949999729
Peak memory usage during training: 927.56640625 MB
Prediction time: 1.1009214000005159
Peak memory usage during prediction: 921.0546875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 14.443093800000497
Peak memory usage during training: 1134.7265625 MB
Prediction time: 1.7237697999953525
Peak memory usage during prediction: 943.70703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 19.471676499997557
Peak memory usage during training: 1161.69140625 MB
Prediction time: 2.4845733999973163
Peak memory usage during prediction: 945.7578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.62009790000593
Peak memory usage during training: 1140.55859375 MB
Prediction time: 1.7357005999947432
Peak memory usage during prediction: 943.70703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 13.320171499995922
Peak memory usage during training: 1151.37890625 MB
Prediction time: 1.5108091000001878
Peak memory usage during prediction: 944.66796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 21.929116899998917
Peak memory usage during training: 1175.0234375 MB
Prediction time: 2.3976155999989714
Peak memory usage during prediction: 946.0 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 12.96436790000007
Peak memory usage during training: 1144.3671875 MB
Prediction time: 1.4786304000008386
Peak memory usage during prediction: 943.828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 17.27854369999841
Peak memory usage during training: 1183.7265625 MB
Prediction time: 1.3947267999974429
Peak memory usage during prediction: 942.578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 47.72514219999721
Peak memory usage during training: 1173.62890625 MB
Prediction time: 2.5469778000042425
Peak memory usage during prediction: 947.078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 20.976426699999138
Peak memory usage during training: 1171.1484375 MB
Prediction time: 1.2628627000012784
Peak memory usage during prediction: 945.3359375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.0376988999996684
Peak memory usage during training: 931.5859375 MB
Prediction time: 1.787626999997883
Peak memory usage during prediction: 922.24609375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.0386679000002914
Peak memory usage during training: 927.8515625 MB
Prediction time: 1.8029721999992034
Peak memory usage during prediction: 921.953125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.0386112999985926
Peak memory usage during training: 927.15625 MB
Prediction time: 1.7966302999993786
Peak memory usage during prediction: 921.90625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.2580495000001974
Peak memory usage during training: 928.8984375 MB
Prediction time: 1.7932738999952562
Peak memory usage during prediction: 922.02734375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7688599000030081
Peak memory usage during training: 928.65625 MB
Prediction time: 1.806069899997965
Peak memory usage during prediction: 921.9375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9629940000013448
Peak memory usage during training: 928.5390625 MB
Prediction time: 1.7906288000012864
Peak memory usage during prediction: 921.83984375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.026409700003569
Peak memory usage during training: 927.09375 MB
Prediction time: 1.2448046999998041
Peak memory usage during prediction: 1109.76953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.032459400004882
Peak memory usage during training: 926.60546875 MB
Prediction time: 1.2315024999988964
Peak memory usage during prediction: 1119.01171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0234780000027968
Peak memory usage during training: 926.4453125 MB
Prediction time: 1.2541543999977876
Peak memory usage during prediction: 1113.22265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0254702999955043
Peak memory usage during training: 926.46484375 MB
Prediction time: 1.263363500002015
Peak memory usage during prediction: 1117.1796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0257376000008662
Peak memory usage during training: 926.62109375 MB
Prediction time: 1.2362132000052952
Peak memory usage during prediction: 1116.15234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0401022000005469
Peak memory usage during training: 925.74609375 MB
Prediction time: 1.2298141999999643
Peak memory usage during prediction: 1118.76171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0265901000020676
Peak memory usage during training: 925.77734375 MB
Prediction time: 1.261533099997905
Peak memory usage during prediction: 1117.4296875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.032549100003962
Peak memory usage during training: 926.03515625 MB
Prediction time: 1.257337800001551
Peak memory usage during prediction: 1114.03125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0203880999979447
Peak memory usage during training: 925.890625 MB
Prediction time: 1.2340557999996236
Peak memory usage during prediction: 1121.86328125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7341937000019243
Peak memory usage during training: 933.77734375 MB
Prediction time: 1.8039721000022837
Peak memory usage during prediction: 922.84765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7888277000020025
Peak memory usage during training: 933.875 MB
Prediction time: 1.8031434000004083
Peak memory usage during prediction: 923.0625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.9179271000029985
Peak memory usage during training: 928.375 MB
Prediction time: 1.8021796999964863
Peak memory usage during prediction: 921.859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7626011000029393
Peak memory usage during training: 932.21484375 MB
Prediction time: 1.8066774000035366
Peak memory usage during prediction: 922.87109375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7940856999994139
Peak memory usage during training: 932.2734375 MB
Prediction time: 1.7999740000013844
Peak memory usage during prediction: 922.94921875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.6090082000009716
Peak memory usage during training: 927.5078125 MB
Prediction time: 1.7849408000038238
Peak memory usage during prediction: 921.765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7687536000012187
Peak memory usage during training: 932.24609375 MB
Prediction time: 1.7811107000015909
Peak memory usage during prediction: 922.8984375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7932918000005884
Peak memory usage during training: 932.30078125 MB
Prediction time: 1.795589100001962
Peak memory usage during prediction: 922.9765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.609653799998341
Peak memory usage during training: 927.421875 MB
Prediction time: 1.8094469000061508
Peak memory usage during prediction: 921.7890625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 11.7794969999959
Peak memory usage during training: 926.21875 MB
Prediction time: 1.8120223000005353
Peak memory usage during prediction: 921.39453125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 11.93465809999907
Peak memory usage during training: 926.234375 MB
Prediction time: 1.81183069999679
Peak memory usage during prediction: 920.8515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 17.276494500001718
Peak memory usage during training: 925.71875 MB
Prediction time: 1.8246520000029705
Peak memory usage during prediction: 921.41796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 17.440048500000557
Peak memory usage during training: 926.35546875 MB
Prediction time: 1.8405210999990231
Peak memory usage during prediction: 921.46484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 22.89487250000093
Peak memory usage during training: 926.53125 MB
Prediction time: 1.8214421000011498
Peak memory usage during prediction: 921.96484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 22.97451629999705
Peak memory usage during training: 926.58203125 MB
Prediction time: 1.8219404999981634
Peak memory usage during prediction: 921.88671875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.2994670999978553
Peak memory usage during training: 926.78125 MB
Prediction time: 1.0092831000001752
Peak memory usage during prediction: 924.92578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.276110600003449
Peak memory usage during training: 926.65234375 MB
Prediction time: 0.9983436999973492
Peak memory usage during prediction: 924.62109375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.2851894999985234
Peak memory usage during training: 926.26171875 MB
Prediction time: 1.0094318999981624
Peak memory usage during prediction: 924.21875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.059216200002993
Peak memory usage during training: 926.4140625 MB
Prediction time: 1.1009053999950993
Peak memory usage during prediction: 924.43359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.050502399994002
Peak memory usage during training: 926.55859375 MB
Prediction time: 1.1021577999999863
Peak memory usage during prediction: 924.68359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.063632600002165
Peak memory usage during training: 926.76953125 MB
Prediction time: 1.1094583999947645
Peak memory usage during prediction: 924.71875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.854188400000567
Peak memory usage during training: 926.7421875 MB
Prediction time: 1.1793440000037663
Peak memory usage during prediction: 924.87890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.813349999996717
Peak memory usage during training: 927.01953125 MB
Prediction time: 1.187235999997938
Peak memory usage during prediction: 925.078125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.890955900002155
Peak memory usage during training: 926.953125 MB
Prediction time: 1.172646099999838
Peak memory usage during prediction: 925.31640625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1309542000017245
Peak memory usage during training: 926.79296875 MB
Prediction time: 1.7975548999966122
Peak memory usage during prediction: 922.09765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1320342999970308
Peak memory usage during training: 926.80078125 MB
Prediction time: 1.7916088999991189
Peak memory usage during prediction: 922.10546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.2463597000023583
Peak memory usage during training: 926.58203125 MB
Prediction time: 1.7959871999992174
Peak memory usage during prediction: 922.16015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.075057399997604
Peak memory usage during training: 927.0 MB
Prediction time: 1.783894499996677
Peak memory usage during prediction: 922.1015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.0854958999989321
Peak memory usage during training: 927.16015625 MB
Prediction time: 1.792870999997831
Peak memory usage during prediction: 922.17578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1137777999974787
Peak memory usage during training: 926.6328125 MB
Prediction time: 1.786121799996181
Peak memory usage during prediction: 922.1953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0729995000001509
Peak memory usage during training: 926.5625 MB
Prediction time: 1.7927958999935072
Peak memory usage during prediction: 922.1953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.0891870999985258
Peak memory usage during training: 926.64453125 MB
Prediction time: 1.788203699994483
Peak memory usage during prediction: 922.1953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0942929000011645
Peak memory usage during training: 926.5625 MB
Prediction time: 1.7962314000033075
Peak memory usage during prediction: 922.1953125 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 8.764503099999274
Peak memory usage during training: 922.1953125 MB
Prediction time: 0.978735400000005
Peak memory usage during prediction: 769.68359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 9.228775000003225
Peak memory usage during training: 775.22265625 MB
Prediction time: 0.9734806999986176
Peak memory usage during prediction: 775.484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 9.214134699999704
Peak memory usage during training: 775.81640625 MB
Prediction time: 0.9811970000009751
Peak memory usage during prediction: 775.8359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 17.109161599997606
Peak memory usage during training: 858.25 MB
Prediction time: 1.0377525000003516
Peak memory usage during prediction: 858.19140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 17.83313690000068
Peak memory usage during training: 857.74609375 MB
Prediction time: 1.0320201000067755
Peak memory usage during prediction: 857.08203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 17.89778490000026
Peak memory usage during training: 857.74609375 MB
Prediction time: 1.040602900000522
Peak memory usage during prediction: 857.0703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 25.211824799996975
Peak memory usage during training: 940.67578125 MB
Prediction time: 1.1012266000034288
Peak memory usage during prediction: 940.91015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 26.517456800000218
Peak memory usage during training: 941.30078125 MB
Prediction time: 1.0966633000061847
Peak memory usage during prediction: 941.5234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 26.347605099996144
Peak memory usage during training: 941.19140625 MB
Prediction time: 1.105751399998553
Peak memory usage during prediction: 941.3828125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 12.33420379999734
Peak memory usage during training: 1155.99609375 MB
Prediction time: 1.4433991000041715
Peak memory usage during prediction: 958.046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 17.46787949999998
Peak memory usage during training: 1166.69140625 MB
Prediction time: 2.3364744999998948
Peak memory usage during prediction: 947.84375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.638905899999372
Peak memory usage during training: 1144.95703125 MB
Prediction time: 1.669214400004421
Peak memory usage during prediction: 946.69921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 16.581750100005593
Peak memory usage during training: 1179.875 MB
Prediction time: 1.4046209000007366
Peak memory usage during prediction: 947.59765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 20.05830259999493
Peak memory usage during training: 1175.3359375 MB
Prediction time: 2.271790399994643
Peak memory usage during prediction: 948.2578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.1692292000007
Peak memory usage during training: 1143.26953125 MB
Prediction time: 1.4145237000047928
Peak memory usage during prediction: 947.7578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 28.539916999994603
Peak memory usage during training: 1163.4375 MB
Prediction time: 1.2527358000006643
Peak memory usage during prediction: 946.35546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 44.696709299998474
Peak memory usage during training: 1166.671875 MB
Prediction time: 2.4758729999957723
Peak memory usage during prediction: 949.328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 14.321732199998223
Peak memory usage during training: 1152.0859375 MB
Prediction time: 1.166305500002636
Peak memory usage during prediction: 947.5625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.0321439999970607
Peak memory usage during training: 932.140625 MB
Prediction time: 1.8032336000032956
Peak memory usage during prediction: 923.94921875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.0314461000016308
Peak memory usage during training: 930.58203125 MB
Prediction time: 1.7914366999975755
Peak memory usage during prediction: 923.64453125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.0235751000000164
Peak memory usage during training: 929.9765625 MB
Prediction time: 1.7991257999965455
Peak memory usage during prediction: 923.375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3022856999959913
Peak memory usage during training: 931.01171875 MB
Prediction time: 1.785222699996666
Peak memory usage during prediction: 923.43359375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8344372999999905
Peak memory usage during training: 930.82421875 MB
Prediction time: 1.7895031999942148
Peak memory usage during prediction: 923.453125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.073336900000868
Peak memory usage during training: 930.859375 MB
Prediction time: 1.791193499993824
Peak memory usage during prediction: 923.21484375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.022216400000616
Peak memory usage during training: 928.984375 MB
Prediction time: 0.7538292999961413
Peak memory usage during prediction: 1042.30078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0169806000048993
Peak memory usage during training: 933.18359375 MB
Prediction time: 0.7496918999968329
Peak memory usage during prediction: 1052.5859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0209816999995383
Peak memory usage during training: 928.09765625 MB
Prediction time: 0.7445165000026464
Peak memory usage during prediction: 1036.359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0194005000012112
Peak memory usage during training: 933.18359375 MB
Prediction time: 0.7440397999962443
Peak memory usage during prediction: 1058.16015625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0155043000049773
Peak memory usage during training: 928.2109375 MB
Prediction time: 0.7527120999948238
Peak memory usage during prediction: 1033.95703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.019626799999969
Peak memory usage during training: 933.1640625 MB
Prediction time: 0.7532977000009851
Peak memory usage during prediction: 1053.109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0135165999963647
Peak memory usage during training: 928.0859375 MB
Prediction time: 0.7472834000000148
Peak memory usage during prediction: 1053.671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.026730999998108
Peak memory usage during training: 933.12890625 MB
Prediction time: 0.747132699994836
Peak memory usage during prediction: 1052.68359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.026030000000901
Peak memory usage during training: 928.06640625 MB
Prediction time: 0.7442452000032063
Peak memory usage during prediction: 1027.24609375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7796148999987054
Peak memory usage during training: 936.6328125 MB
Prediction time: 1.7882631000029505
Peak memory usage during prediction: 924.37109375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8382913000023109
Peak memory usage during training: 934.5859375 MB
Prediction time: 1.790497800000594
Peak memory usage during prediction: 924.5234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.8326162000012118
Peak memory usage during training: 930.8359375 MB
Prediction time: 1.7770722999994177
Peak memory usage during prediction: 923.4609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7729370999950333
Peak memory usage during training: 934.98046875 MB
Prediction time: 1.7963961999994353
Peak memory usage during prediction: 924.48046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8460667000035755
Peak memory usage during training: 934.91796875 MB
Prediction time: 1.7972766000020783
Peak memory usage during prediction: 924.55078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.105146399997466
Peak memory usage during training: 930.76171875 MB
Prediction time: 1.7987227999983588
Peak memory usage during prediction: 923.4296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7785631000006106
Peak memory usage during training: 934.89453125 MB
Prediction time: 1.7894423000034294
Peak memory usage during prediction: 924.34375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.850696000001335
Peak memory usage during training: 934.78515625 MB
Prediction time: 1.7962752000021283
Peak memory usage during prediction: 924.48046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.10456599999452
Peak memory usage during training: 930.6171875 MB
Prediction time: 1.7841866000017035
Peak memory usage during prediction: 923.35546875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 6.950707800002419
Peak memory usage during training: 928.2109375 MB
Prediction time: 1.8069939999986673
Peak memory usage during prediction: 923.4375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 6.895209099995554
Peak memory usage during training: 928.515625 MB
Prediction time: 1.7979878000041936
Peak memory usage during prediction: 923.2734375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 9.994699999995646
Peak memory usage during training: 928.18359375 MB
Prediction time: 1.8166801999977906
Peak memory usage during prediction: 922.84765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 10.062578199998825
Peak memory usage during training: 927.97265625 MB
Prediction time: 1.8142886999994516
Peak memory usage during prediction: 923.29296875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 13.254038699997182
Peak memory usage during training: 928.1640625 MB
Prediction time: 1.8161595999990823
Peak memory usage during prediction: 923.62890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 13.16256340000109
Peak memory usage during training: 928.34765625 MB
Prediction time: 1.8345655999946757
Peak memory usage during prediction: 923.96875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2748552999983076
Peak memory usage during training: 927.89453125 MB
Prediction time: 1.0094659000023967
Peak memory usage during prediction: 927.03125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.280203400005121
Peak memory usage during training: 927.55859375 MB
Prediction time: 1.0041941000017687
Peak memory usage during prediction: 926.48046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2645419999971637
Peak memory usage during training: 927.21484375 MB
Prediction time: 1.0159286999987671
Peak memory usage during prediction: 926.21484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.043986500000756
Peak memory usage during training: 927.41796875 MB
Prediction time: 1.090431399999943
Peak memory usage during prediction: 926.19921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.020250699999451
Peak memory usage during training: 927.30859375 MB
Prediction time: 1.096859500001301
Peak memory usage during prediction: 926.32421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.021810500002175
Peak memory usage during training: 927.53125 MB
Prediction time: 1.089148800005205
Peak memory usage during prediction: 926.28515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.791338999995787
Peak memory usage during training: 927.45703125 MB
Prediction time: 1.181477799997083
Peak memory usage during prediction: 926.47265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.8275840999995125
Peak memory usage during training: 927.71484375 MB
Prediction time: 1.1817640000008396
Peak memory usage during prediction: 926.640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.760715699994762
Peak memory usage during training: 927.91015625 MB
Prediction time: 1.1922048999986146
Peak memory usage during prediction: 926.83984375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2135723999963375
Peak memory usage during training: 927.98046875 MB
Prediction time: 1.7972546000019065
Peak memory usage during prediction: 923.61328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.6917039000036311
Peak memory usage during training: 927.6015625 MB
Prediction time: 1.7974409999951604
Peak memory usage during prediction: 923.62890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7042935999998008
Peak memory usage during training: 927.8828125 MB
Prediction time: 1.7884287999986554
Peak memory usage during prediction: 923.55078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.125280300002487
Peak memory usage during training: 927.8671875 MB
Prediction time: 1.7934163000027183
Peak memory usage during prediction: 923.625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.118584899995767
Peak memory usage during training: 927.984375 MB
Prediction time: 1.818627100001322
Peak memory usage during prediction: 923.59375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.1948716000042623
Peak memory usage during training: 927.88671875 MB
Prediction time: 1.7889668999996502
Peak memory usage during prediction: 923.66796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0886962000004132
Peak memory usage during training: 928.01171875 MB
Prediction time: 1.7862378999998327
Peak memory usage during prediction: 923.609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0867311999973026
Peak memory usage during training: 927.9296875 MB
Prediction time: 1.7897950999977184
Peak memory usage during prediction: 923.6875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.1121658999982174
Peak memory usage during training: 928.01171875 MB
Prediction time: 1.7879726999963168
Peak memory usage during prediction: 923.58984375 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 7.8611392000020714
Peak memory usage during training: 923.66796875 MB
Prediction time: 0.9903612999987672
Peak memory usage during prediction: 768.15625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 8.509693899999547
Peak memory usage during training: 769.97265625 MB
Prediction time: 0.9849965999965207
Peak memory usage during prediction: 769.98828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 8.47658130000491
Peak memory usage during training: 770.00390625 MB
Prediction time: 0.9872601999959443
Peak memory usage during prediction: 770.0 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 15.186609599993972
Peak memory usage during training: 850.75390625 MB
Prediction time: 1.0455666999987443
Peak memory usage during prediction: 843.3046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 16.37812750000012
Peak memory usage during training: 849.1015625 MB
Prediction time: 1.0315373999983422
Peak memory usage during prediction: 842.83984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 16.52882440000394
Peak memory usage during training: 849.328125 MB
Prediction time: 1.0417319999978645
Peak memory usage during prediction: 842.83984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 22.34249329999875
Peak memory usage during training: 928.9296875 MB
Prediction time: 1.1002844000031473
Peak memory usage during prediction: 924.73046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 24.43056009999418
Peak memory usage during training: 927.78515625 MB
Prediction time: 1.0979806000032113
Peak memory usage during prediction: 921.05859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 24.488182499997492
Peak memory usage during training: 927.4140625 MB
Prediction time: 1.0971588999964297
Peak memory usage during prediction: 920.98828125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 14.453238499998406
Peak memory usage during training: 1140.48046875 MB
Prediction time: 1.6974262000003364
Peak memory usage during prediction: 944.76953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 19.487129200002528
Peak memory usage during training: 1162.28125 MB
Prediction time: 2.463639899993723
Peak memory usage during prediction: 946.1796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 14.633840199996484
Peak memory usage during training: 1139.13671875 MB
Prediction time: 1.734083199997258
Peak memory usage during prediction: 944.57421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 13.336170800001128
Peak memory usage during training: 1152.19140625 MB
Prediction time: 1.540483500000846
Peak memory usage during prediction: 945.91796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 21.94680569999764
Peak memory usage during training: 1175.125 MB
Prediction time: 2.4031982000014978
Peak memory usage during prediction: 946.73828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 12.985509699996328
Peak memory usage during training: 1148.62109375 MB
Prediction time: 1.4872363999966183
Peak memory usage during prediction: 943.28515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 17.262814199995773
Peak memory usage during training: 1183.6171875 MB
Prediction time: 1.3956656000009389
Peak memory usage during prediction: 943.921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 48.026805599998625
Peak memory usage during training: 1174.09375 MB
Prediction time: 2.550565199999255
Peak memory usage during prediction: 947.65625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 21.123964300000807
Peak memory usage during training: 1171.87890625 MB
Prediction time: 1.2382952000043588
Peak memory usage during prediction: 945.734375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.0433380999966175
Peak memory usage during training: 932.66015625 MB
Prediction time: 1.8187244999935501
Peak memory usage during prediction: 922.921875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.0429038000002038
Peak memory usage during training: 929.37890625 MB
Prediction time: 1.800971100004972
Peak memory usage during prediction: 922.53125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.0454532999938237
Peak memory usage during training: 928.3828125 MB
Prediction time: 1.8192772999973386
Peak memory usage during prediction: 922.3828125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.2867199999964214
Peak memory usage during training: 930.10546875 MB
Prediction time: 1.8072408000007272
Peak memory usage during prediction: 922.63671875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7913619999962975
Peak memory usage during training: 929.890625 MB
Prediction time: 1.8098538999984157
Peak memory usage during prediction: 922.51953125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9817809000014677
Peak memory usage during training: 929.93359375 MB
Prediction time: 1.8085386000020662
Peak memory usage during prediction: 922.75 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0398509000006015
Peak memory usage during training: 928.46875 MB
Prediction time: 1.2697552000026917
Peak memory usage during prediction: 1106.1640625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0382557999982964
Peak memory usage during training: 928.046875 MB
Prediction time: 1.2515076999989105
Peak memory usage during prediction: 1112.3671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0438299000015832
Peak memory usage during training: 927.8359375 MB
Prediction time: 1.2641337000022759
Peak memory usage during prediction: 1109.48046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.038203500000236
Peak memory usage during training: 927.94140625 MB
Prediction time: 1.281489100001636
Peak memory usage during prediction: 1124.9375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0463013000044157
Peak memory usage during training: 928.07421875 MB
Prediction time: 1.2549606000029598
Peak memory usage during prediction: 1125.00390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0308536000011372
Peak memory usage during training: 927.47265625 MB
Prediction time: 1.2609983000002103
Peak memory usage during prediction: 1114.42578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0338810999965062
Peak memory usage during training: 927.359375 MB
Prediction time: 1.275027499999851
Peak memory usage during prediction: 1105.46484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0351130999988527
Peak memory usage during training: 927.55078125 MB
Prediction time: 1.2485776000030455
Peak memory usage during prediction: 1116.08203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.0378581000040867
Peak memory usage during training: 927.58984375 MB
Prediction time: 1.2495385000001988
Peak memory usage during prediction: 1125.0625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7518749000009848
Peak memory usage during training: 934.16015625 MB
Prediction time: 1.8046563000025344
Peak memory usage during prediction: 923.65625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.7880197999984375
Peak memory usage during training: 933.5625 MB
Prediction time: 1.8038334000011673
Peak memory usage during prediction: 923.88671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.930768000005628
Peak memory usage during training: 929.31640625 MB
Prediction time: 1.8022898999988683
Peak memory usage during prediction: 922.73046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7616753000038443
Peak memory usage during training: 933.765625 MB
Prediction time: 1.802209599998605
Peak memory usage during prediction: 923.6875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.8051805999930366
Peak memory usage during training: 933.48828125 MB
Prediction time: 1.8018155000027036
Peak memory usage during prediction: 923.90234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.635432100003527
Peak memory usage during training: 928.265625 MB
Prediction time: 1.8186514999979408
Peak memory usage during prediction: 922.7578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 0.7615384000018821
Peak memory usage during training: 933.8046875 MB
Prediction time: 1.810865699997521
Peak memory usage during prediction: 923.76953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.813314500002889
Peak memory usage during training: 933.54296875 MB
Prediction time: 1.804104399998323
Peak memory usage during prediction: 923.95703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 2.6353493999995408
Peak memory usage during training: 928.55859375 MB
Prediction time: 1.8004237999994075
Peak memory usage during prediction: 922.703125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 11.706608200001938
Peak memory usage during training: 927.625 MB
Prediction time: 1.830236199995852
Peak memory usage during prediction: 922.27734375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 11.632028200001514
Peak memory usage during training: 927.91796875 MB
Prediction time: 1.8223369999977876
Peak memory usage during prediction: 921.9765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 17.13306569999986
Peak memory usage during training: 927.65625 MB
Prediction time: 1.8275958000012906
Peak memory usage during prediction: 922.06640625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 17.163421400000516
Peak memory usage during training: 927.56640625 MB
Prediction time: 1.8448366000011447
Peak memory usage during prediction: 922.3359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 22.916242799998145
Peak memory usage during training: 927.671875 MB
Prediction time: 1.3940039000008255
Peak memory usage during prediction: 925.15234375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 22.71628029999556
Peak memory usage during training: 927.18359375 MB
Prediction time: 1.867351900000358
Peak memory usage during prediction: 922.78125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.3054784999985714
Peak memory usage during training: 927.41796875 MB
Prediction time: 1.029652499993972
Peak memory usage during prediction: 925.484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.2815057999978308
Peak memory usage during training: 927.296875 MB
Prediction time: 1.0102012999996077
Peak memory usage during prediction: 925.28125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.29146330000367
Peak memory usage during training: 927.34765625 MB
Prediction time: 1.0070132999971975
Peak memory usage during prediction: 925.31640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.1054290999964
Peak memory usage during training: 927.2890625 MB
Prediction time: 1.1329170000026352
Peak memory usage during prediction: 925.31640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.087973699999566
Peak memory usage during training: 927.3515625 MB
Prediction time: 1.103715099998226
Peak memory usage during prediction: 925.37890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 6.053316799996537
Peak memory usage during training: 927.40234375 MB
Prediction time: 1.1081234000012046
Peak memory usage during prediction: 925.390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.859053700005461
Peak memory usage during training: 927.47265625 MB
Prediction time: 1.1865987999990466
Peak memory usage during prediction: 925.48828125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.841468699996767
Peak memory usage during training: 927.58203125 MB
Prediction time: 1.2001977999971132
Peak memory usage during prediction: 919.6640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.801009300004807
Peak memory usage during training: 921.37890625 MB
Prediction time: 1.1933367999954498
Peak memory usage during prediction: 919.83203125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1320492000013473
Peak memory usage during training: 921.3046875 MB
Prediction time: 1.809229400001641
Peak memory usage during prediction: 916.796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.136741100002837
Peak memory usage during training: 921.38671875 MB
Prediction time: 1.8126836999945226
Peak memory usage during prediction: 916.8671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.24470989999827
Peak memory usage during training: 921.453125 MB
Prediction time: 1.8078007000003709
Peak memory usage during prediction: 916.875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.097350500000175
Peak memory usage during training: 921.515625 MB
Prediction time: 1.8026183000038145
Peak memory usage during prediction: 916.84765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.1041076999972574
Peak memory usage during training: 921.40234375 MB
Prediction time: 1.8071390999975847
Peak memory usage during prediction: 916.80859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.1219180000043707
Peak memory usage during training: 921.63671875 MB
Prediction time: 1.8017926000029547
Peak memory usage during prediction: 916.53125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0777095000012196
Peak memory usage during training: 921.5703125 MB
Prediction time: 1.827623199998925
Peak memory usage during prediction: 916.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.0830056999984663
Peak memory usage during training: 921.68359375 MB
Prediction time: 1.8211652999962098
Peak memory usage during prediction: 916.62890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0899573999995482
Peak memory usage during training: 921.6640625 MB
Prediction time: 1.8037392999976873
Peak memory usage during prediction: 916.62890625 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 8.743989499998861
Peak memory usage during training: 916.62890625 MB
Prediction time: 0.9923558000009507
Peak memory usage during prediction: 769.80078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 9.304185699998925
Peak memory usage during training: 775.72265625 MB
Prediction time: 1.4566657999966992
Peak memory usage during prediction: 770.3046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 9.155951900000218
Peak memory usage during training: 775.55078125 MB
Prediction time: 0.9921977999983937
Peak memory usage during prediction: 775.79296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 17.043750000004366
Peak memory usage during training: 858.8203125 MB
Prediction time: 1.0523189999948954
Peak memory usage during prediction: 858.734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 17.84903249999479
Peak memory usage during training: 858.9765625 MB
Prediction time: 1.0503920999981347
Peak memory usage during prediction: 858.3203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 17.829217899998184
Peak memory usage during training: 858.9140625 MB
Prediction time: 1.044342900000629
Peak memory usage during prediction: 858.26953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 25.22981379999692
Peak memory usage during training: 941.16015625 MB
Prediction time: 1.11368969999603
Peak memory usage during prediction: 941.3515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 26.403556899997056
Peak memory usage during training: 942.4453125 MB
Prediction time: 1.1141781999976956
Peak memory usage during prediction: 942.625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 26.480279900002643
Peak memory usage during training: 942.6015625 MB
Prediction time: 1.1048096000013174
Peak memory usage during prediction: 942.82421875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 12.336758099998406
Peak memory usage during training: 1158.8359375 MB
Prediction time: 1.4514584999997169
Peak memory usage during prediction: 959.5 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 17.477207199997792
Peak memory usage during training: 1172.9921875 MB
Prediction time: 2.3670526999994763
Peak memory usage during prediction: 962.15234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.647260600002483
Peak memory usage during training: 1158.26953125 MB
Prediction time: 1.6336178000055952
Peak memory usage during prediction: 960.59765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 16.69488999999885
Peak memory usage during training: 1193.01171875 MB
Prediction time: 1.3980464999985998
Peak memory usage during prediction: 960.90625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 20.078260899994348
Peak memory usage during training: 1188.7265625 MB
Prediction time: 2.290098299999954
Peak memory usage during prediction: 961.90625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 13.186702200000582
Peak memory usage during training: 1162.55859375 MB
Prediction time: 1.4278178999957163
Peak memory usage during prediction: 960.90625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 29.02170570000453
Peak memory usage during training: 1176.8203125 MB
Prediction time: 1.2842024999990826
Peak memory usage during prediction: 960.08984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 44.76240630000393
Peak memory usage during training: 1180.1484375 MB
Prediction time: 2.4416707000054885
Peak memory usage during prediction: 962.69140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 14.368751699999848
Peak memory usage during training: 1165.0078125 MB
Prediction time: 1.1547623999940697
Peak memory usage during prediction: 961.2890625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.0494196999934502
Peak memory usage during training: 945.9375 MB
Prediction time: 1.8155897000033292
Peak memory usage during prediction: 937.4765625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.0314330999972299
Peak memory usage during training: 943.578125 MB
Prediction time: 1.8041082999989158
Peak memory usage during prediction: 937.4296875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.0382829999944079
Peak memory usage during training: 943.5546875 MB
Prediction time: 1.7931656000000658
Peak memory usage during prediction: 937.1328125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3248753000007127
Peak memory usage during training: 945.08203125 MB
Prediction time: 1.802049600002647
Peak memory usage during prediction: 937.25 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8705095999976038
Peak memory usage during training: 944.625 MB
Prediction time: 1.8007243999963976
Peak memory usage during prediction: 937.21875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1039248000015505
Peak memory usage during training: 944.890625 MB
Prediction time: 1.8173047000018414
Peak memory usage during prediction: 937.0234375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0378807999950368
Peak memory usage during training: 943.55859375 MB
Prediction time: 0.7574628000002122
Peak memory usage during prediction: 1042.01171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.6824606000009226
Peak memory usage during training: 947.703125 MB
Prediction time: 0.7564674999957788
Peak memory usage during prediction: 1052.44140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0381010999990394
Peak memory usage during training: 948.09375 MB
Prediction time: 0.7609737000020687
Peak memory usage during prediction: 1048.359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0348439999943366
Peak memory usage during training: 942.984375 MB
Prediction time: 0.7532219999993686
Peak memory usage during prediction: 1064.55859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0324505000025965
Peak memory usage during training: 948.16015625 MB
Prediction time: 0.7581322999976692
Peak memory usage during prediction: 1045.49609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0400205000041751
Peak memory usage during training: 942.72265625 MB
Prediction time: 0.7488045999998576
Peak memory usage during prediction: 1055.1328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0319731000054162
Peak memory usage during training: 947.85546875 MB
Prediction time: 0.748514899998554
Peak memory usage during prediction: 1058.828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0255910999985645
Peak memory usage during training: 942.8203125 MB
Prediction time: 0.7593608000024687
Peak memory usage during prediction: 1058.46484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.0297209999989718
Peak memory usage during training: 947.80078125 MB
Prediction time: 0.756431399997382
Peak memory usage during prediction: 1050.2109375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7646792000014102
Peak memory usage during training: 949.9609375 MB
Prediction time: 1.811488699997426
Peak memory usage during prediction: 937.71875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8422128000020166
Peak memory usage during training: 948.58203125 MB
Prediction time: 1.815771699999459
Peak memory usage during prediction: 937.890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.8137327000004007
Peak memory usage during training: 944.26171875 MB
Prediction time: 1.805606699999771
Peak memory usage during prediction: 936.71484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.8020109999997658
Peak memory usage during training: 948.59375 MB
Prediction time: 1.7996468000055756
Peak memory usage during prediction: 937.77734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.852844200002437
Peak memory usage during training: 948.53515625 MB
Prediction time: 1.807776500005275
Peak memory usage during prediction: 937.859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.10441919999721
Peak memory usage during training: 944.53515625 MB
Prediction time: 1.8104415999987395
Peak memory usage during prediction: 936.84375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7959021999995457
Peak memory usage during training: 948.671875 MB
Prediction time: 1.7949201999945217
Peak memory usage during prediction: 937.73046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 0.8452125999974669
Peak memory usage during training: 948.453125 MB
Prediction time: 1.8142984000005526
Peak memory usage during prediction: 937.7265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 2.1015864000000875
Peak memory usage during training: 944.140625 MB
Prediction time: 1.789009400003124
Peak memory usage during prediction: 936.58984375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 6.951948200003244
Peak memory usage during training: 942.39453125 MB
Prediction time: 1.8456506000002264
Peak memory usage during prediction: 936.58203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 6.936807999998564
Peak memory usage during training: 941.66015625 MB
Prediction time: 1.8200044999975944
Peak memory usage during prediction: 936.21484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 10.006432700000005
Peak memory usage during training: 941.578125 MB
Prediction time: 1.8195775999993202
Peak memory usage during prediction: 936.1015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 10.051332800001546
Peak memory usage during training: 941.76953125 MB
Prediction time: 1.8344606000027852
Peak memory usage during prediction: 936.24609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 13.290175399997679
Peak memory usage during training: 942.05078125 MB
Prediction time: 1.8557085000065854
Peak memory usage during prediction: 936.328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 13.222745499995654
Peak memory usage during training: 941.7109375 MB
Prediction time: 1.833647599996766
Peak memory usage during prediction: 936.74609375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2819154000026174
Peak memory usage during training: 941.1328125 MB
Prediction time: 1.0194233000001987
Peak memory usage during prediction: 940.11328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.287849799999094
Peak memory usage during training: 940.86328125 MB
Prediction time: 1.007279200006451
Peak memory usage during prediction: 939.3125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.282680699994671
Peak memory usage during training: 940.7109375 MB
Prediction time: 1.0126242999976967
Peak memory usage during prediction: 939.38671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.060712599995895
Peak memory usage during training: 940.86328125 MB
Prediction time: 1.108988700005284
Peak memory usage during prediction: 939.30859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.045362599994405
Peak memory usage during training: 940.75 MB
Prediction time: 1.097609399999783
Peak memory usage during prediction: 939.3125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.049831500000437
Peak memory usage during training: 940.9140625 MB
Prediction time: 1.0939257999998517
Peak memory usage during prediction: 939.3125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.848965099998168
Peak memory usage during training: 940.85546875 MB
Prediction time: 1.186997100005101
Peak memory usage during prediction: 939.50390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.848207600000023
Peak memory usage during training: 941.015625 MB
Prediction time: 1.2018731999996817
Peak memory usage during prediction: 939.83984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.842980599998555
Peak memory usage during training: 941.4140625 MB
Prediction time: 1.2174203000031412
Peak memory usage during prediction: 939.85546875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2232220000005327
Peak memory usage during training: 941.10546875 MB
Prediction time: 1.8156564999953844
Peak memory usage during prediction: 936.796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.6964176000037696
Peak memory usage during training: 941.42578125 MB
Prediction time: 1.7963613000029
Peak memory usage during prediction: 936.6875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7353120999978273
Peak memory usage during training: 941.27734375 MB
Prediction time: 1.8041840999940177
Peak memory usage during prediction: 936.765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.130615599999146
Peak memory usage during training: 941.515625 MB
Prediction time: 1.8039313000044785
Peak memory usage during prediction: 936.7265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.143793099996401
Peak memory usage during training: 941.34375 MB
Prediction time: 1.7974631000033696
Peak memory usage during prediction: 936.76171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.1961498000018764
Peak memory usage during training: 941.55859375 MB
Prediction time: 1.8084563999946113
Peak memory usage during prediction: 936.74609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.098017999996955
Peak memory usage during training: 941.3671875 MB
Prediction time: 1.8042824999938603
Peak memory usage during prediction: 936.76953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.093614700002945
Peak memory usage during training: 941.3515625 MB
Prediction time: 1.812406800003373
Peak memory usage during prediction: 936.69140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.1217835999996169
Peak memory usage during training: 941.3515625 MB
Prediction time: 1.8164677999957348
Peak memory usage during prediction: 936.75 MB
----------------------------------------------------------------------------------------------------

# Process results

In [14]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   seed                     396 non-null    object
 1   vectorizer               396 non-null    object
 2   model                    396 non-null    object
 3   params                   396 non-null    object
 4   accuracy                 396 non-null    float64
 5   hamming_loss             396 non-null    float64
 6   training_time            396 non-null    float64
 7   prediction_time          396 non-null    float64
 8   peak_memory_train        396 non-null    float64
 9   peak_memory_prediction   396 non-null    float64
 10  precision_class_cs.AI    396 non-null    float64
 11  recall_class_cs.AI       396 non-null    float64
 12  f1_class_cs.AI           396 non-null    float64
 13  precision_class_cs.CL    396 non-null    float64
 14  recall_class_cs.CL       396 non-null    float64
 15  f1_class_cs.CL           396 non-null    float64
 16  precision_class_cs.LG    396 non-null    float64
 17  recall_class_cs.LG       396 non-null    float64
 18  f1_class_cs.LG           396 non-null    float64
 19  precision_class_math.OC  396 non-null    float64
 20  recall_class_math.OC     396 non-null    float64
 21  f1_class_math.OC         396 non-null    float64
 22  precision_class_stat.ML  396 non-null    float64
 23  recall_class_stat.ML     396 non-null    float64
 24  f1_class_stat.ML         396 non-null    float64
dtypes: float64(21), object(4)
memory usage: 77.5+ KB

In [15]:
results.head()

,seed,vectorizer,model,params,accuracy,hamming_loss,training_time,prediction_time,peak_memory_train,peak_memory_prediction,...,f1_class_cs.CL,precision_class_cs.LG,recall_class_cs.LG,f1_class_cs.LG,precision_class_math.OC,recall_class_math.OC,f1_class_math.OC,precision_class_stat.ML,recall_class_stat.ML,f1_class_stat.ML
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.397314,0.175829,8.043998,1.023780,760.363281,752.941406,...,0.827109,0.748596,0.816233,0.780952,0.829787,0.544186,0.657303,0.690323,0.335423,0.451477
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.402054,0.173302,8.664699,0.989592,759.378906,752.812500,...,0.826739,0.773212,0.777948,0.775573,0.835714,0.544186,0.659155,0.731544,0.341693,0.465812
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.402054,0.173302,8.462641,0.992673,759.152344,759.339844,...,0.826739,0.773212,0.777948,0.775573,0.835714,0.544186,0.659155,0.731544,0.341693,0.465812
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.408373,0.172670,15.037505,1.048737,839.246094,831.632812,...,0.832418,0.759207,0.820827,0.788815,0.848921,0.548837,0.666667,0.683544,0.338558,0.452830
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.403633,0.171090,16.582600,1.044874,838.863281,831.261719,...,0.829001,0.775602,0.788668,0.782080,0.865672,0.539535,0.664756,0.728571,0.319749,0.444444

In [16]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,hamming_loss,training_time,prediction_time,peak_memory_train,peak_memory_prediction,...,precision_class_cs.LG,recall_class_cs.LG,f1_class_cs.LG,precision_class_math.OC,recall_class_math.OC,f1_class_math.OC,precision_class_stat.ML,recall_class_stat.ML,f1_class_stat.ML,f1_avg
0,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.103476,0.263665,4.056924,1.096922,932.381510,930.588542,...,0.762069,0.338438,0.468717,1.000000,0.018605,0.036530,0.000000,0.000000,0.000000,0.183540
1,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.230648,0.221327,4.041683,1.094428,932.286458,930.667969,...,0.776596,0.558959,0.650045,0.835821,0.260465,0.397163,0.863636,0.059561,0.111437,0.383474
2,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.346761,0.184518,4.033176,1.089892,932.537760,930.640625,...,0.787931,0.699847,0.741281,0.798507,0.497674,0.613181,0.604167,0.272727,0.375810,0.590431
3,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 150, 'estimator__l...",3.333333,0.121643,0.257504,5.819623,1.183669,932.369792,930.842448,...,0.772871,0.375191,0.505155,1.000000,0.018605,0.036530,0.000000,0.000000,0.000000,0.202367
4,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 150, 'estimator__l...",3.333333,0.259084,0.209795,5.831298,1.187966,932.725260,931.061198,...,0.784047,0.617152,0.690660,0.844156,0.302326,0.445205,0.826087,0.059561,0.111111,0.435172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'estimator__C': 1, 'estimator__kernel': 'rbf'}",3.333333,0.406003,0.161453,21.928254,2.398623,1170.006510,940.446615,...,0.810937,0.794793,0.802784,0.897059,0.567442,0.695157,0.725191,0.297806,0.422222,0.625141
128,SVC,TfidfVectorizer,"{'estimator__C': 1, 'estimator__kernel': 'sigm...",3.333333,0.408373,0.165087,12.973877,1.492002,1139.014323,938.011719,...,0.778614,0.791730,0.785118,0.836364,0.641860,0.726316,0.647368,0.385580,0.483301,0.650478
129,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'lin...",3.333333,0.346761,0.203160,17.302771,1.391400,1177.936198,937.553385,...,0.719219,0.733538,0.726308,0.753927,0.669767,0.709360,0.497006,0.520376,0.508423,0.648333
130,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'rbf'}",3.333333,0.413112,0.163981,47.800119,2.546013,1168.036458,941.411458,...,0.788110,0.791730,0.789916,0.880795,0.618605,0.726776,0.621359,0.401254,0.487619,0.662213
131,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'sig...",3.333333,0.353081,0.201422,21.026499,1.247442,1165.502604,939.649740,...,0.724924,0.730475,0.727689,0.742424,0.683721,0.711864,0.503289,0.479624,0.491172,0.644639

In [17]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train[classes])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test[classes], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test[classes], y_pred, average=None, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: MultinomialNB
Best model params: {'estimator__alpha': 0.1}
Best vectorizer: CountVectorizer
Best accuracy: 0.39448818897637794

Class cs.AI
Precision: 0.4788273615635179
Recall: 0.4336283185840708
F1: 0.4551083591331269
Support: 339

Class cs.CL
Precision: 0.87409200968523
Recall: 0.891358024691358
F1: 0.882640586797066
Support: 405

Class cs.LG
Precision: 0.7627365356622998
Recall: 0.7987804878048781
F1: 0.7803425167535368
Support: 656

Class math.OC
Precision: 0.748898678414097
Recall: 0.7870370370370371
F1: 0.7674943566591422
Support: 216

Class stat.ML
Precision: 0.5444126074498568
Recall: 0.5993690851735016
F1: 0.5705705705705706
Support: 317

In [18]:
with open('models/best_model_sklearn_multilabel3.pkl', 'wb') as f:
    pickle.dump(pipeline, f)