# Importing libraries

In [3]:
# Basic libraries
import pandas as pd
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from memory_profiler import memory_usage

# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [4]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [5]:
ds = load_dataset("KushT/bbc_news_multiclass_train_val_test")

train = ds['train'].to_pandas()
val = ds['validation'].to_pandas()
test = ds['test'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    1512 non-null   object
 1   label   1512 non-null   int64
dtypes: int64(1), object(1)
memory usage: 23.8+ KB

# Dataset preprocessing

In [6]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [7]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': SVC(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': LogisticRegression(max_iter=1000),
        'params': {
            'C': [0.1, 1, 10],
            'penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': GradientBoostingClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': SGDClassifier(),
        'params': {
            'alpha': [0.0001, 0.001, 0.01],
            'penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [8]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = sorted(train['label'].unique())
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [9]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train['label'])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                accuracy = accuracy_score(val['label'], y_pred)
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val['label'], y_pred, average=None, labels=classes, zero_division=0)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_multiclass2.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.106778800007305
Peak memory usage during training: 384.79296875 MB
Prediction time: 1.0681335999979638
Peak memory usage during prediction: 384.8515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_15560\3414761210.py:66: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 1.1908806999999797
Peak memory usage during training: 387.8828125 MB
Prediction time: 1.0680489999940619
Peak memory usage during prediction: 385.8125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.1871726999961538
Peak memory usage during training: 388.69921875 MB
Prediction time: 1.0640425000019604
Peak memory usage during prediction: 385.8515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.563360999993165
Peak memory usage during training: 388.14453125 MB
Prediction time: 1.0795954999921378
Peak memory usage during prediction: 388.84765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.7513202999980422
Peak memory usage during training: 390.55859375 MB
Prediction time: 1.0723792999924626
Peak memory usage during prediction: 388.83984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.7286679999961052
Peak memory usage during training: 391.1484375 MB
Prediction time: 1.0701224000076763
Peak memory usage during prediction: 385.65625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 2.016935999999987
Peak memory usage during training: 392.0078125 MB
Prediction time: 1.0797829999937676
Peak memory usage during prediction: 391.58984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 2.2829823000065517
Peak memory usage during training: 393.14453125 MB
Prediction time: 1.0864702999970177
Peak memory usage during prediction: 392.94921875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 2.2856455000001006
Peak memory usage during training: 394.35546875 MB
Prediction time: 1.0893149000039557
Peak memory usage during prediction: 392.61328125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 3.22674850000476
Peak memory usage during training: 395.0859375 MB
Prediction time: 0.9164760999992723
Peak memory usage during prediction: 394.12890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.514678899999126
Peak memory usage during training: 401.73828125 MB
Prediction time: 1.033814499998698
Peak memory usage during prediction: 397.1171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 3.37639579999086
Peak memory usage during training: 401.140625 MB
Prediction time: 0.9195856000005733
Peak memory usage during prediction: 395.72265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 2.659694699992542
Peak memory usage during training: 401.83984375 MB
Prediction time: 0.8096935999928974
Peak memory usage during prediction: 395.35546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.4100824000051944
Peak memory usage during training: 397.5078125 MB
Prediction time: 0.9688953000004403
Peak memory usage during prediction: 395.93359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 2.180765400000382
Peak memory usage during training: 398.59375 MB
Prediction time: 0.783947599993553
Peak memory usage during prediction: 394.57421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 2.7420137000008253
Peak memory usage during training: 399.41796875 MB
Prediction time: 0.8126534000039101
Peak memory usage during prediction: 395.734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.4148221999930684
Peak memory usage during training: 398.69921875 MB
Prediction time: 0.9681774999917252
Peak memory usage during prediction: 396.5234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 2.2854406999977073
Peak memory usage during training: 400.7734375 MB
Prediction time: 0.7782167000113986
Peak memory usage during prediction: 395.1640625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.2765886999986833
Peak memory usage during training: 402.98046875 MB
Prediction time: 1.037100500005181
Peak memory usage during prediction: 398.47265625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.2650747000006959
Peak memory usage during training: 402.5 MB
Prediction time: 1.0439016000018455
Peak memory usage during prediction: 396.34765625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.2786748000071384
Peak memory usage during training: 401.29296875 MB
Prediction time: 1.0445056999888038
Peak memory usage during prediction: 398.859375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7459256000001915
Peak memory usage during training: 423.87109375 MB
Prediction time: 1.0375353999988874
Peak memory usage during prediction: 396.30859375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9785750000010012
Peak memory usage during training: 437.34765625 MB
Prediction time: 1.039272499998333
Peak memory usage during prediction: 396.3203125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1256186999962665
Peak memory usage during training: 438.4921875 MB
Prediction time: 1.046950600008131
Peak memory usage during prediction: 396.234375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.276418100009323
Peak memory usage during training: 406.8359375 MB
Prediction time: 1.1055532000027597
Peak memory usage during prediction: 409.85546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.253805000000284
Peak memory usage during training: 406.625 MB
Prediction time: 1.0904029999946943
Peak memory usage during prediction: 405.85546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2676809999975376
Peak memory usage during training: 408.26171875 MB
Prediction time: 1.0899759000021731
Peak memory usage during prediction: 407.9375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2648372999974526
Peak memory usage during training: 406.7109375 MB
Prediction time: 1.090524600003846
Peak memory usage during prediction: 410.3515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2547975000052247
Peak memory usage during training: 406.61328125 MB
Prediction time: 1.0865212000062456
Peak memory usage during prediction: 404.98828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2601058000000194
Peak memory usage during training: 406.73828125 MB
Prediction time: 1.0929090999998152
Peak memory usage during prediction: 408.7578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.262502500001574
Peak memory usage during training: 406.90625 MB
Prediction time: 1.0922148999961792
Peak memory usage during prediction: 405.7109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.266961600005743
Peak memory usage during training: 406.91796875 MB
Prediction time: 1.093416800009436
Peak memory usage during prediction: 411.21875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2616183000063756
Peak memory usage during training: 406.80078125 MB
Prediction time: 1.0979103999998188
Peak memory usage during prediction: 406.94921875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.287634699998307
Peak memory usage during training: 407.7734375 MB
Prediction time: 1.033364500006428
Peak memory usage during prediction: 398.20703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.2808565000013914
Peak memory usage during training: 406.46875 MB
Prediction time: 1.0392942000034964
Peak memory usage during prediction: 398.3359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0054569999920204
Peak memory usage during training: 408.19921875 MB
Prediction time: 1.0442916000029072
Peak memory usage during prediction: 398.40625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.2987003999878652
Peak memory usage during training: 408.10546875 MB
Prediction time: 1.0374977999890689
Peak memory usage during prediction: 398.11328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.287049600010505
Peak memory usage during training: 406.0703125 MB
Prediction time: 1.031698700011475
Peak memory usage during prediction: 398.4140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0795510000025388
Peak memory usage during training: 408.10546875 MB
Prediction time: 1.0352764000126626
Peak memory usage during prediction: 398.01953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.3025800000032177
Peak memory usage during training: 407.48046875 MB
Prediction time: 1.0348794000019552
Peak memory usage during prediction: 398.13671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.2827853999915533
Peak memory usage during training: 407.32421875 MB
Prediction time: 1.032684000005247
Peak memory usage during prediction: 398.28515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0956423000025097
Peak memory usage during training: 408.11328125 MB
Prediction time: 1.0300471000082325
Peak memory usage during prediction: 397.98046875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 31.518176500001573
Peak memory usage during training: 407.91796875 MB
Prediction time: 1.0432129999971949
Peak memory usage during prediction: 403.5859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 34.71767479999107
Peak memory usage during training: 409.16796875 MB
Prediction time: 1.36244440000155
Peak memory usage during prediction: 403.59765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 50.82846319999953
Peak memory usage during training: 409.390625 MB
Prediction time: 1.1785898999951314
Peak memory usage during prediction: 400.08984375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 49.2457868999918
Peak memory usage during training: 408.76953125 MB
Prediction time: 1.1433394999912707
Peak memory usage during prediction: 399.5859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 66.44524790000287
Peak memory usage during training: 408.4375 MB
Prediction time: 1.167410199996084
Peak memory usage during prediction: 400.9765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 65.25136579999526
Peak memory usage during training: 409.7734375 MB
Prediction time: 1.1221601999859558
Peak memory usage during prediction: 400.83203125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.452734299993608
Peak memory usage during training: 409.34765625 MB
Prediction time: 1.1232213000039337
Peak memory usage during prediction: 400.36328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2872924000112107
Peak memory usage during training: 409.2578125 MB
Prediction time: 1.1366125000058673
Peak memory usage during prediction: 400.13671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.288887499991688
Peak memory usage during training: 409.75390625 MB
Prediction time: 1.1247000000003027
Peak memory usage during prediction: 400.13671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.8751224000006914
Peak memory usage during training: 409.28125 MB
Prediction time: 1.1455081000021892
Peak memory usage during prediction: 404.92578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.880250700007309
Peak memory usage during training: 409.04296875 MB
Prediction time: 1.1614921000000322
Peak memory usage during prediction: 400.2890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.8808684999967227
Peak memory usage during training: 408.8515625 MB
Prediction time: 1.162741600011941
Peak memory usage during prediction: 404.9375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.4628021999960765
Peak memory usage during training: 409.046875 MB
Prediction time: 1.1956405000091763
Peak memory usage during prediction: 400.20703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.463815399998566
Peak memory usage during training: 409.37890625 MB
Prediction time: 1.2014199999975972
Peak memory usage during prediction: 400.3359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.509821799991187
Peak memory usage during training: 409.86328125 MB
Prediction time: 1.208736200002022
Peak memory usage during prediction: 400.5 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7036577000108082
Peak memory usage during training: 408.3828125 MB
Prediction time: 1.1302403999870876
Peak memory usage during prediction: 406.1875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.7682163999998011
Peak memory usage during training: 407.984375 MB
Prediction time: 1.1079101000068476
Peak memory usage during prediction: 402.09375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7783733999967808
Peak memory usage during training: 407.5546875 MB
Prediction time: 1.096683199997642
Peak memory usage during prediction: 405.8671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.3810414000035962
Peak memory usage during training: 409.84375 MB
Prediction time: 1.0965002000011737
Peak memory usage during prediction: 406.01953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.7192349000106333
Peak memory usage during training: 408.734375 MB
Prediction time: 1.1014567999955034
Peak memory usage during prediction: 402.34375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.8201522000017576
Peak memory usage during training: 408.453125 MB
Prediction time: 1.095030600001337
Peak memory usage during prediction: 406.01171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7466773000051035
Peak memory usage during training: 409.3359375 MB
Prediction time: 1.0972162999969441
Peak memory usage during prediction: 402.33984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.7077064000040991
Peak memory usage during training: 408.44140625 MB
Prediction time: 1.0963186000008136
Peak memory usage during prediction: 406.0 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7157877999998163
Peak memory usage during training: 408.08984375 MB
Prediction time: 1.100727500001085
Peak memory usage during prediction: 402.32421875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.1614342000102624
Peak memory usage during training: 408.5 MB
Prediction time: 1.106114099995466
Peak memory usage during prediction: 395.38671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.2099217000068165
Peak memory usage during training: 403.3203125 MB
Prediction time: 1.1121281999949133
Peak memory usage during prediction: 395.765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.2205416999931913
Peak memory usage during training: 404.02734375 MB
Prediction time: 1.1204570999980206
Peak memory usage during prediction: 395.46875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.6385592000006
Peak memory usage during training: 405.0546875 MB
Prediction time: 1.1329575999989174
Peak memory usage during prediction: 403.46875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.7472186999948462
Peak memory usage during training: 405.9609375 MB
Prediction time: 1.1260925999959
Peak memory usage during prediction: 399.7109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.744541299995035
Peak memory usage during training: 406.7734375 MB
Prediction time: 1.1353647999931127
Peak memory usage during prediction: 403.375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 2.1166901999968104
Peak memory usage during training: 406.32421875 MB
Prediction time: 1.160031399995205
Peak memory usage during prediction: 402.33203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 2.3535110000084387
Peak memory usage during training: 410.08984375 MB
Prediction time: 1.2690077000006568
Peak memory usage during prediction: 403.0234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 2.414435799990315
Peak memory usage during training: 410.54296875 MB
Prediction time: 1.2035713000077521
Peak memory usage during prediction: 407.78515625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.7285510999936378
Peak memory usage during training: 413.68359375 MB
Prediction time: 0.8013370999979088
Peak memory usage during prediction: 406.82421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 3.4662048000027426
Peak memory usage during training: 409.78125 MB
Prediction time: 1.0655876000091666
Peak memory usage during prediction: 408.5625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 3.018785000007483
Peak memory usage during training: 413.55078125 MB
Prediction time: 0.9308833000104642
Peak memory usage during prediction: 407.79296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.7782174000021769
Peak memory usage during training: 414.1484375 MB
Prediction time: 0.8168117000022903
Peak memory usage during prediction: 405.66015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 2.9293506999965757
Peak memory usage during training: 412.515625 MB
Prediction time: 1.0837537000043085
Peak memory usage during prediction: 408.67578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.9149598999938462
Peak memory usage during training: 419.375 MB
Prediction time: 0.8087679999880493
Peak memory usage during prediction: 406.96875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.724919600004796
Peak memory usage during training: 415.3515625 MB
Prediction time: 0.7609700000029989
Peak memory usage during prediction: 407.2421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 3.1906815999973333
Peak memory usage during training: 413.484375 MB
Prediction time: 0.9700622999953339
Peak memory usage during prediction: 408.984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.4399981000024127
Peak memory usage during training: 413.1328125 MB
Prediction time: 0.7394149000028847
Peak memory usage during prediction: 407.05859375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.3516051000042353
Peak memory usage during training: 412.234375 MB
Prediction time: 1.0978723000007449
Peak memory usage during prediction: 404.11328125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.3472571000020253
Peak memory usage during training: 412.46875 MB
Prediction time: 1.1078123999905074
Peak memory usage during prediction: 403.62890625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.337651999987429
Peak memory usage during training: 410.83984375 MB
Prediction time: 1.0930332999996608
Peak memory usage during prediction: 403.671875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.2941251000011107
Peak memory usage during training: 448.33984375 MB
Prediction time: 1.0869491999910679
Peak memory usage during prediction: 403.65625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.238626899998053
Peak memory usage during training: 448.37890625 MB
Prediction time: 1.102373699992313
Peak memory usage during prediction: 403.7109375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8178666999883717
Peak memory usage during training: 443.61328125 MB
Prediction time: 1.095475099995383
Peak memory usage during prediction: 407.0859375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.3280476000072667
Peak memory usage during training: 411.40625 MB
Prediction time: 1.1814054999995278
Peak memory usage during prediction: 411.4609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.3471266999986256
Peak memory usage during training: 411.59765625 MB
Prediction time: 1.1795084000041243
Peak memory usage during prediction: 413.9453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.3412591999949655
Peak memory usage during training: 411.4921875 MB
Prediction time: 1.2025525999924866
Peak memory usage during prediction: 414.5078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.312281400008942
Peak memory usage during training: 412.86328125 MB
Prediction time: 1.2071869000064908
Peak memory usage during prediction: 415.3671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.401769999996759
Peak memory usage during training: 411.49609375 MB
Prediction time: 1.227529299998423
Peak memory usage during prediction: 412.53125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.3651908000028925
Peak memory usage during training: 411.453125 MB
Prediction time: 1.199056199999177
Peak memory usage during prediction: 414.32421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.3465120999899227
Peak memory usage during training: 411.4765625 MB
Prediction time: 1.264397300008568
Peak memory usage during prediction: 412.8984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.7895837999967625
Peak memory usage during training: 411.359375 MB
Prediction time: 1.3430403000093065
Peak memory usage during prediction: 416.6953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.4082541999960085
Peak memory usage during training: 414.0546875 MB
Prediction time: 1.3222270000114804
Peak memory usage during prediction: 419.37890625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 0.7398222000047099
Peak memory usage during training: 412.265625 MB
Prediction time: 1.2075832999980776
Peak memory usage during prediction: 406.0625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.4260778000025311
Peak memory usage during training: 412.35546875 MB
Prediction time: 1.1494972000073176
Peak memory usage during prediction: 407.765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9829552000010153
Peak memory usage during training: 412.3203125 MB
Prediction time: 1.1146546999952989
Peak memory usage during prediction: 407.2421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.3462586999958148
Peak memory usage during training: 412.31640625 MB
Prediction time: 1.141135400001076
Peak memory usage during prediction: 407.0078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.4665730999986408
Peak memory usage during training: 412.0703125 MB
Prediction time: 1.3168153000005987
Peak memory usage during prediction: 407.80859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.0171636999875773
Peak memory usage during training: 411.48828125 MB
Prediction time: 1.148183199999039
Peak memory usage during prediction: 407.29296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.3852458000037586
Peak memory usage during training: 412.34765625 MB
Prediction time: 1.0957648000039626
Peak memory usage during prediction: 406.09765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.3426966999977594
Peak memory usage during training: 412.7890625 MB
Prediction time: 1.0685387999983504
Peak memory usage during prediction: 406.96875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9595993999973871
Peak memory usage during training: 412.2890625 MB
Prediction time: 1.0407707999984268
Peak memory usage during prediction: 402.75390625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 18.320041600003606
Peak memory usage during training: 412.70703125 MB
Prediction time: 1.09380930000043
Peak memory usage during prediction: 402.3515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.151030499997432
Peak memory usage during training: 412.95703125 MB
Prediction time: 1.0571530000015628
Peak memory usage during prediction: 402.5859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 27.19876359999762
Peak memory usage during training: 412.52734375 MB
Prediction time: 1.126004699995974
Peak memory usage during prediction: 402.73828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 27.089791499995044
Peak memory usage during training: 413.05859375 MB
Prediction time: 1.0572658000019146
Peak memory usage during prediction: 406.703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 36.433400599999004
Peak memory usage during training: 413.10546875 MB
Prediction time: 1.1574961000005715
Peak memory usage during prediction: 403.3984375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 36.43082680000225
Peak memory usage during training: 412.88671875 MB
Prediction time: 1.1889702000044053
Peak memory usage during prediction: 407.44140625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7384254000062356
Peak memory usage during training: 411.9375 MB
Prediction time: 1.2340460999985225
Peak memory usage during prediction: 402.80859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.7712997999915387
Peak memory usage during training: 412.94140625 MB
Prediction time: 1.227513199992245
Peak memory usage during prediction: 407.2734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.6965825999941444
Peak memory usage during training: 412.12109375 MB
Prediction time: 1.1989018000022043
Peak memory usage during prediction: 402.77734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.667046999995364
Peak memory usage during training: 412.80078125 MB
Prediction time: 1.2036183000018355
Peak memory usage during prediction: 407.28125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.6161417000112124
Peak memory usage during training: 412.125 MB
Prediction time: 1.1396391000016592
Peak memory usage during prediction: 402.85546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.8716924999898765
Peak memory usage during training: 413.296875 MB
Prediction time: 1.2063022999936948
Peak memory usage during prediction: 407.28515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.797107499995036
Peak memory usage during training: 412.1328125 MB
Prediction time: 1.3790239000081783
Peak memory usage during prediction: 402.88671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.7764104999951087
Peak memory usage during training: 413.22265625 MB
Prediction time: 1.204685899996548
Peak memory usage during prediction: 407.33984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.5007122000097297
Peak memory usage during training: 412.03515625 MB
Prediction time: 1.1420045999984723
Peak memory usage during prediction: 402.8984375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3420392999978503
Peak memory usage during training: 410.640625 MB
Prediction time: 1.098285300002317
Peak memory usage during prediction: 403.71875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.7934396000055131
Peak memory usage during training: 410.4765625 MB
Prediction time: 1.1464806000003591
Peak memory usage during prediction: 407.1484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.829104999997071
Peak memory usage during training: 409.75390625 MB
Prediction time: 1.242385400008061
Peak memory usage during prediction: 403.70703125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.7826481999945827
Peak memory usage during training: 408.98828125 MB
Prediction time: 1.2175193000002764
Peak memory usage during prediction: 407.3359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.8679949999932433
Peak memory usage during training: 410.49609375 MB
Prediction time: 1.2002250000077765
Peak memory usage during prediction: 403.74609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.8473222000029637
Peak memory usage during training: 409.83203125 MB
Prediction time: 1.168247399997199
Peak memory usage during prediction: 407.35546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3459953000128735
Peak memory usage during training: 411.4765625 MB
Prediction time: 1.0769250999874203
Peak memory usage during prediction: 407.35546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9937474000034854
Peak memory usage during training: 410.3046875 MB
Prediction time: 1.0933064999990165
Peak memory usage during prediction: 407.53125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7565443999919808
Peak memory usage during training: 409.91015625 MB
Prediction time: 1.0790450999920722
Peak memory usage during prediction: 403.74609375 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.1376357999979518
Peak memory usage during training: 407.25 MB
Prediction time: 1.1274135999992723
Peak memory usage during prediction: 394.64453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.251276199996937
Peak memory usage during training: 402.37109375 MB
Prediction time: 1.2078757999988738
Peak memory usage during prediction: 395.0859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.352131299994653
Peak memory usage during training: 402.59765625 MB
Prediction time: 1.192478700002539
Peak memory usage during prediction: 395.109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.6906432999967365
Peak memory usage during training: 402.875 MB
Prediction time: 1.1676339999976335
Peak memory usage during prediction: 402.5078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.8754123000107938
Peak memory usage during training: 403.546875 MB
Prediction time: 1.1381737999909092
Peak memory usage during prediction: 399.12890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.9265434999979334
Peak memory usage during training: 404.4609375 MB
Prediction time: 1.2697647999884794
Peak memory usage during prediction: 403.1171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 2.1808285000006435
Peak memory usage during training: 406.51171875 MB
Prediction time: 1.2240569999994477
Peak memory usage during prediction: 401.78515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 2.4395186999900034
Peak memory usage during training: 406.0859375 MB
Prediction time: 1.126581199991051
Peak memory usage during prediction: 402.5234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 2.3767769999976736
Peak memory usage during training: 408.28515625 MB
Prediction time: 1.1720827000099234
Peak memory usage during prediction: 402.51953125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 3.325307299994165
Peak memory usage during training: 409.35546875 MB
Prediction time: 0.9426089000044158
Peak memory usage during prediction: 406.11328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.6383216999965953
Peak memory usage during training: 412.734375 MB
Prediction time: 1.075155900005484
Peak memory usage during prediction: 407.5546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 3.537662900009309
Peak memory usage during training: 411.57421875 MB
Prediction time: 0.9383271999977296
Peak memory usage during prediction: 407.1953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 2.8003720000124304
Peak memory usage during training: 412.33203125 MB
Prediction time: 0.8643704999994952
Peak memory usage during prediction: 408.3984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.5218949999980396
Peak memory usage during training: 411.23046875 MB
Prediction time: 0.9956392000021879
Peak memory usage during prediction: 407.26171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 2.2352742000075523
Peak memory usage during training: 412.42578125 MB
Prediction time: 0.8494362999917939
Peak memory usage during prediction: 407.359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 2.8432336000114447
Peak memory usage during training: 411.484375 MB
Prediction time: 0.8209843000076944
Peak memory usage during prediction: 407.16015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.468420999997761
Peak memory usage during training: 411.16015625 MB
Prediction time: 0.9782694000023184
Peak memory usage during prediction: 405.89453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 2.319376800005557
Peak memory usage during training: 412.25390625 MB
Prediction time: 0.7877447000064421
Peak memory usage during prediction: 407.37890625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.2869859999918845
Peak memory usage during training: 411.84375 MB
Prediction time: 1.0418342999910237
Peak memory usage during prediction: 407.66015625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.2917984000087017
Peak memory usage during training: 411.328125 MB
Prediction time: 1.0560318999923766
Peak memory usage during prediction: 405.80859375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.2833684000070207
Peak memory usage during training: 411.35546875 MB
Prediction time: 1.0519787000084762
Peak memory usage during prediction: 407.65625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7803913999960059
Peak memory usage during training: 430.984375 MB
Prediction time: 1.0538283999921987
Peak memory usage during prediction: 404.046875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.048155399999814
Peak memory usage during training: 445.58203125 MB
Prediction time: 1.0508157000003848
Peak memory usage during prediction: 404.06640625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0734464999986812
Peak memory usage during training: 443.4296875 MB
Prediction time: 1.0439841999905184
Peak memory usage during prediction: 404.046875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2785843000019668
Peak memory usage during training: 410.73046875 MB
Prediction time: 1.1087895999953616
Peak memory usage during prediction: 412.46875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2754825000010896
Peak memory usage during training: 411.6328125 MB
Prediction time: 1.1048717999947257
Peak memory usage during prediction: 410.640625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.282951500004856
Peak memory usage during training: 410.71875 MB
Prediction time: 1.1027697999961674
Peak memory usage during prediction: 413.59375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.6891284999874188
Peak memory usage during training: 409.6640625 MB
Prediction time: 1.120374999998603
Peak memory usage during prediction: 412.53515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2731769000092754
Peak memory usage during training: 410.6875 MB
Prediction time: 1.1003886999969836
Peak memory usage during prediction: 410.234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2772140000015497
Peak memory usage during training: 410.5625 MB
Prediction time: 1.1075141999899643
Peak memory usage during prediction: 413.66796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.278349000000162
Peak memory usage during training: 410.671875 MB
Prediction time: 1.1233956000069156
Peak memory usage during prediction: 408.94140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.284383499994874
Peak memory usage during training: 410.55859375 MB
Prediction time: 1.1150802999909502
Peak memory usage during prediction: 412.4609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2924507999996422
Peak memory usage during training: 410.25390625 MB
Prediction time: 1.1001193999982206
Peak memory usage during prediction: 412.6796875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.340324499993585
Peak memory usage during training: 411.4375 MB
Prediction time: 1.0638253999932203
Peak memory usage during prediction: 407.0078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.3001771999988705
Peak memory usage during training: 410.97265625 MB
Prediction time: 1.059196999995038
Peak memory usage during prediction: 406.39453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0342543000006117
Peak memory usage during training: 411.7421875 MB
Prediction time: 1.0563282999937655
Peak memory usage during prediction: 406.69140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.3267549000011059
Peak memory usage during training: 411.3671875 MB
Prediction time: 1.0541498999955365
Peak memory usage during prediction: 406.8046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.3278424000018276
Peak memory usage during training: 411.90234375 MB
Prediction time: 1.0486030000029132
Peak memory usage during prediction: 406.09375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.101269399994635
Peak memory usage during training: 411.32421875 MB
Prediction time: 1.060936000008951
Peak memory usage during prediction: 407.0703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.312492100012605
Peak memory usage during training: 411.44140625 MB
Prediction time: 1.052623700001277
Peak memory usage during prediction: 406.93359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.3027949000097578
Peak memory usage during training: 411.09765625 MB
Prediction time: 1.049921700003324
Peak memory usage during prediction: 407.30859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.100593300012406
Peak memory usage during training: 411.77734375 MB
Prediction time: 1.0503632000036305
Peak memory usage during prediction: 406.70703125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 32.28619080000499
Peak memory usage during training: 412.73046875 MB
Prediction time: 1.0564845999906538
Peak memory usage during prediction: 406.17578125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 32.1015003999928
Peak memory usage during training: 412.28125 MB
Prediction time: 1.0668196999904467
Peak memory usage during prediction: 402.2890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 47.92775060000713
Peak memory usage during training: 412.64453125 MB
Prediction time: 1.079258400000981
Peak memory usage during prediction: 402.5 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 47.64793140000256
Peak memory usage during training: 411.39453125 MB
Prediction time: 1.0617012000002433
Peak memory usage during prediction: 406.7890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 63.715539400000125
Peak memory usage during training: 412.8203125 MB
Prediction time: 1.0587596999976085
Peak memory usage during prediction: 397.0390625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 63.06786669998837
Peak memory usage during training: 406.87109375 MB
Prediction time: 1.0717970999976387
Peak memory usage during prediction: 401.3515625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2024079999973765
Peak memory usage during training: 406.13671875 MB
Prediction time: 1.0735379999969155
Peak memory usage during prediction: 401.2578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.204216500002076
Peak memory usage during training: 405.328125 MB
Prediction time: 1.0870617999898968
Peak memory usage during prediction: 400.52734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.210435699991649
Peak memory usage during training: 406.1796875 MB
Prediction time: 1.0846488999959547
Peak memory usage during prediction: 401.2734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.776741100009531
Peak memory usage during training: 405.3203125 MB
Prediction time: 1.1137549000122817
Peak memory usage during prediction: 397.05078125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.771510099992156
Peak memory usage during training: 406.1015625 MB
Prediction time: 1.118127599998843
Peak memory usage during prediction: 401.203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.7674218000029214
Peak memory usage during training: 405.33984375 MB
Prediction time: 1.1338194999989355
Peak memory usage during prediction: 397.05859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.3560839999991
Peak memory usage during training: 406.3046875 MB
Prediction time: 1.136931300003198
Peak memory usage during prediction: 397.05859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.325715800005128
Peak memory usage during training: 406.04296875 MB
Prediction time: 1.156503199992585
Peak memory usage during prediction: 397.05859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.365329899999779
Peak memory usage during training: 406.08984375 MB
Prediction time: 1.173468299995875
Peak memory usage during prediction: 397.05859375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.3137576000008266
Peak memory usage during training: 404.765625 MB
Prediction time: 1.0541528000030667
Peak memory usage during prediction: 397.94140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.7013229000003776
Peak memory usage during training: 403.625 MB
Prediction time: 1.0805355000047712
Peak memory usage during prediction: 401.1796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7671340999950189
Peak memory usage during training: 402.08203125 MB
Prediction time: 1.0551627999957418
Peak memory usage during prediction: 397.96875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.3266957000014372
Peak memory usage during training: 405.2109375 MB
Prediction time: 1.0427129000017885
Peak memory usage during prediction: 397.98828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.6849969999893801
Peak memory usage during training: 402.765625 MB
Prediction time: 1.0605262000026414
Peak memory usage during prediction: 401.22265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7563786999962758
Peak memory usage during training: 402.953125 MB
Prediction time: 1.0490032000088831
Peak memory usage during prediction: 397.953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.3035881000105292
Peak memory usage during training: 405.35546875 MB
Prediction time: 1.0448254000075394
Peak memory usage during prediction: 397.93359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.3334363999892958
Peak memory usage during training: 406.140625 MB
Prediction time: 1.0492205999908037
Peak memory usage during prediction: 397.93359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.6821591000043554
Peak memory usage during training: 402.44140625 MB
Prediction time: 1.0682647000066936
Peak memory usage during prediction: 399.86328125 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.1114263999916147
Peak memory usage during training: 402.65234375 MB
Prediction time: 1.0580293000093661
Peak memory usage during prediction: 394.74609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.1593633000011323
Peak memory usage during training: 397.72265625 MB
Prediction time: 1.0570106000086525
Peak memory usage during prediction: 395.19140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.17229679999582
Peak memory usage during training: 397.984375 MB
Prediction time: 1.0608690999943065
Peak memory usage during prediction: 395.2265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.5779675999947358
Peak memory usage during training: 397.515625 MB
Prediction time: 1.0815682999964338
Peak memory usage during prediction: 393.81640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.690136799996253
Peak memory usage during training: 401.54296875 MB
Prediction time: 1.0741293000028236
Peak memory usage during prediction: 398.57421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.6949389000074007
Peak memory usage during training: 401.37890625 MB
Prediction time: 1.0832159999990836
Peak memory usage during prediction: 394.4296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 2.043567400003667
Peak memory usage during training: 401.22265625 MB
Prediction time: 1.1004168999934336
Peak memory usage during prediction: 401.54296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 2.199776200010092
Peak memory usage during training: 404.125 MB
Prediction time: 1.0892004000052111
Peak memory usage during prediction: 402.78125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 2.2201426999963587
Peak memory usage during training: 404.17578125 MB
Prediction time: 1.096897600000375
Peak memory usage during prediction: 402.56640625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.617364899997483
Peak memory usage during training: 406.8125 MB
Prediction time: 0.7318196999985958
Peak memory usage during prediction: 401.734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 3.33396800000628
Peak memory usage during training: 406.33984375 MB
Prediction time: 1.0387781000026735
Peak memory usage during prediction: 403.09765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 2.9572745000041323
Peak memory usage during training: 408.546875 MB
Prediction time: 0.8980067999946186
Peak memory usage during prediction: 402.546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.6109560000040801
Peak memory usage during training: 409.95703125 MB
Prediction time: 0.7289794999960577
Peak memory usage during prediction: 400.7890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 2.695950900000753
Peak memory usage during training: 408.58203125 MB
Prediction time: 0.9427606000099331
Peak memory usage during prediction: 403.48046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.7511426999990363
Peak memory usage during training: 409.86328125 MB
Prediction time: 0.7552025000040885
Peak memory usage during prediction: 401.78515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.6201201999938348
Peak memory usage during training: 406.3359375 MB
Prediction time: 0.7297027000022354
Peak memory usage during prediction: 401.2734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 3.0753553999966243
Peak memory usage during training: 409.21484375 MB
Prediction time: 0.9373067999986233
Peak memory usage during prediction: 402.53125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.3899526000022888
Peak memory usage during training: 408.08203125 MB
Prediction time: 0.7161191000050167
Peak memory usage during prediction: 401.859375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.285461799998302
Peak memory usage during training: 408.625 MB
Prediction time: 1.0432725999999093
Peak memory usage during prediction: 399.69140625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.2775435000075959
Peak memory usage during training: 406.94140625 MB
Prediction time: 1.044985500004259
Peak memory usage during prediction: 399.2421875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.2738963999872794
Peak memory usage during training: 406.765625 MB
Prediction time: 1.0605664999893634
Peak memory usage during prediction: 399.21484375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1366861999995308
Peak memory usage during training: 441.2578125 MB
Prediction time: 1.0480311999999685
Peak memory usage during prediction: 399.21484375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.069884299999103
Peak memory usage during training: 442.96875 MB
Prediction time: 1.0499851000058698
Peak memory usage during prediction: 399.09375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.7832156000076793
Peak memory usage during training: 429.0234375 MB
Prediction time: 1.039016199996695
Peak memory usage during prediction: 402.8125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2693952999979956
Peak memory usage during training: 407.0703125 MB
Prediction time: 1.1350287000095705
Peak memory usage during prediction: 410.19921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2854225999908522
Peak memory usage during training: 407.4453125 MB
Prediction time: 1.1477354999951785
Peak memory usage during prediction: 407.8359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.3088608000107342
Peak memory usage during training: 406.87890625 MB
Prediction time: 1.1450382000039099
Peak memory usage during prediction: 407.703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.3186386000015773
Peak memory usage during training: 407.85546875 MB
Prediction time: 1.1393717000028118
Peak memory usage during prediction: 407.7109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2865847000066424
Peak memory usage during training: 407.16015625 MB
Prediction time: 1.1431199999933597
Peak memory usage during prediction: 410.44140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.3094215999881271
Peak memory usage during training: 406.953125 MB
Prediction time: 1.1366708999994444
Peak memory usage during prediction: 408.99609375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.278925699996762
Peak memory usage during training: 406.76953125 MB
Prediction time: 1.1386098000075435
Peak memory usage during prediction: 409.46875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2721225999994203
Peak memory usage during training: 407.00390625 MB
Prediction time: 1.1298959000123432
Peak memory usage during prediction: 408.4453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.27656769999885
Peak memory usage during training: 406.98828125 MB
Prediction time: 1.1443674999900395
Peak memory usage during prediction: 407.93359375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.3020910000050208
Peak memory usage during training: 406.75 MB
Prediction time: 1.046875900006853
Peak memory usage during prediction: 402.25 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.307766799989622
Peak memory usage during training: 407.04296875 MB
Prediction time: 1.0815168999979505
Peak memory usage during prediction: 402.62890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9332088000082877
Peak memory usage during training: 406.08984375 MB
Prediction time: 1.062943600001745
Peak memory usage during prediction: 398.1875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.3150626000133343
Peak memory usage during training: 406.83984375 MB
Prediction time: 1.0568327999935718
Peak memory usage during prediction: 398.0 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.2924099000083515
Peak memory usage during training: 406.8828125 MB
Prediction time: 1.0439263000007486
Peak memory usage during prediction: 398.48828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9325952000071993
Peak memory usage during training: 406.6640625 MB
Prediction time: 1.0496703999961028
Peak memory usage during prediction: 398.17578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.3060760999942431
Peak memory usage during training: 406.98828125 MB
Prediction time: 1.0746435000037309
Peak memory usage during prediction: 402.4609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.3172666000027675
Peak memory usage during training: 407.1640625 MB
Prediction time: 1.0545329000015045
Peak memory usage during prediction: 402.55078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9282284999935655
Peak memory usage during training: 406.0703125 MB
Prediction time: 1.0410461999999825
Peak memory usage during prediction: 398.14453125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 18.62444990000222
Peak memory usage during training: 408.09375 MB
Prediction time: 1.0592431999975815
Peak memory usage during prediction: 402.015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.37888109999767
Peak memory usage during training: 407.23046875 MB
Prediction time: 1.0697766999946907
Peak memory usage during prediction: 402.05859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 26.62186300000758
Peak memory usage during training: 408.58203125 MB
Prediction time: 1.060811300005298
Peak memory usage during prediction: 402.0859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 26.696454599994468
Peak memory usage during training: 407.7265625 MB
Prediction time: 1.0510178000113228
Peak memory usage during prediction: 402.28515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 34.748763199997484
Peak memory usage during training: 408.12109375 MB
Prediction time: 1.0480759999918519
Peak memory usage during prediction: 398.57421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 34.78822379998746
Peak memory usage during training: 407.77734375 MB
Prediction time: 1.0637999000027776
Peak memory usage during prediction: 402.87890625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.573362499999348
Peak memory usage during training: 406.39453125 MB
Prediction time: 1.060734799990314
Peak memory usage during prediction: 398.33984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5935723000002326
Peak memory usage during training: 407.46875 MB
Prediction time: 1.078806200006511
Peak memory usage during prediction: 402.671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.582149900001241
Peak memory usage during training: 407.15625 MB
Prediction time: 1.0743293999985326
Peak memory usage during prediction: 398.35546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.5240257999976166
Peak memory usage during training: 407.25390625 MB
Prediction time: 1.1096556999982568
Peak memory usage during prediction: 402.734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.487249099998735
Peak memory usage during training: 407.09375 MB
Prediction time: 1.1031439999933355
Peak memory usage during prediction: 398.41015625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.5476949000003515
Peak memory usage during training: 406.37109375 MB
Prediction time: 1.0978510999993887
Peak memory usage during prediction: 402.80859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.4016823999991175
Peak memory usage during training: 407.14453125 MB
Prediction time: 1.130829800007632
Peak memory usage during prediction: 398.421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.439181699999608
Peak memory usage during training: 407.54296875 MB
Prediction time: 1.1343842999922344
Peak memory usage during prediction: 398.36328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.460059499993804
Peak memory usage during training: 407.08203125 MB
Prediction time: 1.137778200005414
Peak memory usage during prediction: 398.359375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3352411999949254
Peak memory usage during training: 408.26171875 MB
Prediction time: 1.054013800006942
Peak memory usage during prediction: 399.21484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.7522218000085559
Peak memory usage during training: 405.11328125 MB
Prediction time: 1.0466513999999734
Peak memory usage during prediction: 402.1796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7617394999979297
Peak memory usage during training: 405.98828125 MB
Prediction time: 1.050524599995697
Peak memory usage during prediction: 399.23046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3302272000000812
Peak memory usage during training: 407.296875 MB
Prediction time: 1.0494251999916742
Peak memory usage during prediction: 399.26171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.8189190999983111
Peak memory usage during training: 405.71875 MB
Prediction time: 1.0485377000004519
Peak memory usage during prediction: 402.2578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7508545000018785
Peak memory usage during training: 406.234375 MB
Prediction time: 1.0489049000025261
Peak memory usage during prediction: 399.23828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.321366100004525
Peak memory usage during training: 407.30078125 MB
Prediction time: 1.0480352000013227
Peak memory usage during prediction: 399.26171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.951079500009655
Peak memory usage during training: 405.90234375 MB
Prediction time: 1.0512566000106744
Peak memory usage during prediction: 399.26953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7306458000093699
Peak memory usage during training: 405.7890625 MB
Prediction time: 1.0400086000008741
Peak memory usage during prediction: 402.46875 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.1150063000095543
Peak memory usage during training: 405.24609375 MB
Prediction time: 1.0625933000119403
Peak memory usage during prediction: 394.296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.200137599997106
Peak memory usage during training: 396.2890625 MB
Prediction time: 1.0745716999954311
Peak memory usage during prediction: 394.484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.1960007999878144
Peak memory usage during training: 397.16015625 MB
Prediction time: 1.066212399993674
Peak memory usage during prediction: 394.43359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.597272900005919
Peak memory usage during training: 397.41015625 MB
Prediction time: 1.0868797000002814
Peak memory usage during prediction: 393.359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.7564963000040734
Peak memory usage during training: 399.92578125 MB
Prediction time: 1.0870897999993758
Peak memory usage during prediction: 398.14453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.7673414000018965
Peak memory usage during training: 400.34375 MB
Prediction time: 1.130198400001973
Peak memory usage during prediction: 397.5078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 2.051202300004661
Peak memory usage during training: 399.59375 MB
Prediction time: 1.0938285000011092
Peak memory usage during prediction: 396.4140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 2.307106600012048
Peak memory usage during training: 402.20703125 MB
Prediction time: 1.101068200005102
Peak memory usage during prediction: 397.51171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 2.320444299999508
Peak memory usage during training: 403.36328125 MB
Prediction time: 1.1456247999885818
Peak memory usage during prediction: 397.69140625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 3.2774244000029285
Peak memory usage during training: 403.625 MB
Prediction time: 0.9295560000027763
Peak memory usage during prediction: 402.02734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.5664084000018192
Peak memory usage during training: 408.9765625 MB
Prediction time: 1.0417302999994718
Peak memory usage during prediction: 402.7890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 3.4491505000041798
Peak memory usage during training: 407.28515625 MB
Prediction time: 0.9276653999986593
Peak memory usage during prediction: 402.33984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 2.694310000006226
Peak memory usage during training: 408.84765625 MB
Prediction time: 0.8137656000035349
Peak memory usage during prediction: 402.55078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.458090900006937
Peak memory usage during training: 403.9375 MB
Prediction time: 0.9812108000041917
Peak memory usage during prediction: 402.9140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 2.222740299999714
Peak memory usage during training: 404.89453125 MB
Prediction time: 0.7924886000109836
Peak memory usage during prediction: 401.57421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 2.789916900001117
Peak memory usage during training: 404.87109375 MB
Prediction time: 0.8200782000058098
Peak memory usage during prediction: 400.7578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 3.458450299993274
Peak memory usage during training: 406.41796875 MB
Prediction time: 0.9855317000037758
Peak memory usage during prediction: 402.8671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 2.318619800003944
Peak memory usage during training: 407.6953125 MB
Prediction time: 0.7956576000142377
Peak memory usage during prediction: 400.9453125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.2907700999930967
Peak memory usage during training: 407.68359375 MB
Prediction time: 1.0482202999992296
Peak memory usage during prediction: 401.6171875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.2838899000053061
Peak memory usage during training: 405.8359375 MB
Prediction time: 1.04817079998611
Peak memory usage during prediction: 401.7109375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.2809868000040296
Peak memory usage during training: 407.5703125 MB
Prediction time: 1.056125199989765
Peak memory usage during prediction: 402.23046875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7939495000027819
Peak memory usage during training: 437.08984375 MB
Prediction time: 1.0490490999945905
Peak memory usage during prediction: 398.765625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0645985000010114
Peak memory usage during training: 436.1328125 MB
Prediction time: 1.0493165999941994
Peak memory usage during prediction: 398.75390625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.107525400002487
Peak memory usage during training: 439.1640625 MB
Prediction time: 1.0600647999963257
Peak memory usage during prediction: 398.76953125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2870824999990873
Peak memory usage during training: 406.10546875 MB
Prediction time: 1.1066391999920597
Peak memory usage during prediction: 406.7265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.298918100001174
Peak memory usage during training: 406.2265625 MB
Prediction time: 1.1097142000071472
Peak memory usage during prediction: 404.390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2854094000067562
Peak memory usage during training: 406.44921875 MB
Prediction time: 1.1062080999981845
Peak memory usage during prediction: 406.75390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2905579999933252
Peak memory usage during training: 407.46484375 MB
Prediction time: 1.1021403999911854
Peak memory usage during prediction: 407.95703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2793759000051068
Peak memory usage during training: 405.734375 MB
Prediction time: 1.1133918999985326
Peak memory usage during prediction: 408.96484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.2972630000003846
Peak memory usage during training: 407.93359375 MB
Prediction time: 1.1049698999995599
Peak memory usage during prediction: 410.984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2855532000103267
Peak memory usage during training: 405.6640625 MB
Prediction time: 1.1035995999991428
Peak memory usage during prediction: 411.66796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2936921999935294
Peak memory usage during training: 405.66015625 MB
Prediction time: 1.108173500004341
Peak memory usage during prediction: 408.37890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.271039799990831
Peak memory usage during training: 406.5546875 MB
Prediction time: 1.1210916999989422
Peak memory usage during prediction: 404.76171875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.3147234000061871
Peak memory usage during training: 406.890625 MB
Prediction time: 1.0522570999892196
Peak memory usage during prediction: 398.234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.2986691999976756
Peak memory usage during training: 405.6015625 MB
Prediction time: 1.0574138999945717
Peak memory usage during prediction: 398.21875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.016612300009001
Peak memory usage during training: 407.23046875 MB
Prediction time: 1.0617739000008442
Peak memory usage during prediction: 398.078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.3245266000012634
Peak memory usage during training: 406.015625 MB
Prediction time: 1.0497200999961933
Peak memory usage during prediction: 398.1171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.304170699993847
Peak memory usage during training: 406.5625 MB
Prediction time: 1.0524028000072576
Peak memory usage during prediction: 398.16796875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0964709999971092
Peak memory usage during training: 407.25390625 MB
Prediction time: 1.0488483999943128
Peak memory usage during prediction: 398.09375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.30988570000045
Peak memory usage during training: 406.76953125 MB
Prediction time: 1.046613400001661
Peak memory usage during prediction: 398.1328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.304523300001165
Peak memory usage during training: 406.234375 MB
Prediction time: 1.0442862000054447
Peak memory usage during prediction: 398.22265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0972461999917869
Peak memory usage during training: 406.33984375 MB
Prediction time: 1.0391009000013582
Peak memory usage during prediction: 397.96484375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 32.37774609999906
Peak memory usage during training: 406.30078125 MB
Prediction time: 1.0561259999958565
Peak memory usage during prediction: 401.49609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 32.23159290000331
Peak memory usage during training: 406.22265625 MB
Prediction time: 1.0536832000070717
Peak memory usage during prediction: 397.5078125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 47.740190499986056
Peak memory usage during training: 406.30078125 MB
Prediction time: 1.0560874999937369
Peak memory usage during prediction: 397.80078125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 47.58501939999405
Peak memory usage during training: 406.80859375 MB
Prediction time: 1.058262399994419
Peak memory usage during prediction: 397.48828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 63.52908629999729
Peak memory usage during training: 406.2890625 MB
Prediction time: 1.0539595000009285
Peak memory usage during prediction: 401.82421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 63.204594399998314
Peak memory usage during training: 407.62109375 MB
Prediction time: 1.0973515999939991
Peak memory usage during prediction: 398.4921875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.205386900008307
Peak memory usage during training: 407.203125 MB
Prediction time: 1.0849858000001404
Peak memory usage during prediction: 402.6640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2097460000077263
Peak memory usage during training: 405.33984375 MB
Prediction time: 1.0715160999970976
Peak memory usage during prediction: 402.1875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.2042511999898124
Peak memory usage during training: 404.9921875 MB
Prediction time: 1.0782079999917187
Peak memory usage during prediction: 402.203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.7526642000011634
Peak memory usage during training: 407.0390625 MB
Prediction time: 1.1035887000034563
Peak memory usage during prediction: 397.69921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.739587099989876
Peak memory usage during training: 406.10546875 MB
Prediction time: 1.1019766999961575
Peak memory usage during prediction: 401.91015625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.7469795000070008
Peak memory usage during training: 405.5 MB
Prediction time: 1.1522909000050277
Peak memory usage during prediction: 397.69140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.349457300006179
Peak memory usage during training: 406.0390625 MB
Prediction time: 1.1339265999995405
Peak memory usage during prediction: 397.15234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.3013085999991745
Peak memory usage during training: 405.34765625 MB
Prediction time: 1.138965600010124
Peak memory usage during prediction: 397.16796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.463269999992917
Peak memory usage during training: 405.58203125 MB
Prediction time: 1.244249099996523
Peak memory usage during prediction: 397.1953125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.7275407999986783
Peak memory usage during training: 403.7578125 MB
Prediction time: 1.0728180000005523
Peak memory usage during prediction: 400.8359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.7096620000083931
Peak memory usage during training: 404.0859375 MB
Prediction time: 1.0399333000095794
Peak memory usage during prediction: 397.8984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7468701000034343
Peak memory usage during training: 403.68359375 MB
Prediction time: 1.049344300001394
Peak memory usage during prediction: 401.1171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.3187910999986343
Peak memory usage during training: 406.12109375 MB
Prediction time: 1.0505735000042478
Peak memory usage during prediction: 400.96484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.3406009000027552
Peak memory usage during training: 406.1015625 MB
Prediction time: 1.0492889000015566
Peak memory usage during prediction: 400.9609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.7511727999954019
Peak memory usage during training: 403.6640625 MB
Prediction time: 1.0404444000014337
Peak memory usage during prediction: 398.0625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.2959140000020852
Peak memory usage during training: 405.3125 MB
Prediction time: 1.0453503000026103
Peak memory usage during prediction: 397.99609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.3556297000031918
Peak memory usage during training: 405.2890625 MB
Prediction time: 1.0439469999982975
Peak memory usage during prediction: 398.00390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.6763223000016296
Peak memory usage during training: 403.7578125 MB
Prediction time: 1.044401100007235
Peak memory usage during prediction: 401.12109375 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.1067242999997688
Peak memory usage during training: 403.078125 MB
Prediction time: 1.0605191999929957
Peak memory usage during prediction: 395.1640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.155877800003509
Peak memory usage during training: 397.8984375 MB
Prediction time: 1.0604148999991594
Peak memory usage during prediction: 395.08203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.1575724000140326
Peak memory usage during training: 397.984375 MB
Prediction time: 1.05830249999417
Peak memory usage during prediction: 395.28515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.565168500004802
Peak memory usage during training: 397.90234375 MB
Prediction time: 1.0694338999892352
Peak memory usage during prediction: 393.96484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.6725806000031298
Peak memory usage during training: 402.06640625 MB
Prediction time: 1.0856799999892246
Peak memory usage during prediction: 398.84375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.684186900005443
Peak memory usage during training: 401.3515625 MB
Prediction time: 1.071227499996894
Peak memory usage during prediction: 394.62890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 2.0517413999914424
Peak memory usage during training: 401.98046875 MB
Prediction time: 1.0938867999939248
Peak memory usage during prediction: 397.33203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 2.2017090000008466
Peak memory usage during training: 405.26953125 MB
Prediction time: 1.091207999998005
Peak memory usage during prediction: 402.81640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 2.1874678999884054
Peak memory usage during training: 404.5625 MB
Prediction time: 1.0950265999999829
Peak memory usage during prediction: 402.66015625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.614486599995871
Peak memory usage during training: 408.6640625 MB
Prediction time: 0.732008400009363
Peak memory usage during prediction: 401.8203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 3.3396930000017164
Peak memory usage during training: 407.48046875 MB
Prediction time: 1.0323129000025801
Peak memory usage during prediction: 400.99609375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 2.955436500007636
Peak memory usage during training: 410.48046875 MB
Prediction time: 0.894224599993322
Peak memory usage during prediction: 403.35546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.6138296999997692
Peak memory usage during training: 408.234375 MB
Prediction time: 0.7191044000064721
Peak memory usage during prediction: 400.9375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 2.6863749000040116
Peak memory usage during training: 406.43359375 MB
Prediction time: 0.9284779999870807
Peak memory usage during prediction: 402.4453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.7524359000090044
Peak memory usage during training: 407.58203125 MB
Prediction time: 0.7301678000076208
Peak memory usage during prediction: 401.671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.6178740000032121
Peak memory usage during training: 406.39453125 MB
Prediction time: 0.7294724999956088
Peak memory usage during prediction: 400.9375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 3.0748947999964003
Peak memory usage during training: 407.46484375 MB
Prediction time: 0.9345162999961758
Peak memory usage during prediction: 403.71875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.3867233000055421
Peak memory usage during training: 410.1796875 MB
Prediction time: 0.7116821999952663
Peak memory usage during prediction: 400.98046875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.2723754000035115
Peak memory usage during training: 406.4609375 MB
Prediction time: 1.0465760000079172
Peak memory usage during prediction: 403.04296875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.2721114000014495
Peak memory usage during training: 407.03515625 MB
Prediction time: 1.0478877999994438
Peak memory usage during prediction: 402.9296875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.2774996999942232
Peak memory usage during training: 405.73046875 MB
Prediction time: 1.047837799997069
Peak memory usage during prediction: 401.453125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.158322400006
Peak memory usage during training: 442.19140625 MB
Prediction time: 1.0412808999972185
Peak memory usage during prediction: 403.3671875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0147922999894945
Peak memory usage during training: 443.578125 MB
Prediction time: 1.0440624000038952
Peak memory usage during prediction: 403.23828125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.7738068000035128
Peak memory usage during training: 428.17578125 MB
Prediction time: 1.038183199998457
Peak memory usage during prediction: 399.50390625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2724015999992844
Peak memory usage during training: 406.5546875 MB
Prediction time: 1.1237426000006963
Peak memory usage during prediction: 410.25 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2716119000106119
Peak memory usage during training: 406.12890625 MB
Prediction time: 1.129819599998882
Peak memory usage during prediction: 411.14453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.2677775000047404
Peak memory usage during training: 406.40234375 MB
Prediction time: 1.131804299991927
Peak memory usage during prediction: 411.91796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.278447300006519
Peak memory usage during training: 406.40625 MB
Prediction time: 1.127928100002464
Peak memory usage during prediction: 409.203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2736035999987507
Peak memory usage during training: 406.296875 MB
Prediction time: 1.1337542999972356
Peak memory usage during prediction: 414.09375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.269998100004159
Peak memory usage during training: 407.2109375 MB
Prediction time: 1.128009899999597
Peak memory usage during prediction: 412.13671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2772409999888623
Peak memory usage during training: 406.40234375 MB
Prediction time: 1.1321887999947648
Peak memory usage during prediction: 408.64453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.2716899000079138
Peak memory usage during training: 406.13671875 MB
Prediction time: 1.1263898000033805
Peak memory usage during prediction: 412.57421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.2915030000003753
Peak memory usage during training: 405.828125 MB
Prediction time: 1.1299466000054963
Peak memory usage during prediction: 408.9375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.2981606999965152
Peak memory usage during training: 407.421875 MB
Prediction time: 1.0465258000040194
Peak memory usage during prediction: 398.21875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.2805508000019472
Peak memory usage during training: 407.34765625 MB
Prediction time: 1.0503341000003275
Peak memory usage during prediction: 398.21484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9174616999953287
Peak memory usage during training: 407.54296875 MB
Prediction time: 1.0422959999996237
Peak memory usage during prediction: 403.06640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.3002411000052234
Peak memory usage during training: 407.5703125 MB
Prediction time: 1.042468599989661
Peak memory usage during prediction: 403.046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.294347499992
Peak memory usage during training: 407.515625 MB
Prediction time: 1.039772999996785
Peak memory usage during prediction: 402.5859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9292805000004591
Peak memory usage during training: 406.37109375 MB
Prediction time: 1.0390974999900209
Peak memory usage during prediction: 397.9765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.289398799999617
Peak memory usage during training: 406.99609375 MB
Prediction time: 1.0398402999999234
Peak memory usage during prediction: 398.64453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.28444610000588
Peak memory usage during training: 406.5 MB
Prediction time: 1.050187700006063
Peak memory usage during prediction: 398.28515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9441664999903878
Peak memory usage during training: 407.2265625 MB
Prediction time: 1.049648400003207
Peak memory usage during prediction: 398.25 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 18.272018699994078
Peak memory usage during training: 406.5078125 MB
Prediction time: 1.058002799996757
Peak memory usage during prediction: 402.41015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 18.30040779999399
Peak memory usage during training: 407.8671875 MB
Prediction time: 1.0661158000002615
Peak memory usage during prediction: 402.45703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 26.458539200000814
Peak memory usage during training: 405.8828125 MB
Prediction time: 1.048876000000746
Peak memory usage during prediction: 397.86328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 26.53026780000073
Peak memory usage during training: 407.01953125 MB
Prediction time: 1.0666284000035375
Peak memory usage during prediction: 402.765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 34.61233960000391
Peak memory usage during training: 406.4765625 MB
Prediction time: 1.0543313999951351
Peak memory usage during prediction: 402.49609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 34.67933850000554
Peak memory usage during training: 408.328125 MB
Prediction time: 1.0519029999995837
Peak memory usage during prediction: 402.90625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5592534000024898
Peak memory usage during training: 407.23046875 MB
Prediction time: 1.0631367999885697
Peak memory usage during prediction: 398.30859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5904316999949515
Peak memory usage during training: 407.984375 MB
Prediction time: 1.0778678999922704
Peak memory usage during prediction: 402.94140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5589059999911115
Peak memory usage during training: 407.47265625 MB
Prediction time: 1.0909979999996722
Peak memory usage during prediction: 398.375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.4978437999961898
Peak memory usage during training: 407.53515625 MB
Prediction time: 1.1043686999910278
Peak memory usage during prediction: 398.328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.4949848000105703
Peak memory usage during training: 407.171875 MB
Prediction time: 1.1067425000073854
Peak memory usage during prediction: 402.66796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.494291199996951
Peak memory usage during training: 407.53125 MB
Prediction time: 1.1034283000044525
Peak memory usage during prediction: 398.34375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.4020289000036428
Peak memory usage during training: 407.3984375 MB
Prediction time: 1.1289216000004672
Peak memory usage during prediction: 398.25 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.4281303999887314
Peak memory usage during training: 406.40234375 MB
Prediction time: 1.131442199999583
Peak memory usage during prediction: 398.3046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.396874800004298
Peak memory usage during training: 407.11328125 MB
Prediction time: 1.1290780999988783
Peak memory usage during prediction: 398.1171875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3380876000010176
Peak memory usage during training: 406.66796875 MB
Prediction time: 1.048709399998188
Peak memory usage during prediction: 399.36328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.7540000999870244
Peak memory usage during training: 407.2265625 MB
Prediction time: 1.0491976000048453
Peak memory usage during prediction: 402.828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.8034937999909744
Peak memory usage during training: 406.7109375 MB
Prediction time: 1.040650299997651
Peak memory usage during prediction: 399.421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3186713000031887
Peak memory usage during training: 406.609375 MB
Prediction time: 1.0451299999986077
Peak memory usage during prediction: 399.4453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.899474799996824
Peak memory usage during training: 407.36328125 MB
Prediction time: 1.0418191000062507
Peak memory usage during prediction: 402.93359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7427161000086926
Peak memory usage during training: 405.61328125 MB
Prediction time: 1.0361790000024484
Peak memory usage during prediction: 399.55859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3185468000010587
Peak memory usage during training: 408.46484375 MB
Prediction time: 1.037004399986472
Peak memory usage during prediction: 399.44140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.8660770999995293
Peak memory usage during training: 407.265625 MB
Prediction time: 1.0447722999961115
Peak memory usage during prediction: 402.8671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.7433184000110487
Peak memory usage during training: 406.015625 MB
Prediction time: 1.0407811000040965
Peak memory usage during prediction: 399.4296875 MB
----------------------------------------------------------------------------------------------------

# Process results

In [10]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seed                    396 non-null    object
 1   vectorizer              396 non-null    object
 2   model                   396 non-null    object
 3   params                  396 non-null    object
 4   accuracy                396 non-null    float64
 5   training_time           396 non-null    float64
 6   prediction_time         396 non-null    float64
 7   peak_memory_train       396 non-null    float64
 8   peak_memory_prediction  396 non-null    float64
 9   precision_class_0       396 non-null    float64
 10  recall_class_0          396 non-null    float64
 11  f1_class_0              396 non-null    float64
 12  precision_class_1       396 non-null    float64
 13  recall_class_1          396 non-null    float64
 14  f1_class_1              396 non-null    float64
 15  precision_class_2       396 non-null    float64
 16  recall_class_2          396 non-null    float64
 17  f1_class_2              396 non-null    float64
 18  precision_class_3       396 non-null    float64
 19  recall_class_3          396 non-null    float64
 20  f1_class_3              396 non-null    float64
 21  precision_class_4       396 non-null    float64
 22  recall_class_4          396 non-null    float64
 23  f1_class_4              396 non-null    float64
dtypes: float64(20), object(4)
memory usage: 74.4+ KB

In [11]:
results.head()

,seed,vectorizer,model,params,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,...,f1_class_1,precision_class_2,recall_class_2,f1_class_2,precision_class_3,recall_class_3,f1_class_3,precision_class_4,recall_class_4,f1_class_4
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.931398,1.106779,1.068134,384.792969,384.851562,0.870000,...,0.907692,0.955882,0.915493,0.935252,0.945652,1.0,0.972067,1.000000,0.808824,0.894309
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.920844,1.190881,1.068049,387.882812,385.812500,0.913978,...,0.907692,0.984615,0.901408,0.941176,0.870000,1.0,0.930481,0.947368,0.794118,0.864000
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.920844,1.187173,1.064043,388.699219,385.851562,0.913978,...,0.907692,0.984615,0.901408,0.941176,0.870000,1.0,0.930481,0.947368,0.794118,0.864000
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.941953,1.563361,1.079595,388.144531,388.847656,0.905263,...,0.932331,0.969697,0.901408,0.934307,0.935484,1.0,0.966667,1.000000,0.852941,0.920635
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.934037,1.751320,1.072379,390.558594,388.839844,0.934066,...,0.916031,0.955882,0.915493,0.935252,0.896907,1.0,0.945652,0.982759,0.838235,0.904762

In [12]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,...,precision_class_2,recall_class_2,f1_class_2,precision_class_3,recall_class_3,f1_class_3,precision_class_4,recall_class_4,f1_class_4,f1_avg
0,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.01}",3.333333,0.641161,2.562972,1.139214,409.196615,402.781250,0.493243,...,1.000000,0.450704,0.621359,0.615942,0.977011,0.755556,0.923077,0.352941,0.510638,0.616617
1,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.1}",3.333333,0.791557,2.532792,1.116509,408.796875,401.311198,0.666667,...,0.750000,0.887324,0.812903,0.851485,0.988506,0.914894,1.000000,0.352941,0.521739,0.769002
2,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 1.0}",3.333333,0.757256,2.637893,1.135861,409.066406,402.812500,0.707071,...,0.671053,0.718310,0.693878,0.774510,0.908046,0.835979,0.952381,0.588235,0.727273,0.751170
3,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.01}",3.333333,0.672823,3.533606,1.212925,408.891927,399.852865,0.477419,...,1.000000,0.478873,0.647619,0.708333,0.977011,0.821256,0.954545,0.308824,0.466667,0.653282
4,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.1}",3.333333,0.815303,3.547908,1.156837,409.055990,401.335938,0.683333,...,0.777778,0.887324,0.828947,0.924731,0.988506,0.955556,1.000000,0.338235,0.505495,0.788329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'rbf'}",3.333333,0.965699,3.463356,0.981915,404.225260,402.036458,0.945055,...,0.985294,0.943662,0.964029,0.945652,1.000000,0.972067,1.000000,0.882353,0.937500,0.964993
128,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'sigmoid'}",3.333333,0.970976,2.212927,0.808624,405.304688,401.169271,0.943820,...,0.971014,0.943662,0.957143,0.988636,1.000000,0.994286,0.984848,0.955882,0.970149,0.970713
129,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'linear'}",3.333333,0.973615,2.791721,0.817905,405.257812,401.217448,0.954545,...,0.971014,0.943662,0.957143,0.988636,1.000000,0.994286,0.984848,0.955882,0.970149,0.973330
130,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'rbf'}",3.333333,0.965699,3.447231,0.977326,405.425781,401.761719,0.945055,...,0.985294,0.943662,0.964029,0.945652,1.000000,0.972067,1.000000,0.882353,0.937500,0.964993
131,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'sigmoid'}",3.333333,0.970976,2.307812,0.787206,406.907552,401.162760,0.965116,...,0.957746,0.957746,0.957746,0.977528,1.000000,0.988636,0.984848,0.955882,0.970149,0.970703

In [13]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train['label'])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test['label'], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test['label'], y_pred, average=None, labels=classes, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: MultinomialNB
Best model params: {'alpha': 0.1}
Best vectorizer: CountVectorizer
Best accuracy: 0.9850299401197605

Class 0
Precision: 1.0
Recall: 0.9605263157894737
F1: 0.9798657718120806
Support: 76

Class 1
Precision: 0.9824561403508771
Recall: 0.9655172413793104
F1: 0.9739130434782609
Support: 58

Class 2
Precision: 0.984375
Recall: 1.0
F1: 0.9921259842519685
Support: 63

Class 3
Precision: 1.0
Recall: 1.0
F1: 1.0
Support: 77

Class 4
Precision: 0.9523809523809523
Recall: 1.0
F1: 0.975609756097561
Support: 60

In [14]:
with open('models/best_model_sklearn_multiclass2.pkl', 'wb') as f:
    pickle.dump(pipeline, f)