# Importing libraries

In [3]:
# Basic libraries
import pandas as pd
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from memory_profiler import memory_usage

# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [4]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [5]:
ds = load_dataset("cardiffnlp/tweet_eval", "irony")

train = ds['train'].to_pandas()
val = ds['validation'].to_pandas()
test = ds['test'].to_pandas()

train

                                                   text  label
0     seeing ppl walking w/ crutches makes me really...      1
1     look for the girl with the broken smile, ask h...      0
2     Now I remember why I buy books online @user #s...      1
3     @user @user So is he banded from wearing the c...      1
4     Just found out there are Etch A Sketch apps.  ...      1
...                                                 ...    ...
2857  I don't have to respect your beliefs.||I only ...      0
2858  Women getting hit on by married managers at @u...      1
2859  @user no but i followed you and i saw you post...      0
2860  @user I dont know what it is but I'm in love y...      0
2861  @user @user @user For having union representat...      1

[2862 rows x 2 columns]

# Dataset preprocessing

In [6]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [7]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': SVC(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': LogisticRegression(max_iter=1000),
        'params': {
            'C': [0.1, 1, 10],
            'penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': GradientBoostingClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': SGDClassifier(),
        'params': {
            'alpha': [0.0001, 0.001, 0.01],
            'penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [8]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = sorted(train['label'].unique())
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [9]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train['label'])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                accuracy = accuracy_score(val['label'], y_pred)
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val['label'], y_pred, average=None, labels=classes, zero_division=0)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_binary3.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.4229368000014802
Peak memory usage during training: 375.06640625 MB
Prediction time: 1.5393062000002828
Peak memory usage during prediction: 374.1640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_19876\2750059118.py:66: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 1.341890499999863
Peak memory usage during training: 374.66015625 MB
Prediction time: 1.033367799995176
Peak memory usage during prediction: 373.9453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.3755227999936324
Peak memory usage during training: 375.4140625 MB
Prediction time: 1.1089317000005394
Peak memory usage during prediction: 373.95703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 2.277243600001384
Peak memory usage during training: 383.33984375 MB
Prediction time: 1.049833099998068
Peak memory usage during prediction: 382.67578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 2.2697283000015887
Peak memory usage during training: 382.9375 MB
Prediction time: 1.1356059999961872
Peak memory usage during prediction: 381.84375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 2.25501219999569
Peak memory usage during training: 382.31640625 MB
Prediction time: 1.1624003999968409
Peak memory usage during prediction: 381.84375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 3.1634032000001753
Peak memory usage during training: 391.64453125 MB
Prediction time: 1.2033138999977382
Peak memory usage during prediction: 391.6953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 3.1564206999973976
Peak memory usage during training: 390.98046875 MB
Prediction time: 1.2251431999975466
Peak memory usage during prediction: 390.6171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 3.0687099999995553
Peak memory usage during training: 391.0 MB
Prediction time: 1.0943072000009124
Peak memory usage during prediction: 390.21875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.874266799997713
Peak memory usage during training: 417.15234375 MB
Prediction time: 1.1435943000033149
Peak memory usage during prediction: 397.4921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9130130000048666
Peak memory usage during training: 418.4921875 MB
Prediction time: 1.224537900001451
Peak memory usage during prediction: 391.76171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.899098400004732
Peak memory usage during training: 417.5 MB
Prediction time: 1.1537119000058738
Peak memory usage during prediction: 397.73828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.9598475000020699
Peak memory usage during training: 420.5703125 MB
Prediction time: 1.1616414000018267
Peak memory usage during prediction: 391.90234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.927903800002241
Peak memory usage during training: 424.4375 MB
Prediction time: 1.2345126000000164
Peak memory usage during prediction: 391.37890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.9143777999997837
Peak memory usage during training: 425.0859375 MB
Prediction time: 1.1348456000050646
Peak memory usage during prediction: 391.484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.007412500002829
Peak memory usage during training: 421.0859375 MB
Prediction time: 1.1890419999981532
Peak memory usage during prediction: 397.90625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9538264000002528
Peak memory usage during training: 424.78125 MB
Prediction time: 1.2207473000016762
Peak memory usage during prediction: 391.9765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.8669222999960766
Peak memory usage during training: 418.14453125 MB
Prediction time: 1.1448511999988114
Peak memory usage during prediction: 399.91015625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 2.129743600002257
Peak memory usage during training: 393.91015625 MB
Prediction time: 1.999465799999598
Peak memory usage during prediction: 392.6875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.934528699996008
Peak memory usage during training: 393.4375 MB
Prediction time: 1.9616048999960185
Peak memory usage during prediction: 392.4453125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.08310789999814
Peak memory usage during training: 393.421875 MB
Prediction time: 2.089631000002555
Peak memory usage during prediction: 392.45703125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.118427100002009
Peak memory usage during training: 394.60546875 MB
Prediction time: 1.9604793000034988
Peak memory usage during prediction: 392.16796875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.6066688999999315
Peak memory usage during training: 394.5625 MB
Prediction time: 1.9217762999978731
Peak memory usage during prediction: 392.1484375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0610836999985622
Peak memory usage during training: 394.5546875 MB
Prediction time: 2.0888861999992514
Peak memory usage during prediction: 392.1484375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.6355862000054913
Peak memory usage during training: 393.08984375 MB
Prediction time: 1.0784155000001192
Peak memory usage during prediction: 430.13671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.5106105000013486
Peak memory usage during training: 393.19140625 MB
Prediction time: 1.1633771999986493
Peak memory usage during prediction: 438.2109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.609476799996628
Peak memory usage during training: 393.17578125 MB
Prediction time: 1.1584978999962914
Peak memory usage during prediction: 432.66796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.5939644000027329
Peak memory usage during training: 393.1796875 MB
Prediction time: 1.1182257999971625
Peak memory usage during prediction: 421.54296875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.038892800002941
Peak memory usage during training: 393.1796875 MB
Prediction time: 1.1277584999988903
Peak memory usage during prediction: 434.28125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.557158800002071
Peak memory usage during training: 393.1484375 MB
Prediction time: 1.1018573000037577
Peak memory usage during prediction: 419.33203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.031690999996499
Peak memory usage during training: 393.15625 MB
Prediction time: 1.0441868999987491
Peak memory usage during prediction: 434.42578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.4666675999978906
Peak memory usage during training: 393.32421875 MB
Prediction time: 1.049167999997735
Peak memory usage during prediction: 420.953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.4786863999979687
Peak memory usage during training: 393.28515625 MB
Prediction time: 1.040611500000523
Peak memory usage during prediction: 419.46484375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.0479116999995313
Peak memory usage during training: 399.5703125 MB
Prediction time: 1.9350000000049477
Peak memory usage during prediction: 392.8828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.056521700003941
Peak memory usage during training: 393.83984375 MB
Prediction time: 1.8816999999980908
Peak memory usage during prediction: 393.07421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.8848741999972844
Peak memory usage during training: 393.80859375 MB
Prediction time: 1.8736475000041537
Peak memory usage during prediction: 392.82421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.0591011000069557
Peak memory usage during training: 393.83984375 MB
Prediction time: 1.8794043000016245
Peak memory usage during prediction: 392.76953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.0445478999972693
Peak memory usage during training: 393.91796875 MB
Prediction time: 1.8917025999980979
Peak memory usage during prediction: 392.9453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9204714999941643
Peak memory usage during training: 393.80078125 MB
Prediction time: 1.867345300001034
Peak memory usage during prediction: 392.828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.0958591000016895
Peak memory usage during training: 393.83203125 MB
Prediction time: 1.8631074000004446
Peak memory usage during prediction: 392.7578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.0486572000008891
Peak memory usage during training: 393.83203125 MB
Prediction time: 1.8685803999978816
Peak memory usage during prediction: 393.03515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9280236999984481
Peak memory usage during training: 393.76953125 MB
Prediction time: 1.8816268000009586
Peak memory usage during prediction: 392.796875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.4173809999992955
Peak memory usage during training: 394.1796875 MB
Prediction time: 1.8821998999992502
Peak memory usage during prediction: 393.7421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.407581699997536
Peak memory usage during training: 394.296875 MB
Prediction time: 1.877057400000922
Peak memory usage during prediction: 393.98828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.8505979000037769
Peak memory usage during training: 394.30078125 MB
Prediction time: 1.903159900000901
Peak memory usage during prediction: 394.11328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.8518483000007109
Peak memory usage during training: 394.296875 MB
Prediction time: 1.9031681999986176
Peak memory usage during prediction: 393.99609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 2.342718400002923
Peak memory usage during training: 394.390625 MB
Prediction time: 1.8841408000007505
Peak memory usage during prediction: 394.1015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 2.3381234999978915
Peak memory usage during training: 394.4140625 MB
Prediction time: 2.0490606000021216
Peak memory usage during prediction: 393.9296875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7724463999984437
Peak memory usage during training: 394.4765625 MB
Prediction time: 1.9385966999980155
Peak memory usage during prediction: 393.609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7294547999990755
Peak memory usage during training: 394.34375 MB
Prediction time: 1.952985699994315
Peak memory usage during prediction: 393.38671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8195483000017703
Peak memory usage during training: 394.14453125 MB
Prediction time: 2.1540451000037137
Peak memory usage during prediction: 393.38671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0226470999987214
Peak memory usage during training: 394.12890625 MB
Prediction time: 1.6148281999994651
Peak memory usage during prediction: 393.37109375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.010736000003817
Peak memory usage during training: 394.1484375 MB
Prediction time: 1.6550648999982513
Peak memory usage during prediction: 393.390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9855298999973456
Peak memory usage during training: 394.140625 MB
Prediction time: 2.0541952999992645
Peak memory usage during prediction: 393.3984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1918581999998423
Peak memory usage during training: 394.140625 MB
Prediction time: 1.0205844000010984
Peak memory usage during prediction: 393.40625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1570904000036535
Peak memory usage during training: 394.15625 MB
Prediction time: 1.4887384999965434
Peak memory usage during prediction: 393.40625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1790123999962816
Peak memory usage during training: 394.1484375 MB
Prediction time: 1.0106910000031348
Peak memory usage during prediction: 393.4140625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.4907330999994883
Peak memory usage during training: 394.2890625 MB
Prediction time: 1.8722357999940868
Peak memory usage during prediction: 393.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.0499105999988387
Peak memory usage during training: 394.3203125 MB
Prediction time: 1.8692269000021042
Peak memory usage during prediction: 393.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.016141799998877
Peak memory usage during training: 394.328125 MB
Prediction time: 1.8676942000020063
Peak memory usage during prediction: 393.5625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.4913324000008288
Peak memory usage during training: 394.328125 MB
Prediction time: 1.864867399999639
Peak memory usage during prediction: 393.5390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.4749986000024364
Peak memory usage during training: 394.3046875 MB
Prediction time: 1.896801000002597
Peak memory usage during prediction: 393.5390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.48364930000389
Peak memory usage during training: 394.31640625 MB
Prediction time: 1.865352199994959
Peak memory usage during prediction: 393.55078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.9517622999992454
Peak memory usage during training: 394.28515625 MB
Prediction time: 1.859426099996199
Peak memory usage during prediction: 393.55078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.9356369999950402
Peak memory usage during training: 394.28515625 MB
Prediction time: 1.8681785000007949
Peak memory usage during prediction: 393.55078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.9979961999997613
Peak memory usage during training: 394.28515625 MB
Prediction time: 1.8839557000028435
Peak memory usage during prediction: 393.55078125 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.425717000005534
Peak memory usage during training: 393.55078125 MB
Prediction time: 1.505619099996693
Peak memory usage during prediction: 379.40234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.3677831000022707
Peak memory usage during training: 382.12890625 MB
Prediction time: 1.0146087999964948
Peak memory usage during prediction: 379.05859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.36341619999439
Peak memory usage during training: 381.7734375 MB
Prediction time: 1.0145926000041072
Peak memory usage during prediction: 379.1875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 2.3249072000035085
Peak memory usage during training: 389.9609375 MB
Prediction time: 1.051803700000164
Peak memory usage during prediction: 389.12890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 2.256752499997674
Peak memory usage during training: 389.640625 MB
Prediction time: 1.109303400000499
Peak memory usage during prediction: 388.45703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 2.238535700002103
Peak memory usage during training: 389.67578125 MB
Prediction time: 1.0641474000003655
Peak memory usage during prediction: 388.4609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 3.2292949999973644
Peak memory usage during training: 399.54296875 MB
Prediction time: 1.1068868000002112
Peak memory usage during prediction: 398.83203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 3.0970547999968403
Peak memory usage during training: 398.859375 MB
Prediction time: 1.1178291999967769
Peak memory usage during prediction: 398.1640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 3.0999460000020918
Peak memory usage during training: 398.640625 MB
Prediction time: 1.113275199997588
Peak memory usage during prediction: 398.765625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 0.8693901000006008
Peak memory usage during training: 425.29296875 MB
Prediction time: 1.1173495999973966
Peak memory usage during prediction: 405.140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.9023935000004712
Peak memory usage during training: 425.83203125 MB
Prediction time: 1.2423191999987466
Peak memory usage during prediction: 399.12109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.8750553000063519
Peak memory usage during training: 424.9609375 MB
Prediction time: 1.1434957000019494
Peak memory usage during prediction: 398.9375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.1044127000059234
Peak memory usage during training: 430.08203125 MB
Prediction time: 1.1560796999983722
Peak memory usage during prediction: 405.1015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.948022900003707
Peak memory usage during training: 425.22265625 MB
Prediction time: 1.2191711999985273
Peak memory usage during prediction: 399.16015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.8566408999977284
Peak memory usage during training: 424.29296875 MB
Prediction time: 1.2114442000020063
Peak memory usage during prediction: 399.1640625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.0851936000035494
Peak memory usage during training: 429.0859375 MB
Prediction time: 1.1418591999972705
Peak memory usage during prediction: 405.3984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.012716699995508
Peak memory usage during training: 431.390625 MB
Prediction time: 1.208712599996943
Peak memory usage during prediction: 399.6953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.8302669999975478
Peak memory usage during training: 421.375 MB
Prediction time: 1.0553058000004967
Peak memory usage during prediction: 405.50390625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.927458199999819
Peak memory usage during training: 399.98046875 MB
Prediction time: 1.851515999995172
Peak memory usage during prediction: 399.0 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.8937939000024926
Peak memory usage during training: 400.1953125 MB
Prediction time: 1.8957837999987532
Peak memory usage during prediction: 398.8046875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.4762840000039432
Peak memory usage during training: 399.96875 MB
Prediction time: 1.8183664000025601
Peak memory usage during prediction: 398.76171875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.007771299999149
Peak memory usage during training: 401.421875 MB
Prediction time: 1.85083460000169
Peak memory usage during prediction: 398.89453125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.024325400001544
Peak memory usage during training: 401.30078125 MB
Prediction time: 1.8419531999970786
Peak memory usage during prediction: 398.88671875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0250319999977364
Peak memory usage during training: 401.3359375 MB
Prediction time: 1.8429393999977037
Peak memory usage during prediction: 398.88671875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.442339000001084
Peak memory usage during training: 399.89453125 MB
Prediction time: 1.0604585999972187
Peak memory usage during prediction: 433.6953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.4357133000012254
Peak memory usage during training: 399.68359375 MB
Prediction time: 1.059497399997781
Peak memory usage during prediction: 435.46484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.436118700003135
Peak memory usage during training: 399.68359375 MB
Prediction time: 1.0530166999960784
Peak memory usage during prediction: 446.5546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.4407683000026736
Peak memory usage during training: 399.625 MB
Prediction time: 1.0571563000048627
Peak memory usage during prediction: 425.86328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.4416579000026104
Peak memory usage during training: 399.625 MB
Prediction time: 1.0570970999979181
Peak memory usage during prediction: 443.515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8892030999995768
Peak memory usage during training: 399.609375 MB
Prediction time: 1.0580885000017588
Peak memory usage during prediction: 443.2421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.4310691999999108
Peak memory usage during training: 399.609375 MB
Prediction time: 1.0656023999981699
Peak memory usage during prediction: 436.703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9431687999967835
Peak memory usage during training: 399.609375 MB
Prediction time: 1.056511100003263
Peak memory usage during prediction: 445.34375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.9027451999936602
Peak memory usage during training: 399.609375 MB
Prediction time: 1.0881832000013674
Peak memory usage during prediction: 432.05078125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.1017921000020579
Peak memory usage during training: 399.98828125 MB
Prediction time: 2.048857699999644
Peak memory usage during prediction: 398.98046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0673729000045569
Peak memory usage during training: 400.4375 MB
Prediction time: 1.8768065999975079
Peak memory usage during prediction: 399.08203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.8350968000013381
Peak memory usage during training: 399.95703125 MB
Prediction time: 1.8957415000040783
Peak memory usage during prediction: 398.76953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.0380223000029218
Peak memory usage during training: 399.90625 MB
Prediction time: 1.8416003000020282
Peak memory usage during prediction: 398.9765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0404387000016868
Peak memory usage during training: 400.4765625 MB
Prediction time: 1.851396099998965
Peak memory usage during prediction: 399.08203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.8742896000039764
Peak memory usage during training: 399.95703125 MB
Prediction time: 1.843070599999919
Peak memory usage during prediction: 398.76953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.0452673000036157
Peak memory usage during training: 399.95703125 MB
Prediction time: 1.8385928999996395
Peak memory usage during prediction: 398.98828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.1137421999956132
Peak memory usage during training: 400.4375 MB
Prediction time: 1.887093500001356
Peak memory usage during prediction: 399.09375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9302814999973634
Peak memory usage during training: 399.96875 MB
Prediction time: 1.894738100003451
Peak memory usage during prediction: 398.7578125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.239997399999993
Peak memory usage during training: 399.80859375 MB
Prediction time: 1.9218935999961104
Peak memory usage during prediction: 399.0703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.2437196000028052
Peak memory usage during training: 399.78515625 MB
Prediction time: 1.9007042000012007
Peak memory usage during prediction: 399.08203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.610171200001787
Peak memory usage during training: 399.796875 MB
Prediction time: 1.9040926000016043
Peak memory usage during prediction: 399.29296875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.607027999998536
Peak memory usage during training: 399.81640625 MB
Prediction time: 1.8826993000038783
Peak memory usage during prediction: 399.30859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.9643308999948204
Peak memory usage during training: 399.8203125 MB
Prediction time: 1.8849799999952666
Peak memory usage during prediction: 399.31640625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.9844500000035623
Peak memory usage during training: 399.88671875 MB
Prediction time: 1.9006163000012748
Peak memory usage during prediction: 399.4375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3753037999995286
Peak memory usage during training: 400.0078125 MB
Prediction time: 1.8428951999958372
Peak memory usage during prediction: 399.3046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3353290999948513
Peak memory usage during training: 400.13671875 MB
Prediction time: 1.8404416999983368
Peak memory usage during prediction: 399.24609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3125989999971353
Peak memory usage during training: 400.12109375 MB
Prediction time: 1.8498542000015732
Peak memory usage during prediction: 399.24609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8354067999971448
Peak memory usage during training: 399.9609375 MB
Prediction time: 1.8548597999979393
Peak memory usage during prediction: 398.91796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8354916000025696
Peak memory usage during training: 399.79296875 MB
Prediction time: 1.4002911999996286
Peak memory usage during prediction: 398.91796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8401889999950072
Peak memory usage during training: 399.70703125 MB
Prediction time: 1.849269300000742
Peak memory usage during prediction: 399.0390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0122097999992548
Peak memory usage during training: 399.78125 MB
Prediction time: 1.4225685000055819
Peak memory usage during prediction: 399.046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0284018999955151
Peak memory usage during training: 399.796875 MB
Prediction time: 0.9700484999993932
Peak memory usage during prediction: 399.046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0083408999998937
Peak memory usage during training: 399.7890625 MB
Prediction time: 1.8896103000006406
Peak memory usage during prediction: 399.0546875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9709520000033081
Peak memory usage during training: 399.95703125 MB
Prediction time: 1.7932952000046498
Peak memory usage during prediction: 399.22265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.4425651999990805
Peak memory usage during training: 400.00390625 MB
Prediction time: 1.8000503000002936
Peak memory usage during prediction: 399.2265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.4381129999965196
Peak memory usage during training: 400.0390625 MB
Prediction time: 1.8056381000060355
Peak memory usage during prediction: 399.1328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9721478999999817
Peak memory usage during training: 400.0078125 MB
Prediction time: 1.3844787999987602
Peak memory usage during prediction: 399.1328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9706338000032702
Peak memory usage during training: 400.0078125 MB
Prediction time: 1.7937802000014926
Peak memory usage during prediction: 399.046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9887467999942601
Peak memory usage during training: 399.94921875 MB
Prediction time: 1.7966584999958286
Peak memory usage during prediction: 399.07421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.4107538999960525
Peak memory usage during training: 400.0078125 MB
Prediction time: 1.7935623999946984
Peak memory usage during prediction: 399.01953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.4048436000011861
Peak memory usage during training: 399.8671875 MB
Prediction time: 1.783381900000677
Peak memory usage during prediction: 399.11328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.413218700006837
Peak memory usage during training: 399.85546875 MB
Prediction time: 1.7958339999968302
Peak memory usage during prediction: 399.12109375 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.354401800002961
Peak memory usage during training: 399.12109375 MB
Prediction time: 0.9631436000054237
Peak memory usage during prediction: 378.7265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.3224570000020321
Peak memory usage during training: 380.98828125 MB
Prediction time: 1.4121030000023893
Peak memory usage during prediction: 378.5546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.3285748999987845
Peak memory usage during training: 381.30859375 MB
Prediction time: 1.402016599997296
Peak memory usage during prediction: 378.43359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 2.220003499998711
Peak memory usage during training: 388.59765625 MB
Prediction time: 1.0082569000005606
Peak memory usage during prediction: 387.171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 2.157467799996084
Peak memory usage during training: 387.171875 MB
Prediction time: 1.011906200001249
Peak memory usage during prediction: 386.75 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 2.1751566999955685
Peak memory usage during training: 386.94140625 MB
Prediction time: 1.0053021000057925
Peak memory usage during prediction: 387.02734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 3.0988960999966366
Peak memory usage during training: 396.20703125 MB
Prediction time: 1.0459931000004872
Peak memory usage during prediction: 396.234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 3.141407999995863
Peak memory usage during training: 396.88671875 MB
Prediction time: 1.054949299999862
Peak memory usage during prediction: 394.77734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 3.0177693000005092
Peak memory usage during training: 395.04296875 MB
Prediction time: 1.0529160000005504
Peak memory usage during prediction: 395.109375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.8580437999989954
Peak memory usage during training: 421.1484375 MB
Prediction time: 1.0991265999982716
Peak memory usage during prediction: 401.02734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.8655731000035303
Peak memory usage during training: 421.328125 MB
Prediction time: 1.1520885999998427
Peak memory usage during prediction: 395.125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.8841188000005786
Peak memory usage during training: 420.875 MB
Prediction time: 1.1058271000001696
Peak memory usage during prediction: 395.3203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.8502957000018796
Peak memory usage during training: 421.65625 MB
Prediction time: 1.0798690999945393
Peak memory usage during prediction: 395.37890625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.8805405000020983
Peak memory usage during training: 422.2109375 MB
Prediction time: 1.1518971000041347
Peak memory usage during prediction: 394.84765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.866440199999488
Peak memory usage during training: 421.234375 MB
Prediction time: 1.0896808999968925
Peak memory usage during prediction: 395.03515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.9468135999995866
Peak memory usage during training: 425.22265625 MB
Prediction time: 1.0736424999995506
Peak memory usage during prediction: 395.0390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.8969091000035405
Peak memory usage during training: 429.06640625 MB
Prediction time: 1.1520221999962814
Peak memory usage during prediction: 395.328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.7824026999951457
Peak memory usage during training: 421.79296875 MB
Prediction time: 1.0478402000007918
Peak memory usage during prediction: 402.84375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.8599121000006562
Peak memory usage during training: 397.47265625 MB
Prediction time: 1.7842476000005263
Peak memory usage during prediction: 395.33203125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.3984047999983886
Peak memory usage during training: 396.42578125 MB
Prediction time: 1.8018162000007578
Peak memory usage during prediction: 395.390625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.8548345000017434
Peak memory usage during training: 396.4296875 MB
Prediction time: 1.7747457000004943
Peak memory usage during prediction: 395.10546875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.967808999994304
Peak memory usage during training: 397.78125 MB
Prediction time: 1.7906947000010405
Peak memory usage during prediction: 394.93359375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9798163000014029
Peak memory usage during training: 397.75390625 MB
Prediction time: 1.7875236999971094
Peak memory usage during prediction: 394.9140625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.006640100000368
Peak memory usage during training: 397.73046875 MB
Prediction time: 1.7894987000036053
Peak memory usage during prediction: 394.86328125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8621084000042174
Peak memory usage during training: 396.07421875 MB
Prediction time: 0.9995937000057893
Peak memory usage during prediction: 422.4453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.4223264000029303
Peak memory usage during training: 395.71875 MB
Prediction time: 1.000293299999612
Peak memory usage during prediction: 442.55078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.4074156999995466
Peak memory usage during training: 395.83984375 MB
Prediction time: 0.9951719999953639
Peak memory usage during prediction: 436.05859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.3974019999950542
Peak memory usage during training: 401.51171875 MB
Prediction time: 1.001023400000122
Peak memory usage during prediction: 425.515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8715481000035652
Peak memory usage during training: 395.90234375 MB
Prediction time: 0.9969750000018394
Peak memory usage during prediction: 434.98046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.9017129999992903
Peak memory usage during training: 395.88671875 MB
Prediction time: 0.9970929000046453
Peak memory usage during prediction: 422.63671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8690141000042786
Peak memory usage during training: 395.7734375 MB
Prediction time: 0.9957560999973794
Peak memory usage during prediction: 430.23828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8556689999968512
Peak memory usage during training: 395.76171875 MB
Prediction time: 0.9975261999934446
Peak memory usage during prediction: 432.21484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.4037504000007175
Peak memory usage during training: 395.8125 MB
Prediction time: 1.0052327000012156
Peak memory usage during prediction: 438.6171875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.0047486000039498
Peak memory usage during training: 396.109375 MB
Prediction time: 1.8040907999966294
Peak memory usage during prediction: 395.0390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.0053893999938737
Peak memory usage during training: 396.12890625 MB
Prediction time: 1.8087931999980356
Peak memory usage during prediction: 395.0625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.8436132999995607
Peak memory usage during training: 396.09375 MB
Prediction time: 1.7953789999955916
Peak memory usage during prediction: 394.8359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.0031671000033384
Peak memory usage during training: 396.1171875 MB
Prediction time: 1.792855799998506
Peak memory usage during prediction: 395.01953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 0.9898138999997173
Peak memory usage during training: 396.1171875 MB
Prediction time: 1.7991646000009496
Peak memory usage during prediction: 395.0546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9381476999988081
Peak memory usage during training: 396.0859375 MB
Prediction time: 1.8093052000040188
Peak memory usage during prediction: 394.8359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.0227003000036348
Peak memory usage during training: 396.1171875 MB
Prediction time: 1.783585499993933
Peak memory usage during prediction: 395.01953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.0023909000010462
Peak memory usage during training: 396.1171875 MB
Prediction time: 1.8073252000031061
Peak memory usage during prediction: 395.01953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9120631000041612
Peak memory usage during training: 396.05078125 MB
Prediction time: 1.79298540000309
Peak memory usage during prediction: 394.828125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.3866128000008757
Peak memory usage during training: 396.265625 MB
Prediction time: 1.7942441999985022
Peak memory usage during prediction: 395.1328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.3831548999951337
Peak memory usage during training: 396.06640625 MB
Prediction time: 1.80137900000409
Peak memory usage during prediction: 395.17578125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.8351130000010016
Peak memory usage during training: 396.12109375 MB
Prediction time: 1.7914108999975724
Peak memory usage during prediction: 395.44921875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.836112899996806
Peak memory usage during training: 396.09375 MB
Prediction time: 1.7765263999972376
Peak memory usage during prediction: 395.41015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 2.304734699995606
Peak memory usage during training: 396.2109375 MB
Prediction time: 1.7955913999976474
Peak memory usage during prediction: 395.41796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 2.3054697000043234
Peak memory usage during training: 396.125 MB
Prediction time: 1.7932169000050635
Peak memory usage during prediction: 395.55078125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7091497000001254
Peak memory usage during training: 396.0625 MB
Prediction time: 1.8202163000023575
Peak memory usage during prediction: 395.01171875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7088956000006874
Peak memory usage during training: 395.890625 MB
Prediction time: 1.8219293000001926
Peak memory usage during prediction: 394.90234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7073837999996613
Peak memory usage during training: 395.77734375 MB
Prediction time: 1.841728699997475
Peak memory usage during prediction: 394.90234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9247156999990693
Peak memory usage during training: 395.83203125 MB
Prediction time: 1.8623800999994273
Peak memory usage during prediction: 394.84765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9173104999936186
Peak memory usage during training: 395.72265625 MB
Prediction time: 1.399251999995613
Peak memory usage during prediction: 394.84765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9258943000022555
Peak memory usage during training: 395.73828125 MB
Prediction time: 2.0666923999961
Peak memory usage during prediction: 394.86328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1938107000023592
Peak memory usage during training: 395.76953125 MB
Prediction time: 1.584563700002036
Peak memory usage during prediction: 394.87109375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2836469000030775
Peak memory usage during training: 395.8046875 MB
Prediction time: 1.5635919999986072
Peak memory usage during prediction: 394.8984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2444562000018777
Peak memory usage during training: 395.8046875 MB
Prediction time: 1.6560214000055566
Peak memory usage during prediction: 394.9140625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.1307178999995813
Peak memory usage during training: 395.79296875 MB
Prediction time: 2.1710055000003194
Peak memory usage during prediction: 394.89453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.0982135999947786
Peak memory usage during training: 395.76953125 MB
Prediction time: 2.1224030000012135
Peak memory usage during prediction: 394.89453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0576909000010346
Peak memory usage during training: 395.76953125 MB
Prediction time: 1.9722560000009253
Peak memory usage during prediction: 394.89453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.037851299995964
Peak memory usage during training: 395.76953125 MB
Prediction time: 1.9685058000031859
Peak memory usage during prediction: 394.89453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2264128999959212
Peak memory usage during training: 395.77734375 MB
Prediction time: 2.0857097999978578
Peak memory usage during prediction: 394.90625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.6094229999944218
Peak memory usage during training: 395.79296875 MB
Prediction time: 2.043478999999934
Peak memory usage during prediction: 394.91796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.6273127000022214
Peak memory usage during training: 395.79296875 MB
Prediction time: 1.9652550000027986
Peak memory usage during prediction: 394.91796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.529190400004154
Peak memory usage during training: 395.79296875 MB
Prediction time: 1.943104800004221
Peak memory usage during prediction: 394.91796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.5462002999993274
Peak memory usage during training: 395.79296875 MB
Prediction time: 1.9707011000064085
Peak memory usage during prediction: 394.85546875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.4934955999997328
Peak memory usage during training: 394.85546875 MB
Prediction time: 1.5721368999948027
Peak memory usage during prediction: 380.26171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.4299463999996078
Peak memory usage during training: 381.0546875 MB
Prediction time: 1.0635294000021531
Peak memory usage during prediction: 380.75390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.4230091999997967
Peak memory usage during training: 382.57421875 MB
Prediction time: 1.0522789000024204
Peak memory usage during prediction: 379.88671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 2.4556291999979294
Peak memory usage during training: 390.68359375 MB
Prediction time: 1.1046075999984168
Peak memory usage during prediction: 389.93359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 2.392782900002203
Peak memory usage during training: 390.4921875 MB
Prediction time: 1.1097953999997117
Peak memory usage during prediction: 389.39453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 2.402435300005891
Peak memory usage during training: 390.578125 MB
Prediction time: 1.1133235000015702
Peak memory usage during prediction: 389.46484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 3.4549520000000484
Peak memory usage during training: 400.16796875 MB
Prediction time: 1.1581453000035253
Peak memory usage during prediction: 400.17578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 3.2853424999993877
Peak memory usage during training: 400.17578125 MB
Prediction time: 1.151317600000766
Peak memory usage during prediction: 398.98828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 3.2842347000041627
Peak memory usage during training: 399.484375 MB
Prediction time: 1.1635706000015489
Peak memory usage during prediction: 399.51953125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 0.9054908999969484
Peak memory usage during training: 425.796875 MB
Prediction time: 1.1642558000021381
Peak memory usage during prediction: 399.37109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.9217509999944014
Peak memory usage during training: 426.51953125 MB
Prediction time: 1.23464669999521
Peak memory usage during prediction: 399.69921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.9065511000007973
Peak memory usage during training: 425.3828125 MB
Prediction time: 1.1863148999982513
Peak memory usage during prediction: 399.34765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.068996000001789
Peak memory usage during training: 428.453125 MB
Prediction time: 1.1726405000008526
Peak memory usage during prediction: 406.3125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.9281667999966885
Peak memory usage during training: 425.55078125 MB
Prediction time: 1.238074399996549
Peak memory usage during prediction: 399.6015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.8673979000013787
Peak memory usage during training: 424.09375 MB
Prediction time: 1.1672633999987738
Peak memory usage during prediction: 399.6796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.063132900002529
Peak memory usage during training: 429.5546875 MB
Prediction time: 1.0969109999932698
Peak memory usage during prediction: 406.36328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.9158711000054609
Peak memory usage during training: 432.27734375 MB
Prediction time: 1.1545321000012336
Peak memory usage during prediction: 400.20703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.799035099997127
Peak memory usage during training: 422.16015625 MB
Prediction time: 1.0356160000010277
Peak memory usage during prediction: 406.265625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.41008320000401
Peak memory usage during training: 401.20703125 MB
Prediction time: 1.8071802000049502
Peak memory usage during prediction: 399.76953125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 2.154472499998519
Peak memory usage during training: 400.6015625 MB
Prediction time: 2.0476415999946767
Peak memory usage during prediction: 399.6015625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 2.0142820999972173
Peak memory usage during training: 400.69140625 MB
Prediction time: 2.249169199996686
Peak memory usage during prediction: 399.5546875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3566391999993357
Peak memory usage during training: 401.953125 MB
Prediction time: 2.5944133999946644
Peak memory usage during prediction: 399.46875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3084687999944435
Peak memory usage during training: 401.78125 MB
Prediction time: 2.4484134000013
Peak memory usage during prediction: 399.46484375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.3501881000047433
Peak memory usage during training: 401.78125 MB
Prediction time: 2.509114000000409
Peak memory usage during prediction: 399.3828125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.4307526999982656
Peak memory usage during training: 399.96484375 MB
Prediction time: 1.2580691999974078
Peak memory usage during prediction: 445.4375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.144568999996409
Peak memory usage during training: 400.046875 MB
Prediction time: 1.1299476999993203
Peak memory usage during prediction: 443.25 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 2.0211615999942296
Peak memory usage during training: 400.046875 MB
Prediction time: 1.1455639000050724
Peak memory usage during prediction: 446.140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.538319200000842
Peak memory usage during training: 400.0 MB
Prediction time: 1.1284530999982962
Peak memory usage during prediction: 443.203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.0560065999961807
Peak memory usage during training: 400.08984375 MB
Prediction time: 1.1437584000013885
Peak memory usage during prediction: 445.23828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.5677142000058666
Peak memory usage during training: 400.02734375 MB
Prediction time: 1.1330073999997694
Peak memory usage during prediction: 433.2109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.5338139000014053
Peak memory usage during training: 400.07421875 MB
Prediction time: 1.1431523999999627
Peak memory usage during prediction: 427.00390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.551200299996708
Peak memory usage during training: 400.04296875 MB
Prediction time: 1.1424371999964933
Peak memory usage during prediction: 446.61328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 2.03060849999747
Peak memory usage during training: 400.02734375 MB
Prediction time: 1.1292428000015207
Peak memory usage during prediction: 442.1953125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.1008602000001702
Peak memory usage during training: 406.15625 MB
Prediction time: 1.9714913999996497
Peak memory usage during prediction: 399.50390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.1045369999992545
Peak memory usage during training: 400.8515625 MB
Prediction time: 1.9661463000011281
Peak memory usage during prediction: 399.578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.8616750000001048
Peak memory usage during training: 400.3125 MB
Prediction time: 1.9624554000038188
Peak memory usage during prediction: 399.265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.116603499998746
Peak memory usage during training: 400.3046875 MB
Prediction time: 1.9594929000013508
Peak memory usage during prediction: 399.44921875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0994821000058437
Peak memory usage during training: 400.83203125 MB
Prediction time: 1.9844683999981498
Peak memory usage during prediction: 399.71484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9438613000020268
Peak memory usage during training: 400.44921875 MB
Prediction time: 1.9629768000013428
Peak memory usage during prediction: 399.40234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.1062429000012344
Peak memory usage during training: 400.38671875 MB
Prediction time: 1.941737600005581
Peak memory usage during prediction: 399.58203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0917214999935823
Peak memory usage during training: 400.96484375 MB
Prediction time: 1.9901198000006843
Peak memory usage during prediction: 399.72265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9333793999976479
Peak memory usage during training: 400.45703125 MB
Prediction time: 1.9397094000014476
Peak memory usage during prediction: 399.3203125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.2697200999973575
Peak memory usage during training: 400.44921875 MB
Prediction time: 1.9572736999980407
Peak memory usage during prediction: 399.57421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.2596216000019922
Peak memory usage during training: 400.36328125 MB
Prediction time: 1.9287803999977768
Peak memory usage during prediction: 399.671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.624130199998035
Peak memory usage during training: 400.34765625 MB
Prediction time: 1.9552949999997509
Peak memory usage during prediction: 399.83203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.6713650000019697
Peak memory usage during training: 400.38671875 MB
Prediction time: 2.1429117000006954
Peak memory usage during prediction: 399.70703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 2.1612191000021994
Peak memory usage during training: 400.390625 MB
Prediction time: 2.332696900004521
Peak memory usage during prediction: 399.87109375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 2.349670600000536
Peak memory usage during training: 400.43359375 MB
Prediction time: 2.0292737999989185
Peak memory usage during prediction: 399.75390625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4196420000007492
Peak memory usage during training: 400.52734375 MB
Prediction time: 2.0007184999994934
Peak memory usage during prediction: 399.640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7775062999935471
Peak memory usage during training: 400.37890625 MB
Prediction time: 2.184184199999436
Peak memory usage during prediction: 399.7890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5109921999974176
Peak memory usage during training: 400.44921875 MB
Prediction time: 2.0498033999974723
Peak memory usage during prediction: 399.62109375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9058846999978414
Peak memory usage during training: 399.87890625 MB
Prediction time: 1.526917199997115
Peak memory usage during prediction: 399.87890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8930106000043452
Peak memory usage during training: 400.27734375 MB
Prediction time: 1.5529026000003796
Peak memory usage during prediction: 399.375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9009786999959033
Peak memory usage during training: 400.1328125 MB
Prediction time: 2.0828996999989613
Peak memory usage during prediction: 399.578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0703271000020322
Peak memory usage during training: 400.34375 MB
Prediction time: 1.0540315000034752
Peak memory usage during prediction: 399.609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0642695000060485
Peak memory usage during training: 400.3984375 MB
Prediction time: 1.5592327999984263
Peak memory usage during prediction: 399.6484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.086812399997143
Peak memory usage during training: 400.40234375 MB
Prediction time: 1.5557664000007208
Peak memory usage during prediction: 399.66796875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.8894798000037554
Peak memory usage during training: 400.40234375 MB
Prediction time: 2.083039099998132
Peak memory usage during prediction: 399.66796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0937463000009302
Peak memory usage during training: 400.375 MB
Prediction time: 1.9526463000001968
Peak memory usage during prediction: 399.640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.57961890000297
Peak memory usage during training: 400.4375 MB
Prediction time: 1.9839719000010518
Peak memory usage during prediction: 399.578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0549533000012161
Peak memory usage during training: 400.4453125 MB
Prediction time: 1.9528170999983558
Peak memory usage during prediction: 399.69140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.064600400000927
Peak memory usage during training: 400.328125 MB
Prediction time: 1.9593917000020156
Peak memory usage during prediction: 399.54296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.096202100001392
Peak memory usage during training: 400.2890625 MB
Prediction time: 2.1563669000024674
Peak memory usage during prediction: 399.5234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1176555999991251
Peak memory usage during training: 400.29296875 MB
Prediction time: 1.9476309000019683
Peak memory usage during prediction: 399.55859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.577037000002747
Peak memory usage during training: 400.45703125 MB
Prediction time: 1.9384499000007054
Peak memory usage during prediction: 399.640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.5435206000038306
Peak memory usage during training: 400.37890625 MB
Prediction time: 1.9225666999991518
Peak memory usage during prediction: 399.64453125 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.4043277000018861
Peak memory usage during training: 399.64453125 MB
Prediction time: 1.5264093000005232
Peak memory usage during prediction: 378.61328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.389899100002367
Peak memory usage during training: 380.78515625 MB
Prediction time: 1.0515814000027603
Peak memory usage during prediction: 378.67578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.3901020999983302
Peak memory usage during training: 379.48828125 MB
Prediction time: 1.5379804999975022
Peak memory usage during prediction: 378.45703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 2.278405400000338
Peak memory usage during training: 388.2734375 MB
Prediction time: 1.0919778999959817
Peak memory usage during prediction: 388.2734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 2.2165817999994033
Peak memory usage during training: 387.51171875 MB
Prediction time: 1.0966574999984005
Peak memory usage during prediction: 387.1796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 2.1974340999950073
Peak memory usage during training: 387.7421875 MB
Prediction time: 1.1014265999983763
Peak memory usage during prediction: 387.01953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 3.209087499999441
Peak memory usage during training: 396.83984375 MB
Prediction time: 1.139576000001398
Peak memory usage during prediction: 396.875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 3.0883447999949567
Peak memory usage during training: 396.125 MB
Prediction time: 1.137117300000682
Peak memory usage during prediction: 395.83984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 3.0593688000008115
Peak memory usage during training: 395.01953125 MB
Prediction time: 1.144117700001516
Peak memory usage during prediction: 395.0703125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.9007763000045088
Peak memory usage during training: 421.953125 MB
Prediction time: 1.1812138999957824
Peak memory usage during prediction: 394.80078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9147261000034632
Peak memory usage during training: 420.375 MB
Prediction time: 1.235663100000238
Peak memory usage during prediction: 395.26953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.943591600000218
Peak memory usage during training: 428.265625 MB
Prediction time: 1.2022016999981133
Peak memory usage during prediction: 395.09765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 0.9230476000011549
Peak memory usage during training: 420.484375 MB
Prediction time: 1.1683144999988144
Peak memory usage during prediction: 395.20703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9338466999979573
Peak memory usage during training: 427.21484375 MB
Prediction time: 1.268011199994362
Peak memory usage during prediction: 401.1875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.9266196999960812
Peak memory usage during training: 420.1875 MB
Prediction time: 1.1816751000005752
Peak memory usage during prediction: 394.9140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.005626799997117
Peak memory usage during training: 423.8359375 MB
Prediction time: 1.1588907000041218
Peak memory usage during prediction: 394.9765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9564110999999684
Peak memory usage during training: 427.93359375 MB
Prediction time: 1.2463315000059083
Peak memory usage during prediction: 394.92578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.8650530000013532
Peak memory usage during training: 421.46875 MB
Prediction time: 1.1456496000027983
Peak memory usage during prediction: 402.73046875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.546925900001952
Peak memory usage during training: 397.49609375 MB
Prediction time: 1.940616300002148
Peak memory usage during prediction: 395.78125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.5604916000011144
Peak memory usage during training: 396.26953125 MB
Prediction time: 2.1819140000006882
Peak memory usage during prediction: 395.515625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.5980714000033913
Peak memory usage during training: 396.23046875 MB
Prediction time: 1.9393478999991203
Peak memory usage during prediction: 395.25390625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.5466937999954098
Peak memory usage during training: 397.6171875 MB
Prediction time: 1.9697673000046052
Peak memory usage during prediction: 395.3359375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.056040399998892
Peak memory usage during training: 397.56640625 MB
Prediction time: 1.9983090000023367
Peak memory usage during prediction: 395.16796875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0817050999976345
Peak memory usage during training: 397.3828125 MB
Prediction time: 1.9281979000006686
Peak memory usage during prediction: 395.1328125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.025696600001538
Peak memory usage during training: 395.875 MB
Prediction time: 1.0884551999988616
Peak memory usage during prediction: 423.58984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.5442201999976533
Peak memory usage during training: 395.875 MB
Prediction time: 1.1769225000025472
Peak memory usage during prediction: 422.37109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.5651874000031967
Peak memory usage during training: 395.62109375 MB
Prediction time: 1.0865540000013425
Peak memory usage during prediction: 442.625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.0266893999942113
Peak memory usage during training: 395.6328125 MB
Prediction time: 1.0757207999995444
Peak memory usage during prediction: 442.60546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.0285052999970503
Peak memory usage during training: 395.6328125 MB
Prediction time: 1.089675700000953
Peak memory usage during prediction: 422.9140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.5590710000033141
Peak memory usage during training: 395.6328125 MB
Prediction time: 1.0945282000029692
Peak memory usage during prediction: 431.71875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.5234886000034749
Peak memory usage during training: 395.6328125 MB
Prediction time: 1.0905262000014773
Peak memory usage during prediction: 436.02734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.5518669000011869
Peak memory usage during training: 395.6328125 MB
Prediction time: 1.0818279999948572
Peak memory usage during prediction: 422.5703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.5438770999971894
Peak memory usage during training: 395.6328125 MB
Prediction time: 1.1939482999950997
Peak memory usage during prediction: 439.29296875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.260063199995784
Peak memory usage during training: 401.80859375 MB
Prediction time: 2.075846600004297
Peak memory usage during prediction: 395.109375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.0985007999988738
Peak memory usage during training: 395.8984375 MB
Prediction time: 1.947187900004792
Peak memory usage during prediction: 395.15625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.8720166999992216
Peak memory usage during training: 395.890625 MB
Prediction time: 1.9968407999986084
Peak memory usage during prediction: 394.9140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.1030428000012762
Peak memory usage during training: 395.8984375 MB
Prediction time: 1.9523059999992256
Peak memory usage during prediction: 395.08203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.084285800003272
Peak memory usage during training: 395.8984375 MB
Prediction time: 1.9389683999979752
Peak memory usage during prediction: 395.15234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9683078000016394
Peak memory usage during training: 395.88671875 MB
Prediction time: 1.9486641000039526
Peak memory usage during prediction: 394.9140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.092197900004976
Peak memory usage during training: 395.8984375 MB
Prediction time: 1.9516676000057487
Peak memory usage during prediction: 395.08203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.0870577000023331
Peak memory usage during training: 395.8984375 MB
Prediction time: 1.9489156999989063
Peak memory usage during prediction: 395.13671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9777136999982758
Peak memory usage during training: 395.87890625 MB
Prediction time: 1.9460465000011027
Peak memory usage during prediction: 394.90625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.4763056000010693
Peak memory usage during training: 395.98046875 MB
Prediction time: 2.396216299996013
Peak memory usage during prediction: 395.4765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.5350879999969038
Peak memory usage during training: 395.99609375 MB
Prediction time: 1.9751766999979736
Peak memory usage during prediction: 395.5703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.9441413000022294
Peak memory usage during training: 395.5703125 MB
Prediction time: 2.2719773999997415
Peak memory usage during prediction: 395.35546875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.99647179999738
Peak memory usage during training: 396.0546875 MB
Prediction time: 1.9671624000038719
Peak memory usage during prediction: 395.65625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 2.432180199997674
Peak memory usage during training: 396.00390625 MB
Prediction time: 1.9973883000056958
Peak memory usage during prediction: 395.5703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 2.412163100001635
Peak memory usage during training: 396.109375 MB
Prediction time: 2.1111421000023256
Peak memory usage during prediction: 395.53515625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8644639999984065
Peak memory usage during training: 396.0703125 MB
Prediction time: 2.1557192000036594
Peak memory usage during prediction: 395.21484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7689677000016673
Peak memory usage during training: 395.890625 MB
Prediction time: 2.012262500000361
Peak memory usage during prediction: 395.09765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7805061999970349
Peak memory usage during training: 395.85546875 MB
Prediction time: 2.0097959999984596
Peak memory usage during prediction: 395.09765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9818094999936875
Peak memory usage during training: 395.8359375 MB
Prediction time: 2.0382248000023537
Peak memory usage during prediction: 394.953125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9925183000013931
Peak memory usage during training: 395.70703125 MB
Prediction time: 1.5319134999954258
Peak memory usage during prediction: 394.953125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.005504100001417
Peak memory usage during training: 395.73828125 MB
Prediction time: 2.015225900002406
Peak memory usage during prediction: 395.0 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.227813999998034
Peak memory usage during training: 395.7421875 MB
Prediction time: 2.043823700005305
Peak memory usage during prediction: 395.0078125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.2333807999966666
Peak memory usage during training: 395.78125 MB
Prediction time: 1.0544928000017535
Peak memory usage during prediction: 395.03125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.220861400004651
Peak memory usage during training: 395.7734375 MB
Prediction time: 1.5410912000006647
Peak memory usage during prediction: 395.0390625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0581988999983878
Peak memory usage during training: 395.77734375 MB
Prediction time: 2.0946330999940983
Peak memory usage during prediction: 395.16796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.2545290999987628
Peak memory usage during training: 395.90234375 MB
Prediction time: 2.0884742999987793
Peak memory usage during prediction: 395.16796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.570572999997239
Peak memory usage during training: 395.77734375 MB
Prediction time: 1.9682030999974813
Peak memory usage during prediction: 395.04296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.5337349000037648
Peak memory usage during training: 395.77734375 MB
Prediction time: 1.9312642000004416
Peak memory usage during prediction: 395.04296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.5053015000012238
Peak memory usage during training: 395.77734375 MB
Prediction time: 1.9137061000001268
Peak memory usage during prediction: 395.04296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.551286900001287
Peak memory usage during training: 395.77734375 MB
Prediction time: 1.908899800000654
Peak memory usage during prediction: 395.04296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.4988130000056117
Peak memory usage during training: 395.77734375 MB
Prediction time: 1.9267137999995612
Peak memory usage during prediction: 395.04296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.5027780999953393
Peak memory usage during training: 395.79296875 MB
Prediction time: 1.8983125999948243
Peak memory usage during prediction: 395.03515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.017791499994928
Peak memory usage during training: 395.76953125 MB
Prediction time: 1.898877599996922
Peak memory usage during prediction: 395.03515625 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.4418389999991632
Peak memory usage during training: 395.03515625 MB
Prediction time: 1.0334308000019519
Peak memory usage during prediction: 380.01953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.376723099994706
Peak memory usage during training: 381.875 MB
Prediction time: 1.5228647000039928
Peak memory usage during prediction: 379.73828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.3818567000053008
Peak memory usage during training: 382.31640625 MB
Prediction time: 1.0347266999960993
Peak memory usage during prediction: 379.8515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 2.3600851000010152
Peak memory usage during training: 390.72265625 MB
Prediction time: 1.0677289000013843
Peak memory usage during prediction: 390.0546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 2.2621311000038986
Peak memory usage during training: 390.30859375 MB
Prediction time: 1.082711000002746
Peak memory usage during prediction: 389.3359375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 2.26736019999953
Peak memory usage during training: 390.46484375 MB
Prediction time: 1.1080130000045756
Peak memory usage during prediction: 389.4375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 3.3464813999962644
Peak memory usage during training: 400.37109375 MB
Prediction time: 1.16552159999992
Peak memory usage during prediction: 399.52734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 3.1690082999994047
Peak memory usage during training: 399.53125 MB
Prediction time: 1.1398465000020224
Peak memory usage during prediction: 399.16015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 3.162556700001005
Peak memory usage during training: 399.625 MB
Prediction time: 1.1215293999994174
Peak memory usage during prediction: 399.63671875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 0.8734752999953344
Peak memory usage during training: 425.71875 MB
Prediction time: 1.133869200006302
Peak memory usage during prediction: 405.78125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.965815499999735
Peak memory usage during training: 432.37109375 MB
Prediction time: 1.3065041000008932
Peak memory usage during prediction: 399.4296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.9693421999982093
Peak memory usage during training: 430.81640625 MB
Prediction time: 1.2593271000005188
Peak memory usage during prediction: 399.19921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.114350399999239
Peak memory usage during training: 431.00390625 MB
Prediction time: 1.2182795999979135
Peak memory usage during prediction: 405.6875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.9634686999997939
Peak memory usage during training: 431.484375 MB
Prediction time: 1.314554099997622
Peak memory usage during prediction: 399.59765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.8993884000010439
Peak memory usage during training: 423.8515625 MB
Prediction time: 1.3119445000047563
Peak memory usage during prediction: 399.45703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.1102533000012045
Peak memory usage during training: 429.37890625 MB
Prediction time: 1.1945515000043088
Peak memory usage during prediction: 406.140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.0172816000049352
Peak memory usage during training: 432.109375 MB
Prediction time: 1.2977160000009462
Peak memory usage during prediction: 406.44921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.8692308000026969
Peak memory usage during training: 421.56640625 MB
Prediction time: 1.0988364000004367
Peak memory usage during prediction: 405.875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 2.0383533999993233
Peak memory usage during training: 400.2421875 MB
Prediction time: 2.079191000004357
Peak memory usage during prediction: 399.28125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 2.0962072999973316
Peak memory usage during training: 400.25 MB
Prediction time: 1.9422747999997227
Peak memory usage during prediction: 399.03125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.5196739000020898
Peak memory usage during training: 400.2421875 MB
Prediction time: 2.0129002000030596
Peak memory usage during prediction: 399.30859375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.644004000001587
Peak memory usage during training: 401.57421875 MB
Prediction time: 1.9752403000020422
Peak memory usage during prediction: 399.1484375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.038230800004385
Peak memory usage during training: 401.58984375 MB
Prediction time: 1.869707500001823
Peak memory usage during prediction: 399.1328125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.056394299994281
Peak memory usage during training: 401.53125 MB
Prediction time: 1.8398937000019941
Peak memory usage during prediction: 399.14453125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.969797899997502
Peak memory usage during training: 399.984375 MB
Prediction time: 1.08663319999323
Peak memory usage during prediction: 433.86328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.6171603000038886
Peak memory usage during training: 399.87890625 MB
Prediction time: 1.105462899999111
Peak memory usage during prediction: 447.11328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.4826535000029253
Peak memory usage during training: 399.984375 MB
Prediction time: 1.0902920000007725
Peak memory usage during prediction: 445.8046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.480777400000079
Peak memory usage during training: 399.98046875 MB
Prediction time: 1.0900484000012511
Peak memory usage during prediction: 427.15625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9928794000006747
Peak memory usage during training: 399.93359375 MB
Prediction time: 1.1105896000008215
Peak memory usage during prediction: 432.8203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.9571960999965086
Peak memory usage during training: 399.86328125 MB
Prediction time: 1.094468399998732
Peak memory usage during prediction: 435.65625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9324814999999944
Peak memory usage during training: 399.79296875 MB
Prediction time: 1.0845721999939997
Peak memory usage during prediction: 434.18359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.488310700005968
Peak memory usage during training: 399.96484375 MB
Prediction time: 1.109438699997554
Peak memory usage during prediction: 426.828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.4691516999955638
Peak memory usage during training: 399.89453125 MB
Prediction time: 1.0945788000026369
Peak memory usage during prediction: 433.6015625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.0687114999964251
Peak memory usage during training: 399.75390625 MB
Prediction time: 1.8980432000025758
Peak memory usage during prediction: 399.00390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0580373000047985
Peak memory usage during training: 400.296875 MB
Prediction time: 1.8824592999953893
Peak memory usage during prediction: 399.26953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.8413276999999653
Peak memory usage during training: 399.9375 MB
Prediction time: 1.8849936999977217
Peak memory usage during prediction: 398.98828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.0590836000046693
Peak memory usage during training: 399.8125 MB
Prediction time: 1.8744319999968866
Peak memory usage during prediction: 398.921875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0542607000024873
Peak memory usage during training: 400.30859375 MB
Prediction time: 1.869089100000565
Peak memory usage during prediction: 399.31640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.8966749000028358
Peak memory usage during training: 400.09375 MB
Prediction time: 1.8791094999978668
Peak memory usage during prediction: 399.00390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.0557696000032593
Peak memory usage during training: 399.859375 MB
Prediction time: 1.9187711999984458
Peak memory usage during prediction: 399.00390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.0523627000002307
Peak memory usage during training: 400.2578125 MB
Prediction time: 1.8934723999991547
Peak memory usage during prediction: 399.3359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.8931981999994605
Peak memory usage during training: 400.08203125 MB
Prediction time: 1.8676000999985263
Peak memory usage during prediction: 399.19140625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.21342619999632
Peak memory usage during training: 400.19140625 MB
Prediction time: 1.889676500002679
Peak memory usage during prediction: 399.41015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.2172267999994801
Peak memory usage during training: 399.9375 MB
Prediction time: 1.8755025999998907
Peak memory usage during prediction: 399.8046875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.5643299000003026
Peak memory usage during training: 400.01953125 MB
Prediction time: 1.8942714000004344
Peak memory usage during prediction: 399.51953125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.561977700002899
Peak memory usage during training: 399.96875 MB
Prediction time: 1.9960424000018975
Peak memory usage during prediction: 399.15625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 2.026556200005871
Peak memory usage during training: 399.96484375 MB
Prediction time: 1.8857063999967068
Peak memory usage during prediction: 399.515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.9026321999990614
Peak memory usage during training: 399.9765625 MB
Prediction time: 1.8810075000001234
Peak memory usage during prediction: 399.640625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3541190999967512
Peak memory usage during training: 400.1484375 MB
Prediction time: 1.904364900001383
Peak memory usage during prediction: 399.43359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3646074999996927
Peak memory usage during training: 400.17578125 MB
Prediction time: 1.8952850999994553
Peak memory usage during prediction: 399.42578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3594678999943426
Peak memory usage during training: 400.33984375 MB
Prediction time: 1.928607000001648
Peak memory usage during prediction: 399.49609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.9194171999988612
Peak memory usage during training: 400.0703125 MB
Prediction time: 2.1362699000019347
Peak memory usage during prediction: 399.28125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8774297999989358
Peak memory usage during training: 399.89453125 MB
Prediction time: 1.972863100003451
Peak memory usage during prediction: 399.28515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8540473999964888
Peak memory usage during training: 400.01953125 MB
Prediction time: 1.9064134000000195
Peak memory usage during prediction: 399.28515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0279796000031638
Peak memory usage during training: 399.90234375 MB
Prediction time: 1.4997195999967516
Peak memory usage during prediction: 399.29296875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.046597100001236
Peak memory usage during training: 400.05859375 MB
Prediction time: 1.51492529999814
Peak memory usage during prediction: 399.1640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0579540000035195
Peak memory usage during training: 399.9296875 MB
Prediction time: 1.0762260999981663
Peak memory usage during prediction: 399.37109375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0391757999968831
Peak memory usage during training: 400.31640625 MB
Prediction time: 1.896560799999861
Peak memory usage during prediction: 399.46484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0178840000007767
Peak memory usage during training: 400.01171875 MB
Prediction time: 1.8675624999959837
Peak memory usage during prediction: 399.33984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.02097700000013
Peak memory usage during training: 400.14453125 MB
Prediction time: 1.8717935000022408
Peak memory usage during prediction: 399.33984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0230240000018966
Peak memory usage during training: 400.14453125 MB
Prediction time: 1.8892217000029632
Peak memory usage during prediction: 399.375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.5024340999952983
Peak memory usage during training: 400.0234375 MB
Prediction time: 1.855600200004119
Peak memory usage during prediction: 399.0 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.0327026000013575
Peak memory usage during training: 400.04296875 MB
Prediction time: 1.964853999998013
Peak memory usage during prediction: 399.296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1906520999982604
Peak memory usage during training: 400.078125 MB
Prediction time: 2.0856010999996215
Peak memory usage during prediction: 399.30078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.5343408000044292
Peak memory usage during training: 400.03125 MB
Prediction time: 1.9531150000038906
Peak memory usage during prediction: 399.2734375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.066401299998688
Peak memory usage during training: 400.04296875 MB
Prediction time: 1.9289311000029556
Peak memory usage during prediction: 399.265625 MB
----------------------------------------------------------------------------------------------------

# Process results

In [10]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seed                    396 non-null    object
 1   vectorizer              396 non-null    object
 2   model                   396 non-null    object
 3   params                  396 non-null    object
 4   accuracy                396 non-null    float64
 5   training_time           396 non-null    float64
 6   prediction_time         396 non-null    float64
 7   peak_memory_train       396 non-null    float64
 8   peak_memory_prediction  396 non-null    float64
 9   precision_class_0       396 non-null    float64
 10  recall_class_0          396 non-null    float64
 11  f1_class_0              396 non-null    float64
 12  precision_class_1       396 non-null    float64
 13  recall_class_1          396 non-null    float64
 14  f1_class_1              396 non-null    float64
dtypes: float64(11), object(4)
memory usage: 46.5+ KB

In [11]:
results.head()

,seed,vectorizer,model,params,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,recall_class_0,f1_class_0,precision_class_1,recall_class_1,f1_class_1
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.636649,1.422937,1.539306,375.066406,374.164062,0.625828,0.757515,0.685403,0.655271,0.504386,0.570012
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.626178,1.341890,1.033368,374.660156,373.945312,0.620339,0.733467,0.672176,0.635616,0.508772,0.565164
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.626178,1.375523,1.108932,375.414062,373.957031,0.620339,0.733467,0.672176,0.635616,0.508772,0.565164
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.628272,2.277244,1.049833,383.339844,382.675781,0.616883,0.761523,0.681614,0.648968,0.482456,0.553459
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.627225,2.269728,1.135606,382.937500,381.843750,0.620168,0.739479,0.674589,0.638889,0.504386,0.563725

In [12]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,recall_class_0,f1_class_0,precision_class_1,recall_class_1,f1_class_1,f1_avg
0,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.01}",3.333333,0.544503,0.886903,1.839349,399.970052,399.359375,0.588889,0.424850,0.493597,0.517647,0.675439,0.586108,0.539853
1,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.1}",3.333333,0.562304,0.868644,1.642019,399.988281,399.192708,0.612813,0.440882,0.512821,0.531879,0.695175,0.602662,0.557741
2,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 1.0}",3.333333,0.572426,0.865072,1.946194,399.953125,399.300781,0.622300,0.462258,0.530470,0.540789,0.692982,0.607498,0.568984
3,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.01}",3.333333,0.544503,1.036839,1.325440,400.009115,399.316406,0.588889,0.424850,0.493597,0.517647,0.675439,0.586108,0.539853
4,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.1}",3.333333,0.593717,1.046423,1.348069,400.084635,399.286458,0.574899,0.853707,0.687097,0.658879,0.309211,0.420896,0.553996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'rbf'}",3.333333,0.620942,0.914097,1.218140,424.621094,395.804688,0.626617,0.679359,0.651923,0.613527,0.557018,0.583908,0.617916
128,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'sigmoid'}",3.333333,0.616754,0.902479,1.135401,422.169271,393.811198,0.626186,0.661323,0.643275,0.605140,0.567982,0.585973,0.614624
129,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'linear'}",3.333333,0.591623,0.986618,1.140525,423.381510,395.973958,0.607495,0.617234,0.612326,0.573661,0.563596,0.568584,0.590455
130,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'rbf'}",3.333333,0.612565,0.935716,1.206367,427.260417,394.076823,0.628743,0.631263,0.630000,0.594714,0.592105,0.593407,0.611703
131,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'sigmoid'}",3.333333,0.565445,1.838126,1.112780,420.468750,401.828125,0.590909,0.547094,0.568158,0.541582,0.585526,0.562698,0.565428

In [13]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train['label'])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test['label'], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test['label'], y_pred, average=None, labels=classes, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: SVC
Best model params: {'C': 0.1, 'kernel': 'linear'}
Best vectorizer: CountVectorizer
Best accuracy: 0.6607142857142857

Class 0
Precision: 0.7379310344827587
Recall: 0.678646934460888
F1: 0.7070484581497798
Support: 473

Class 1
Precision: 0.5644699140401146
Recall: 0.6334405144694534
F1: 0.5969696969696969
Support: 311

In [14]:
with open('models/best_model_sklearn_binary3.pkl', 'wb') as f:
    pickle.dump(pipeline, f)