In [9]:
# Basic libraries
import time
import torch
import pandas as pd
from datasets import load_dataset

# Transformers library for LLM
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# Utilities and metrics
from memory_profiler import memory_usage
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Using device: {torch.cuda.get_device_name(0)}")
    print(f"Device index: {torch.cuda.current_device()}")
else:
    print("CUDA is not available. Using CPU.")
    device = torch.device("cpu")

print(f"Device: {device}")

Using device: NVIDIA GeForce RTX 3060 Ti
Device index: 0
Device: cuda

# Quantization setup

In [11]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16
)

# LLM setup

In [12]:
model_name = 'meta-llama/Llama-3.2-3B-Instruct'

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

print(model.hf_device_map)

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.46G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

{'': 0}

# Defining a classification function

In [13]:
def classify(prompt, labels):
    if torch.cuda.is_available():
        torch.cuda.reset_max_memory_allocated()

    messages = [
        {"role": "system", "content": "You are a classification assistant. Your objective is to read the provided text and classify it according to the task and labels described. You are capable of handling binary classification tasks based on user instructions. Only respond with the label that best describe the text. If the text does not fit any of the labels, respond with 'none'."},
        {"role": "user", "content": f"Classify the following text based on the task: Sentiment analysis. The possible labels are: {labels}. Text: {prompt}"}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    model_inputs = tokenizer([text], return_tensors="pt").to(device)

    num_input_tokens = model_inputs.input_ids.size(1)

    max_label_length = max([len(tokenizer.encode(label, add_special_tokens=False)) for label in labels])

    generated_ids = model.generate(
        model_inputs.input_ids,
        attention_mask=model_inputs.attention_mask,
        max_new_tokens=max_label_length,
        temperature=0.0,
        do_sample=False,
        top_k=0,
        top_p=1.0,
        num_beams=1
    )

    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    num_output_tokens = generated_ids[0].size(0)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    print(response)

    response = response.strip().lower()

    if response not in labels:
        response = "none"

    max_vram_usage = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else None


    return [response, num_input_tokens, num_output_tokens, max_vram_usage]

# Loading test dataset

#### Only testing is necessary as the model is pre-trained, so no training/tuning is necessary.

In [14]:
ds = load_dataset("cornell-movie-review-data/rotten_tomatoes")

test = ds['test'].to_pandas()

test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1066 entries, 0 to 1065
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    1066 non-null   object
 1   label   1066 non-null   int64
dtypes: int64(1), object(1)
memory usage: 16.8+ KB

# Preprocessing the dataset

In [15]:
test['label'] = test['label'].apply(lambda x: 'positive' if x == 1 else 'negative')

labels = test['label'].unique()
labels

array(['positive', 'negative'], dtype=object)

# Classifying dataset

In [16]:
columns = ['text', 'true_label', 'predicted_label', 'peak_memory_usage', 'max_vram_usage', 'inference_time', 'num_input_tokens', 'num_output_tokens']

results = pd.DataFrame(columns=columns)
results

Empty DataFrame
Columns: [text, true_label, predicted_label, peak_memory_usage, max_vram_usage, inference_time, num_input_tokens, num_output_tokens]
Index: []

In [17]:
for index, row in test.iterrows():
    text = row['text']
    print(f"Text: {text}")


    start = time.perf_counter()
    peak_memory_usage, response = memory_usage((classify, (text, labels),), max_usage=True, retval=True)
    total_time = time.perf_counter() - start

    generated_text = response[0]
    num_input_tokens = response[1]
    num_output_tokens = response[2]
    max_vram_usage = response[3]
    print(f"Response: {generated_text}")
    print(f"Input tokens: {num_input_tokens} || Output tokens: {num_output_tokens}")
    print(f"Peak memory Usage: {peak_memory_usage}")
    print(f"Max VRAM Usage: {max_vram_usage}")
    print(f"Total Time: {total_time}")

    # concat to results
    result = {
        'text': text,
        'true_label': row['label'],
        'predicted_label': generated_text,
        'peak_memory_usage': peak_memory_usage,
        'max_vram_usage': max_vram_usage,
        'inference_time': total_time,
        'num_input_tokens': num_input_tokens,
        'num_output_tokens': num_output_tokens
    }

    results = pd.concat([results, pd.DataFrame([result], columns=columns)], ignore_index=True)
    print("-" * 75)

Text: lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness .

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\torch\cuda\memory.py:343: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\transformers\generation\configuration_utils.py:601: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\transformers\generation\configuration_utils.py:623: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\transformers\models\llama\modeling_llama.py:655: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)
C:\Users\Rafael\AppData\Local\Temp\ipykernel_15900\711679153.py:32: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([result], columns=columns)], ignore_index=True)

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1464.6171875
Max VRAM Usage: 2366.41845703125
Total Time: 2.028370000072755
---------------------------------------------------------------------------
Text: consistently clever and suspenseful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1472.9296875
Max VRAM Usage: 2363.12744140625
Total Time: 1.3544626999646425
---------------------------------------------------------------------------
Text: it's like a " big chill " reunion of the baader-meinhof gang , only these guys are more harmless pranksters than political activists .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1473.0546875
Max VRAM Usage: 2367.07666015625
Total Time: 1.3003862999612466
---------------------------------------------------------------------------
Text: the story gives ample opportunity for large-scale action and suspense , which director shekhar kapur supplies with tremendous skill .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1473.09765625
Max VRAM Usage: 2366.08935546875
Total Time: 1.287320900009945
---------------------------------------------------------------------------
Text: red dragon " never cuts corners .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1473.125
Max VRAM Usage: 2363.29248046875
Total Time: 1.3177191999275237
---------------------------------------------------------------------------
Text: fresnadillo has something serious to say about the ways in which extravagant chance can distort our perspective and throw us off the path of good sense .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1473.15234375
Max VRAM Usage: 2366.91259765625
Total Time: 1.2982205000007525
---------------------------------------------------------------------------
Text: throws in enough clever and unexpected twists to make the formula feel fresh .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1473.19140625
Max VRAM Usage: 2364.44384765625
Total Time: 1.3227553999749944
---------------------------------------------------------------------------
Text: weighty and ponderous but every bit as filling as the treat of the title .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1473.21875
Max VRAM Usage: 2364.93798828125
Total Time: 1.2723126000491902
---------------------------------------------------------------------------
Text: a real audience-pleaser that will strike a chord with anyone who's ever waited in a doctor's office , emergency room , hospital bed or insurance company office .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1473.26171875
Max VRAM Usage: 2367.57080078125
Total Time: 1.2693046999629587
---------------------------------------------------------------------------
Text: generates an enormous feeling of empathy for its characters .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1473.30078125
Max VRAM Usage: 2363.78564453125
Total Time: 1.298155799973756
---------------------------------------------------------------------------
Text: exposing the ways we fool ourselves is one hour photo's real strength .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1473.30859375
Max VRAM Usage: 2364.44384765625
Total Time: 1.3163504999829456
---------------------------------------------------------------------------
Text: it's up to you to decide whether to admire these people's dedication to their cause or be repelled by their dogmatism , manipulativeness and narrow , fearful view of american life .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1473.37109375
Max VRAM Usage: 2368.72216796875
Total Time: 1.2661940000252798
---------------------------------------------------------------------------
Text: mostly , [goldbacher] just lets her complicated characters be unruly , confusing and , through it all , human .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1473.39453125
Max VRAM Usage: 2366.25439453125
Total Time: 1.2713489000452682
---------------------------------------------------------------------------
Text: . . . quite good at providing some good old fashioned spooks .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1473.421875
Max VRAM Usage: 2364.44384765625
Total Time: 1.3066997999558225
---------------------------------------------------------------------------
Text: at its worst , the movie is pretty diverting ; the pity is that it rarely achieves its best .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1473.44140625
Max VRAM Usage: 2365.59619140625
Total Time: 1.2683667000383139
---------------------------------------------------------------------------
Text: scherfig's light-hearted profile of emotional desperation is achingly honest and delightfully cheeky .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1473.453125
Max VRAM Usage: 2365.43115234375
Total Time: 1.2717904000310227
---------------------------------------------------------------------------
Text: a journey spanning nearly three decades of bittersweet camaraderie and history , in which we feel that we truly know what makes holly and marina tick , and our hearts go out to them as both continue to negotiate their imperfect , love-hate relationship .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 181 || Output tokens: 1
Peak memory Usage: 1473.53125
Max VRAM Usage: 2371.16650390625
Total Time: 1.2673716000281274
---------------------------------------------------------------------------
Text: the wonderfully lush morvern callar is pure punk existentialism , and ms . ramsay and her co-writer , liana dognini , have dramatized the alan warner novel , which itself felt like an answer to irvine welsh's book trainspotting .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 186 || Output tokens: 1
Peak memory Usage: 1473.671875
Max VRAM Usage: 2371.79345703125
Total Time: 1.2963823999743909
---------------------------------------------------------------------------
Text: as it turns out , you can go home again .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1473.67578125
Max VRAM Usage: 2363.95068359375
Total Time: 1.303787300013937
---------------------------------------------------------------------------
Text: you've already seen city by the sea under a variety of titles , but it's worth yet another visit .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1473.69140625
Max VRAM Usage: 2365.76025390625
Total Time: 1.2830848000012338
---------------------------------------------------------------------------
Text: this kind of hands-on storytelling is ultimately what makes shanghai ghetto move beyond a good , dry , reliable textbook and what allows it to rank with its worthy predecessors .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1473.72265625
Max VRAM Usage: 2367.57080078125
Total Time: 1.2764029999962077
---------------------------------------------------------------------------
Text: making such a tragedy the backdrop to a love story risks trivializing it , though chouraqui no doubt intended the film to affirm love's power to help people endure almost unimaginable horror .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1473.7421875
Max VRAM Usage: 2368.55810546875
Total Time: 1.2486272000242025
---------------------------------------------------------------------------
Text: grown-up quibbles are beside the point here . the little girls understand , and mccracken knows that's all that matters .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1473.75390625
Max VRAM Usage: 2366.58349609375
Total Time: 1.2645854000002146
---------------------------------------------------------------------------
Text: a powerful , chilling , and affecting study of one man's dying fall .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1473.76171875
Max VRAM Usage: 2364.60888671875
Total Time: 1.2648750999942422
---------------------------------------------------------------------------
Text: this is a fascinating film because there is no clear-cut hero and no all-out villain .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1473.7734375
Max VRAM Usage: 2365.10205078125
Total Time: 1.2718296999810264
---------------------------------------------------------------------------
Text: a dreadful day in irish history is given passionate , if somewhat flawed , treatment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1473.77734375
Max VRAM Usage: 2364.93798828125
Total Time: 1.2666993000311777
---------------------------------------------------------------------------
Text: . . . a good film that must have baffled the folks in the marketing department .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1473.77734375
Max VRAM Usage: 2365.10205078125
Total Time: 1.2671763999387622
---------------------------------------------------------------------------
Text: . . . is funny in the way that makes you ache with sadness ( the way chekhov is funny ) , profound without ever being self-important , warm without ever succumbing to sentimentality .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1473.78125
Max VRAM Usage: 2368.72216796875
Total Time: 1.2609816000331193
---------------------------------------------------------------------------
Text: devotees of star trek ii : the wrath of khan will feel a nagging sense of deja vu , and the grandeur of the best next generation episodes is lacking .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1473.7890625
Max VRAM Usage: 2367.89990234375
Total Time: 1.2741984999738634
---------------------------------------------------------------------------
Text: a soul-stirring documentary about the israeli/palestinian conflict as revealed through the eyes of some children who remain curious about each other against all odds .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1473.7890625
Max VRAM Usage: 2367.57080078125
Total Time: 1.262796700000763
---------------------------------------------------------------------------
Text: what's so striking about jolie's performance is that she never lets her character become a caricature -- not even with that radioactive hair .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1473.79296875
Max VRAM Usage: 2366.74755859375
Total Time: 1.2788468999788165
---------------------------------------------------------------------------
Text: the main story . . . is compelling enough , but it's difficult to shrug off the annoyance of that chatty fish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1473.79296875
Max VRAM Usage: 2366.41845703125
Total Time: 1.2750386000843719
---------------------------------------------------------------------------
Text: the performances are immaculate , with roussillon providing comic relief .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1473.79296875
Max VRAM Usage: 2364.44384765625
Total Time: 1.2995880999369547
---------------------------------------------------------------------------
Text: kinnear . . . gives his best screen performance with an oddly winning portrayal of one of life's ultimate losers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1473.80078125
Max VRAM Usage: 2366.08935546875
Total Time: 1.2692522999132052
---------------------------------------------------------------------------
Text: hugh grant , who has a good line in charm , has never been more charming than in about a boy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1473.8125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2662380000110716
---------------------------------------------------------------------------
Text: there's a lot of tooth in roger dodger . but what's nice is that there's a casual intelligence that permeates the script .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1473.82421875
Max VRAM Usage: 2366.91259765625
Total Time: 1.2656486999476328
---------------------------------------------------------------------------
Text: reminiscent of alfred hitchcock's thrillers , most of the scary parts in 'signs' occur while waiting for things to happen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1473.8359375
Max VRAM Usage: 2366.74755859375
Total Time: 1.263100799988024
---------------------------------------------------------------------------
Text: one of the best looking and stylish animated movies in quite a while . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1473.83984375
Max VRAM Usage: 2364.77294921875
Total Time: 1.2713961000554264
---------------------------------------------------------------------------
Text: its use of the thriller form to examine the labyrinthine ways in which people's lives cross and change , buffeted by events seemingly out of their control , is intriguing , provocative stuff .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1473.84765625
Max VRAM Usage: 2368.22900390625
Total Time: 1.2644823000300676
---------------------------------------------------------------------------
Text: denver should not get the first and last look at one of the most triumphant performances of vanessa redgrave's career . it deserves to be seen everywhere .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1473.84765625
Max VRAM Usage: 2367.57080078125
Total Time: 1.2711215000599623
---------------------------------------------------------------------------
Text: you needn't be steeped in '50s sociology , pop culture or movie lore to appreciate the emotional depth of haynes' work . though haynes' style apes films from the period . . . its message is not rooted in that decade .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 180 || Output tokens: 1
Peak memory Usage: 1473.87109375
Max VRAM Usage: 2371.04052734375
Total Time: 1.2493459000252187
---------------------------------------------------------------------------
Text: waiting for godard can be fruitful : 'in praise of love' is the director's epitaph for himself .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1473.87890625
Max VRAM Usage: 2365.92529296875
Total Time: 1.276563600054942
---------------------------------------------------------------------------
Text: a gangster movie with the capacity to surprise .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1473.90234375
Max VRAM Usage: 2363.78564453125
Total Time: 1.288835100014694
---------------------------------------------------------------------------
Text: the film has a laundry list of minor shortcomings , but the numerous scenes of gory mayhem are worth the price of admission . . . if " gory mayhem " is your idea of a good time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1473.90234375
Max VRAM Usage: 2369.21630859375
Total Time: 1.2546853999374434
---------------------------------------------------------------------------
Text: if not a home run , then at least a solid base hit .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1473.90625
Max VRAM Usage: 2364.44384765625
Total Time: 1.2939922999357805
---------------------------------------------------------------------------
Text: goldmember is funny enough to justify the embarrassment of bringing a barf bag to the moviehouse .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1473.90625
Max VRAM Usage: 2365.43115234375
Total Time: 1.2673027000855654
---------------------------------------------------------------------------
Text: . . . a fairly disposable yet still entertaining b picture .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1473.90625
Max VRAM Usage: 2364.11474609375
Total Time: 1.3021273000631481
---------------------------------------------------------------------------
Text: it may not be particularly innovative , but the film's crisp , unaffected style and air of gentle longing make it unexpectedly rewarding .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1473.890625
Max VRAM Usage: 2366.25439453125
Total Time: 1.2642730999505147
---------------------------------------------------------------------------
Text: the film truly does rescue [the funk brothers] from motown's shadows . it's about time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1473.89453125
Max VRAM Usage: 2365.59619140625
Total Time: 1.2606145999161527
---------------------------------------------------------------------------
Text: drawing on an irresistible , languid romanticism , byler reveals the ways in which a sultry evening or a beer-fueled afternoon in the sun can inspire even the most retiring heart to venture forth .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1473.92578125
Max VRAM Usage: 2369.05126953125
Total Time: 1.2672638000221923
---------------------------------------------------------------------------
Text: works because we're never sure if ohlinger's on the level or merely a dying , delusional man trying to get into the history books before he croaks .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1473.92578125
Max VRAM Usage: 2367.73486328125
Total Time: 1.261877299984917
---------------------------------------------------------------------------
Text: [scherfig] has made a movie that will leave you wondering about the characters' lives after the clever credits roll .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1473.9296875
Max VRAM Usage: 2366.25439453125
Total Time: 1.2596541999373585
---------------------------------------------------------------------------
Text: a heady , biting , be-bop ride through nighttime manhattan , a loquacious videologue of the modern male and the lengths to which he'll go to weave a protective cocoon around his own ego .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2369.38037109375
Total Time: 1.2519172999309376
---------------------------------------------------------------------------
Text: skin of man gets a few cheap shocks from its kids-in-peril theatrics , but it also taps into the primal fears of young people trying to cope with the mysterious and brutal nature of adults .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2368.72216796875
Total Time: 1.2416636999696493
---------------------------------------------------------------------------
Text: the piano teacher is not an easy film . it forces you to watch people doing unpleasant things to each other and themselves , and it maintains a cool distance from its material that is deliberately unsettling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2368.39306640625
Total Time: 1.2485275000799447
---------------------------------------------------------------------------
Text: as refreshing as a drink from a woodland stream .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2363.78564453125
Total Time: 1.3005533999530599
---------------------------------------------------------------------------
Text: williams absolutely nails sy's queasy infatuation and overall strangeness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2364.77294921875
Total Time: 1.2646361999213696
---------------------------------------------------------------------------
Text: can i admit xxx is as deep as a petri dish and as well-characterized as a telephone book but still say it was a guilty pleasure ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2367.07666015625
Total Time: 1.2590679000131786
---------------------------------------------------------------------------
Text: while it's nothing we haven't seen before from murphy , i spy is still fun and enjoyable and so aggressively silly that it's more than a worthwhile effort .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1473.93359375
Max VRAM Usage: 2367.57080078125
Total Time: 1.2681902999756858
---------------------------------------------------------------------------
Text: by the time it ends in a rush of sequins , flashbulbs , blaring brass and back-stabbing babes , it has said plenty about how show business has infiltrated every corner of society -- and not always for the better .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 177 || Output tokens: 1
Peak memory Usage: 1473.9453125
Max VRAM Usage: 2370.20361328125
Total Time: 1.2480375999584794
---------------------------------------------------------------------------
Text: an intimate contemplation of two marvelously messy lives .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2363.95068359375
Total Time: 1.3186996999429539
---------------------------------------------------------------------------
Text: rarely has skin looked as beautiful , desirable , even delectable , as it does in trouble every day .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2365.76025390625
Total Time: 1.2523750000400469
---------------------------------------------------------------------------
Text: this is one of those rare docs that paints a grand picture of an era and makes the journey feel like a party .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2366.08935546875
Total Time: 1.27313589991536
---------------------------------------------------------------------------
Text: poignant if familiar story of a young person suspended between two cultures .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2364.27978515625
Total Time: 1.2985743000172079
---------------------------------------------------------------------------
Text: a metaphor for a modern-day urban china searching for its identity .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2364.27978515625
Total Time: 1.3092540999641642
---------------------------------------------------------------------------
Text: for all its brooding quality , ash wednesday is suspenseful and ultimately unpredictable , with a sterling ensemble cast .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2365.92529296875
Total Time: 1.2626608000136912
---------------------------------------------------------------------------
Text: an odd drama set in the world of lingerie models and bar dancers in the midwest that held my interest precisely because it didn't try to .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1473.9609375
Max VRAM Usage: 2366.91259765625
Total Time: 1.2996462000301108
---------------------------------------------------------------------------
Text: the film feels uncomfortably real , its language and locations bearing the unmistakable stamp of authority .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1473.96875
Max VRAM Usage: 2365.26708984375
Total Time: 1.3053770000115037
---------------------------------------------------------------------------
Text: despite its faults , gangs excels in spectacle and pacing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1473.97265625
Max VRAM Usage: 2364.11474609375
Total Time: 1.3059046000707895
---------------------------------------------------------------------------
Text: entertaining despite its one-joke premise with the thesis that women from venus and men from mars can indeed get together .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1473.9765625
Max VRAM Usage: 2366.08935546875
Total Time: 1.2726102999877185
---------------------------------------------------------------------------
Text: a tightly directed , highly professional film that's old-fashioned in all the best possible ways .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1473.98046875
Max VRAM Usage: 2365.10205078125
Total Time: 1.2579874000512064
---------------------------------------------------------------------------
Text: it's dark but has wonderfully funny moments ; you care about the characters ; and the action and special effects are first-rate .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1473.984375
Max VRAM Usage: 2366.25439453125
Total Time: 1.2638789999764413
---------------------------------------------------------------------------
Text: in visual fertility treasure planet rivals the top japanese animations of recent vintage .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1473.9921875
Max VRAM Usage: 2364.44384765625
Total Time: 1.3005134999984875
---------------------------------------------------------------------------
Text: enormously enjoyable , high-adrenaline documentary .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1473.9921875
Max VRAM Usage: 2363.62158203125
Total Time: 1.285712799988687
---------------------------------------------------------------------------
Text: buy is an accomplished actress , and this is a big , juicy role .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1473.9921875
Max VRAM Usage: 2364.60888671875
Total Time: 1.2717177000595257
---------------------------------------------------------------------------
Text: it works its magic with such exuberance and passion that the film's length becomes a part of its fun .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1473.99609375
Max VRAM Usage: 2365.92529296875
Total Time: 1.2645872000139207
---------------------------------------------------------------------------
Text: beautifully crafted and brutally honest , promises offers an unexpected window into the complexities of the middle east struggle and into the humanity of its people .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.0078125
Max VRAM Usage: 2366.58349609375
Total Time: 1.2666731000645086
---------------------------------------------------------------------------
Text: an old-fashioned but emotionally stirring adventure tale of the kind they rarely make anymore .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.015625
Max VRAM Usage: 2364.77294921875
Total Time: 1.264204500010237
---------------------------------------------------------------------------
Text: charlotte sometimes is a gem . it's always enthralling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1474.015625
Max VRAM Usage: 2364.44384765625
Total Time: 1.3040887999814004
---------------------------------------------------------------------------
Text: in my opinion , analyze that is not as funny or entertaining as analyze this , but it is a respectable sequel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.015625
Max VRAM Usage: 2365.92529296875
Total Time: 1.262862200033851
---------------------------------------------------------------------------
Text: a remarkable film by bernard rose .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1474.01953125
Max VRAM Usage: 2363.45654296875
Total Time: 1.3023442999692634
---------------------------------------------------------------------------
Text: zhuangzhuang creates delicate balance of style , text , and subtext that's so simple and precise that anything discordant would topple the balance , but against all odds , nothing does .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1474.03515625
Max VRAM Usage: 2368.88720703125
Total Time: 1.2556071999715641
---------------------------------------------------------------------------
Text: a much more successful translation than its most famous previous film adaptation , writer-director anthony friedman's similarly updated 1970 british production .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1474.03515625
Max VRAM Usage: 2366.91259765625
Total Time: 1.2661585999885574
---------------------------------------------------------------------------
Text: an original and highly cerebral examination of the psychopathic mind

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1474.03515625
Max VRAM Usage: 2363.95068359375
Total Time: 1.3006051999982446
---------------------------------------------------------------------------
Text: michel piccoli's moving performance is this films reason for being .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1474.03515625
Max VRAM Usage: 2364.44384765625
Total Time: 1.2963652999605983
---------------------------------------------------------------------------
Text: a captivating and intimate study about dying and loving . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1474.04296875
Max VRAM Usage: 2364.11474609375
Total Time: 1.3012856000568718
---------------------------------------------------------------------------
Text: this is an elegantly balanced movie -- every member of the ensemble has something fascinating to do -- that doesn't reveal even a hint of artifice .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1474.04296875
Max VRAM Usage: 2367.07666015625
Total Time: 1.280985299963504
---------------------------------------------------------------------------
Text: [grant] goes beyond his usual fluttering and stammering and captures the soul of a man in pain who gradually comes to recognize it and deal with it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.05078125
Max VRAM Usage: 2367.57080078125
Total Time: 1.260478699929081
---------------------------------------------------------------------------
Text: a high-spirited buddy movie about the reunion of berlin anarchists who face arrest 15 years after their crime .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.05078125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2597055999794975
---------------------------------------------------------------------------
Text: about the best thing you could say about narc is that it's a rock-solid little genre picture . whether you like it or not is basically a matter of taste .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.05078125
Max VRAM Usage: 2367.57080078125
Total Time: 1.2666860999306664
---------------------------------------------------------------------------
Text: an involving , inspirational drama that sometimes falls prey to its sob-story trappings .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.05078125
Max VRAM Usage: 2364.77294921875
Total Time: 1.262468299944885
---------------------------------------------------------------------------
Text: some of the most inventive silliness you are likely to witness in a movie theatre for some time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.05078125
Max VRAM Usage: 2365.43115234375
Total Time: 1.262542099924758
---------------------------------------------------------------------------
Text: canadian filmmaker gary burns' inventive and mordantly humorous take on the soullessness of work in the city .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.0625
Max VRAM Usage: 2365.92529296875
Total Time: 1.2640110000502318
---------------------------------------------------------------------------
Text: a rollicking ride , with jaw-dropping action sequences , striking villains , a gorgeous color palette , astounding technology , stirring music and a boffo last hour that leads up to a strangely sinister happy ending .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1474.08984375
Max VRAM Usage: 2369.21630859375
Total Time: 1.245705800014548
---------------------------------------------------------------------------
Text: everyone's insecure in lovely and amazing , a poignant and wryly amusing film about mothers , daughters and their relationships .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1474.09765625
Max VRAM Usage: 2366.08935546875
Total Time: 1.2664971000049263
---------------------------------------------------------------------------
Text: the closest thing to the experience of space travel

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1474.08203125
Max VRAM Usage: 2363.62158203125
Total Time: 1.2937648999504745
---------------------------------------------------------------------------
Text: full of surprises .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 132 || Output tokens: 1
Peak memory Usage: 1474.11328125
Max VRAM Usage: 2362.79833984375
Total Time: 1.2932738999370486
---------------------------------------------------------------------------
Text: connoisseurs of chinese film will be pleased to discover that tian's meticulous talent has not withered during his enforced hiatus .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.11328125
Max VRAM Usage: 2366.58349609375
Total Time: 1.2623988999985158
---------------------------------------------------------------------------
Text: if you can push on through the slow spots , you'll be rewarded with some fine acting .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1474.11328125
Max VRAM Usage: 2365.26708984375
Total Time: 1.2677609999664128
---------------------------------------------------------------------------
Text: an unusually dry-eyed , even analytical approach to material that is generally played for maximum moisture .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1474.11328125
Max VRAM Usage: 2365.10205078125
Total Time: 1.2761786000337452
---------------------------------------------------------------------------
Text: symbolically , warm water under a red bridge is a celebration of feminine energy , a tribute to the power of women to heal .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1474.11328125
Max VRAM Usage: 2366.41845703125
Total Time: 1.2723033999791369
---------------------------------------------------------------------------
Text: spy kids 2 also happens to be that rarity among sequels : it actually improves upon the original hit movie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.1171875
Max VRAM Usage: 2365.92529296875
Total Time: 1.2627872999291867
---------------------------------------------------------------------------
Text: exceptionally well acted by diane lane and richard gere .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1474.1171875
Max VRAM Usage: 2364.11474609375
Total Time: 1.292188199935481
---------------------------------------------------------------------------
Text: like a precious and finely cut diamond , magnificent to behold in its sparkling beauty yet in reality it's one tough rock .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1474.1171875
Max VRAM Usage: 2366.08935546875
Total Time: 1.264176799915731
---------------------------------------------------------------------------
Text: in addition to scoring high for originality of plot -- putting together familiar themes of family , forgiveness and love in a new way -- lilo & stitch has a number of other assets to commend it to movie audiences both innocent and jaded .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 176 || Output tokens: 1
Peak memory Usage: 1474.125
Max VRAM Usage: 2370.03857421875
Total Time: 1.2679885000688955
---------------------------------------------------------------------------
Text: miller has crafted an intriguing story of maternal instincts and misguided acts of affection .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.125
Max VRAM Usage: 2364.77294921875
Total Time: 1.2673322999617085
---------------------------------------------------------------------------
Text: one of the most exciting action films to come out of china in recent years .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.125
Max VRAM Usage: 2364.77294921875
Total Time: 1.2772503000451252
---------------------------------------------------------------------------
Text: this is a nervy , risky film , and villeneuve has inspired croze to give herself over completely to the tormented persona of bibi .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1474.125
Max VRAM Usage: 2367.24169921875
Total Time: 1.2591525999596342
---------------------------------------------------------------------------
Text: my little eye is the best little " horror " movie i've seen in years .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1474.12890625
Max VRAM Usage: 2364.93798828125
Total Time: 1.2611493000295013
---------------------------------------------------------------------------
Text: tunney , brimming with coltish , neurotic energy , holds the screen like a true star .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.12890625
Max VRAM Usage: 2365.76025390625
Total Time: 1.2594089000485837
---------------------------------------------------------------------------
Text: even if the naipaul original remains the real masterpiece , the movie possesses its own languorous charm .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1474.1328125
Max VRAM Usage: 2365.59619140625
Total Time: 1.259446799987927
---------------------------------------------------------------------------
Text: [the film] tackles the topic of relationships in such a straightforward , emotionally honest manner that by the end , it's impossible to ascertain whether the film is , at its core , deeply pessimistic or quietly hopeful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1474.140625
Max VRAM Usage: 2369.21630859375
Total Time: 1.2577906000660732
---------------------------------------------------------------------------
Text: sometimes we feel as if the film careens from one colorful event to another without respite , but sometimes it must have seemed to frida kahlo as if her life did , too .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1474.140625
Max VRAM Usage: 2368.39306640625
Total Time: 1.255313399946317
---------------------------------------------------------------------------
Text: the strength of the film lies in its two central performances by sven wollter as the stricken composer and viveka seldahl as his desperate violinist wife .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1474.1484375
Max VRAM Usage: 2367.73486328125
Total Time: 1.259933999972418
---------------------------------------------------------------------------
Text: like the series , the movie is funny , smart , visually inventive , and most of all , alive .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1474.15234375
Max VRAM Usage: 2365.59619140625
Total Time: 1.285857200040482
---------------------------------------------------------------------------
Text: it was filled with shootings , beatings , and more cussing than you could shake a stick at .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.15234375
Max VRAM Usage: 2365.76025390625
Total Time: 1.2718644000124186
---------------------------------------------------------------------------
Text: you don't know whether to admire the film's stately nature and call it classicism or be exasperated by a noticeable lack of pace . or both .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.203125
Max VRAM Usage: 2367.57080078125
Total Time: 1.2682610999327153
---------------------------------------------------------------------------
Text: sure , i hated myself in the morning . but then again , i hate myself most mornings . i still like moonlight mile , better judgment be damned .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1474.21484375
Max VRAM Usage: 2367.24169921875
Total Time: 1.2635294999927282
---------------------------------------------------------------------------
Text: time out is as serious as a pink slip . and more than that , it's an observant , unfussily poetic meditation about identity and alienation .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1474.234375
Max VRAM Usage: 2367.40576171875
Total Time: 1.2703890999546275
---------------------------------------------------------------------------
Text: will assuredly rank as one of the cleverest , most deceptively amusing comedies of the year .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.234375
Max VRAM Usage: 2365.76025390625
Total Time: 1.2766429000766948
---------------------------------------------------------------------------
Text: maryam is a small film , but it offers large rewards .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1474.23828125
Max VRAM Usage: 2364.27978515625
Total Time: 1.2939968999708071
---------------------------------------------------------------------------
Text: a highly watchable , giggly little story with a sweet edge to it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.24609375
Max VRAM Usage: 2364.77294921875
Total Time: 1.266630299971439
---------------------------------------------------------------------------
Text: the most consistently funny of the austin powers films .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1474.25
Max VRAM Usage: 2363.95068359375
Total Time: 1.3019248000346124
---------------------------------------------------------------------------
Text: ana's journey is not a stereotypical one of self-discovery , as she's already comfortable enough in her own skin to be proud of her rubenesque physique . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1474.2578125
Max VRAM Usage: 2368.06396484375
Total Time: 1.2678117000032216
---------------------------------------------------------------------------
Text: cockettes has the glorious , gaudy benefit of much stock footage of those days , featuring all manner of drag queen , bearded lady and lactating hippie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1474.2578125
Max VRAM Usage: 2367.89990234375
Total Time: 1.2769531999947503
---------------------------------------------------------------------------
Text: there's something poignant about an artist of 90-plus years taking the effort to share his impressions of life and loss and time and art with us .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1474.26171875
Max VRAM Usage: 2367.07666015625
Total Time: 1.259222799912095
---------------------------------------------------------------------------
Text: the comedy makes social commentary more palatable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1474.26171875
Max VRAM Usage: 2363.62158203125
Total Time: 1.293993000057526
---------------------------------------------------------------------------
Text: an ideal love story for those intolerant of the more common saccharine genre .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1474.26953125
Max VRAM Usage: 2364.93798828125
Total Time: 1.275847899960354
---------------------------------------------------------------------------
Text: one funny popcorn flick .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1474.26953125
Max VRAM Usage: 2362.96337890625
Total Time: 1.2928069999907166
---------------------------------------------------------------------------
Text: this new zealand coming-of-age movie isn't really about anything . when it's this rich and luscious , who cares ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.26953125
Max VRAM Usage: 2366.58349609375
Total Time: 1.268559699994512
---------------------------------------------------------------------------
Text: tully is worth a look for its true-to-life characters , its sensitive acting , its unadorned view of rural life and the subtle direction of first-timer hilary birmingham .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1474.26953125
Max VRAM Usage: 2368.55810546875
Total Time: 1.247509399894625
---------------------------------------------------------------------------
Text: this gorgeous epic is guaranteed to lift the spirits of the whole family .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1474.26953125
Max VRAM Usage: 2364.44384765625
Total Time: 1.2964335998985916
---------------------------------------------------------------------------
Text: the wild thornberrys movie is pleasant enough and the message of our close ties with animals can certainly not be emphasized enough .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.2734375
Max VRAM Usage: 2366.58349609375
Total Time: 1.2673613999504596
---------------------------------------------------------------------------
Text: williams creates a stunning , taxi driver-esque portrayal of a man teetering on the edge of sanity .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.28125
Max VRAM Usage: 2365.76025390625
Total Time: 1.2591736000031233
---------------------------------------------------------------------------
Text: if you're in the right b-movie frame of mind , it may just scare the pants off you .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.28125
Max VRAM Usage: 2365.76025390625
Total Time: 1.2612536000087857
---------------------------------------------------------------------------
Text: a movie of riveting power and sadness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1474.28515625
Max VRAM Usage: 2363.62158203125
Total Time: 1.3091814999934286
---------------------------------------------------------------------------
Text: both a detective story and a romance spiced with the intrigue of academic skullduggery and politics .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.2890625
Max VRAM Usage: 2365.76025390625
Total Time: 1.2743445999221876
---------------------------------------------------------------------------
Text: quietly engaging .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 131 || Output tokens: 1
Peak memory Usage: 1474.30078125
Max VRAM Usage: 2362.63427734375
Total Time: 1.2950117000145838
---------------------------------------------------------------------------
Text: ludicrous , but director carl franklin adds enough flourishes and freak-outs to make it entertaining .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.30078125
Max VRAM Usage: 2365.43115234375
Total Time: 1.2599756000563502
---------------------------------------------------------------------------
Text: director roger kumble offers just enough sweet and traditional romantic comedy to counter the crudity . and there's the inimitable diaz , holding it all together .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1474.31640625
Max VRAM Usage: 2367.73486328125
Total Time: 1.267519999993965
---------------------------------------------------------------------------
Text: spielberg's picture is smarter and subtler than [total recall and blade runner] , although its plot may prove too convoluted for fun-seeking summer audiences .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.3203125
Max VRAM Usage: 2367.57080078125
Total Time: 1.2757069000508636
---------------------------------------------------------------------------
Text: it's got all the familiar bruckheimer elements , and schumacher does probably as good a job as anyone at bringing off the hopkins/rock collision of acting styles and onscreen personas .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1474.32421875
Max VRAM Usage: 2368.72216796875
Total Time: 1.2500211999285966
---------------------------------------------------------------------------
Text: a grittily beautiful film that looks , sounds , and feels more like an extended , open-ended poem than a traditionally structured story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.32421875
Max VRAM Usage: 2366.58349609375
Total Time: 1.2640718000475317
---------------------------------------------------------------------------
Text: dense , exhilarating documentary .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1474.32421875
Max VRAM Usage: 2363.12744140625
Total Time: 1.2956641999771819
---------------------------------------------------------------------------
Text: the production values are of the highest and the performances attractive without being memorable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2364.60888671875
Total Time: 1.260715899989009
---------------------------------------------------------------------------
Text: a well-rounded tribute to a man whose achievements -- and complexities -- reached far beyond the end zone .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2365.43115234375
Total Time: 1.2726602999027818
---------------------------------------------------------------------------
Text: finely crafted , finely written , exquisitely performed

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2363.95068359375
Total Time: 1.2925366000272334
---------------------------------------------------------------------------
Text: ramsay and morton fill this character study with poetic force and buoyant feeling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2365.10205078125
Total Time: 1.2711762000108138
---------------------------------------------------------------------------
Text: this submarine drama earns the right to be favorably compared to das boot .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2364.60888671875
Total Time: 1.2657897999743
---------------------------------------------------------------------------
Text: claude chabrol's camera has a way of gently swaying back and forth as it cradles its characters , veiling tension beneath otherwise tender movements .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2367.57080078125
Total Time: 1.2585482000140473
---------------------------------------------------------------------------
Text: there's a great deal of corny dialogue and preposterous moments . and yet , it still works .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2365.76025390625
Total Time: 1.2642402000492439
---------------------------------------------------------------------------
Text: the film was immensely enjoyable thanks to great performances by both steve buscemi and rosario dawson . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2366.08935546875
Total Time: 1.2621476000640541
---------------------------------------------------------------------------
Text: like many western action films , this thriller is too loud and thoroughly overbearing , but its heartfelt concern about north korea's recent past and south korea's future adds a much needed moral weight .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1474.33203125
Max VRAM Usage: 2368.72216796875
Total Time: 1.2494346000021324
---------------------------------------------------------------------------
Text: special p . o . v . camera mounts on bikes , skateboards , and motorcycles provide an intense experience when splashed across the immense imax screen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1474.3359375
Max VRAM Usage: 2367.24169921875
Total Time: 1.2625913999509066
---------------------------------------------------------------------------
Text: a joyous occasion

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 132 || Output tokens: 1
Peak memory Usage: 1474.3359375
Max VRAM Usage: 2362.79833984375
Total Time: 1.3007397999754176
---------------------------------------------------------------------------
Text: mike white's deft combination of serious subject matter and dark , funny humor make " " the good girl " a film worth watching .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.3359375
Max VRAM Usage: 2366.58349609375
Total Time: 1.2585855999495834
---------------------------------------------------------------------------
Text: this is a shrewd and effective film from a director who understands how to create and sustain a mood .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.3515625
Max VRAM Usage: 2365.76025390625
Total Time: 1.2627517000073567
---------------------------------------------------------------------------
Text: meant to reduce blake's philosophy into a tragic coming-of-age saga punctuated by bursts of animator todd mcfarlane's superhero dystopia .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1474.3515625
Max VRAM Usage: 2367.07666015625
Total Time: 1.2739754999056458
---------------------------------------------------------------------------
Text: assayas' ambitious , sometimes beautiful adaptation of jacques chardonne's novel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1474.3515625
Max VRAM Usage: 2364.93798828125
Total Time: 1.2585868999594823
---------------------------------------------------------------------------
Text: as ex-marine walter , who may or may not have shot kennedy , actor raymond j . barry is perfectly creepy and believable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1474.359375
Max VRAM Usage: 2367.07666015625
Total Time: 1.264843999990262
---------------------------------------------------------------------------
Text: those who don't entirely 'get' godard's distinctive discourse will still come away with a sense of his reserved but existential poignancy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1474.359375
Max VRAM Usage: 2366.91259765625
Total Time: 1.2676943000406027
---------------------------------------------------------------------------
Text: pete's screenplay manages to find that real natural , even-flowing tone that few movies are able to accomplish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.36328125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2734899999340996
---------------------------------------------------------------------------
Text: like brosnan's performance , evelyn comes from the heart .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1474.36328125
Max VRAM Usage: 2364.60888671875
Total Time: 1.2844690000638366
---------------------------------------------------------------------------
Text: it uses some of the figures from the real-life story to portray themselves in the film . the result is a powerful , naturally dramatic piece of low-budget filmmaking .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.3671875
Max VRAM Usage: 2367.57080078125
Total Time: 1.2651754999533296
---------------------------------------------------------------------------
Text: its spirit of iconoclastic abandon -- however canned -- makes for unexpectedly giddy viewing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1474.3671875
Max VRAM Usage: 2365.10205078125
Total Time: 1.2738471999764442
---------------------------------------------------------------------------
Text: the early and middle passages are surprising in how much they engage and even touch us . this is not a classical dramatic animated feature , nor a hip , contemporary , in-jokey one . it's sort of in-between , and it works .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 177 || Output tokens: 1
Peak memory Usage: 1474.3828125
Max VRAM Usage: 2370.20361328125
Total Time: 1.256643799948506
---------------------------------------------------------------------------
Text: this quiet , introspective and entertaining independent is worth seeking .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1474.390625
Max VRAM Usage: 2364.11474609375
Total Time: 1.3057196999434382
---------------------------------------------------------------------------
Text: whether our action-and-popcorn obsessed culture will embrace this engaging and literate psychodrama isn't much of a mystery , unfortunately .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2366.58349609375
Total Time: 1.267239800072275
---------------------------------------------------------------------------
Text: whether or not ram dass proves as clear and reliable an authority on that as he was about inner consciousness , fierce grace reassures us that he will once again be an honest and loving one .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2368.39306640625
Total Time: 1.2508871000027284
---------------------------------------------------------------------------
Text: sly , sophisticated and surprising .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2363.12744140625
Total Time: 1.3001508999150246
---------------------------------------------------------------------------
Text: spare but quietly effective retelling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2363.29248046875
Total Time: 1.30755849997513
---------------------------------------------------------------------------
Text: demonstrates a vivid imagination and an impressive style that result in some terrific setpieces .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2364.77294921875
Total Time: 1.2622847999446094
---------------------------------------------------------------------------
Text: by its modest , straight-ahead standards , undisputed scores a direct hit .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2364.60888671875
Total Time: 1.2656771999318153
---------------------------------------------------------------------------
Text: its story about a young chinese woman , ah na , who has come to new york city to replace past tragedy with the american dream is one that any art-house moviegoer is likely to find compelling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1474.39453125
Max VRAM Usage: 2368.88720703125
Total Time: 1.2538330999668688
---------------------------------------------------------------------------
Text: for those who like quirky , slightly strange french films , this is a must !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.3984375
Max VRAM Usage: 2364.77294921875
Total Time: 1.2636498000938445
---------------------------------------------------------------------------
Text: there are so few films about the plight of american indians in modern america that skins comes as a welcome , if downbeat , missive from a forgotten front .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.40234375
Max VRAM Usage: 2367.57080078125
Total Time: 1.2716531999176368
---------------------------------------------------------------------------
Text: [shyamalan] continues to cut a swathe through mainstream hollywood , while retaining an integrity and refusing to compromise his vision .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1474.40234375
Max VRAM Usage: 2366.74755859375
Total Time: 1.2662165000801906
---------------------------------------------------------------------------
Text: a whale of a good time for both children and parents seeking christian-themed fun .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.40234375
Max VRAM Usage: 2364.77294921875
Total Time: 1.2675382000161335
---------------------------------------------------------------------------
Text: what begins as a film in the tradition of the graduate quickly switches into something more recyclable than significant .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1474.40625
Max VRAM Usage: 2365.59619140625
Total Time: 1.2584241000004113
---------------------------------------------------------------------------
Text: much smarter and more attentive than it first sets out to be .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1474.40625
Max VRAM Usage: 2364.27978515625
Total Time: 1.3244677999755368
---------------------------------------------------------------------------
Text: the story is smart and entirely charming in intent and execution .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1474.40625
Max VRAM Usage: 2364.11474609375
Total Time: 1.3132818000158295
---------------------------------------------------------------------------
Text: a movie of technical skill and rare depth of intellect and feeling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1474.41015625
Max VRAM Usage: 2364.27978515625
Total Time: 1.3020038000540808
---------------------------------------------------------------------------
Text: represents a worthy departure from the culture clash comedies that have marked an emerging indian american cinema .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1474.41015625
Max VRAM Usage: 2365.26708984375
Total Time: 1.2762413000455126
---------------------------------------------------------------------------
Text: doesn't do more than expand a tv show to movie length . however , it's pleasant enough and its ecological , pro-wildlife sentiments are certainly welcome .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1474.4375
Max VRAM Usage: 2367.40576171875
Total Time: 1.2953986000502482
---------------------------------------------------------------------------
Text: if you're looking for an intelligent movie in which you can release your pent up anger , enough is just the ticket you need .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1474.4453125
Max VRAM Usage: 2366.41845703125
Total Time: 1.2689712999854237
---------------------------------------------------------------------------
Text: a pointed , often tender , examination of the pros and cons of unconditional love and familial duties .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1474.45703125
Max VRAM Usage: 2365.26708984375
Total Time: 1.2645424000220373
---------------------------------------------------------------------------
Text: as well-acted and well-intentioned as all or nothing is , however , the film comes perilously close to being too bleak , too pessimistic and too unflinching for its own good .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1474.46875
Max VRAM Usage: 2369.05126953125
Total Time: 1.2560896000359207
---------------------------------------------------------------------------
Text: a comedy-drama of nearly epic proportions rooted in a sincere performance by the title character undergoing midlife crisis .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.46875
Max VRAM Usage: 2365.76025390625
Total Time: 1.272428199998103
---------------------------------------------------------------------------
Text: it's about issues most adults have to face in marriage and i think that's what i liked about it -- the real issues tucked between the silly and crude storyline .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1474.4765625
Max VRAM Usage: 2367.57080078125
Total Time: 1.267805999959819
---------------------------------------------------------------------------
Text: elegantly produced and expressively performed , the six musical numbers crystallize key plot moments into minutely detailed wonders of dreamlike ecstasy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2366.58349609375
Total Time: 1.2667103999992833
---------------------------------------------------------------------------
Text: enriched by a strong and unforced supporting cast .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2363.78564453125
Total Time: 1.2990681999363005
---------------------------------------------------------------------------
Text: writer/ director m . night shyamalan's ability to pull together easily accessible stories that resonate with profundity is undeniable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2366.25439453125
Total Time: 1.2662637999746948
---------------------------------------------------------------------------
Text: if you can keep your eyes open amid all the blood and gore , you'll see del toro has brought unexpected gravity to blade ii .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2366.74755859375
Total Time: 1.254931699950248
---------------------------------------------------------------------------
Text: not a strike against yang's similarly themed yi yi , but i found what time ? to be more engaging on an emotional level , funnier , and on the whole less detached .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2368.06396484375
Total Time: 1.2641942999325693
---------------------------------------------------------------------------
Text: a breathtaking adventure for all ages , spirit tells its poignant and uplifting story in a stunning fusion of music and images .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2365.92529296875
Total Time: 1.2723419999238104
---------------------------------------------------------------------------
Text: a charming and funny story of clashing cultures and a clashing mother/daughter relationship .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1474.48046875
Max VRAM Usage: 2365.10205078125
Total Time: 1.263244800036773
---------------------------------------------------------------------------
Text: never lets go your emotions , taking them to surprising highs , sorrowful lows and hidden impulsive niches . . . gorgeous , passionate , and at times uncommonly moving .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1474.484375
Max VRAM Usage: 2367.89990234375
Total Time: 1.2659828000469133
---------------------------------------------------------------------------
Text: " . . . something appears to have been lost in the translation this time . the importance of being earnest movie seems to be missing a great deal of the acerbic repartee of the play . "

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1474.48828125
Max VRAM Usage: 2369.05126953125
Total Time: 1.2560867998981848
---------------------------------------------------------------------------
Text: [washington's] strong hand , keen eye , sweet spirit and good taste are reflected in almost every scene .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.48828125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2627306999638677
---------------------------------------------------------------------------
Text: shiner can certainly go the distance , but isn't world championship material

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1474.48828125
Max VRAM Usage: 2364.44384765625
Total Time: 1.3221818000311032
---------------------------------------------------------------------------
Text: the film's desire to be liked sometimes undermines the possibility for an exploration of the thornier aspects of the nature/nurture argument in regards to homosexuality .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1474.48828125
Max VRAM Usage: 2367.40576171875
Total Time: 1.2743060000939295
---------------------------------------------------------------------------
Text: . . . a quietly introspective portrait of the self-esteem of employment and the shame of losing a job . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1474.4921875
Max VRAM Usage: 2366.08935546875
Total Time: 1.2645142999244854
---------------------------------------------------------------------------
Text: affable if not timeless , like mike raises some worthwhile themes while delivering a wholesome fantasy for kids .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.4921875
Max VRAM Usage: 2365.43115234375
Total Time: 1.2634179999586195
---------------------------------------------------------------------------
Text: a film of delicate interpersonal dances . caine makes us watch as his character awakens to the notion that to be human is eventually to have to choose . it's a sight to behold .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1474.4921875
Max VRAM Usage: 2368.39306640625
Total Time: 1.2429333999752998
---------------------------------------------------------------------------
Text: it's an unusual , thoughtful bio-drama with a rich subject and some fantastic moments and scenes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.4921875
Max VRAM Usage: 2365.43115234375
Total Time: 1.2662934999680147
---------------------------------------------------------------------------
Text: saved from being merely way-cool by a basic , credible compassion .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1474.49609375
Max VRAM Usage: 2364.44384765625
Total Time: 1.2957886999938637
---------------------------------------------------------------------------
Text: the increasingly diverse french director has created a film that one can honestly describe as looking , sounding and simply feeling like no other film in recent history .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1474.49609375
Max VRAM Usage: 2366.91259765625
Total Time: 1.2600585999898612
---------------------------------------------------------------------------
Text: gangs , despite the gravity of its subject matter , is often as fun to watch as a good spaghetti western .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.5
Max VRAM Usage: 2365.76025390625
Total Time: 1.2674629000248387
---------------------------------------------------------------------------
Text: peter jackson has done the nearly impossible . he has improved upon the first and taken it a step further , richer and deeper . what jackson has done is proven that no amount of imagination , no creature , no fantasy story and no incredibly outlandish scenery

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 180 || Output tokens: 1
Peak memory Usage: 1474.5
Max VRAM Usage: 2371.04052734375
Total Time: 1.2816087000537664
---------------------------------------------------------------------------
Text: there has to be a few advantages to never growing old . like being able to hit on a 15-year old when you're over 100 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

I

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

I
Response: none
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1474.50390625
Max VRAM Usage: 2367.07666015625
Total Time: 1.2652669999515638
---------------------------------------------------------------------------
Text: ice age won't drop your jaw , but it will warm your heart , and i'm giving it a strong thumbs up .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1474.50390625
Max VRAM Usage: 2366.25439453125
Total Time: 1.2685387999517843
---------------------------------------------------------------------------
Text: like kissing jessica stein , amy's orgasm has a key strength in its willingness to explore its principal characters with honesty , insight and humor .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1474.73046875
Max VRAM Usage: 2367.07666015625
Total Time: 1.2686757000628859
---------------------------------------------------------------------------
Text: the lady and the duke is eric rohmer's economical antidote to the bloated costume drama

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1474.74609375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2564037999836728
---------------------------------------------------------------------------
Text: one of the year's best films , featuring an oscar-worthy performance by julianne moore .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.75
Max VRAM Usage: 2365.43115234375
Total Time: 1.2822966000530869
---------------------------------------------------------------------------
Text: a small gem from belgium .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1474.765625
Max VRAM Usage: 2363.29248046875
Total Time: 1.2992770998971537
---------------------------------------------------------------------------
Text: combines a comically dismal social realism with a farcically bawdy fantasy of redemption and regeneration .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1474.77734375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2743340999586508
---------------------------------------------------------------------------
Text: a soap-opera quality twist in the last 20 minutes . . . almost puts the kibosh on what is otherwise a sumptuous work of b-movie imagination .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1474.78125
Max VRAM Usage: 2368.06396484375
Total Time: 1.2830808999715373
---------------------------------------------------------------------------
Text: the most ingenious film comedy since being john malkovich .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1474.78515625
Max VRAM Usage: 2364.11474609375
Total Time: 1.3050584000302479
---------------------------------------------------------------------------
Text: there's something to be said for a studio-produced film that never bothers to hand viewers a suitcase full of easy answers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1474.7890625
Max VRAM Usage: 2366.08935546875
Total Time: 1.260854099993594
---------------------------------------------------------------------------
Text: a movie where story is almost an afterthought amidst a swirl of colors and inexplicable events .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1474.7890625
Max VRAM Usage: 2365.26708984375
Total Time: 1.2759744999930263
---------------------------------------------------------------------------
Text: manages to accomplish what few sequels can -- it equals the original and in some ways even betters it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1474.80078125
Max VRAM Usage: 2365.76025390625
Total Time: 1.26273499999661
---------------------------------------------------------------------------
Text: to call this one an eventual cult classic would be an understatement , and woe is the horror fan who opts to overlook this goofily endearing and well-lensed gorefest .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1474.80859375
Max VRAM Usage: 2368.39306640625
Total Time: 1.2491771000204608
---------------------------------------------------------------------------
Text: jolie gives it that extra little something that makes it worth checking out at theaters , especially if you're in the mood for something more comfortable than challenging .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1474.8203125
Max VRAM Usage: 2367.24169921875
Total Time: 1.2682630999479443
---------------------------------------------------------------------------
Text: although melodramatic and predictable , this romantic comedy explores the friendship between five filipino-americans and their frantic efforts to find love .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2366.91259765625
Total Time: 1.2629082999192178
---------------------------------------------------------------------------
Text: i have a new favorite musical -- and i'm not even a fan of the genre

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2364.93798828125
Total Time: 1.284418600029312
---------------------------------------------------------------------------
Text: it's unlikely we'll see a better thriller this year .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2364.11474609375
Total Time: 1.2981803000438958
---------------------------------------------------------------------------
Text: there is a real subject here , and it is handled with intelligence and care .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2645064999815077
---------------------------------------------------------------------------
Text: jason patric and ray liotta make for one splendidly cast pair .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2639637999236584
---------------------------------------------------------------------------
Text: noyce creates a film of near-hypnotic physical beauty even as he tells a story as horrifying as any in the heart-breakingly extensive annals of white-on-black racism .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2368.39306640625
Total Time: 1.2548763999948278
---------------------------------------------------------------------------
Text: starts slowly , but adrien brody  in the title role  helps make the film's conclusion powerful and satisfying .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1474.82421875
Max VRAM Usage: 2366.41845703125
Total Time: 1.269918099977076
---------------------------------------------------------------------------
Text: very predictable but still entertaining

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1474.828125
Max VRAM Usage: 2362.96337890625
Total Time: 1.2957724999869242
---------------------------------------------------------------------------
Text: nothing short of a masterpiece -- and a challenging one .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1474.828125
Max VRAM Usage: 2363.95068359375
Total Time: 1.2973301999736577
---------------------------------------------------------------------------
Text: pratfalls aside , barbershop gets its greatest play from the timeless spectacle of people really talking to each other .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.828125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2608320999424905
---------------------------------------------------------------------------
Text: this amiable picture talks tough , but it's all bluster -- in the end it's as sweet as greenfingers . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1474.83984375
Max VRAM Usage: 2366.74755859375
Total Time: 1.261613699956797
---------------------------------------------------------------------------
Text: this is one of mr . chabrol's subtlest works , but also one of his most uncanny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1474.828125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2651162999682128
---------------------------------------------------------------------------
Text: an engrossing iranian film about two itinerant teachers and some lost and desolate people they encounter in a place where war has savaged the lives and liberties of the poor and the dispossessed .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1474.86328125
Max VRAM Usage: 2369.21630859375
Total Time: 1.2624773000134155
---------------------------------------------------------------------------
Text: even though we know the outcome , the seesawing of the general's fate in the arguments of competing lawyers has the stomach-knotting suspense of a legal thriller , while the testimony of witnesses lends the film a resonant undertone of tragedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 178 || Output tokens: 1
Peak memory Usage: 1474.91015625
Max VRAM Usage: 2370.36767578125
Total Time: 1.2462042999686673
---------------------------------------------------------------------------
Text: watching spirited away is like watching an eastern imagination explode .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1474.91015625
Max VRAM Usage: 2363.95068359375
Total Time: 1.295839300029911
---------------------------------------------------------------------------
Text: as relationships shift , director robert j . siegel allows the characters to inhabit their world without cleaving to a narrative arc .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1474.91015625
Max VRAM Usage: 2366.25439453125
Total Time: 1.2634224999928847
---------------------------------------------------------------------------
Text: twohy knows how to inflate the mundane into the scarifying , and gets full mileage out of the rolling of a stray barrel or the unexpected blast of a phonograph record .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1474.91015625
Max VRAM Usage: 2367.89990234375
Total Time: 1.260969200055115
---------------------------------------------------------------------------
Text: while the story does seem pretty unbelievable at times , it's awfully entertaining to watch .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1474.91015625
Max VRAM Usage: 2365.10205078125
Total Time: 1.2670683999313042
---------------------------------------------------------------------------
Text: a smart and funny , albeit sometimes superficial , cautionary tale of a technology in search of an artist .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1474.921875
Max VRAM Usage: 2365.59619140625
Total Time: 1.2639977000653744
---------------------------------------------------------------------------
Text: examines its explosive subject matter as nonjudgmentally as wiseman's previous studies of inner-city high schools , hospitals , courts and welfare centers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1474.921875
Max VRAM Usage: 2366.91259765625
Total Time: 1.263185599935241
---------------------------------------------------------------------------
Text: i prefer soderbergh's concentration on his two lovers over tarkovsky's mostly male , mostly patriarchal debating societies .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1474.92578125
Max VRAM Usage: 2366.41845703125
Total Time: 1.2780944000696763
---------------------------------------------------------------------------
Text: 'if you are in the mood for an intelligent weepy , it can easily worm its way into your heart . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1474.9296875
Max VRAM Usage: 2366.08935546875
Total Time: 1.264997599995695
---------------------------------------------------------------------------
Text: in imax in short , it's just as wonderful on the big screen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.9296875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2609358000336215
---------------------------------------------------------------------------
Text: does a good job of establishing a time and place , and of telling a fascinating character's story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1474.93359375
Max VRAM Usage: 2365.43115234375
Total Time: 1.279544600052759
---------------------------------------------------------------------------
Text: i'm going to give it a marginal thumbs up . i liked it just enough .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1474.9375
Max VRAM Usage: 2364.93798828125
Total Time: 1.274504299974069
---------------------------------------------------------------------------
Text: those of you who don't believe in santa claus probably also think that sequels can never capture the magic of the original . well , this movie proves you wrong on both counts .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1474.94140625
Max VRAM Usage: 2368.22900390625
Total Time: 1.243768799933605
---------------------------------------------------------------------------
Text: a deliciously nonsensical comedy about a city coming apart at its seams .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.94921875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2695818999782205
---------------------------------------------------------------------------
Text: the rare imax movie that you'll wish was longer than an hour .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1474.94921875
Max VRAM Usage: 2364.60888671875
Total Time: 1.2646573999663815
---------------------------------------------------------------------------
Text: my wife's plotting is nothing special ; it's the delivery that matters here .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1474.94921875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2623618999496102
---------------------------------------------------------------------------
Text: i've yet to find an actual vietnam war combat movie actually produced by either the north or south vietnamese , but at least now we've got something pretty damn close .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1474.98046875
Max VRAM Usage: 2367.89990234375
Total Time: 1.2684538000030443
---------------------------------------------------------------------------
Text: a moving and not infrequently breathtaking film .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1474.98046875
Max VRAM Usage: 2363.62158203125
Total Time: 1.3014567999634892
---------------------------------------------------------------------------
Text: it's a sharp movie about otherwise dull subjects .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1474.98828125
Max VRAM Usage: 2363.78564453125
Total Time: 1.3079609000124037
---------------------------------------------------------------------------
Text: [an] absorbing documentary .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1474.9921875
Max VRAM Usage: 2363.12744140625
Total Time: 1.2975853000534698
---------------------------------------------------------------------------
Text: it's like rocky and bullwinkle on speed , but that's neither completely enlightening , nor does it catch the intensity of the movie's strangeness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1474.9921875
Max VRAM Usage: 2367.40576171875
Total Time: 1.271508700097911
---------------------------------------------------------------------------
Text: as action-adventure , this space-based homage to robert louis stevenson's treasure island fires on all plasma conduits .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1474.99609375
Max VRAM Usage: 2366.25439453125
Total Time: 1.2804057999746874
---------------------------------------------------------------------------
Text: a melancholy , emotional film .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1475.00390625
Max VRAM Usage: 2363.29248046875
Total Time: 1.312686000019312
---------------------------------------------------------------------------
Text: while the filmmaking may be a bit disjointed , the subject matter is so fascinating that you won't care .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.0078125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2627127000596374
---------------------------------------------------------------------------
Text: intensely romantic , thought-provoking and even an engaging mystery .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1475.0078125
Max VRAM Usage: 2364.27978515625
Total Time: 1.301454299944453
---------------------------------------------------------------------------
Text: goofy , nutty , consistently funny . and educational !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1475.0234375
Max VRAM Usage: 2363.95068359375
Total Time: 1.2976914999308065
---------------------------------------------------------------------------
Text: not a schlocky creature feature but something far more stylish and cerebral--and , hence , more chillingly effective .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.0234375
Max VRAM Usage: 2366.08935546875
Total Time: 1.2693379999836907
---------------------------------------------------------------------------
Text: another in a long line of ultra-violent war movies , this one is not quite what it could have been as a film , but the story and theme make up for it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.0234375
Max VRAM Usage: 2368.06396484375
Total Time: 1.2740690000355244
---------------------------------------------------------------------------
Text: it leaves little doubt that kidman has become one of our best actors .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.0234375
Max VRAM Usage: 2364.60888671875
Total Time: 1.2620828000362962
---------------------------------------------------------------------------
Text: the film boasts dry humor and jarring shocks , plus moments of breathtaking mystery .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.0234375
Max VRAM Usage: 2364.77294921875
Total Time: 1.265066499938257
---------------------------------------------------------------------------
Text: beautifully directed and convincingly acted .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1475.0234375
Max VRAM Usage: 2363.29248046875
Total Time: 1.3003119999775663
---------------------------------------------------------------------------
Text: gambling and throwing a basketball game for money isn't a new plot -- in fact toback himself used it in black and white . but toback's deranged immediacy makes it seem fresh again .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.05078125
Max VRAM Usage: 2368.72216796875
Total Time: 1.2690072000259534
---------------------------------------------------------------------------
Text: in the director's cut , the film is not only a love song to the movies but it also is more fully an example of the kind of lush , all-enveloping movie experience it rhapsodizes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1475.05078125
Max VRAM Usage: 2369.21630859375
Total Time: 1.265858699916862
---------------------------------------------------------------------------
Text: bring on the sequel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1475.05078125
Max VRAM Usage: 2362.96337890625
Total Time: 1.2977503000292927
---------------------------------------------------------------------------
Text: graced with the kind of social texture and realism that would be foreign in american teen comedies .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.0546875
Max VRAM Usage: 2365.43115234375
Total Time: 1.2715687999734655
---------------------------------------------------------------------------
Text: if we sometimes need comforting fantasies about mental illness , we also need movies like tim mccann's revolution no . 9 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.0625
Max VRAM Usage: 2366.25439453125
Total Time: 1.273173600086011
---------------------------------------------------------------------------
Text: the film occasionally tries the viewer's patience with slow pacing and a main character who sometimes defies sympathy , but it ultimately satisfies with its moving story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.0625
Max VRAM Usage: 2367.07666015625
Total Time: 1.2869298999430612
---------------------------------------------------------------------------
Text: a big-budget/all-star movie as unblinkingly pure as the hours is a distinct rarity , and an event .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.0625
Max VRAM Usage: 2365.92529296875
Total Time: 1.2695205999771133
---------------------------------------------------------------------------
Text: . . . certainly an entertaining ride , despite many talky , slow scenes . but something seems to be missing . a sense of real magic , perhaps .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.0625
Max VRAM Usage: 2367.24169921875
Total Time: 1.2829006999963894
---------------------------------------------------------------------------
Text: that haynes can both maintain and dismantle the facades that his genre and his character construct is a wonderous accomplishment of veracity and narrative grace .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.0625
Max VRAM Usage: 2367.07666015625
Total Time: 1.2754852999933064
---------------------------------------------------------------------------
Text: the movie worked for me right up to the final scene , and then it caved in .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1475.0703125
Max VRAM Usage: 2365.26708984375
Total Time: 1.271172699984163
---------------------------------------------------------------------------
Text: . . . one of the most entertaining monster movies in ages . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.07421875
Max VRAM Usage: 2364.60888671875
Total Time: 1.2683149999938905
---------------------------------------------------------------------------
Text: plunges you into a reality that is , more often then not , difficult and sad , and then , without sentimentalizing it or denying its brutality , transforms that reality into a lyrical and celebratory vision .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1475.07421875
Max VRAM Usage: 2369.05126953125
Total Time: 1.2541570999892429
---------------------------------------------------------------------------
Text: would you laugh if a tuba-playing dwarf rolled down a hill in a trash can ? do you chuckle at the thought of an ancient librarian whacking a certain part of a man's body ? if you answered yes , by all means enjoy the new guy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 181 || Output tokens: 1
Peak memory Usage: 1475.078125
Max VRAM Usage: 2371.16650390625
Total Time: 1.2564141999464482
---------------------------------------------------------------------------
Text: the film is . . . determined to treat its characters , weak and strong , as fallible human beings , not caricatures , and to carefully delineate the cost of the inevitable conflicts between human urges and an institution concerned with self-preservation .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 177 || Output tokens: 1
Peak memory Usage: 1475.078125
Max VRAM Usage: 2370.20361328125
Total Time: 1.2544363000197336
---------------------------------------------------------------------------
Text: missteps take what was otherwise a fascinating , riveting story and send it down the path of the mundane .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.08203125
Max VRAM Usage: 2365.76025390625
Total Time: 1.2574079000623897
---------------------------------------------------------------------------
Text: an indispensable peek at the art and the agony of making people laugh .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.08203125
Max VRAM Usage: 2364.44384765625
Total Time: 1.3027495999122038
---------------------------------------------------------------------------
Text: steadfastly uncinematic but powerfully dramatic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.0859375
Max VRAM Usage: 2363.78564453125
Total Time: 1.3010910999728367
---------------------------------------------------------------------------
Text: the engagingly primitive animated special effects contribute to a mood that's sustained through the surprisingly somber conclusion .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.0859375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2663424999918789
---------------------------------------------------------------------------
Text: made-up lampoons the moviemaking process itself , while shining a not particularly flattering spotlight on america's skin-deep notions of pulchritude .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.0859375
Max VRAM Usage: 2367.24169921875
Total Time: 1.2717069999780506
---------------------------------------------------------------------------
Text: evokes the 19th century with a subtlety that is an object lesson in period filmmaking .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.0859375
Max VRAM Usage: 2365.76025390625
Total Time: 1.2602578999940306
---------------------------------------------------------------------------
Text: ya-yas everywhere will forgive the flaws and love the film .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1475.0859375
Max VRAM Usage: 2364.27978515625
Total Time: 1.295227500027977
---------------------------------------------------------------------------
Text: the film's best trick is the way that it treats conspiracy as a kind of political blair witch , a monstrous murk that haunts us precisely because it can never be seen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.09375
Max VRAM Usage: 2368.22900390625
Total Time: 1.2625112999230623
---------------------------------------------------------------------------
Text: the artwork is spectacular and unlike most animaton from japan , the characters move with grace and panache .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.09375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2622303999960423
---------------------------------------------------------------------------
Text: the picture's fascinating byways are littered with trenchant satirical jabs at the peculiar egocentricities of the acting breed .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.09375
Max VRAM Usage: 2366.74755859375
Total Time: 1.2814655000111088
---------------------------------------------------------------------------
Text: the modern remake of dumas's story is long on narrative and ( too ) short on action .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.09375
Max VRAM Usage: 2365.43115234375
Total Time: 1.2664817000040784
---------------------------------------------------------------------------
Text: fred schepisi's film is paced at a speed that is slow to those of us in middle age and deathly slow to any teen . with a cast of a-list brit actors , it is worth searching out .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1475.09375
Max VRAM Usage: 2369.38037109375
Total Time: 1.2595895999111235
---------------------------------------------------------------------------
Text: suffers from its timid parsing of the barn-side target of sons trying to breach gaps in their relationships with their fathers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.09765625
Max VRAM Usage: 2365.92529296875
Total Time: 1.2633632000070065
---------------------------------------------------------------------------
Text: nonchalantly freaky and uncommonly pleasurable , warm water may well be the year's best and most unpredictable comedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.1015625
Max VRAM Usage: 2366.25439453125
Total Time: 1.2638562999200076
---------------------------------------------------------------------------
Text: it's like an old warner bros . costumer jived with sex -- this could be the movie errol flynn always wanted to make , though bette davis , cast as joan , would have killed him .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 175 || Output tokens: 1
Peak memory Usage: 1475.1015625
Max VRAM Usage: 2369.87451171875
Total Time: 1.2508526999736205
---------------------------------------------------------------------------
Text: it's a great american adventure and a wonderful film to bring to imax .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2614795999834314
---------------------------------------------------------------------------
Text: satisfyingly scarifying , fresh and old-fashioned at the same time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2364.44384765625
Total Time: 1.3171243999386206
---------------------------------------------------------------------------
Text: oh , james ! your 20th outing shows off a lot of stamina and vitality , and get this , madonna's cameo doesn't suck !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2367.07666015625
Total Time: 1.26107529993169
---------------------------------------------------------------------------
Text: a genuine mind-bender .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2363.12744140625
Total Time: 1.3033091999823228
---------------------------------------------------------------------------
Text: that death is merely a transition is a common tenet in the world's religions . this deeply spiritual film taps into the meaning and consolation in afterlife communications .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1475.1171875
Max VRAM Usage: 2367.40576171875
Total Time: 1.2610738000366837
---------------------------------------------------------------------------
Text: there is something that is so meditative and lyrical about babak payami's boldly quirky iranian drama secret ballot . . . a charming and evoking little ditty that manages to show the gentle and humane side of middle eastern world politics

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 177 || Output tokens: 1
Peak memory Usage: 1475.1171875
Max VRAM Usage: 2370.20361328125
Total Time: 1.2574297999963164
---------------------------------------------------------------------------
Text: a huge box-office hit in korea , shiri is a must for genre fans .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.1171875
Max VRAM Usage: 2365.10205078125
Total Time: 1.2678880000021309
---------------------------------------------------------------------------
Text: . . . planos fijos , tomas largas , un ritmo pausado y una sutil observación de sus personajes , sin estridencias ni grandes revelaciones .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.1171875
Max VRAM Usage: 2368.72216796875
Total Time: 1.251550400047563
---------------------------------------------------------------------------
Text: i'm not a fan of the phrase 'life affirming' because it usually means 'schmaltzy , ' but real women have curves truly is life affirming .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.1171875
Max VRAM Usage: 2367.89990234375
Total Time: 1.2893696000101045
---------------------------------------------------------------------------
Text: the symbols float like butterflies and the spinning styx sting like bees . i wanted more .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.1171875
Max VRAM Usage: 2365.10205078125
Total Time: 1.2759300000034273
---------------------------------------------------------------------------
Text: if it's unnerving suspense you're after -- you'll find it with ring , an indisputably spooky film ; with a screenplay to die for .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2367.24169921875
Total Time: 1.2639241999713704
---------------------------------------------------------------------------
Text: the art direction and costumes are gorgeous and finely detailed , and kurys' direction is clever and insightful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2365.59619140625
Total Time: 1.2542928999755532
---------------------------------------------------------------------------
Text: red dragon makes one appreciate silence of the lambs .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1475.10546875
Max VRAM Usage: 2363.95068359375
Total Time: 1.3023382999235764
---------------------------------------------------------------------------
Text: proves a servicable world war ii drama that can't totally hide its contrivances , but it at least calls attention to a problem hollywood too long has ignored .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.109375
Max VRAM Usage: 2367.73486328125
Total Time: 1.263968399958685
---------------------------------------------------------------------------
Text: leigh isn't breaking new ground , but he knows how a daily grind can kill love .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1475.109375
Max VRAM Usage: 2365.26708984375
Total Time: 1.267662200029008
---------------------------------------------------------------------------
Text: while broomfield's film doesn't capture the effect of these tragic deaths on hip-hop culture , it succeeds as a powerful look at a failure of our justice system .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.109375
Max VRAM Usage: 2367.73486328125
Total Time: 1.259891299996525
---------------------------------------------------------------------------
Text: . . . strips bible stores of the potential for sanctimoniousness , making them meaningful for both kids and church-wary adults .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.12109375
Max VRAM Usage: 2366.58349609375
Total Time: 1.2684829999925569
---------------------------------------------------------------------------
Text: laugh-out-loud lines , adorably ditsy but heartfelt performances , and sparkling , bittersweet dialogue that cuts to the chase of the modern girl's dilemma .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.1328125
Max VRAM Usage: 2367.89990234375
Total Time: 1.267535399994813
---------------------------------------------------------------------------
Text: tends to pile too many " serious issues " on its plate at times , yet remains fairly light , always entertaining , and smartly written .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.13671875
Max VRAM Usage: 2366.74755859375
Total Time: 1.2660298000555485
---------------------------------------------------------------------------
Text: a solidly entertaining little film .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1475.13671875
Max VRAM Usage: 2363.29248046875
Total Time: 1.302822700003162
---------------------------------------------------------------------------
Text: it's an entertaining movie , and the effects , boosted to the size of a downtown hotel , will all but take you to outer space .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.13671875
Max VRAM Usage: 2366.74755859375
Total Time: 1.2689877999946475
---------------------------------------------------------------------------
Text: sayles has a knack for casting , often resurrecting performers who rarely work in movies now . . . and drawing flavorful performances from bland actors .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.140625
Max VRAM Usage: 2366.91259765625
Total Time: 1.2606665999628603
---------------------------------------------------------------------------
Text: despite an overwrought ending , the film works as well as it does because of the performances .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.140625
Max VRAM Usage: 2365.43115234375
Total Time: 1.2615740000037476
---------------------------------------------------------------------------
Text: a passionately inquisitive film determined to uncover the truth and hopefully inspire action .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.14453125
Max VRAM Usage: 2364.77294921875
Total Time: 1.2791855999967083
---------------------------------------------------------------------------
Text: though nijinsky's words grow increasingly disturbed , the film maintains a beguiling serenity and poise that make it accessible for a non-narrative feature .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.14453125
Max VRAM Usage: 2367.73486328125
Total Time: 1.2615013000322506
---------------------------------------------------------------------------
Text: a muddle splashed with bloody beauty as vivid as any scorsese has ever given us .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.1484375
Max VRAM Usage: 2365.43115234375
Total Time: 1.2635045000351965
---------------------------------------------------------------------------
Text: from both a great and a terrible story , mr . nelson has made a film that is an undeniably worthy and devastating experience .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.15234375
Max VRAM Usage: 2366.74755859375
Total Time: 1.2617380000883713
---------------------------------------------------------------------------
Text: spider-man is about growing strange hairs , getting a more mature body , and finding it necessary to hide new secretions from the parental units .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.16015625
Max VRAM Usage: 2366.74755859375
Total Time: 1.2680145999183878
---------------------------------------------------------------------------
Text: the first shocking thing about sorority boys is that it's actually watchable . even more baffling is that it's funny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.16015625
Max VRAM Usage: 2366.58349609375
Total Time: 1.2672716000815853
---------------------------------------------------------------------------
Text: highlighted by a gritty style and an excellent cast , it's better than one might expect when you look at the list of movies starring ice-t in a major role .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.1640625
Max VRAM Usage: 2367.57080078125
Total Time: 1.2644098999444395
---------------------------------------------------------------------------
Text: neither quite a comedy nor a romance , more of an impish divertissement of themes that interest attal and gainsbourg -- they live together -- the film has a lot of charm .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.1640625
Max VRAM Usage: 2368.22900390625
Total Time: 1.2462793999584392
---------------------------------------------------------------------------
Text: first and foremost . . . the reason to go see " blue crush " is the phenomenal , water-born cinematography by david hennings .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.171875
Max VRAM Usage: 2366.91259765625
Total Time: 1.2621747000375763
---------------------------------------------------------------------------
Text: a visionary marvel , but it's lacking a depth in storytelling usually found in anime like this .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1475.171875
Max VRAM Usage: 2365.26708984375
Total Time: 1.2674433999927714
---------------------------------------------------------------------------
Text: the problems and characters it reveals are universal and involving , and the film itself -- as well its delightful cast -- is so breezy , pretty and gifted , it really won my heart .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.203125
Max VRAM Usage: 2368.22900390625
Total Time: 1.255224799970165
---------------------------------------------------------------------------
Text: in his latest effort , storytelling , solondz has finally made a movie that isn't just offensive -- it also happens to be good .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.203125
Max VRAM Usage: 2366.74755859375
Total Time: 1.2625783000839874
---------------------------------------------------------------------------
Text: how i killed my father would be a rarity in hollywood . it's an actor's showcase that accomplishes its primary goal without the use of special effects , but rather by emphasizing the characters -- including the supporting ones .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1475.2109375
Max VRAM Usage: 2369.38037109375
Total Time: 1.259565099957399
---------------------------------------------------------------------------
Text: i just saw this movie . . . well , it's probably not accurate to call it a movie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.2109375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2528562999796122
---------------------------------------------------------------------------
Text: what's most memorable about circuit is that it's shot on digital video , whose tiny camera enables shafer to navigate spaces both large . . . and small . . . with considerable aplomb .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.2109375
Max VRAM Usage: 2368.55810546875
Total Time: 1.2495538999792188
---------------------------------------------------------------------------
Text: scherfig , the writer-director , has made a film so unabashedly hopeful that it actually makes the heart soar . yes , soar .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.21875
Max VRAM Usage: 2367.07666015625
Total Time: 1.2742318999953568
---------------------------------------------------------------------------
Text: a delicious and delicately funny look at the residents of a copenhagen neighborhood coping with the befuddling complications life tosses at them .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.23046875
Max VRAM Usage: 2366.74755859375
Total Time: 1.2774291998939589
---------------------------------------------------------------------------
Text: " what really happened ? " is a question for philosophers , not filmmakers ; all the filmmakers need to do is engage an audience .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.234375
Max VRAM Usage: 2366.41845703125
Total Time: 1.262340100016445
---------------------------------------------------------------------------
Text: soderbergh , like kubrick before him , may not touch the planet's skin , but understands the workings of its spirit .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.234375
Max VRAM Usage: 2366.74755859375
Total Time: 1.278821500018239
---------------------------------------------------------------------------
Text: much credit must be given to the water-camera operating team of don king , sonny miller , and michael stewart . their work is fantastic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.234375
Max VRAM Usage: 2367.07666015625
Total Time: 1.2735208000522107
---------------------------------------------------------------------------
Text: crush is so warm and fuzzy you might be able to forgive its mean-spirited second half .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.234375
Max VRAM Usage: 2365.43115234375
Total Time: 1.2734573999186978
---------------------------------------------------------------------------
Text: franco is an excellent choice for the walled-off but combustible hustler , but he does not give the transcendent performance sonny needs to overcome gaps in character development and story logic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.23828125
Max VRAM Usage: 2368.55810546875
Total Time: 1.2578365000663325
---------------------------------------------------------------------------
Text: tsai ming-liang's witty , wistful new film , what time is it there ? , is a temporal inquiry that shoulders its philosophical burden lightly .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1475.23828125
Max VRAM Usage: 2367.40576171875
Total Time: 1.2628283000085503
---------------------------------------------------------------------------
Text: the pianist lacks the quick emotional connections of steven spielberg's schindler's list . but mr . polanski creates images even more haunting than those in mr . spielberg's 1993 classic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1475.25
Max VRAM Usage: 2369.38037109375
Total Time: 1.2613382999552414
---------------------------------------------------------------------------
Text: steers , in his feature film debut , has created a brilliant motion picture .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2632366999750957
---------------------------------------------------------------------------
Text: a brilliant , absurd collection of vignettes that , in their own idiosyncratic way , sum up the strange horror of life in the new millennium .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2367.40576171875
Total Time: 1.2584925999399275
---------------------------------------------------------------------------
Text: as warm as it is wise , deftly setting off uproarious humor with an underlying seriousness that sneaks up on the viewer , providing an experience that is richer than anticipated .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2368.06396484375
Total Time: 1.2704461000394076
---------------------------------------------------------------------------
Text: the film may not hit as hard as some of the better drug-related pictures , but it still manages to get a few punches in .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2366.58349609375
Total Time: 1.2823721000459045
---------------------------------------------------------------------------
Text: old-fashioned but thoroughly satisfying entertainment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2363.29248046875
Total Time: 1.3084313999861479
---------------------------------------------------------------------------
Text: an energizing , intoxicating documentary charting the rise of hip-hop culture in general and the art of scratching ( or turntablism ) in particular .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2367.24169921875
Total Time: 1.2671567000215873
---------------------------------------------------------------------------
Text: a fun family movie that's suitable for all ages -- a movie that will make you laugh , cry and realize , 'it's never too late to believe in your dreams . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2368.06396484375
Total Time: 1.287105800001882
---------------------------------------------------------------------------
Text: if you open yourself up to mr . reggio's theory of this imagery as the movie's set . . . it can impart an almost visceral sense of dislocation and change .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2368.06396484375
Total Time: 1.2638240000233054
---------------------------------------------------------------------------
Text: i had a dream that a smart comedy would come along to rescue me from a summer of teen-driven , toilet-humor codswallop , and its name was earnest .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2367.89990234375
Total Time: 1.292913099983707
---------------------------------------------------------------------------
Text: even though the film doesn't manage to hit all of its marks , it's still entertaining to watch the target practice .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2366.08935546875
Total Time: 1.3118928000330925
---------------------------------------------------------------------------
Text: where this was lazy but enjoyable , a formula comedy redeemed by its stars , that is even lazier and far less enjoyable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2366.25439453125
Total Time: 1.2683991000521928
---------------------------------------------------------------------------
Text: the 3-d vistas from orbit , with the space station suspended like a huge set of wind chimes over the great blue globe , are stanzas of breathtaking , awe-inspiring visual poetry .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2368.72216796875
Total Time: 1.2587745999917388
---------------------------------------------------------------------------
Text: the attraction between these two marginal characters is complex from the start -- and , refreshingly , stays that way .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2365.76025390625
Total Time: 1.3234434999758378
---------------------------------------------------------------------------
Text: fans of the modern day hong kong action film finally have the worthy successor to a better tomorrow and the killer which they have been patiently waiting for .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.26171875
Max VRAM Usage: 2367.24169921875
Total Time: 1.4669673000462353
---------------------------------------------------------------------------
Text: even when he's not at his most critically insightful , godard can still be smarter than any 50 other filmmakers still at work .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.26953125
Max VRAM Usage: 2366.58349609375
Total Time: 1.3381767999380827
---------------------------------------------------------------------------
Text: what sets this romantic comedy apart from most hollywood romantic comedies is its low-key way of tackling what seems like done-to-death material .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.28515625
Max VRAM Usage: 2366.74755859375
Total Time: 1.3307307000504807
---------------------------------------------------------------------------
Text: has enough wit , energy and geniality to please not only the fanatical adherents on either side , but also people who know nothing about the subject and think they're not interested .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1475.28515625
Max VRAM Usage: 2368.39306640625
Total Time: 1.3298365999944508
---------------------------------------------------------------------------
Text: this seductive tease of a thriller gets the job done . it's a scorcher .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.28515625
Max VRAM Usage: 2365.10205078125
Total Time: 1.4051081999205053
---------------------------------------------------------------------------
Text: bittersweet comedy/drama full of life , hand gestures , and some really adorable italian guys .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.28515625
Max VRAM Usage: 2365.43115234375
Total Time: 1.413708099978976
---------------------------------------------------------------------------
Text: works as pretty contagious fun .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1475.28515625
Max VRAM Usage: 2363.12744140625
Total Time: 0.7350310999900103
---------------------------------------------------------------------------
Text: the best didacticism is one carried by a strong sense of humanism , and bertrand tavernier's oft-brilliant safe conduct ( " laissez-passer " ) wears its heart on its sleeve .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1475.30078125
Max VRAM Usage: 2369.21630859375
Total Time: 1.3417647000169381
---------------------------------------------------------------------------
Text: a realistically terrifying movie that puts another notch in the belt of the long list of renegade-cop tales .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.30078125
Max VRAM Usage: 2365.76025390625
Total Time: 1.1412947000935674
---------------------------------------------------------------------------
Text: a charming , banter-filled comedy . . . one of those airy cinematic bon bons whose aims -- and by extension , accomplishments -- seem deceptively slight on the surface .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.31640625
Max VRAM Usage: 2367.89990234375
Total Time: 1.1223471000557765
---------------------------------------------------------------------------
Text: a film with almost as many delights for adults as there are for children and dog lovers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.31640625
Max VRAM Usage: 2365.10205078125
Total Time: 1.1034815999446437
---------------------------------------------------------------------------
Text: serious movie-goers embarking upon this journey will find that the road to perdition leads to a satisfying destination .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.31640625
Max VRAM Usage: 2365.92529296875
Total Time: 1.1178970000473782
---------------------------------------------------------------------------
Text: heartwarming and gently comic even as the film breaks your heart .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.31640625
Max VRAM Usage: 2364.44384765625
Total Time: 1.1153749000513926
---------------------------------------------------------------------------
Text: caruso sometimes descends into sub-tarantino cuteness . . . but for the most part he makes sure the salton sea works the way a good noir should , keeping it tight and nasty .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1475.31640625
Max VRAM Usage: 2368.88720703125
Total Time: 1.1162672999780625
---------------------------------------------------------------------------
Text: a " black austin powers ? " i prefer to think of it as " pootie tang with a budget . " sa da tay !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2366.91259765625
Total Time: 1.1052755999844521
---------------------------------------------------------------------------
Text: oddly , the film isn't nearly as downbeat as it sounds , but strikes a tone that's alternately melancholic , hopeful and strangely funny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2367.07666015625
Total Time: 1.1029912000522017
---------------------------------------------------------------------------
Text: i would be shocked if there was actually one correct interpretation , but that shouldn't make the movie or the discussion any less enjoyable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2366.41845703125
Total Time: 1.103928199969232
---------------------------------------------------------------------------
Text: chouraqui brings documentary-like credibility to the horrors of the killing field and the barbarism of 'ethnic cleansing . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2366.25439453125
Total Time: 1.1074208999052644
---------------------------------------------------------------------------
Text: the best thing i can say about this film is that i can't wait to see what the director does next .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2365.92529296875
Total Time: 1.1209387000417337
---------------------------------------------------------------------------
Text: smarter than its commercials make it seem .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2363.45654296875
Total Time: 1.111619499977678
---------------------------------------------------------------------------
Text: great character interaction .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 132 || Output tokens: 1
Peak memory Usage: 1475.3203125
Max VRAM Usage: 2362.79833984375
Total Time: 1.1007815999910235
---------------------------------------------------------------------------
Text: one of the funnier movies in town .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.328125
Max VRAM Usage: 2363.62158203125
Total Time: 1.1019157000118867
---------------------------------------------------------------------------
Text: campanella's competent direction and his excellent cast overcome the obstacles of a predictable outcome and a screenplay that glosses over rafael's evolution .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.33203125
Max VRAM Usage: 2367.07666015625
Total Time: 1.0908915000036359
---------------------------------------------------------------------------
Text: by turns very dark and very funny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.33203125
Max VRAM Usage: 2363.45654296875
Total Time: 1.0958018000237644
---------------------------------------------------------------------------
Text: steven soderbergh doesn't remake andrei tarkovsky's solaris so much as distill it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.33203125
Max VRAM Usage: 2366.08935546875
Total Time: 1.0811370000010356
---------------------------------------------------------------------------
Text: for more than two decades mr . nachtwey has traveled to places in the world devastated by war , famine and poverty and documented the cruelty and suffering he has found with an devastating , eloquent clarity .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1475.33984375
Max VRAM Usage: 2369.05126953125
Total Time: 1.1067480000201613
---------------------------------------------------------------------------
Text: simultaneously heartbreakingly beautiful and exquisitely sad .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1475.33984375
Max VRAM Usage: 2364.11474609375
Total Time: 1.172900699893944
---------------------------------------------------------------------------
Text: though overall an overwhelmingly positive portrayal , the film doesn't ignore the more problematic aspects of brown's life .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.33984375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2068650999572128
---------------------------------------------------------------------------
Text: the philosophical musings of the dialogue jar against the tawdry soap opera antics of the film's action in a way that is surprisingly enjoyable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.33984375
Max VRAM Usage: 2366.91259765625
Total Time: 1.2219908999977633
---------------------------------------------------------------------------
Text: not too fancy , not too filling , not too fluffy , but definitely tasty and sweet .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.36328125
Max VRAM Usage: 2365.10205078125
Total Time: 1.1521071000024676
---------------------------------------------------------------------------
Text: quando tiros em columbine acerta o alvo ( com o perdão do trocadilho ) , não há como negar o brilhantismo da argumentação de seu diretor .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1475.3828125
Max VRAM Usage: 2369.05126953125
Total Time: 1.13158739998471
---------------------------------------------------------------------------
Text: director lee has a true cinematic knack , but it's also nice to see a movie with its heart so thoroughly , unabashedly on its sleeve .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.3984375
Max VRAM Usage: 2367.07666015625
Total Time: 1.1045384000753984
---------------------------------------------------------------------------
Text: as allen's execution date closes in , the documentary gives an especially poignant portrait of her friendship with the never flagging legal investigator david presson .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.40234375
Max VRAM Usage: 2366.91259765625
Total Time: 1.101712900097482
---------------------------------------------------------------------------
Text: jones has tackled a meaty subject and drawn engaging characters while peppering the pages with memorable zingers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.40234375
Max VRAM Usage: 2365.76025390625
Total Time: 1.1143303000135347
---------------------------------------------------------------------------
Text: a vivid , spicy footnote to history , and a movie that grips and holds you in rapt attention from start to finish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.40234375
Max VRAM Usage: 2366.25439453125
Total Time: 1.115487299975939
---------------------------------------------------------------------------
Text: if s&m seems like a strange route to true love , maybe it is , but it's to this film's ( and its makers' ) credit that we believe that that's exactly what these two people need to find each other -- and themselves .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 178 || Output tokens: 1
Peak memory Usage: 1475.4140625
Max VRAM Usage: 2370.36767578125
Total Time: 1.1277199999894947
---------------------------------------------------------------------------
Text: if the film's vision of sport as a secular religion is a bit cloying , its through-line of family and community is heartening in the same way that each season marks a new start .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.41796875
Max VRAM Usage: 2368.72216796875
Total Time: 1.0873188999248669
---------------------------------------------------------------------------
Text: one of the best of a growing strain of daring films . . . that argue that any sexual relationship that doesn't hurt anyone and works for its participants is a relationship that is worthy of our respect .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.42578125
Max VRAM Usage: 2368.72216796875
Total Time: 1.1130416999803856
---------------------------------------------------------------------------
Text: an adorably whimsical comedy that deserves more than a passing twinkle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.42578125
Max VRAM Usage: 2364.77294921875
Total Time: 1.0970900000538677
---------------------------------------------------------------------------
Text: an engrossing story that combines psychological drama , sociological reflection , and high-octane thriller .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.4296875
Max VRAM Usage: 2365.59619140625
Total Time: 1.0847237000707537
---------------------------------------------------------------------------
Text: it's easy to be cynical about documentaries in which underdogs beat the odds and the human spirit triumphs , but westbrook's foundation and dalrymple's film earn their uplift .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1475.4375
Max VRAM Usage: 2368.39306640625
Total Time: 1.078353099990636
---------------------------------------------------------------------------
Text: mel gibson fights the good fight in vietnam in director randall wallace's flag-waving war flick with a core of decency .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.44921875
Max VRAM Usage: 2366.74755859375
Total Time: 1.1153001999482512
---------------------------------------------------------------------------
Text: there's real visual charge to the filmmaking , and a strong erotic spark to the most crucial lip-reading sequence .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.44921875
Max VRAM Usage: 2366.08935546875
Total Time: 1.0896669999929145
---------------------------------------------------------------------------
Text: a brutal and funny work . nicole holofcenter , the insightful writer/director responsible for this illuminating comedy doesn't wrap the proceedings up neatly but the ideas tie together beautifully .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.44921875
Max VRAM Usage: 2368.22900390625
Total Time: 1.134978900081478
---------------------------------------------------------------------------
Text: the film is a blunt indictment , part of a perhaps surreal campaign to bring kissinger to trial for crimes against humanity .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.44921875
Max VRAM Usage: 2366.08935546875
Total Time: 1.145888000028208
---------------------------------------------------------------------------
Text: one of the most important and exhilarating forms of animated filmmaking since old walt doodled steamboat willie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.453125
Max VRAM Usage: 2366.08935546875
Total Time: 1.309049400035292
---------------------------------------------------------------------------
Text: move over bond ; this girl deserves a sequel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.453125
Max VRAM Usage: 2363.78564453125
Total Time: 0.6971100999508053
---------------------------------------------------------------------------
Text: the kind of trifle that date nights were invented for .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1475.453125
Max VRAM Usage: 2364.11474609375
Total Time: 1.4674826000118628
---------------------------------------------------------------------------
Text: . it's a testament to the film's considerable charm that it succeeds in entertaining , despite playing out like a feature-length sitcom replete with stereotypical familial quandaries . there's a sheer unbridled delight in the way the story unfurls . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 180 || Output tokens: 1
Peak memory Usage: 1475.45703125
Max VRAM Usage: 2371.04052734375
Total Time: 1.324740800075233
---------------------------------------------------------------------------
Text: tells ( the story ) with such atmospheric ballast that shrugging off the plot's persnickety problems is simply a matter of ( being ) in a shrugging mood .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.45703125
Max VRAM Usage: 2367.89990234375
Total Time: 1.201070399954915
---------------------------------------------------------------------------
Text: the film is hard to dismiss -- moody , thoughtful , and lit by flashes of mordant humor .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1536898000631481
---------------------------------------------------------------------------
Text: if the man from elysian fields is doomed by its smallness , it is also elevated by it--the kind of movie that you enjoy more because you're one of the lucky few who sought it out .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2369.21630859375
Total Time: 1.1716414000838995
---------------------------------------------------------------------------
Text: what emerges is an unsettling picture of childhood innocence combined with indoctrinated prejudice . promises is a compelling piece that demonstrates just how well children can be trained to live out and carry on their parents' anguish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2368.88720703125
Total Time: 1.2413777000037953
---------------------------------------------------------------------------
Text: meticulously uncovers a trail of outrageous force and craven concealment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2364.44384765625
Total Time: 1.2047487000236288
---------------------------------------------------------------------------
Text: hey , happy ! is many things -- stoner midnight flick , sci-fi deconstruction , gay fantasia -- but above all it's a love story as sanguine as its title .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2368.39306640625
Total Time: 1.1687260000035167
---------------------------------------------------------------------------
Text: you won't look at religious fanatics -- or backyard sheds -- the same way again .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2365.10205078125
Total Time: 1.1597865000367165
---------------------------------------------------------------------------
Text: at its best . . . festival in cannes bubbles with the excitement of the festival in cannes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2365.59619140625
Total Time: 1.1227136000525206
---------------------------------------------------------------------------
Text: there is a general air of exuberance in all about the benjamins that's hard to resist .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1421348999720067
---------------------------------------------------------------------------
Text: a lovably old-school hollywood confection .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2363.78564453125
Total Time: 1.1671711000381038
---------------------------------------------------------------------------
Text: i'm happy to have seen it -- not as an alternate version , but as the ultimate exercise in viewing deleted scenes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2366.08935546875
Total Time: 1.154425699962303
---------------------------------------------------------------------------
Text: by turns gripping , amusing , tender and heart-wrenching , laissez-passer has all the earmarks of french cinema at its best .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2366.91259765625
Total Time: 1.1256158000323921
---------------------------------------------------------------------------
Text: the warnings to resist temptation in this film . . . are blunt and challenging and offer no easy rewards for staying clean .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2366.08935546875
Total Time: 1.1437366999452934
---------------------------------------------------------------------------
Text: wonder of wonders -- a teen movie with a humanistic message .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2364.27978515625
Total Time: 1.112359800026752
---------------------------------------------------------------------------
Text: a quirky comedy set in newfoundland that cleverly captures the dry wit that's so prevalent on the rock .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2365.76025390625
Total Time: 1.0928800000110641
---------------------------------------------------------------------------
Text: peppered with witty dialogue and inventive moments .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2363.62158203125
Total Time: 1.1326706999680027
---------------------------------------------------------------------------
Text: i'd rather watch a rerun of the powerpuff girls

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2364.27978515625
Total Time: 1.1401296999538317
---------------------------------------------------------------------------
Text: with the prospect of films like kangaroo jack about to burst across america's winter movie screens it's a pleasure to have a film like the hours as an alternative .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2367.57080078125
Total Time: 1.1177002000622451
---------------------------------------------------------------------------
Text: the wonderful combination of the sweetness and the extraordinary technical accomplishments of the first film are maintained , but its overall impact falls a little flat with a storyline that never quite delivers the original magic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2368.22900390625
Total Time: 1.1204873999813572
---------------------------------------------------------------------------
Text: like its title character , this nicholas nickleby finds itself in reduced circumstances -- and , also like its hero , it remains brightly optimistic , coming through in the end .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2367.89990234375
Total Time: 1.1511602000100538
---------------------------------------------------------------------------
Text: as a thoughtful and unflinching examination of an alternative lifestyle , sex with strangers is a success .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2365.59619140625
Total Time: 1.111592400004156
---------------------------------------------------------------------------
Text: unpretentious , charming , quirky , original

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2363.62158203125
Total Time: 1.1587950000539422
---------------------------------------------------------------------------
Text: spinning a web of dazzling entertainment may be overstating it , but " spider-man " certainly delivers the goods .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.46875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1560557999182492
---------------------------------------------------------------------------
Text: other than the slightly flawed ( and fairly unbelievable ) finale , everything else is top shelf .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2365.10205078125
Total Time: 1.1628030999563634
---------------------------------------------------------------------------
Text: this fascinating look at israel in ferment feels as immediate as the latest news footage from gaza and , because of its heightened , well-shaped dramas , twice as powerful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.48046875
Max VRAM Usage: 2367.73486328125
Total Time: 1.0927596000256017
---------------------------------------------------------------------------
Text: manages to delight without much of a story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2363.62158203125
Total Time: 1.1530984999844804
---------------------------------------------------------------------------
Text: there's no denying that burns is a filmmaker with a bright future ahead of him .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2364.93798828125
Total Time: 1.106675099930726
---------------------------------------------------------------------------
Text: i have a confession to make : i didn't particularly like e . t . the first time i saw it as a young boy . that is because - damn it ! - i also wanted a little alien as a friend !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2369.54541015625
Total Time: 1.1303979998920113
---------------------------------------------------------------------------
Text: fairy-tale formula , serves as a paper skeleton for some very good acting , dialogue , comedy , direction and especially charm .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2366.25439453125
Total Time: 1.10394429997541
---------------------------------------------------------------------------
Text: a genuinely funny ensemble comedy that also asks its audience -- in a heartwarming , nonjudgmental kind of way -- to consider what we value in our daily lives .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2367.89990234375
Total Time: 1.0858266000868753
---------------------------------------------------------------------------
Text: though the aboriginal aspect lends the ending an extraordinary poignancy , and the story itself could be played out in any working class community in the nation .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2367.24169921875
Total Time: 1.15084899996873
---------------------------------------------------------------------------
Text: an energetic and engaging film that never pretends to be something it isn't .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2364.77294921875
Total Time: 1.1144040999934077
---------------------------------------------------------------------------
Text: a violent initiation rite for the audience , as much as it is for angelique , the [opening] dance guarantees karmen's enthronement among the cinema's memorable women .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2368.39306640625
Total Time: 1.1383591999765486
---------------------------------------------------------------------------
Text: an animation landmark as monumental as disney's 1937 breakthrough snow white and the seven dwarfs .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2365.59619140625
Total Time: 1.1362459999509156
---------------------------------------------------------------------------
Text: an entertaining , if ultimately minor , thriller .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2363.62158203125
Total Time: 1.1156492999289185
---------------------------------------------------------------------------
Text: sex with strangers is fascinating . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none
Response: none
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2363.45654296875
Total Time: 1.1316853000316769
---------------------------------------------------------------------------
Text: a subtle , poignant picture of goodness that is flawed , compromised and sad .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2364.60888671875
Total Time: 1.1228304000105709
---------------------------------------------------------------------------
Text: a wry , affectionate delight .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2363.45654296875
Total Time: 1.1083594999508932
---------------------------------------------------------------------------
Text: the acting in pauline and paulette is good all round , but what really sets the film apart is debrauwer's refusal to push the easy emotional buttons .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2367.89990234375
Total Time: 1.142611199989915
---------------------------------------------------------------------------
Text: one of those joyous films that leaps over national boundaries and celebrates universal human nature .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2364.93798828125
Total Time: 1.1446093999547884
---------------------------------------------------------------------------
Text: a penetrating glimpse into the tissue-thin ego of the stand-up comic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.5
Max VRAM Usage: 2364.60888671875
Total Time: 1.0849238999653608
---------------------------------------------------------------------------
Text: kids should have a stirring time at this beautifully drawn movie . and adults will at least have a dream image of the west to savor whenever the film's lamer instincts are in the saddle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.51171875
Max VRAM Usage: 2368.55810546875
Total Time: 1.1557243999559432
---------------------------------------------------------------------------
Text: paid in full is remarkably engaging despite being noticeably derivative of goodfellas and at least a half dozen other trouble-in-the-ghetto flicks .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.51171875
Max VRAM Usage: 2367.07666015625
Total Time: 1.1112671999726444
---------------------------------------------------------------------------
Text: less cinematically powerful than quietly and deeply moving , which is powerful in itself .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.51171875
Max VRAM Usage: 2364.93798828125
Total Time: 1.101040399982594
---------------------------------------------------------------------------
Text: waydowntown manages to nail the spirit-crushing ennui of denuded urban living without giving in to it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.51171875
Max VRAM Usage: 2365.92529296875
Total Time: 1.1076720000710338
---------------------------------------------------------------------------
Text: each of these stories has the potential for touched by an angel simplicity and sappiness , but thirteen conversations about one thing , for all its generosity and optimism , never resorts to easy feel-good sentiments .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.51171875
Max VRAM Usage: 2368.55810546875
Total Time: 1.1336450000526384
---------------------------------------------------------------------------
Text: if borstal boy isn't especially realistic , it is an engaging nostalgia piece .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.51171875
Max VRAM Usage: 2364.77294921875
Total Time: 1.1770196000579745
---------------------------------------------------------------------------
Text: often demented in a good way , but it is an uneven film for the most part .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.52734375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1150463999947533
---------------------------------------------------------------------------
Text: the script's snazzy dialogue establishes a realistic atmosphere that involves us in the unfolding crisis , but the lazy plotting ensures that little of our emotional investment pays off .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.53125
Max VRAM Usage: 2367.57080078125
Total Time: 1.1354375999653712
---------------------------------------------------------------------------
Text: maggie smith as the ya-ya member with the o2-tank will absolutely crack you up with her crass , then gasp for gas , verbal deportment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.53125
Max VRAM Usage: 2367.73486328125
Total Time: 1.161611899966374
---------------------------------------------------------------------------
Text: this is a movie that refreshes the mind and spirit along with the body , so original is its content , look , and style .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.53125
Max VRAM Usage: 2366.58349609375
Total Time: 1.2094225999899209
---------------------------------------------------------------------------
Text: although i didn't hate this one , it's not very good either . it can be safely recommended as a video/dvd babysitter .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.53125
Max VRAM Usage: 2366.74755859375
Total Time: 1.2226307999808341
---------------------------------------------------------------------------
Text: another best of the year selection .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1475.53125
Max VRAM Usage: 2363.29248046875
Total Time: 1.2309824000112712
---------------------------------------------------------------------------
Text: the film has the high-buffed gloss and high-octane jolts you expect of de palma , but what makes it transporting is that it's also one of the smartest , most pleasurable expressions of pure movie love to come from an american director in years .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 184 || Output tokens: 1
Peak memory Usage: 1475.56640625
Max VRAM Usage: 2371.54248046875
Total Time: 1.1155201999936253
---------------------------------------------------------------------------
Text: it's a very valuable film . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.56640625
Max VRAM Usage: 2363.62158203125
Total Time: 1.147087899968028
---------------------------------------------------------------------------
Text: max pokes , provokes , takes expressionistic license and hits a nerve . . . as far as art is concerned , it's mission accomplished .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.56640625
Max VRAM Usage: 2367.07666015625
Total Time: 1.1215005000121891
---------------------------------------------------------------------------
Text: literary purists may not be pleased , but as far as mainstream matinee-style entertainment goes , it does a bang-up job of pleasing the crowds .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.5703125
Max VRAM Usage: 2367.07666015625
Total Time: 1.118726299959235
---------------------------------------------------------------------------
Text: here polanski looks back on those places he saw at childhood , and captures them by freeing them from artefact , and by showing them heartbreakingly drably .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.5703125
Max VRAM Usage: 2367.73486328125
Total Time: 1.140871699899435
---------------------------------------------------------------------------
Text: intriguing and stylish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 132 || Output tokens: 1
Peak memory Usage: 1475.5703125
Max VRAM Usage: 2362.79833984375
Total Time: 1.118130899965763
---------------------------------------------------------------------------
Text: the story itself it mostly told through on-camera interviews with several survivors , whose riveting memories are rendered with such clarity that it's as if it all happened only yesterday .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.578125
Max VRAM Usage: 2367.73486328125
Total Time: 1.1201697000069544
---------------------------------------------------------------------------
Text: a compelling story of musical passion against governmental odds .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.578125
Max VRAM Usage: 2363.78564453125
Total Time: 1.1463649000506848
---------------------------------------------------------------------------
Text: with " ichi the killer " , takashi miike , japan's wildest filmmaker gives us a crime fighter carrying more emotional baggage than batman . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.578125
Max VRAM Usage: 2367.57080078125
Total Time: 1.1290063000051305
---------------------------------------------------------------------------
Text: you never know where changing lanes is going to take you but it's a heck of a ride . samuel l . jackson is one of the best actors there is .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.578125
Max VRAM Usage: 2367.89990234375
Total Time: 1.112883499939926
---------------------------------------------------------------------------
Text: [breheny's] lensing of the new zealand and cook island locations captures both the beauty of the land and the people .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.578125
Max VRAM Usage: 2366.74755859375
Total Time: 1.1116930999560282
---------------------------------------------------------------------------
Text: an almost unbearably morbid love story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.578125
Max VRAM Usage: 2363.78564453125
Total Time: 1.1566596999764442
---------------------------------------------------------------------------
Text: the wild thornberrys movie has all the sibling rivalry and general family chaos to which anyone can relate .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.6015625
Max VRAM Usage: 2365.92529296875
Total Time: 1.0964945000596344
---------------------------------------------------------------------------
Text: a forceful drama of an alienated executive who re-invents himself .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.625
Max VRAM Usage: 2364.60888671875
Total Time: 1.1126832999289036
---------------------------------------------------------------------------
Text: spielberg's realization of a near-future america is masterful . this makes minority report necessary viewing for sci-fi fans , as the film has some of the best special effects ever .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.6328125
Max VRAM Usage: 2368.22900390625
Total Time: 1.13500979996752
---------------------------------------------------------------------------
Text: the gags that fly at such a furiously funny pace that the only rip off that we were aware of was the one we felt when the movie ended so damned soon .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.64453125
Max VRAM Usage: 2367.89990234375
Total Time: 1.100642399978824
---------------------------------------------------------------------------
Text: the best film of the year 2002 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.64453125
Max VRAM Usage: 2363.78564453125
Total Time: 1.1203831000020728
---------------------------------------------------------------------------
Text: an enthralling , entertaining feature .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.64453125
Max VRAM Usage: 2363.45654296875
Total Time: 1.1028562999563292
---------------------------------------------------------------------------
Text: stripped almost entirely of such tools as nudity , profanity and violence , labute does manage to make a few points about modern man and his problematic quest for human connection .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.64453125
Max VRAM Usage: 2367.73486328125
Total Time: 1.0947222999529913
---------------------------------------------------------------------------
Text: a remarkable movie with an unsatisfying ending , which is just the point .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.64453125
Max VRAM Usage: 2364.77294921875
Total Time: 1.1165182000258937
---------------------------------------------------------------------------
Text: all in all , brown sugar is a satisfying well-made romantic comedy that's both charming and well acted . it will guarantee to have you leaving the theater with a smile on your face .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.64453125
Max VRAM Usage: 2368.22900390625
Total Time: 1.1634834998985752
---------------------------------------------------------------------------
Text: smith finds amusing juxtapositions that justify his exercise .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1475.65234375
Max VRAM Usage: 2363.95068359375
Total Time: 1.1105648999800906
---------------------------------------------------------------------------
Text: working from a surprisingly sensitive script co-written by gianni romoli . . . ozpetek avoids most of the pitfalls you'd expect in such a potentially sudsy set-up .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.65234375
Max VRAM Usage: 2368.06396484375
Total Time: 1.1013400999363512
---------------------------------------------------------------------------
Text: an older cad instructs a younger lad in zen and the art of getting laid in this prickly indie comedy of manners and misanthropy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.65234375
Max VRAM Usage: 2366.91259765625
Total Time: 1.1322104999562725
---------------------------------------------------------------------------
Text: " austin powers in goldmember " has the right stuff for silly summer entertainment and has enough laughs to sustain interest to the end .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2366.58349609375
Total Time: 1.1592094999505207
---------------------------------------------------------------------------
Text: one of [jaglom's] better efforts -- a wry and sometime bitter movie about love .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2365.59619140625
Total Time: 1.1434719999087974
---------------------------------------------------------------------------
Text: schaeffer isn't in this film , which may be why it works as well as it does .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2365.59619140625
Total Time: 1.1052587000885978
---------------------------------------------------------------------------
Text: a fresh , entertaining comedy that looks at relationships minus traditional gender roles .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2364.44384765625
Total Time: 1.1551334999967366
---------------------------------------------------------------------------
Text: although estela bravo's documentary is cloyingly hagiographic in its portrait of cuban leader fidel castro , it's still a guilty pleasure to watch .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2367.89990234375
Total Time: 1.149799200007692
---------------------------------------------------------------------------
Text: surprisingly , the film is a hilarious adventure and i shamelessly enjoyed it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2364.60888671875
Total Time: 1.0988886000122875
---------------------------------------------------------------------------
Text: the way home is an ode to unconditional love and compassion garnered from years of seeing it all , a condition only the old are privy to , and . . . often misconstrued as weakness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2368.72216796875
Total Time: 1.095281400019303
---------------------------------------------------------------------------
Text: brutally honest and told with humor and poignancy , which makes its message resonate .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2364.93798828125
Total Time: 1.1238944999640808
---------------------------------------------------------------------------
Text: if you can read the subtitles ( the opera is sung in italian ) and you like 'masterpiece theatre' type costumes , you'll enjoy this movie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2367.24169921875
Total Time: 1.1017810000339523
---------------------------------------------------------------------------
Text: a pretty funny movie , with most of the humor coming , as before , from the incongruous but chemically perfect teaming of crystal and de niro .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2367.57080078125
Total Time: 1.1035264999372885
---------------------------------------------------------------------------
Text: gangster no . 1 is solid , satisfying fare for adults .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.65625
Max VRAM Usage: 2364.44384765625
Total Time: 1.1312522999942303
---------------------------------------------------------------------------
Text: this chicago has hugely imaginative and successful casting to its great credit , as well as one terrific score and attitude to spare .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.66796875
Max VRAM Usage: 2366.08935546875
Total Time: 1.0891527000349015
---------------------------------------------------------------------------
Text: has enough gun battles and throwaway humor to cover up the yawning chasm where the plot should be .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.66796875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1117554000811651
---------------------------------------------------------------------------
Text: with its jerky hand-held camera and documentary feel , bloody sunday is a sobering recount of a very bleak day in derry .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.66796875
Max VRAM Usage: 2366.58349609375
Total Time: 1.103518999996595
---------------------------------------------------------------------------
Text: you will likely prefer to keep on watching .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.66796875
Max VRAM Usage: 2363.62158203125
Total Time: 1.178776300046593
---------------------------------------------------------------------------
Text: insomnia loses points when it surrenders to a formulaic bang-bang , shoot-em-up scene at the conclusion . but the performances of pacino , williams , and swank keep the viewer wide-awake all the way through .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 177 || Output tokens: 1
Peak memory Usage: 1475.6796875
Max VRAM Usage: 2370.20361328125
Total Time: 1.1106285999994725
---------------------------------------------------------------------------
Text: what might have been readily dismissed as the tiresome rant of an aging filmmaker still thumbing his nose at convention takes a surprising , subtle turn at the midway point .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.6796875
Max VRAM Usage: 2367.57080078125
Total Time: 1.1002021000022069
---------------------------------------------------------------------------
Text: at a time when commercialism has squeezed the life out of whatever idealism american moviemaking ever had , godfrey reggio's career shines like a lonely beacon .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.6796875
Max VRAM Usage: 2367.73486328125
Total Time: 1.1363595000002533
---------------------------------------------------------------------------
Text: an inuit masterpiece that will give you goosebumps as its uncanny tale of love , communal discord , and justice unfolds .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.6796875
Max VRAM Usage: 2366.41845703125
Total Time: 1.101788300089538
---------------------------------------------------------------------------
Text: this is popcorn movie fun with equal doses of action , cheese , ham and cheek ( as well as a serious debt to the road warrior ) , but it feels like unrealized potential

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.6796875
Max VRAM Usage: 2368.06396484375
Total Time: 1.1349345999769866
---------------------------------------------------------------------------
Text: it's a testament to de niro and director michael caton-jones that by movie's end , we accept the characters and the film , flaws and all .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.68359375
Max VRAM Usage: 2367.57080078125
Total Time: 1.097437100019306
---------------------------------------------------------------------------
Text: performances are potent , and the women's stories are ably intercut and involving .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.69140625
Max VRAM Usage: 2364.93798828125
Total Time: 1.1292684000218287
---------------------------------------------------------------------------
Text: an enormously entertaining movie , like nothing we've ever seen before , and yet completely familiar .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.7109375
Max VRAM Usage: 2365.10205078125
Total Time: 1.1051625000545755
---------------------------------------------------------------------------
Text: lan yu is a genuine love story , full of traditional layers of awakening and ripening and separation and recovery .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.71484375
Max VRAM Usage: 2365.76025390625
Total Time: 1.1013335000025108
---------------------------------------------------------------------------
Text: your children will be occupied for 72 minutes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1475.71875
Max VRAM Usage: 2363.78564453125
Total Time: 1.139724100008607
---------------------------------------------------------------------------
Text: pull[s] off the rare trick of recreating not only the look of a certain era , but also the feel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.71875
Max VRAM Usage: 2366.08935546875
Total Time: 1.095164200058207
---------------------------------------------------------------------------
Text: twohy's a good yarn-spinner , and ultimately the story compels .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.71875
Max VRAM Usage: 2364.60888671875
Total Time: 1.0961077000247315
---------------------------------------------------------------------------
Text: 'tobey maguire is a poster boy for the geek generation . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.71875
Max VRAM Usage: 2364.77294921875
Total Time: 1.12737660005223
---------------------------------------------------------------------------
Text: . . . a sweetly affecting story about four sisters who are coping , in one way or another , with life's endgame .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.72265625
Max VRAM Usage: 2366.58349609375
Total Time: 1.1215768000110984
---------------------------------------------------------------------------
Text: passion , melodrama , sorrow , laugther , and tears cascade over the screen effortlessly . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2365.59619140625
Total Time: 1.1127612999407575
---------------------------------------------------------------------------
Text: road to perdition does display greatness , and it's worth seeing . but it also comes with the laziness and arrogance of a thing that already knows it's won .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2367.73486328125
Total Time: 1.158123999950476
---------------------------------------------------------------------------
Text: a marvelous performance by allison lohman as an identity-seeking foster child .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2364.77294921875
Total Time: 1.1371688999934122
---------------------------------------------------------------------------
Text: arliss howard's ambitious , moving , and adventurous directorial debut , big bad love , meets so many of the challenges it poses for itself that one can forgive the film its flaws .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2368.55810546875
Total Time: 1.10112200002186
---------------------------------------------------------------------------
Text: critics need a good laugh , too , and this too-extreme-for-tv rendition of the notorious mtv show delivers the outrageous , sickening , sidesplitting goods in steaming , visceral heaps .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2368.88720703125
Total Time: 1.1009732000529766
---------------------------------------------------------------------------
Text: what a dumb , fun , curiously adolescent movie this is .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2364.27978515625
Total Time: 1.128044700017199
---------------------------------------------------------------------------
Text: many insightful moments .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 132 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2362.79833984375
Total Time: 1.1195010000374168
---------------------------------------------------------------------------
Text: the charms of the lead performances allow us to forget most of the film's problems .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.7265625
Max VRAM Usage: 2364.93798828125
Total Time: 1.1391698999796063
---------------------------------------------------------------------------
Text: a vivid , sometimes surreal , glimpse into the mysteries of human behavior .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.73046875
Max VRAM Usage: 2364.44384765625
Total Time: 1.1247483999468386
---------------------------------------------------------------------------
Text: a tour de force of modern cinema .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.73046875
Max VRAM Usage: 2363.45654296875
Total Time: 1.1313878000946715
---------------------------------------------------------------------------
Text: peralta captures , in luminous interviews and amazingly evocative film from three decades ago , the essence of the dogtown experience .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.73046875
Max VRAM Usage: 2366.58349609375
Total Time: 1.1209023999981582
---------------------------------------------------------------------------
Text: the lively appeal of the last kiss lies in the ease with which it integrates thoughtfulness and pasta-fagioli comedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.73046875
Max VRAM Usage: 2366.08935546875
Total Time: 1.1169190000509843
---------------------------------------------------------------------------
Text: without resorting to camp or parody , haynes ( like sirk , but differently ) has transformed the rhetoric of hollywood melodrama into something provocative , rich , and strange .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2368.06396484375
Total Time: 1.161579499952495
---------------------------------------------------------------------------
Text: the performances are an absolute joy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2363.29248046875
Total Time: 1.1348287999862805
---------------------------------------------------------------------------
Text: a quasi-documentary by french filmmaker karim dridi that celebrates the hardy spirit of cuban music .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2365.76025390625
Total Time: 1.0901705001015216
---------------------------------------------------------------------------
Text: grant carries the day with impeccable comic timing , raffish charm and piercing intellect .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2364.93798828125
Total Time: 1.123273800010793
---------------------------------------------------------------------------
Text: a sensitive and astute first feature by anne-sophie birot .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2364.60888671875
Total Time: 1.1184031000593677
---------------------------------------------------------------------------
Text: both exuberantly romantic and serenely melancholy , what time is it there ? may prove to be [tsai's] masterpiece .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2366.91259765625
Total Time: 1.0973851999733597
---------------------------------------------------------------------------
Text: mazel tov to a film about a family's joyous life acting on the yiddish stage .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1475.734375
Max VRAM Usage: 2365.76025390625
Total Time: 1.1105043001007289
---------------------------------------------------------------------------
Text: standing in the shadows of motown is the best kind of documentary , one that makes a depleted yesterday feel very much like a brand-new tomorrow .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.73828125
Max VRAM Usage: 2366.91259765625
Total Time: 1.1284422000171617
---------------------------------------------------------------------------
Text: it's nice to see piscopo again after all these years , and chaykin and headly are priceless .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.7421875
Max VRAM Usage: 2365.92529296875
Total Time: 1.14790959993843
---------------------------------------------------------------------------
Text: provides a porthole into that noble , trembling incoherence that defines us all .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.7421875
Max VRAM Usage: 2365.10205078125
Total Time: 1.122710399911739
---------------------------------------------------------------------------
Text: this slender plot feels especially thin stretched over the nearly 80-minute running time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.7421875
Max VRAM Usage: 2364.77294921875
Total Time: 1.1044614999555051
---------------------------------------------------------------------------
Text: a film that will probably please people already fascinated by behan but leave everyone else yawning with admiration .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.7421875
Max VRAM Usage: 2365.59619140625
Total Time: 1.1312284000450745
---------------------------------------------------------------------------
Text: davis the performer is plenty fetching enough , but she needs to shake up the mix , and work in something that doesn't feel like a half-baked stand-up routine .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.7421875
Max VRAM Usage: 2367.89990234375
Total Time: 1.1111131999641657
---------------------------------------------------------------------------
Text: the densest distillation of roberts' movies ever made .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1475.76171875
Max VRAM Usage: 2364.27978515625
Total Time: 1.1765207001008093
---------------------------------------------------------------------------
Text: ultimately , the film never recovers from the clumsy cliché of the ugly american abroad , and the too-frosty exterior ms . paltrow employs to authenticate her british persona is another liability .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.76953125
Max VRAM Usage: 2368.72216796875
Total Time: 1.1056481999112293
---------------------------------------------------------------------------
Text: a handsome but unfulfilling suspense drama more suited to a quiet evening on pbs than a night out at an amc .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.78125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1231563000474125
---------------------------------------------------------------------------
Text: tom green and an ivy league college should never appear together on a marquee , especially when the payoff is an unschooled comedy like stealing harvard , which fails to keep 80 minutes from seeming like 800 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1475.78125
Max VRAM Usage: 2369.54541015625
Total Time: 1.133354999939911
---------------------------------------------------------------------------
Text: ( it ) highlights not so much the crime lord's messianic bent , but spacey's .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.78125
Max VRAM Usage: 2365.59619140625
Total Time: 1.117820099927485
---------------------------------------------------------------------------
Text: master of disguise runs for only 71 minutes and feels like three hours .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.78125
Max VRAM Usage: 2364.60888671875
Total Time: 1.1312581000383943
---------------------------------------------------------------------------
Text: a reworking of die hard and cliffhanger but it's nowhere near as exciting as either .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.78125
Max VRAM Usage: 2365.43115234375
Total Time: 1.142808199976571
---------------------------------------------------------------------------
Text: suffers from unlikable characters and a self-conscious sense of its own quirky hipness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.796875
Max VRAM Usage: 2365.10205078125
Total Time: 1.0942001000512391
---------------------------------------------------------------------------
Text: a film without surprise geared toward maximum comfort and familiarity .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1475.796875
Max VRAM Usage: 2363.95068359375
Total Time: 1.130481900065206
---------------------------------------------------------------------------
Text: fessenden continues to do interesting work , and it would be nice to see what he could make with a decent budget . but the problem with wendigo , for all its effective moments , isn't really one of resources .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 174 || Output tokens: 1
Peak memory Usage: 1475.8046875
Max VRAM Usage: 2369.70947265625
Total Time: 1.121340399957262
---------------------------------------------------------------------------
Text: spirit is a visual treat , and it takes chances that are bold by studio standards , but it lacks a strong narrative .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.81640625
Max VRAM Usage: 2366.08935546875
Total Time: 1.096346199978143
---------------------------------------------------------------------------
Text: it stars schticky chris rock and stolid anthony hopkins , who seem barely in the same movie . their contrast is neither dramatic nor comic -- it's just a weird fizzle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1475.82421875
Max VRAM Usage: 2368.72216796875
Total Time: 1.147735200007446
---------------------------------------------------------------------------
Text: this is a children's film in the truest sense . it's packed with adventure and a worthwhile environmental message , so it's great for the kids . parents , on the other hand , will be ahead of the plot at all times , and there isn't enough clever innuendo to fil

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 187 || Output tokens: 1
Peak memory Usage: 1475.82421875
Max VRAM Usage: 2371.91943359375
Total Time: 1.1183093000436202
---------------------------------------------------------------------------
Text: the niftiest trick perpetrated by the importance of being earnest is the alchemical transmogrification of wilde into austen--and a hollywood-ized austen at that .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1475.828125
Max VRAM Usage: 2368.39306640625
Total Time: 1.087660799967125
---------------------------------------------------------------------------
Text: tykwer's surface flash isn't just a poor fit with kieslowski's lyrical pessimism ; it completely contradicts everything kieslowski's work aspired to , including the condition of art .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1475.8359375
Max VRAM Usage: 2369.38037109375
Total Time: 1.1187739999732003
---------------------------------------------------------------------------
Text: ice age is the first computer-generated feature cartoon to feel like other movies , and that makes for some glacial pacing early on .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.8359375
Max VRAM Usage: 2366.41845703125
Total Time: 1.109514500014484
---------------------------------------------------------------------------
Text: too slick and manufactured to claim street credibility .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.8359375
Max VRAM Usage: 2363.62158203125
Total Time: 1.1116596999345347
---------------------------------------------------------------------------
Text: cherry orchard is badly edited , often awkwardly directed and suffers from the addition of a wholly unnecessary pre-credit sequence designed to give some of the characters a 'back story . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.8359375
Max VRAM Usage: 2368.22900390625
Total Time: 1.0838780000340194
---------------------------------------------------------------------------
Text: what ensues are much blood-splattering , mass drug-induced bowel evacuations , and none-too-funny commentary on the cultural distinctions between americans and brits .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.8359375
Max VRAM Usage: 2367.73486328125
Total Time: 1.1109707000432536
---------------------------------------------------------------------------
Text: a dark comedy that goes for sick and demented humor simply to do so . the movie is without intent .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.8359375
Max VRAM Usage: 2365.92529296875
Total Time: 1.0942326000658795
---------------------------------------------------------------------------
Text: visually exciting sci-fi film which suffers from a lackluster screenplay .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.8515625
Max VRAM Usage: 2364.44384765625
Total Time: 1.1290948999812827
---------------------------------------------------------------------------
Text: while hollywood ending has its share of belly laughs ( including a knockout of a closing line ) , the movie winds up feeling like a great missed opportunity .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.87109375
Max VRAM Usage: 2367.24169921875
Total Time: 1.100338299991563
---------------------------------------------------------------------------
Text: if the full monty was a freshman fluke , lucky break is [cattaneo] sophomore slump .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.87109375
Max VRAM Usage: 2365.92529296875
Total Time: 1.1025920000392944
---------------------------------------------------------------------------
Text: sandra bullock and hugh grant make a great team , but this predictable romantic comedy should get a pink slip .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.87109375
Max VRAM Usage: 2366.08935546875
Total Time: 1.096204899949953
---------------------------------------------------------------------------
Text: allegiance to chekhov , which director michael cacoyannis displays with somber earnestness in the new adaptation of the cherry orchard , is a particularly vexing handicap .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.87109375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1080399000784382
---------------------------------------------------------------------------
Text: you expect more from director michael apted ( enigma ) and screenwriter nicholas kazan ( reversal of fortune ) than this cliche pileup .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2367.07666015625
Total Time: 1.1014148000394925
---------------------------------------------------------------------------
Text: the first mistake , i suspect , is casting shatner as a legendary professor and kunis as a brilliant college student--where's pauly shore as the rocket scientist ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2367.89990234375
Total Time: 1.1277856999076903
---------------------------------------------------------------------------
Text: the dramatic scenes are frequently unintentionally funny , and the action sequences -- clearly the main event -- are surprisingly uninvolving .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2366.25439453125
Total Time: 1.1225069999927655
---------------------------------------------------------------------------
Text: replacing john carpenter's stylish tracking shots is degraded , handheld blair witch video-cam footage . of all the halloween's , this is the most visually unappealing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2368.06396484375
Total Time: 1.1129865000257269
---------------------------------------------------------------------------
Text: it has the requisite faux-urban vibe and hotter-two-years-ago rap and r&b names and references .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2365.92529296875
Total Time: 1.1022892999462783
---------------------------------------------------------------------------
Text: despite its dry wit and compassion , the film suffers from a philosophical emptiness and maddeningly sedate pacing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2365.92529296875
Total Time: 1.1324190000304952
---------------------------------------------------------------------------
Text: . . . feels as if ( there's ) a choke leash around your neck so director nick cassavetes can give it a good , hard yank whenever he wants you to feel something .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2368.55810546875
Total Time: 1.0911025000968948
---------------------------------------------------------------------------
Text: attal pushes too hard to make this a comedy or serious drama . he seems to want both , but succeeds in making neither .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2366.41845703125
Total Time: 1.113566100015305
---------------------------------------------------------------------------
Text: i could have used my two hours better watching being john malkovich again .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2364.77294921875
Total Time: 1.1133520000148565
---------------------------------------------------------------------------
Text: it's not a bad plot ; but , unfortunately , the movie is nowhere near as refined as all the classic dramas it borrows from .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2366.74755859375
Total Time: 1.0922325000865385
---------------------------------------------------------------------------
Text: flat , misguided comedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2362.96337890625
Total Time: 1.116084499983117
---------------------------------------------------------------------------
Text: girlfriends are bad , wives are worse and babies are the kiss of death in this bitter italian comedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2365.43115234375
Total Time: 1.113126700045541
---------------------------------------------------------------------------
Text: the only young people who possibly will enjoy it are infants . . . who might be distracted by the movie's quick movements and sounds .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1010528999613598
---------------------------------------------------------------------------
Text: the film boasts at least a few good ideas and features some decent performances , but the result is disappointing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2365.59619140625
Total Time: 1.1453931999858469
---------------------------------------------------------------------------
Text: no such thing breaks no new ground and treads old turf like a hippopotamus ballerina .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2365.59619140625
Total Time: 1.097804799908772
---------------------------------------------------------------------------
Text: unfortunately , neither sendak nor the directors are particularly engaging or articulate .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2364.44384765625
Total Time: 1.1292209000093862
---------------------------------------------------------------------------
Text: a wishy-washy melodramatic movie that shows us plenty of sturm und drung , but explains its characters' decisions only unsatisfactorily .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2367.57080078125
Total Time: 1.0970943999709561
---------------------------------------------------------------------------
Text: bang ! zoom ! it's actually pretty funny , but in all the wrong places .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.8828125
Max VRAM Usage: 2364.93798828125
Total Time: 1.1192350999917835
---------------------------------------------------------------------------
Text: lurid and less than lucid work .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2363.62158203125
Total Time: 1.1876767000649124
---------------------------------------------------------------------------
Text: a wannabe comedy of manners about a brainy prep-school kid with a mrs . robinson complex founders on its own preciousness -- and squanders its beautiful women .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2367.89990234375
Total Time: 1.108721699914895
---------------------------------------------------------------------------
Text: at a brief 42 minutes , we need more x and less blab .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2364.77294921875
Total Time: 1.0951233999803662
---------------------------------------------------------------------------
Text: if anything , see it for karen black , who camps up a storm as a fringe feminist conspiracy theorist named dirty dick .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2366.41845703125
Total Time: 1.123338000033982
---------------------------------------------------------------------------
Text: this 90-minute dud could pass for mike tyson's e ! true hollywood story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2365.43115234375
Total Time: 1.1195101999910548
---------------------------------------------------------------------------
Text: this is surely one of the most frantic , virulent and foul-natured christmas season pics ever delivered by a hollywood studio .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2366.58349609375
Total Time: 1.0984375999541953
---------------------------------------------------------------------------
Text: once the expectation of laughter has been quashed by whatever obscenity is at hand , even the funniest idea isn't funny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2366.41845703125
Total Time: 1.134734700084664
---------------------------------------------------------------------------
Text: a porn film without the sex scenes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none
Response: none
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2363.45654296875
Total Time: 1.1106656999327242
---------------------------------------------------------------------------
Text: the connected stories of breitbart and hanussen are actually fascinating , but the filmmaking in invincible is such that the movie does not do them justice .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2367.24169921875
Total Time: 1.0981997000053525
---------------------------------------------------------------------------
Text: a depressingly retrograde , 'post-feminist' romantic comedy that takes an astonishingly condescending attitude toward women .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2366.25439453125
Total Time: 1.1041646000230685
---------------------------------------------------------------------------
Text: return to never land is much more p . c . than the original version ( no more racist portraits of indians , for instance ) , but the excitement is missing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2367.73486328125
Total Time: 1.1102459999965504
---------------------------------------------------------------------------
Text: by the end , you just don't care whether that cold-hearted snake petrovich ( that would be reno ) gets his comeuppance . just bring on the battle bots , please !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2368.55810546875
Total Time: 1.1091604999965057
---------------------------------------------------------------------------
Text: while it's all quite tasteful to look at , the attention process tends to do a little fleeing of its own .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.88671875
Max VRAM Usage: 2366.08935546875
Total Time: 1.1561978999525309
---------------------------------------------------------------------------
Text: broder's screenplay is shallow , offensive and redundant , with pitifully few real laughs .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2365.26708984375
Total Time: 1.1440152999712154
---------------------------------------------------------------------------
Text: yes they can swim , the title is merely anne-sophie birot's off-handed way of saying girls find adolescence difficult to wade through .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2367.07666015625
Total Time: 1.1148649998940527
---------------------------------------------------------------------------
Text: don michael paul uses quick-cuts , ( very ) large shadows and wide-angle shots taken from a distance to hide the liberal use of a body double ( for seagal ) .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2368.06396484375
Total Time: 1.118873499915935
---------------------------------------------------------------------------
Text: slow , silly and unintentionally hilarious .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2363.45654296875
Total Time: 1.147969700046815
---------------------------------------------------------------------------
Text: the sweetest thing leaves a bitter taste .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2363.62158203125
Total Time: 1.1131128000561148
---------------------------------------------------------------------------
Text: in a big corner office in hell , satan is throwing up his hands in surrender , is firing his r&d people , and has decided he will just screen the master of disguise 24/7 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2369.05126953125
Total Time: 1.0970426999265328
---------------------------------------------------------------------------
Text: for something as splendid-looking as this particular film , the viewer expects something special but instead gets [sci-fi] rehash .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.90234375
Max VRAM Usage: 2366.25439453125
Total Time: 1.135363099980168
---------------------------------------------------------------------------
Text: a thriller without a lot of thrills .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1475.9296875
Max VRAM Usage: 2363.62158203125
Total Time: 1.1233801000053063
---------------------------------------------------------------------------
Text: this stuck pig of a movie flails limply between bizarre comedy and pallid horror .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.9296875
Max VRAM Usage: 2365.10205078125
Total Time: 1.1172075000358745
---------------------------------------------------------------------------
Text: ah , the travails of metropolitan life ! alas , another breathless movie about same !

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1475.95703125
Max VRAM Usage: 2365.10205078125
Total Time: 1.1233784999931231
---------------------------------------------------------------------------
Text: in moonlight mile , no one gets shut out of the hug cycle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.95703125
Max VRAM Usage: 2364.60888671875
Total Time: 1.164187500020489
---------------------------------------------------------------------------
Text: though uniformly well acted , especially by young ballesta and galan ( a first-time actor ) , writer/director achero manas's film is schematic and obvious .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1192065000068396
---------------------------------------------------------------------------
Text: done in mostly by a weak script that can't support the epic treatment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2364.60888671875
Total Time: 1.1090821000980213
---------------------------------------------------------------------------
Text: despite its visual virtuosity , 'naqoyqatsi' is banal in its message and the choice of material to convey it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2367.07666015625
Total Time: 1.1321837999857962
---------------------------------------------------------------------------
Text: slap her - she's not funny ! no french people were harmed during the making of this movie , but they were insulted and the audience was put through torture for an hour and a half .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2368.55810546875
Total Time: 1.1137386999325827
---------------------------------------------------------------------------
Text: though its rather routine script is loaded with familiar situations , the movie has a cinematic fluidity and sense of intelligence that makes it work more than it probably should .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2367.40576171875
Total Time: 1.1149493999546394
---------------------------------------------------------------------------
Text: " one look at a girl in tight pants and big tits and you turn stupid ? " um . . isn't that the basis for the entire plot ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

I

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

I
Response: none
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2367.40576171875
Total Time: 1.0982549000764266
---------------------------------------------------------------------------
Text: " not really as bad as you might think ! "

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2363.95068359375
Total Time: 1.131896400009282
---------------------------------------------------------------------------
Text: strident and inelegant in its 'message-movie' posturing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2364.60888671875
Total Time: 1.1668391999555752
---------------------------------------------------------------------------
Text: one regards reign of fire with awe . what a vast enterprise has been marshaled in the service of such a minute idea .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2366.25439453125
Total Time: 1.1001252999994904
---------------------------------------------------------------------------
Text: it has the right approach and the right opening premise , but it lacks the zest and it goes for a plot twist instead of trusting the material .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2366.91259765625
Total Time: 1.1034290000097826
---------------------------------------------------------------------------
Text: its impressive images of crematorium chimney fires and stacks of dead bodies are undermined by the movie's presentation , which is way too stagy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2366.74755859375
Total Time: 1.1389847999671474
---------------------------------------------------------------------------
Text: seeing as the film lacks momentum and its position remains mostly undeterminable , the director's experiment is a successful one .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1460857999045402
---------------------------------------------------------------------------
Text: the plot is romantic comedy boilerplate from start to finish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2364.11474609375
Total Time: 1.1273886000271887
---------------------------------------------------------------------------
Text: i suspect this is the kind of production that would have been funnier if the director had released the outtakes theatrically and used the film as a bonus feature on the dvd .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2368.22900390625
Total Time: 1.1267289000097662
---------------------------------------------------------------------------
Text: an unfortunate title for a film that has nothing endearing about it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2364.44384765625
Total Time: 1.1379170001018792
---------------------------------------------------------------------------
Text: ninety minutes of viva castro ! can be as tiresome as 9 seconds of jesse helms' anti- castro rhetoric , which are included

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2367.40576171875
Total Time: 1.1127229999983683
---------------------------------------------------------------------------
Text: comes off as a long , laborious whine , the bellyaching of a paranoid and unlikable man .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1475.9609375
Max VRAM Usage: 2365.92529296875
Total Time: 1.1253944999771193
---------------------------------------------------------------------------
Text: it just goes to show , an intelligent person isn't necessarily an admirable storyteller .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1475.984375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1028626000043005
---------------------------------------------------------------------------
Text: in a 102-minute film , aaliyah gets at most 20 minutes of screen time . . . . most viewers will wish there had been more of the " queen " and less of the " damned . "

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1475.99609375
Max VRAM Usage: 2369.38037109375
Total Time: 1.1277257000328973
---------------------------------------------------------------------------
Text: hopelessly inane , humorless and under-inspired .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1476.0
Max VRAM Usage: 2363.95068359375
Total Time: 1.1153899999335408
---------------------------------------------------------------------------
Text: kapur fails to give his audience a single character worth rooting for ( or worth rooting against , for that matter ) .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1476.0
Max VRAM Usage: 2366.08935546875
Total Time: 1.1053327999543399
---------------------------------------------------------------------------
Text: it reduces the complexities to bromides and slogans and it gets so preachy-keen and so tub-thumpingly loud it makes you feel like a chump just for sitting through it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1476.0
Max VRAM Usage: 2368.55810546875
Total Time: 1.1248361999168992
---------------------------------------------------------------------------
Text: none of this has the suavity or classical familiarity of bond , but much of it is good for a laugh . the problem with " xxx " is that its own action isn't very effective .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1476.01171875
Max VRAM Usage: 2368.55810546875
Total Time: 1.1065623000031337
---------------------------------------------------------------------------
Text: a great script brought down by lousy direction . same guy with both hats . big mistake .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1476.01171875
Max VRAM Usage: 2365.26708984375
Total Time: 1.1188073999946937
---------------------------------------------------------------------------
Text: a mediocre exercise in target demographics , unaware that it's the butt of its own joke .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1476.01171875
Max VRAM Usage: 2365.10205078125
Total Time: 1.1064177000662312
---------------------------------------------------------------------------
Text: director kevin bray excels in breaking glass and marking off the " miami vice " checklist of power boats , latin music and dog tracks . he doesn't , however , deliver nearly enough of the show's trademark style and flash .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 176 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2370.03857421875
Total Time: 1.1094520000042394
---------------------------------------------------------------------------
Text: in gleefully , thumpingly hyperbolic terms , it covers just about every cliche in the compendium about crass , jaded movie types and the phony baloney movie biz .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2368.88720703125
Total Time: 1.137218500021845
---------------------------------------------------------------------------
Text: the spalding gray equivalent of a teen gross-out comedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2364.27978515625
Total Time: 1.1339156000176445
---------------------------------------------------------------------------
Text: perhaps even the slc high command found writer-director mitch davis's wall of kitsch hard going .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2365.92529296875
Total Time: 1.198039900045842
---------------------------------------------------------------------------
Text: according to wendigo , 'nature' loves the members of the upper class almost as much as they love themselves .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2366.08935546875
Total Time: 1.1156770000234246
---------------------------------------------------------------------------
Text: an encouraging effort from mccrudden

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2363.29248046875
Total Time: 1.1184372999705374
---------------------------------------------------------------------------
Text: the romance between the leads isn't as compelling or as believable as it should be .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1476.015625
Max VRAM Usage: 2364.93798828125
Total Time: 1.0982057999353856
---------------------------------------------------------------------------
Text: if i could have looked into my future and saw how bad this movie was , i would go back and choose to skip it . fortunately , you still have that option .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1476.01953125
Max VRAM Usage: 2367.73486328125
Total Time: 1.1226911999983713
---------------------------------------------------------------------------
Text: supposedly authentic account of a historical event that's far too tragic to merit such superficial treatment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1476.0234375
Max VRAM Usage: 2365.10205078125
Total Time: 1.1104292999953032
---------------------------------------------------------------------------
Text: adroit but finally a trifle flat , mad love doesn't galvanize its outrage the way , say , jane campion might have done , but at least it possesses some .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1476.0234375
Max VRAM Usage: 2368.22900390625
Total Time: 1.1310519999824464
---------------------------------------------------------------------------
Text: to blandly go where we went 8 movies ago . . .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1476.0234375
Max VRAM Usage: 2364.44384765625
Total Time: 1.1074921999825165
---------------------------------------------------------------------------
Text: a slow-moving police-procedural thriller that takes its title all too literally .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1476.0234375
Max VRAM Usage: 2364.77294921875
Total Time: 1.1654464000603184
---------------------------------------------------------------------------
Text: this u-boat doesn't have a captain .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1476.0234375
Max VRAM Usage: 2363.78564453125
Total Time: 1.1286055999808013
---------------------------------------------------------------------------
Text: with nary a glimmer of self-knowledge , [crane] becomes more specimen than character -- and auto focus remains a chilly , clinical lab report .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1476.0546875
Max VRAM Usage: 2367.40576171875
Total Time: 1.0912923000287265
---------------------------------------------------------------------------
Text: this one aims for the toilet and scores a direct hit .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1476.0546875
Max VRAM Usage: 2364.11474609375
Total Time: 1.1175181000726297
---------------------------------------------------------------------------
Text: dull , a road-trip movie that's surprisingly short of both adventure and song .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1476.07421875
Max VRAM Usage: 2364.93798828125
Total Time: 1.09092599991709
---------------------------------------------------------------------------
Text: i walked away not really know who " they " were , what " they " looked like . why " they " were here and what " they " wanted and quite honestly , i didn't care .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 168 || Output tokens: 1
Peak memory Usage: 1476.07421875
Max VRAM Usage: 2368.72216796875
Total Time: 1.1365660999435931
---------------------------------------------------------------------------
Text: predictably melodramatic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1476.07421875
Max VRAM Usage: 2363.12744140625
Total Time: 1.119535000063479
---------------------------------------------------------------------------
Text: after several scenes of this tacky nonsense , you'll be wistful for the testosterone-charged wizardry of jerry bruckheimer productions , especially because half past dead is like the rock on a wal-mart budget .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 174 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2369.70947265625
Total Time: 1.0949871999910101
---------------------------------------------------------------------------
Text: a relatively effective little potboiler until its absurd , contrived , overblown , and entirely implausible finale .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1047661999473348
---------------------------------------------------------------------------
Text: the country bears wastes an exceptionally good idea . but the movie that doesn't really deliver for country music fans or for family audiences

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2366.25439453125
Total Time: 1.130010599968955
---------------------------------------------------------------------------
Text: adults will certainly want to spend their time in the theater thinking up grocery lists and ways to tell their kids how not to act like pinocchio . as for children , they won't enjoy the movie at all .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2369.21630859375
Total Time: 1.1237527000484988
---------------------------------------------------------------------------
Text: . . . you can be forgiven for realizing that you've spent the past 20 minutes looking at your watch and waiting for frida to just die already .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2367.40576171875
Total Time: 1.1682603999506682
---------------------------------------------------------------------------
Text: too bad writer-director adam rifkin situates it all in a plot as musty as one of the golden eagle's carpets .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2366.58349609375
Total Time: 1.1207011999795213
---------------------------------------------------------------------------
Text: it's lazy for a movie to avoid solving one problem by trying to distract us with the solution to another .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2365.76025390625
Total Time: 1.1979305000277236
---------------------------------------------------------------------------
Text: the movie is genial but never inspired , and little about it will stay with you .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2365.10205078125
Total Time: 1.232397299958393
---------------------------------------------------------------------------
Text: the movie obviously seeks to re-create the excitement of such '50s flicks as jules verne's '20 , 000 leagues under the sea' and the george pal version of h . g . wells' 'the time machine . ' but its storytelling prowess and special effects are both listless .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 191 || Output tokens: 1
Peak memory Usage: 1476.0859375
Max VRAM Usage: 2372.50732421875
Total Time: 1.2096340999705717
---------------------------------------------------------------------------
Text: despite the opulent lushness of every scene , the characters never seem to match the power of their surroundings .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1476.0703125
Max VRAM Usage: 2365.76025390625
Total Time: 1.1143920000176877
---------------------------------------------------------------------------
Text: even after 90 minutes of playing opposite each other bullock and grant still look ill at ease sharing the same scene . what should have been a painless time-killer becomes instead a grating endurance test .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1476.08203125
Max VRAM Usage: 2369.05126953125
Total Time: 1.1292905000736937
---------------------------------------------------------------------------
Text: a bland , obnoxious 88-minute infomercial for universal studios and its ancillary products .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1476.08203125
Max VRAM Usage: 2365.43115234375
Total Time: 1.2218751000473276
---------------------------------------------------------------------------
Text: . . little action , almost no suspense or believable tension , one-dimensional characters up the wazoo and sets that can only be described as sci-fi generic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1476.08203125
Max VRAM Usage: 2367.40576171875
Total Time: 1.1473256999161094
---------------------------------------------------------------------------
Text: the movie strains to stay on the light , comic side of the issue , despite the difficulty of doing so when dealing with the destruction of property and , potentially , of life itself .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1352.33984375
Max VRAM Usage: 2368.06396484375
Total Time: 1.132910699932836
---------------------------------------------------------------------------
Text: the master of disguise is awful . it's pauly shore awful . don't say you weren't warned .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1352.35546875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1705545999575406
---------------------------------------------------------------------------
Text: disappointing in comparison to other recent war moviesor any other john woo flick for that matter .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1352.359375
Max VRAM Usage: 2365.26708984375
Total Time: 1.1201103000203148
---------------------------------------------------------------------------
Text: the entire movie is filled with deja vu moments .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1352.37890625
Max VRAM Usage: 2363.78564453125
Total Time: 1.1293885000050068
---------------------------------------------------------------------------
Text: 'opening up' the play more has partly closed it down .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1352.41015625
Max VRAM Usage: 2364.27978515625
Total Time: 1.102441699942574
---------------------------------------------------------------------------
Text: what [frei] gives us . . . is a man who uses the damage of war -- far more often than the warfare itself -- to create the kind of art shots that fill gallery shows .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1352.4296875
Max VRAM Usage: 2368.55810546875
Total Time: 1.1231649999972433
---------------------------------------------------------------------------
Text: an ugly , revolting movie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1352.4296875
Max VRAM Usage: 2363.45654296875
Total Time: 1.129076899960637
---------------------------------------------------------------------------
Text: the film is way too full of itself ; it's stuffy and pretentious in a give-me-an-oscar kind of way .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1352.4296875
Max VRAM Usage: 2366.58349609375
Total Time: 1.126105000032112
---------------------------------------------------------------------------
Text: the movie is concocted and carried out by folks worthy of scorn , and the nicest thing i can say is that i can't remember a single name responsible for it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1352.4296875
Max VRAM Usage: 2368.06396484375
Total Time: 1.1443400999996811
---------------------------------------------------------------------------
Text: watching " ending " is too often like looking over the outdated clothes and plastic knickknacks at your neighbor's garage sale . you can't believe anyone would really buy this stuff .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1352.4296875
Max VRAM Usage: 2368.22900390625
Total Time: 1.144255500053987
---------------------------------------------------------------------------
Text: certainly beautiful to look at , but its not very informative about its titular character and no more challenging than your average television biopic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1352.4296875
Max VRAM Usage: 2366.41845703125
Total Time: 1.1375013999640942
---------------------------------------------------------------------------
Text: it desperately wants to be a wacky , screwball comedy , but the most screwy thing here is how so many talented people were convinced to waste their time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1352.52734375
Max VRAM Usage: 2367.57080078125
Total Time: 1.1297122000250965
---------------------------------------------------------------------------
Text: the skills of a calculus major at m . i . t . are required to balance all the formulaic equations in the long-winded heist comedy who is cletis tout ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1352.5390625
Max VRAM Usage: 2368.22900390625
Total Time: 1.105378600070253
---------------------------------------------------------------------------
Text: from the choppy editing to the annoying score to 'special effects' by way of replacing objects in a character's hands below the camera line , " besotted " is misbegotten

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1352.546875
Max VRAM Usage: 2368.22900390625
Total Time: 1.1262667999835685
---------------------------------------------------------------------------
Text: my advice is to skip the film and pick up the soundtrack .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1352.546875
Max VRAM Usage: 2364.27978515625
Total Time: 1.1657834999496117
---------------------------------------------------------------------------
Text: a film that presents an interesting , even sexy premise then ruins itself with too many contrivances and goofy situations .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1352.546875
Max VRAM Usage: 2365.92529296875
Total Time: 1.115034700022079
---------------------------------------------------------------------------
Text: filled with low-brow humor , gratuitous violence and a disturbing disregard for life .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1352.55078125
Max VRAM Usage: 2364.93798828125
Total Time: 1.1370416999561712
---------------------------------------------------------------------------
Text: directed in a flashy , empty sub-music video style by a director so self-possessed he actually adds a period to his first name

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1352.55078125
Max VRAM Usage: 2366.74755859375
Total Time: 1.103745499975048
---------------------------------------------------------------------------
Text: the 70-year-old godard has become , to judge from in praise of love , the sort of bitter old crank who sits behind his light meter and harangues the supposed injustices of the artistic world-at-large without doing all that much to correct them .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 181 || Output tokens: 1
Peak memory Usage: 1352.55078125
Max VRAM Usage: 2371.16650390625
Total Time: 1.1127965999767184
---------------------------------------------------------------------------
Text: an unsophisticated sci-fi drama that takes itself all too seriously .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1352.5546875
Max VRAM Usage: 2364.60888671875
Total Time: 1.1227283999323845
---------------------------------------------------------------------------
Text: solondz is without doubt an artist of uncompromising vision , but that vision is beginning to feel , if not morally bankrupt , at least terribly monotonous .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1352.55859375
Max VRAM Usage: 2367.73486328125
Total Time: 1.1286881000269204
---------------------------------------------------------------------------
Text: harvard man is a semi-throwback , a reminiscence without nostalgia or sentimentality .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1352.55859375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1000164999859408
---------------------------------------------------------------------------
Text: supposedly based upon real , or at least soberly reported incidents , the film ends with a large human tragedy . alas , getting there is not even half the interest .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1352.5625
Max VRAM Usage: 2367.57080078125
Total Time: 1.0928262999514118
---------------------------------------------------------------------------
Text: while hoffman's performance is great , the subject matter goes nowhere .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1352.5625
Max VRAM Usage: 2364.60888671875
Total Time: 1.1380962999537587
---------------------------------------------------------------------------
Text: the smash 'em-up , crash 'em-up , shoot 'em-up ending comes out of nowhere substituting mayhem for suspense .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1352.5703125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1138041000813246
---------------------------------------------------------------------------
Text: deuces wild treads heavily into romeo and juliet/west side story territory , where it plainly has no business going .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1352.5703125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1146092999260873
---------------------------------------------------------------------------
Text: hart's war seems to want to be a character study , but apparently can't quite decide which character .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1352.5703125
Max VRAM Usage: 2365.59619140625
Total Time: 1.1474099999759346
---------------------------------------------------------------------------
Text: theological matters aside , the movie is so clumsily sentimental and ineptly directed it may leave you speaking in tongues .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2366.08935546875
Total Time: 1.0996891000540927
---------------------------------------------------------------------------
Text: this latest installment of the horror film franchise that is apparently as invulnerable as its trademark villain has arrived for an incongruous summer playoff , demonstrating yet again that the era of the intelligent , well-made b movie is long gone .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 174 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2369.70947265625
Total Time: 1.1347928000614047
---------------------------------------------------------------------------
Text: novak contemplates a heartland so overwhelmed by its lack of purpose that it seeks excitement in manufactured high drama .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2365.92529296875
Total Time: 1.1139916999964043
---------------------------------------------------------------------------
Text: been there , done that , liked it much better the first time around - when it was called the professional .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2365.76025390625
Total Time: 1.1039922999916598
---------------------------------------------------------------------------
Text: the film is all over the place , really . it dabbles all around , never gaining much momentum .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2365.76025390625
Total Time: 1.1316674000117928
---------------------------------------------------------------------------
Text: the beautiful , unusual music is this film's chief draw , but its dreaminess may lull you to sleep .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2365.92529296875
Total Time: 1.113980400026776
---------------------------------------------------------------------------
Text: the action quickly sinks into by-the-numbers territory .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2363.95068359375
Total Time: 1.164240499958396
---------------------------------------------------------------------------
Text: forages for audience sympathy like a temperamental child begging for attention , giving audiences no reason to truly care for its decrepit freaks beyond the promise of a reprieve from their incessant whining .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1352.578125
Max VRAM Usage: 2368.88720703125
Total Time: 1.136526699992828
---------------------------------------------------------------------------
Text: when [reno] lets her radical flag fly , taking angry potshots at george w . bush , henry kissinger , larry king , et al . , reno devolves into a laugh-free lecture .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1352.58203125
Max VRAM Usage: 2369.38037109375
Total Time: 1.121382600045763
---------------------------------------------------------------------------
Text: such a premise is ripe for all manner of lunacy , but kaufman and gondry rarely seem sure of where it should go .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1352.58203125
Max VRAM Usage: 2366.91259765625
Total Time: 1.1140721999108791
---------------------------------------------------------------------------
Text: burns' fifth beer-soaked film feels in almost every possible way -- from the writing and direction to the soggy performances -- tossed off .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1352.58203125
Max VRAM Usage: 2366.74755859375
Total Time: 1.1424135999986902
---------------------------------------------------------------------------
Text: 'es en verdad una pena que mandoki esté realizando cintas tan malas desde hace algún tiempo , pues talento tiene , pero quién sabe dónde lo tiene escondido . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1352.58203125
Max VRAM Usage: 2369.05126953125
Total Time: 1.0977409000042826
---------------------------------------------------------------------------
Text: while this one gets off with a good natured warning , future lizard endeavors will need to adhere more closely to the laws of laughter

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2366.41845703125
Total Time: 1.1210678000934422
---------------------------------------------------------------------------
Text: another boorish movie from the i-heard-a-joke- at-a-frat-party school of screenwriting .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1131351001095027
---------------------------------------------------------------------------
Text: too much of the movie feels contrived , as if the filmmakers were worried the story wouldn't work without all those gimmicks .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2366.41845703125
Total Time: 1.0946027000900358
---------------------------------------------------------------------------
Text: it's hard to understand why anyone in his right mind would even think to make the attraction a movie . and it's harder still to believe that anyone in his right mind would want to see the it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2368.88720703125
Total Time: 1.1208479999331757
---------------------------------------------------------------------------
Text: the ethos of the chelsea hotel may shape hawke's artistic aspirations , but he hasn't yet coordinated his own dv poetry with the beat he hears in his soul .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1118224000092596
---------------------------------------------------------------------------
Text: the sight of the name bruce willis brings to mind images of a violent battlefield action picture , but the film has a lot more on its mind--maybe too much .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1134739000117406
---------------------------------------------------------------------------
Text: why sit through a crummy , wannabe-hip crime comedy that refers incessantly to old movies , when you could just rent those movies instead , let alone seek out a respectable new one ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1352.5859375
Max VRAM Usage: 2368.55810546875
Total Time: 1.1141233999514952
---------------------------------------------------------------------------
Text: the obnoxious special effects , the obligatory outbursts of flatulence and the incessant , so-five-minutes-ago pop music on the soundtrack overwhelm what is left of the scruffy , dopey old hanna-barbera charm .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 177 || Output tokens: 1
Peak memory Usage: 1352.59375
Max VRAM Usage: 2370.20361328125
Total Time: 1.114070300012827
---------------------------------------------------------------------------
Text: exploring value choices is a worthwhile topic for a film -- but here the choices are as contrived and artificial as kerrigan's platinum-blonde hair .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1352.59375
Max VRAM Usage: 2367.40576171875
Total Time: 1.0953789999475703
---------------------------------------------------------------------------
Text: the movie's downfall is to substitute plot for personality . it doesn't really know or care about the characters , and uses them as markers for a series of preordained events .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1352.59375
Max VRAM Usage: 2368.06396484375
Total Time: 1.1005564000224695
---------------------------------------------------------------------------
Text: all mood and no movie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none
Response: none
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1352.59375
Max VRAM Usage: 2363.12744140625
Total Time: 1.111550800036639
---------------------------------------------------------------------------
Text: press the delete key .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none
Response: none
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2362.96337890625
Total Time: 1.1028402999509126
---------------------------------------------------------------------------
Text: simone is not a bad film . it just doesn't have anything really interesting to say .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2365.26708984375
Total Time: 1.1300291999941692
---------------------------------------------------------------------------
Text: once he starts learning to compromise with reality enough to become comparatively sane and healthy , the film becomes predictably conventional .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2365.92529296875
Total Time: 1.085747200064361
---------------------------------------------------------------------------
Text: . . . hopefully it'll be at the dollar theatres by the time christmas rolls around . wait to see it then .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.25439453125
Total Time: 1.1495500999735668
---------------------------------------------------------------------------
Text: there's no disguising this as one of the worst films of the summer . or for the year , for that matter .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.25439453125
Total Time: 1.100076699978672
---------------------------------------------------------------------------
Text: lacks the spirit of the previous two , and makes all those jokes about hos and even more unmentionable subjects seem like mere splashing around in the muck .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2367.57080078125
Total Time: 1.1459637000225484
---------------------------------------------------------------------------
Text: this hastily mounted production exists only to capitalize on hopkins' inclination to play hannibal lecter again , even though harris has no immediate inclination to provide a fourth book .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2367.89990234375
Total Time: 1.1004335000179708
---------------------------------------------------------------------------
Text: death to smoochy tells a moldy-oldie , not-nearly -as-nasty -as-it- thinks-it-is joke . over and over again .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2367.57080078125
Total Time: 1.1231537000276148
---------------------------------------------------------------------------
Text: the threat implied in the title pokémon 4ever is terrifying  like locusts in a horde these things will keep coming .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.91259765625
Total Time: 1.125595899997279
---------------------------------------------------------------------------
Text: the film never gets over its own investment in conventional arrangements , in terms of love , age , gender , race , and class .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.41845703125
Total Time: 1.1365840999642387
---------------------------------------------------------------------------
Text: to call this film a lump of coal would only be to flatter it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2364.77294921875
Total Time: 1.1413153000175953
---------------------------------------------------------------------------
Text: entertainment more disposable than hanna-barbera's half-hour cartoons ever were .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2364.77294921875
Total Time: 1.1640105000697076
---------------------------------------------------------------------------
Text: the film falls short on tension , eloquence , spiritual challenge -- things that have made the original new testament stories so compelling for 20 centuries .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.91259765625
Total Time: 1.1216714000329375
---------------------------------------------------------------------------
Text: by the end of it all i sort of loved the people onscreen , even though i could not stand them . perhaps the film should be seen as a conversation starter . it's not an easy one to review .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2369.21630859375
Total Time: 1.0963076999178156
---------------------------------------------------------------------------
Text: at best this is a film for the under-7 crowd . but it would be better to wait for the video . and a very rainy day .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2367.07666015625
Total Time: 1.139012800063938
---------------------------------------------------------------------------
Text: the whole talking-animal thing is grisly .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2363.78564453125
Total Time: 1.095451100030914
---------------------------------------------------------------------------
Text: never again , while nothing special , is pleasant , diverting and modest -- definitely a step in the right direction .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2365.92529296875
Total Time: 1.0963326999917626
---------------------------------------------------------------------------
Text: wouldn't it be funny if a bunch of allied soldiers went undercover as women in a german factory during world war ii ? um , no . but here's a movie about it anyway .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2368.22900390625
Total Time: 1.107625399949029
---------------------------------------------------------------------------
Text: has not so much been written as assembled , frankenstein-like , out of other , marginally better shoot-em-ups .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.08935546875
Total Time: 1.1167593999998644
---------------------------------------------------------------------------
Text: the punch lines that miss , unfortunately , outnumber the hits by three-to-one . but death to smoochy keeps firing until the bitter end .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.91259765625
Total Time: 1.1129382000071928
---------------------------------------------------------------------------
Text: mushes the college-friends genre ( the big chill ) together with the contrivances and overwrought emotion of soap operas .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1352.6015625
Max VRAM Usage: 2366.74755859375
Total Time: 1.1192900000605732
---------------------------------------------------------------------------
Text: showtime's starry cast could be both an asset and a detriment . those who trek to the 'plex predisposed to like it probably will enjoy themselves . but ticket-buyers with great expectations will wind up as glum as mr . de niro .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 180 || Output tokens: 1
Peak memory Usage: 1352.61328125
Max VRAM Usage: 2371.04052734375
Total Time: 1.1343796999426559
---------------------------------------------------------------------------
Text: a determined , ennui-hobbled slog that really doesn't have much to say beyond the news flash that loneliness can make people act weird .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1352.6171875
Max VRAM Usage: 2366.74755859375
Total Time: 1.11970540008042
---------------------------------------------------------------------------
Text: too daft by half . . . but supremely good natured .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1352.6171875
Max VRAM Usage: 2364.60888671875
Total Time: 1.1302255999762565
---------------------------------------------------------------------------
Text: fails in making this character understandable , in getting under her skin , in exploring motivation . . . well before the end , the film grows as dull as its characters , about whose fate it is hard to care .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1352.62109375
Max VRAM Usage: 2369.05126953125
Total Time: 1.1172498000087216
---------------------------------------------------------------------------
Text: it's a shame that the storyline and its underlying themes . . . finally seem so impersonal or even shallow .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1352.62109375
Max VRAM Usage: 2365.92529296875
Total Time: 1.1031795999733731
---------------------------------------------------------------------------
Text: woody , what happened ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none
Response: none
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1352.62109375
Max VRAM Usage: 2363.12744140625
Total Time: 1.1826950999675319
---------------------------------------------------------------------------
Text: juliette binoche's sand is vivacious , but it's hard to sense that powerhouse of 19th-century prose behind her childlike smile .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1352.62109375
Max VRAM Usage: 2367.40576171875
Total Time: 1.1346041000215337
---------------------------------------------------------------------------
Text: it's supposed to be post-feminist breezy but ends up as tedious as the chatter of parrots raised on oprah .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1352.62109375
Max VRAM Usage: 2366.58349609375
Total Time: 1.1200388999423012
---------------------------------------------------------------------------
Text: you can tell almost immediately that welcome to collinwood isn't going to jell .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1352.62890625
Max VRAM Usage: 2365.10205078125
Total Time: 1.1190053999889642
---------------------------------------------------------------------------
Text: throughout all the tumult , a question comes to mind : so why is this so boring ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2365.10205078125
Total Time: 1.1210893999086693
---------------------------------------------------------------------------
Text: cattaneo reworks the formula that made the full monty a smashing success . . . but neglects to add the magic that made it all work .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2367.57080078125
Total Time: 1.099949499941431
---------------------------------------------------------------------------
Text: routine and rather silly .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2362.96337890625
Total Time: 1.1345721000107005
---------------------------------------------------------------------------
Text: a rip-off twice removed , modeled after [seagal's] earlier copycat under siege , sometimes referred to as die hard on a boat .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2366.91259765625
Total Time: 1.101457200013101
---------------------------------------------------------------------------
Text: totally overwrought , deeply biased , and wholly designed to make you feel guilty about ignoring what the filmmakers clearly believe are the greatest musicians of all time .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2367.24169921875
Total Time: 1.118569300044328
---------------------------------------------------------------------------
Text: you can practically hear george orwell turning over .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2363.95068359375
Total Time: 1.1368588999612257
---------------------------------------------------------------------------
Text: behan's memoir is great material for a film -- rowdy , brawny and lyrical in the best irish sense -- but sheridan has settled for a lugubrious romance .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2368.55810546875
Total Time: 1.0970456999493763
---------------------------------------------------------------------------
Text: while holm is terrific as both men and hjejle quite appealing , the film fails to make the most out of the intriguing premise .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2366.74755859375
Total Time: 1.136419599992223
---------------------------------------------------------------------------
Text: lazy filmmaking , with the director taking a hands-off approach when he should have shaped the story to show us why it's compelling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1352.6328125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1226532999426126
---------------------------------------------------------------------------
Text: if it were any more of a turkey , it would gobble in dolby digital stereo . if nothing else , " rollerball " 2002 may go down in cinema history as the only movie ever in which the rest of the cast was outshined by ll cool j .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 185 || Output tokens: 1
Peak memory Usage: 1352.64453125
Max VRAM Usage: 2371.66845703125
Total Time: 1.1293632000451908
---------------------------------------------------------------------------
Text: a movie that falls victim to frazzled wackiness and frayed satire .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1352.6484375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1046432999428362
---------------------------------------------------------------------------
Text: how do you make a movie with depth about a man who lacked any ? on the evidence before us , the answer is clear : not easily and , in the end , not well enough .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1352.6484375
Max VRAM Usage: 2368.39306640625
Total Time: 1.1129810999846086
---------------------------------------------------------------------------
Text: the film's trailer also looked like crap , so crap is what i was expecting .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.51953125
Max VRAM Usage: 2364.93798828125
Total Time: 1.146579800057225
---------------------------------------------------------------------------
Text: more trifle than triumph .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1271.51953125
Max VRAM Usage: 2363.12744140625
Total Time: 1.1284455000422895
---------------------------------------------------------------------------
Text: the movie is almost completely lacking in suspense , surprise and consistent emotional conviction .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1271.51953125
Max VRAM Usage: 2364.60888671875
Total Time: 1.0978160999948159
---------------------------------------------------------------------------
Text: festers in just such a dungpile that you'd swear you were watching monkeys flinging their feces at you .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1036736000096425
---------------------------------------------------------------------------
Text: lyne's latest , the erotic thriller unfaithful , further demonstrates just how far his storytelling skills have eroded .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1046507999999449
---------------------------------------------------------------------------
Text: it sounds like another clever if pointless excursion into the abyss , and that's more or less how it plays out .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2365.92529296875
Total Time: 1.1224135999800637
---------------------------------------------------------------------------
Text: rumor , a muddled drama about coming to terms with death , feels impersonal , almost generic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1335305999964476
---------------------------------------------------------------------------
Text: report card : doesn't live up to the exalted tagline - there's definite room for improvement . doesn't deserve a passing grade ( even on a curve ) .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2367.73486328125
Total Time: 1.1262125000357628
---------------------------------------------------------------------------
Text: the pacing is deadly , the narration helps little and naipaul , a juicy writer , is negated .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2365.76025390625
Total Time: 1.1140407999046147
---------------------------------------------------------------------------
Text: as his circle of friends keeps getting smaller one of the characters in long time dead says 'i'm telling you , this is f * * * ed' . maybe he was reading the minds of the audience .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2369.05126953125
Total Time: 1.12017630005721
---------------------------------------------------------------------------
Text: . . . if it had been only half-an-hour long or a tv special , the humor would have been fast and furious-- at ninety minutes , it drags .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2367.73486328125
Total Time: 1.1149245999986306
---------------------------------------------------------------------------
Text: bean drops the ball too many times . . . hoping the nifty premise will create enough interest to make up for an unfocused screenplay .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2366.74755859375
Total Time: 1.1089499000227079
---------------------------------------------------------------------------
Text: a well-acted , but one-note film .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2363.78564453125
Total Time: 1.1725942000048235
---------------------------------------------------------------------------
Text: blood work is laughable in the solemnity with which it tries to pump life into overworked elements from eastwood's dirty harry period .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2366.91259765625
Total Time: 1.1302621000213549
---------------------------------------------------------------------------
Text: the movie is too amateurishly square to make the most of its own ironic implications .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1406345000723377
---------------------------------------------------------------------------
Text: [lee] treats his audience the same way that jim brown treats his women -- as dumb , credulous , unassuming , subordinate subjects . and lee seems just as expectant of an adoring , wide-smiling reception .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2369.54541015625
Total Time: 1.1139653000282124
---------------------------------------------------------------------------
Text: there's not one decent performance from the cast and not one clever line of dialogue .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2364.93798828125
Total Time: 1.122001799987629
---------------------------------------------------------------------------
Text: one of the worst movies of the year . . . . watching it was painful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1027854999992996
---------------------------------------------------------------------------
Text: a era do gelo diverte , mas não convence . É um passatempo descompromissado  e só .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2366.74755859375
Total Time: 1.1089002001099288
---------------------------------------------------------------------------
Text: no amount of burning , blasting , stabbing , and shooting can hide a weak script .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1124411999480799
---------------------------------------------------------------------------
Text: it's an odd show , pregnant with moods , stillborn except as a harsh conceptual exercise .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1760766999796033
---------------------------------------------------------------------------
Text: nearly all the fundamentals you take for granted in most films are mishandled here .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1740515000419691
---------------------------------------------------------------------------
Text: the armenian genocide deserves a more engaged and honest treatment .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1271.5234375
Max VRAM Usage: 2364.27978515625
Total Time: 1.1678503999719396
---------------------------------------------------------------------------
Text: earnest yet curiously tepid and choppy recycling in which predictability is the only winner .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.52734375
Max VRAM Usage: 2365.26708984375
Total Time: 1.0978497000178322
---------------------------------------------------------------------------
Text: ultimately this is a frustrating patchwork : an uneasy marriage of louis begley's source novel ( about schmidt ) and an old payne screenplay .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1271.5859375
Max VRAM Usage: 2367.07666015625
Total Time: 1.1186620999360457
---------------------------------------------------------------------------
Text: the exploitative , clumsily staged violence overshadows everything , including most of the actors .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.59765625
Max VRAM Usage: 2365.10205078125
Total Time: 1.1429752999683842
---------------------------------------------------------------------------
Text: we started to wonder if  some unpaid intern had just typed 'chris rock , ' 'anthony hopkins' and 'terrorists' into some univac-like script machine .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2368.55810546875
Total Time: 1.1005311999469995
---------------------------------------------------------------------------
Text: even when crush departs from the 4w formula . . . it feels like a glossy rehash .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2365.76025390625
Total Time: 1.1039416999556124
---------------------------------------------------------------------------
Text: more likely to have you scratching your head than hiding under your seat .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2364.44384765625
Total Time: 1.1267569999909028
---------------------------------------------------------------------------
Text: bears is even worse than i imagined a movie ever could be .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2364.27978515625
Total Time: 1.1204051000531763
---------------------------------------------------------------------------
Text: when you find yourself rooting for the monsters in a horror movie , you know the picture is in trouble .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2365.59619140625
Total Time: 1.1258024000562727
---------------------------------------------------------------------------
Text: this is very much of a mixed bag , with enough negatives to outweigh the positives .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1043111999752
---------------------------------------------------------------------------
Text: marinated in clichés and mawkish dialogue .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1271.734375
Max VRAM Usage: 2363.95068359375
Total Time: 1.114476399961859
---------------------------------------------------------------------------
Text: whether it's the worst movie of 2002 , i can't say for sure : memories of rollerball have faded , and i skipped country bears . but this new jangle of noise , mayhem and stupidity must be a serious contender for the title .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 180 || Output tokens: 1
Peak memory Usage: 1271.7421875
Max VRAM Usage: 2371.04052734375
Total Time: 1.0968403000151739
---------------------------------------------------------------------------
Text: [a] boldly stroked , luridly coloured , uni-dimensional nonsense machine that strokes the eyeballs while it evaporates like so much crypt mist in the brain .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1271.74609375
Max VRAM Usage: 2367.73486328125
Total Time: 1.118966200039722
---------------------------------------------------------------------------
Text: not once in the rush to save the day did i become very involved in the proceedings ; to me , it was just a matter of 'eh . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.75
Max VRAM Usage: 2367.24169921875
Total Time: 1.140655199997127
---------------------------------------------------------------------------
Text: rollerball is as bad as you think , and worse than you can imagine .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1271.75
Max VRAM Usage: 2364.77294921875
Total Time: 1.1150370999239385
---------------------------------------------------------------------------
Text: the first question to ask about bad company is why anthony hopkins is in it . we assume he had a bad run in the market or a costly divorce , because there is no earthly reason other than money why this distinguished actor would stoop so low .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 180 || Output tokens: 1
Peak memory Usage: 1271.75390625
Max VRAM Usage: 2371.04052734375
Total Time: 1.1038680999772623
---------------------------------------------------------------------------
Text: not exaggerated enough to be a parody of gross-out flicks , college flicks , or even flicks in general . it merely indulges in the worst elements of all of them .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1271.7578125
Max VRAM Usage: 2368.22900390625
Total Time: 1.1411537999520078
---------------------------------------------------------------------------
Text: shame on writer/director vicente aranda for making a florid biopic about mad queens , obsessive relationships , and rampant adultery so dull .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1271.7578125
Max VRAM Usage: 2366.91259765625
Total Time: 1.1200650000246242
---------------------------------------------------------------------------
Text: suffers from a decided lack of creative storytelling .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1271.7578125
Max VRAM Usage: 2363.62158203125
Total Time: 1.1658313000807539
---------------------------------------------------------------------------
Text: violent , vulgar and forgettably entertaining .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1271.7578125
Max VRAM Usage: 2363.62158203125
Total Time: 1.1547808999894187
---------------------------------------------------------------------------
Text: nothing happens , and it happens to flat characters .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1271.7578125
Max VRAM Usage: 2363.78564453125
Total Time: 1.1233101999387145
---------------------------------------------------------------------------
Text: with a completely predictable plot , you'll swear that you've seen it all before , even if you've never come within a mile of the longest yard .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.7578125
Max VRAM Usage: 2367.24169921875
Total Time: 1.1405569999478757
---------------------------------------------------------------------------
Text: remember back when thrillers actually thrilled ? when the twist endings were actually surprising ? when the violence actually shocked ? when the heroes were actually under 40 ? sadly , as blood work proves , that was a long , long time ago .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 175 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2369.87451171875
Total Time: 1.142785899923183
---------------------------------------------------------------------------
Text: blue crush has all the trappings of an energetic , extreme-sports adventure , but ends up more of a creaky " pretty woman " retread , with the emphasis on self-empowering schmaltz and big-wave surfing that gives pic its title an afterthought .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 185 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2371.66845703125
Total Time: 1.1091240000678226
---------------------------------------------------------------------------
Text: this movie plays like an extended dialogue exercise in retard 101 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2364.27978515625
Total Time: 1.1539359000744298
---------------------------------------------------------------------------
Text: what we get in feardotcom is more like something from a bad clive barker movie . in other words , it's badder than bad .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2367.40576171875
Total Time: 1.1679919000016525
---------------------------------------------------------------------------
Text: if they broke out into elaborate choreography , singing and finger snapping it might have held my attention , but as it stands i kept looking for the last exit from brooklyn .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2367.89990234375
Total Time: 1.1576478000497445
---------------------------------------------------------------------------
Text: a sloppy slapstick throwback to long gone bottom-of-the-bill fare like the ghost and mr . chicken .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2365.92529296875
Total Time: 1.127331200055778
---------------------------------------------------------------------------
Text: a small independent film suffering from a severe case of hollywood-itis .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2364.60888671875
Total Time: 1.1625587999587879
---------------------------------------------------------------------------
Text: where the film falters is in its tone .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2363.95068359375
Total Time: 1.1477680000243708
---------------------------------------------------------------------------
Text: the story alone could force you to scratch a hole in your head .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2364.44384765625
Total Time: 1.1718668000539765
---------------------------------------------------------------------------
Text: ultimately , sarah's dedication to finding her husband seems more psychotic than romantic , and nothing in the movie makes a convincing case that one woman's broken heart outweighs all the loss we witness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2368.55810546875
Total Time: 1.126038599992171
---------------------------------------------------------------------------
Text: it's supposed to be a humorous , all-too-human look at how hope can breed a certain kind of madness -- and strength -- but it never quite adds up .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2367.57080078125
Total Time: 1.1369987999787554
---------------------------------------------------------------------------
Text: feels more like a rejected x-files episode than a credible account of a puzzling real-life happening .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2365.43115234375
Total Time: 1.1346145999850705
---------------------------------------------------------------------------
Text: some motion pictures portray ultimate passion ; others create ultimate thrills . men in black ii achieves ultimate insignificance -- it's the sci-fi comedy spectacle as whiffle-ball epic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2368.06396484375
Total Time: 1.1313532999483868
---------------------------------------------------------------------------
Text: an enigmatic film that's too clever for its own good , it's a conundrum not worth solving .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2365.92529296875
Total Time: 1.1120170000940561
---------------------------------------------------------------------------
Text: a zombie movie in every sense of the word--mindless , lifeless , meandering , loud , painful , obnoxious .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2366.41845703125
Total Time: 1.1493143000407144
---------------------------------------------------------------------------
Text: rashomon-for-dipsticks tale .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2363.45654296875
Total Time: 1.1233402999350801
---------------------------------------------------------------------------
Text: a film that clearly means to preach exclusively to the converted .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1271.76171875
Max VRAM Usage: 2364.11474609375
Total Time: 1.1324720000848174
---------------------------------------------------------------------------
Text: it doesn't take a rocket scientist to figure out that this is a mormon family movie , and a sappy , preachy one at that .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2367.24169921875
Total Time: 1.1269885000074282
---------------------------------------------------------------------------
Text: definitely a crowd-pleaser , but then , so was the roman colosseum .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2365.26708984375
Total Time: 1.126176799996756
---------------------------------------------------------------------------
Text: certainly not a good movie , but it wasn't horrible either .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2364.27978515625
Total Time: 1.1532878000289202
---------------------------------------------------------------------------
Text: although it starts off so bad that you feel like running out screaming , it eventually works its way up to merely bad rather than painfully awful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2366.74755859375
Total Time: 1.1163226999342442
---------------------------------------------------------------------------
Text: the result is so tame that even slightly wised-up kids would quickly change the channel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2365.10205078125
Total Time: 1.1430216999724507
---------------------------------------------------------------------------
Text: it appears to have been modeled on the worst revenge-of-the-nerds clichés the filmmakers could dredge up .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2366.08935546875
Total Time: 1.0985172000946477
---------------------------------------------------------------------------
Text: nothing but an episode of smackdown ! in period costume and with a bigger budget .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2364.93798828125
Total Time: 1.1360094000119716
---------------------------------------------------------------------------
Text: it takes you somewhere you're not likely to have seen before , but beneath the exotic surface ( and exotic dancing ) it's surprisingly old-fashioned .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1271.76953125
Max VRAM Usage: 2366.91259765625
Total Time: 1.1354300000239164
---------------------------------------------------------------------------
Text: while the story is better-focused than the incomprehensible anne rice novel it's based upon , queen of the damned is a pointless , meandering celebration of the goth-vampire , tortured woe-is-me lifestyle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1271.78125
Max VRAM Usage: 2369.38037109375
Total Time: 1.1440681000240147
---------------------------------------------------------------------------
Text: it should be interesting , it should be poignant , it turns out to be affected and boring .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.78125
Max VRAM Usage: 2365.26708984375
Total Time: 1.1324764000019059
---------------------------------------------------------------------------
Text: a good-looking but ultimately pointless political thriller with plenty of action and almost no substance .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.78125
Max VRAM Usage: 2364.93798828125
Total Time: 1.1069552999688312
---------------------------------------------------------------------------
Text: a tired , predictable , bordering on offensive , waste of time , money and celluloid .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.78125
Max VRAM Usage: 2365.26708984375
Total Time: 1.222578400047496
---------------------------------------------------------------------------
Text: if hill isn't quite his generation's don siegel ( or robert aldrich ) , it's because there's no discernible feeling beneath the chest hair ; it's all bluster and cliché .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1271.7890625
Max VRAM Usage: 2369.05126953125
Total Time: 1.2134723999770358
---------------------------------------------------------------------------
Text: stealing harvard will dip into your wallet , swipe 90 minutes of your time , and offer you precisely this in recompense : a few early laughs scattered around a plot as thin as it is repetitious .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2369.21630859375
Total Time: 1.2166762000415474
---------------------------------------------------------------------------
Text: this is an insultingly inept and artificial examination of grief and its impacts upon the relationships of the survivors .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1889758000615984
---------------------------------------------------------------------------
Text: does anyone much think the central story of brendan behan is that he was a bisexual sweetheart before he took to drink ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2366.41845703125
Total Time: 1.1425944999791682
---------------------------------------------------------------------------
Text: `martin lawrence live' is so self-pitying , i almost expected there to be a collection taken for the comedian at the end of the show .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2367.57080078125
Total Time: 1.1281381000299007
---------------------------------------------------------------------------
Text: the dialogue is cumbersome , the simpering soundtrack and editing more so .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2364.44384765625
Total Time: 1.1382807999616489
---------------------------------------------------------------------------
Text: never decides whether it wants to be a black comedy , drama , melodrama or some combination of the three .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2365.76025390625
Total Time: 1.1216002000728622
---------------------------------------------------------------------------
Text: it has become apparent that the franchise's best years are long past .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2364.44384765625
Total Time: 1.163573500001803
---------------------------------------------------------------------------
Text: does what should seem impossible : it makes serial killer jeffrey dahmer boring .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2364.93798828125
Total Time: 1.1552292000269517
---------------------------------------------------------------------------
Text: don't hate el crimen del padre amaro because it's anti-catholic . hate it because it's lousy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1271.79296875
Max VRAM Usage: 2366.25439453125
Total Time: 1.138730000006035
---------------------------------------------------------------------------
Text: . . . better described as a ghost story gone badly awry .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.796875
Max VRAM Usage: 2364.44384765625
Total Time: 1.1562018999829888
---------------------------------------------------------------------------
Text: like a bad improvisation exercise , the superficially written characters ramble on tediously about their lives , loves and the art they're struggling to create .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2367.24169921875
Total Time: 1.1307283999631181
---------------------------------------------------------------------------
Text: the filmmakers are playing to the big boys in new york and l . a . to that end , they mock the kind of folks they don't understand , ones they figure the power-lunchers don't care to understand , either .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 175 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2369.87451171875
Total Time: 1.1448449000017717
---------------------------------------------------------------------------
Text: competently directed but terminally cute drama .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2363.62158203125
Total Time: 1.1342020999873057
---------------------------------------------------------------------------
Text: the big finish is a bit like getting all excited about a chocolate eclair and then biting into it and finding the filling missing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2366.41845703125
Total Time: 1.1478834999725223
---------------------------------------------------------------------------
Text: not just unlikable . disturbing . disgusting . without any redeeming value whatsoever .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2364.93798828125
Total Time: 1.1229286999441683
---------------------------------------------------------------------------
Text: this thing is virtually unwatchable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2363.45654296875
Total Time: 1.1276943000266328
---------------------------------------------------------------------------
Text: those eternally devoted to the insanity of black will have an intermittently good time . feel free to go get popcorn whenever he's not onscreen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2367.24169921875
Total Time: 1.1212012000614777
---------------------------------------------------------------------------
Text: the self-serious equilibrium makes its point too well ; a movie , like life , isn't much fun without the highs and lows .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1362307000672445
---------------------------------------------------------------------------
Text: the work of an exhausted , desiccated talent who can't get out of his own way .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2365.43115234375
Total Time: 1.1633753998903558
---------------------------------------------------------------------------
Text: the main characters are simply named the husband , the wife and the kidnapper , emphasizing the disappointingly generic nature of the entire effort .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1271.80078125
Max VRAM Usage: 2366.58349609375
Total Time: 1.140350200003013
---------------------------------------------------------------------------
Text: in terms of execution this movie is careless and unfocused .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1271.8046875
Max VRAM Usage: 2364.11474609375
Total Time: 1.160443599917926
---------------------------------------------------------------------------
Text: swims in mediocrity , sticking its head up for a breath of fresh air now and then .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.8046875
Max VRAM Usage: 2365.43115234375
Total Time: 1.1278564999811351
---------------------------------------------------------------------------
Text: the only type of lives this glossy comedy-drama resembles are ones in formulaic mainstream movies .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.8046875
Max VRAM Usage: 2365.26708984375
Total Time: 1.1544103999622166
---------------------------------------------------------------------------
Text: the characters . . . are paper-thin , and their personalities undergo radical changes when it suits the script .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.76025390625
Total Time: 1.194970199954696
---------------------------------------------------------------------------
Text: a sha-na-na sketch punctuated with graphic violence .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2363.95068359375
Total Time: 1.2631881000706926
---------------------------------------------------------------------------
Text: the trouble is , its filmmakers run out of clever ideas and visual gags about halfway through .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.26708984375
Total Time: 1.1299007999477908
---------------------------------------------------------------------------
Text: spy-vs . -spy action flick with antonio banderas and lucy liu never comes together .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.59619140625
Total Time: 1.110985599923879
---------------------------------------------------------------------------
Text: a so-so , made-for-tv something posing as a real movie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2364.60888671875
Total Time: 1.130777099984698
---------------------------------------------------------------------------
Text: the only upside to all of this unpleasantness is , given its labor day weekend upload , feardotcom should log a minimal number of hits .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2367.07666015625
Total Time: 1.1212388999992982
---------------------------------------------------------------------------
Text: whether this is art imitating life or life imitating art , it's an unhappy situation all around .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.59619140625
Total Time: 1.1480482999468222
---------------------------------------------------------------------------
Text: an uneasy mix of run-of-the-mill raunchy humor and seemingly sincere personal reflection .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.26708984375
Total Time: 1.1245484999381006
---------------------------------------------------------------------------
Text: a formula family tearjerker told with a heavy irish brogue . . . accentuating , rather than muting , the plot's saccharine thrust .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2367.57080078125
Total Time: 1.091148899984546
---------------------------------------------------------------------------
Text: this is sandler running on empty , repeating what he's already done way too often .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.10205078125
Total Time: 1.1265519999433309
---------------------------------------------------------------------------
Text: this is as lax and limp a comedy as i've seen in a while , a meander through worn-out material .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1230891000013798
---------------------------------------------------------------------------
Text: time literally stops on a dime in the tries-so-hard-to-be-cool " clockstoppers , " but that doesn't mean it still won't feel like the longest 90 minutes of your movie-going life .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2369.21630859375
Total Time: 1.1420557000674307
---------------------------------------------------------------------------
Text: the sort of picture in which , whenever one of the characters has some serious soul searching to do , they go to a picture-perfect beach during sunset .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2367.24169921875
Total Time: 1.1315333999227732
---------------------------------------------------------------------------
Text: aptly named , this shimmering , beautifully costumed and filmed production doesn't work for me .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.80859375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1177032999694347
---------------------------------------------------------------------------
Text: a preposterously melodramatic paean to gang-member teens in brooklyn circa 1958 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.8125
Max VRAM Usage: 2365.59619140625
Total Time: 1.181448100018315
---------------------------------------------------------------------------
Text: has none of the crackle of " fatal attraction " , " 9 ½ weeks " , or even " indecent proposal " , and feels more like lyne's stolid remake of " lolita " .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1271.81640625
Max VRAM Usage: 2369.38037109375
Total Time: 1.1456075999885798
---------------------------------------------------------------------------
Text: everything its title implies , a standard-issue crime drama spat out from the tinseltown assembly line .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.8203125
Max VRAM Usage: 2365.59619140625
Total Time: 1.11534500005655
---------------------------------------------------------------------------
Text: an extraordinarily silly thriller .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1271.8203125
Max VRAM Usage: 2362.96337890625
Total Time: 1.1411205000476912
---------------------------------------------------------------------------
Text: a rehash of every gangster movie from the past decade .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1271.82421875
Max VRAM Usage: 2364.27978515625
Total Time: 1.1231743999524042
---------------------------------------------------------------------------
Text: gaping plot holes sink this 'sub'-standard thriller and drag audience enthusiasm to crush depth .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.82421875
Max VRAM Usage: 2365.10205078125
Total Time: 1.1100154999876395
---------------------------------------------------------------------------
Text: talkiness isn't necessarily bad , but the dialogue frequently misses the mark .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1271.82421875
Max VRAM Usage: 2364.60888671875
Total Time: 1.1407934000017121
---------------------------------------------------------------------------
Text: the beautiful images and solemn words cannot disguise the slack complacency of [godard's] vision , any more than the gorgeous piano and strings on the soundtrack can drown out the tinny self-righteousness of his voice .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1271.83203125
Max VRAM Usage: 2369.54541015625
Total Time: 1.1343120000092313
---------------------------------------------------------------------------
Text: the stunt work is top-notch ; the dialogue and drama often food-spittingly funny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.83203125
Max VRAM Usage: 2365.10205078125
Total Time: 1.1240352999884635
---------------------------------------------------------------------------
Text: the movie isn't painfully bad , something to be 'fully experienced' ; it's just tediously bad , something to be fully forgotten .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.83203125
Max VRAM Usage: 2366.74755859375
Total Time: 1.1571336999768391
---------------------------------------------------------------------------
Text: charly comes off as emotionally manipulative and sadly imitative of innumerable past love story derisions .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.83203125
Max VRAM Usage: 2365.76025390625
Total Time: 1.1440790999913588
---------------------------------------------------------------------------
Text: what a great shame that such a talented director as chen kaige has chosen to make his english-language debut with a film so poorly plotted and scripted .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.83203125
Max VRAM Usage: 2367.24169921875
Total Time: 1.1259087999351323
---------------------------------------------------------------------------
Text: no amount of good intentions is able to overcome the triviality of the story .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1271.83203125
Max VRAM Usage: 2364.77294921875
Total Time: 1.102318900055252
---------------------------------------------------------------------------
Text: the film . . . presents classic moral-condundrum drama : what would you have done to survive ? the problem with the film is whether these ambitions , laudable in themselves , justify a theatrical simulation of the death camp of auschwitz ii-birkenau .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 183 || Output tokens: 1
Peak memory Usage: 1271.859375
Max VRAM Usage: 2371.41748046875
Total Time: 1.1289533999515697
---------------------------------------------------------------------------
Text: . . . for all its social and political potential , state property doesn't end up being very inspiring or insightful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.859375
Max VRAM Usage: 2365.92529296875
Total Time: 1.1620269999839365
---------------------------------------------------------------------------
Text: a film really has to be exceptional to justify a three hour running time , and this isn't .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1271.859375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1450574999907985
---------------------------------------------------------------------------
Text: little more than a stylish exercise in revisionism whose point . . . is no doubt true , but serves as a rather thin moral to such a knowing fable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1271.859375
Max VRAM Usage: 2367.57080078125
Total Time: 1.1179702000226825
---------------------------------------------------------------------------
Text: the nonstop artifice ultimately proves tiresome , with the surface histrionics failing to compensate for the paper-thin characterizations and facile situations .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.86328125
Max VRAM Usage: 2367.24169921875
Total Time: 1.1823637000052258
---------------------------------------------------------------------------
Text: this is a monumental achievement in practically every facet of inept filmmaking : joyless , idiotic , annoying , heavy-handed , visually atrocious , and often downright creepy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2367.89990234375
Total Time: 1.1198811000213027
---------------------------------------------------------------------------
Text: this off-putting french romantic comedy is sure to test severely the indulgence of fans of amélie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2365.92529296875
Total Time: 1.1529916001018137
---------------------------------------------------------------------------
Text: overburdened with complicated plotting and banal dialogue

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2363.95068359375
Total Time: 1.1301340000936761
---------------------------------------------------------------------------
Text: ensemble movies , like soap operas , depend on empathy . if there ain't none , you have a problem .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2365.92529296875
Total Time: 1.1733341000508517
---------------------------------------------------------------------------
Text: the master of disguise falls under the category of 'should have been a sketch on saturday night live . '

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2365.76025390625
Total Time: 1.1421042000874877
---------------------------------------------------------------------------
Text: yet another self-consciously overwritten story about a rag-tag bunch of would-be characters that team up for a can't-miss heist -- only to have it all go wrong .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2368.06396484375
Total Time: 1.1826037999708205
---------------------------------------------------------------------------
Text: koepp's screenplay isn't nearly surprising or clever enough to sustain a reasonable degree of suspense on its own .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2365.92529296875
Total Time: 1.2499752000439912
---------------------------------------------------------------------------
Text: is it really an advantage to invest such subtlety and warmth in an animatronic bear when the humans are acting like puppets ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2366.74755859375
Total Time: 1.1785980000859126
---------------------------------------------------------------------------
Text: more successful at relating history than in creating an emotionally complex , dramatically satisfying heroine

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2364.60888671875
Total Time: 1.1416174999903888
---------------------------------------------------------------------------
Text: clumsy , obvious , preposterous , the movie will likely set the cause of woman warriors back decades .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2365.59619140625
Total Time: 1.145853399997577
---------------------------------------------------------------------------
Text: it's hard to pity the 'plain' girl who becomes a ravishing waif after applying a smear of lip-gloss . rather , pity anyone who sees this mishmash .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2368.22900390625
Total Time: 1.1250879999715835
---------------------------------------------------------------------------
Text: a banal , virulently unpleasant excuse for a romantic comedy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2364.44384765625
Total Time: 1.157772900070995
---------------------------------------------------------------------------
Text: the drama discloses almost nothing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2363.29248046875
Total Time: 1.1628717000130564
---------------------------------------------------------------------------
Text: a minor-league soccer remake of the longest yard .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2363.78564453125
Total Time: 1.1510207999963313
---------------------------------------------------------------------------
Text: belongs in the too-hot-for-tv direct-to-video/dvd category , and this is why i have given it a one-star rating .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2366.74755859375
Total Time: 1.118224099976942
---------------------------------------------------------------------------
Text: as earnest as a community-college advertisement , american chai is enough to make you put away the guitar , sell the amp , and apply to medical school .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2367.24169921875
Total Time: 1.1636768999742344
---------------------------------------------------------------------------
Text: a dim-witted and lazy spin-off of the animal planet documentary series , crocodile hunter is entertainment opportunism at its most glaring .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2366.58349609375
Total Time: 1.2161390000255778
---------------------------------------------------------------------------
Text: there is more than one joke about putting the toilet seat down . and that should tell you everything you need to know about all the queen's men .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2367.07666015625
Total Time: 1.2159345999825746
---------------------------------------------------------------------------
Text: even fans of ismail merchant's work , i suspect , would have a hard time sitting through this one .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2365.76025390625
Total Time: 1.1497846000129357
---------------------------------------------------------------------------
Text: it's really just another silly hollywood action film , one among a multitude of simple-minded , yahoo-ing death shows .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2366.08935546875
Total Time: 1.1405063999118283
---------------------------------------------------------------------------
Text: it's not a particularly good film , but neither is it a monsterous one .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2364.93798828125
Total Time: 1.1252248999662697
---------------------------------------------------------------------------
Text: the world needs more filmmakers with passionate enthusiasms like martin scorsese . but it doesn't need gangs of new york .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2366.41845703125
Total Time: 1.1219005000311881
---------------------------------------------------------------------------
Text: enchanted with low-life tragedy and liberally seasoned with emotional outbursts . . . what is sorely missing , however , is the edge of wild , lunatic invention that we associate with cage's best acting .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1271.91015625
Max VRAM Usage: 2369.21630859375
Total Time: 1.1145413999911398
---------------------------------------------------------------------------
Text: harry potter and the chamber of secrets is deja vu all over again , and while that is a cliche , nothing could be more appropriate . it's likely that whatever you thought of the first production -- pro or con -- you'll likely think of this one .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 182 || Output tokens: 1
Peak memory Usage: 1271.921875
Max VRAM Usage: 2371.29150390625
Total Time: 1.1463477000361308
---------------------------------------------------------------------------
Text: sade achieves the near-impossible : it turns the marquis de sade into a dullard .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.92578125
Max VRAM Usage: 2365.59619140625
Total Time: 1.1462337999837473
---------------------------------------------------------------------------
Text: [lin chung's] voice is rather unexceptional , even irritating ( at least to this western ear ) , making it awfully hard to buy the impetus for the complicated love triangle that develops between the three central characters .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 174 || Output tokens: 1
Peak memory Usage: 1271.9296875
Max VRAM Usage: 2369.70947265625
Total Time: 1.1583208999363706
---------------------------------------------------------------------------
Text: one of the most plain , unimaginative romantic comedies i've ever seen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1271.9296875
Max VRAM Usage: 2364.77294921875
Total Time: 1.1281899000750855
---------------------------------------------------------------------------
Text: though there's a clarity of purpose and even-handedness to the film's direction , the drama feels rigged and sluggish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.9296875
Max VRAM Usage: 2366.08935546875
Total Time: 1.1166639999719337
---------------------------------------------------------------------------
Text: unfortunately , the experience of actually watching the movie is less compelling than the circumstances of its making .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1271.94921875
Max VRAM Usage: 2365.26708984375
Total Time: 1.1638899999670684
---------------------------------------------------------------------------
Text: unless there are zoning ordinances to protect your community from the dullest science fiction , impostor is opening today at a theater near you .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.94921875
Max VRAM Usage: 2366.74755859375
Total Time: 1.142237599939108
---------------------------------------------------------------------------
Text: it should be doing a lot of things , but doesn't .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2364.27978515625
Total Time: 1.1280208000680432
---------------------------------------------------------------------------
Text: chen films the resolutely downbeat smokers only with every indulgent , indie trick in the book .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2365.59619140625
Total Time: 1.1129849000135437
---------------------------------------------------------------------------
Text: . . . a rather bland affair .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2363.45654296875
Total Time: 1.12030379998032
---------------------------------------------------------------------------
Text: far-fetched premise , convoluted plot , and thematic mumbo jumbo about destiny and redemptive love .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1146763999713585
---------------------------------------------------------------------------
Text: the movie tries to be ethereal , but ends up seeming goofy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2364.44384765625
Total Time: 1.1586155999684706
---------------------------------------------------------------------------
Text: i was hoping that it would be sleazy and fun , but it was neither .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1873784000054002
---------------------------------------------------------------------------
Text: harris is supposed to be the star of the story , but comes across as pretty dull and wooden .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.9609375
Max VRAM Usage: 2365.59619140625
Total Time: 1.1390471999766305
---------------------------------------------------------------------------
Text: soulless and -- even more damning -- virtually joyless , xxx achieves near virtuosity in its crapulence .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2365.92529296875
Total Time: 1.111721899942495
---------------------------------------------------------------------------
Text: a boring masquerade ball where normally good actors , even kingsley , are made to look bad .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2365.59619140625
Total Time: 1.2109214999945834
---------------------------------------------------------------------------
Text: all the queen's men is a throwback war movie that fails on so many levels , it should pay reparations to viewers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.41845703125
Total Time: 1.208815599908121
---------------------------------------------------------------------------
Text: the filmmakers keep pushing the jokes at the expense of character until things fall apart .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2364.77294921875
Total Time: 1.2452637000242248
---------------------------------------------------------------------------
Text: rather than real figures , elling and kjell bjarne become symbolic characters whose actions are supposed to relate something about the naïf's encounter with the world .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2367.57080078125
Total Time: 1.1564224000321701
---------------------------------------------------------------------------
Text: mariah carey gives us another peek at some of the magic we saw in glitter here in wisegirls .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.08935546875
Total Time: 1.122860400006175
---------------------------------------------------------------------------
Text: it's all arty and jazzy and people sit and stare and turn away from one another instead of talking and it's all about the silences and if you're into that , have at it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 169 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2368.88720703125
Total Time: 1.1249356999760494
---------------------------------------------------------------------------
Text: i suspect that you'll be as bored watching morvern callar as the characters are in it . if you go , pack your knitting needles .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.91259765625
Total Time: 1.1356060999678448
---------------------------------------------------------------------------
Text: the lead actors share no chemistry or engaging charisma . we don't even like their characters .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2365.10205078125
Total Time: 1.1856254000449553
---------------------------------------------------------------------------
Text: some writer dude , i think his name was , uh , michael zaidan , was supposed to have like written the screenplay or something , but , dude , the only thing that i ever saw that was written down were the zeroes on my paycheck .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 178 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2370.36767578125
Total Time: 1.1797719000605866
---------------------------------------------------------------------------
Text: the movie doesn't generate a lot of energy . it is dark , brooding and slow , and takes its central idea way too seriously .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.74755859375
Total Time: 1.158104700036347
---------------------------------------------------------------------------
Text: this feature is about as necessary as a hole in the head

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2364.11474609375
Total Time: 1.12763260002248
---------------------------------------------------------------------------
Text: the cinematic equivalent of patronizing a bar favored by pretentious , untalented artistes who enjoy moaning about their cruel fate .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.58349609375
Total Time: 1.1407551999436691
---------------------------------------------------------------------------
Text: spectators will indeed sit open-mouthed before the screen , not screaming but yawning .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1404324999311939
---------------------------------------------------------------------------
Text: it feels like very light errol morris , focusing on eccentricity but failing , ultimately , to make something bigger out of its scrapbook of oddballs .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2367.40576171875
Total Time: 1.2044705000007525
---------------------------------------------------------------------------
Text: a period story about a catholic boy who tries to help a jewish friend get into heaven by sending the audience straight to hell .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

none
Response: none
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.25439453125
Total Time: 1.1593435000395402
---------------------------------------------------------------------------
Text: the premise itself is just sooooo tired . pair that with really poor comedic writing . . . and you've got a huge mess .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2366.58349609375
Total Time: 1.1568851000629365
---------------------------------------------------------------------------
Text: proves a lovely trifle that , unfortunately , is a little too in love with its own cuteness .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 149 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2365.59619140625
Total Time: 1.1230084999697283
---------------------------------------------------------------------------
Text: did we really need a remake of " charade ? "

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2364.11474609375
Total Time: 1.2348653000080958
---------------------------------------------------------------------------
Text: some movies can get by without being funny simply by structuring the scenes as if they were jokes : a setup , delivery and payoff . stealing harvard can't even do that much . each scene immediately succumbs to gravity and plummets to earth .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 179 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2370.53271484375
Total Time: 1.1625231000361964
---------------------------------------------------------------------------
Text: the only fun part of the movie is playing the obvious game . you try to guess the order in which the kids in the house will be gored .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.96484375
Max VRAM Usage: 2367.24169921875
Total Time: 1.187721399939619
---------------------------------------------------------------------------
Text: i spied with my little eye . . . a mediocre collection of cookie-cutter action scenes and occasionally inspired dialogue bits

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.96875
Max VRAM Usage: 2366.08935546875
Total Time: 1.1846179000567645
---------------------------------------------------------------------------
Text: entertains not so much because of its music or comic antics , but through the perverse pleasure of watching disney scrape the bottom of its own cracker barrel .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1271.97265625
Max VRAM Usage: 2367.40576171875
Total Time: 1.1240815999917686
---------------------------------------------------------------------------
Text: the satire is just too easy to be genuinely satisfying .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1271.97265625
Max VRAM Usage: 2363.95068359375
Total Time: 1.1322755999863148
---------------------------------------------------------------------------
Text: bearable . barely .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1271.98046875
Max VRAM Usage: 2362.96337890625
Total Time: 1.1340126000577584
---------------------------------------------------------------------------
Text: less funny than it should be and less funny than it thinks it is .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 143 || Output tokens: 1
Peak memory Usage: 1271.98046875
Max VRAM Usage: 2364.60888671875
Total Time: 1.1515463000396267
---------------------------------------------------------------------------
Text: an " o bruin , where art thou ? " -style cross-country adventure . . . it has sporadic bursts of liveliness , some so-so slapstick and a few ear-pleasing songs on its soundtrack .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1271.984375
Max VRAM Usage: 2369.54541015625
Total Time: 1.13599650003016
---------------------------------------------------------------------------
Text: a feeble tootsie knockoff .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1271.984375
Max VRAM Usage: 2363.62158203125
Total Time: 1.1491481000557542
---------------------------------------------------------------------------
Text: an awful movie that will only satisfy the most emotionally malleable of filmgoers .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1271.984375
Max VRAM Usage: 2365.10205078125
Total Time: 1.2550191000336781
---------------------------------------------------------------------------
Text: the story is far-flung , illogical , and plain stupid .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1271.984375
Max VRAM Usage: 2364.44384765625
Total Time: 1.2301844999892637
---------------------------------------------------------------------------
Text: the very simple story seems too simple and the working out of the plot almost arbitrary .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1271.984375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1355212999042124
---------------------------------------------------------------------------
Text: an allegory concerning the chronically mixed signals african american professionals get about overachieving could be intriguing , but the supernatural trappings only obscure the message .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1271.984375
Max VRAM Usage: 2367.24169921875
Total Time: 1.1474028000375256
---------------------------------------------------------------------------
Text: a very familiar tale , one that's been told by countless filmmakers about italian- , chinese- , irish- , latin- , indian- , russian- and other hyphenate american young men struggling to balance conflicting cultural messages .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 175 || Output tokens: 1
Peak memory Usage: 1271.99609375
Max VRAM Usage: 2369.87451171875
Total Time: 1.1606858000159264
---------------------------------------------------------------------------
Text: one key problem with these ardently christian storylines is that there is never any question of how things will turn out .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1271.99609375
Max VRAM Usage: 2366.08935546875
Total Time: 1.1477182001108304
---------------------------------------------------------------------------
Text: essentially , the film is weak on detail and strong on personality

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1271.99609375
Max VRAM Usage: 2364.11474609375
Total Time: 1.155810899916105
---------------------------------------------------------------------------
Text: a relentless , bombastic and ultimately empty world war ii action flick .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2364.44384765625
Total Time: 1.1175279000308365
---------------------------------------------------------------------------
Text: [hell is] looking down at your watch and realizing serving sara isn't even halfway through .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2365.43115234375
Total Time: 1.144657799974084
---------------------------------------------------------------------------
Text: too long , and larded with exposition , this somber cop drama ultimately feels as flat as the scruffy sands of its titular community .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2366.74755859375
Total Time: 1.166137299966067
---------------------------------------------------------------------------
Text: leaves viewers out in the cold and undermines some phenomenal performances .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2364.11474609375
Total Time: 1.1527310999808833
---------------------------------------------------------------------------
Text: . . . a ho-hum affair , always watchable yet hardly memorable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2364.77294921875
Total Time: 1.1314632999710739
---------------------------------------------------------------------------
Text: swiftly deteriorates into a terribly obvious melodrama and rough-hewn vanity project for lead actress andie macdowell .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2366.08935546875
Total Time: 1.1485241000773385
---------------------------------------------------------------------------
Text: the histrionic muse still eludes madonna and , playing a charmless witch , she is merely a charmless witch .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1272.0
Max VRAM Usage: 2366.41845703125
Total Time: 1.159164599957876
---------------------------------------------------------------------------
Text: you have no affinity for most of the characters . nothing about them is attractive . what they see in each other also is difficult to fathom .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2366.91259765625
Total Time: 1.1182698999764398
---------------------------------------------------------------------------
Text: diaz , applegate , blair and posey are suitably kooky which should appeal to women and they strip down often enough to keep men alert , if not amused .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2368.06396484375
Total Time: 1.13739849999547
---------------------------------------------------------------------------
Text: a technically well-made suspenser . . . but its abrupt drop in iq points as it races to the finish line proves simply too discouraging to let slide .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2367.40576171875
Total Time: 1.1896182999480516
---------------------------------------------------------------------------
Text: an inept , tedious spoof of '70s kung fu pictures , it contains almost enough chuckles for a three-minute sketch , and no more .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2367.24169921875
Total Time: 1.1582968999864534
---------------------------------------------------------------------------
Text: it's a mystery how the movie could be released in this condition .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2364.44384765625
Total Time: 1.1527232000371441
---------------------------------------------------------------------------
Text: absolutely ( and unintentionally ) terrifying .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2363.45654296875
Total Time: 1.140856400015764
---------------------------------------------------------------------------
Text: eckstraordinarily lame and severely boring .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2363.78564453125
Total Time: 1.1800473000621423
---------------------------------------------------------------------------
Text: eight legged freaks falls flat as a spoof .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2363.95068359375
Total Time: 1.1705805000383407
---------------------------------------------------------------------------
Text: no matter how much he runs around and acts like a doofus , accepting a 50-year-old in the role is creepy in a michael jackson sort of way .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2367.89990234375
Total Time: 1.1518180000130087
---------------------------------------------------------------------------
Text: you'll just have your head in your hands wondering why lee's character didn't just go to a bank manager and save everyone the misery .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1272.00390625
Max VRAM Usage: 2366.74755859375
Total Time: 1.1326261999784037
---------------------------------------------------------------------------
Text: 'dragonfly' dwells on crossing-over mumbo jumbo , manipulative sentimentality , and sappy dialogue .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2366.08935546875
Total Time: 1.151000100071542
---------------------------------------------------------------------------
Text: in his determination to lighten the heavy subject matter , silberling also , to a certain extent , trivializes the movie with too many nervous gags and pratfalls .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 162 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2367.73486328125
Total Time: 1.1473525000037625
---------------------------------------------------------------------------
Text: blade ii has a brilliant director and charismatic star , but it suffers from rampant vampire devaluation .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2365.26708984375
Total Time: 1.120427199988626
---------------------------------------------------------------------------
Text: veers uncomfortably close to pro-serb propaganda .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2363.95068359375
Total Time: 1.1316293999552727
---------------------------------------------------------------------------
Text: staggeringly dreadful romance .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2362.96337890625
Total Time: 1.1812990000471473
---------------------------------------------------------------------------
Text: movies like high crimes flog the dead horse of surprise as if it were an obligation . how about surprising us by trying something new ?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2366.58349609375
Total Time: 1.1165230999467894
---------------------------------------------------------------------------
Text: final verdict : you've seen it all before .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2363.78564453125
Total Time: 1.1371809999691322
---------------------------------------------------------------------------
Text: throwing in everything except someone pulling the pin from a grenade with his teeth , windtalkers seems to have ransacked every old world war ii movie for overly familiar material .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2367.89990234375
Total Time: 1.1082171999150887
---------------------------------------------------------------------------
Text: if a few good men told us that we " can't handle the truth " than high crimes poetically states at one point in this movie that we " don't care about the truth . "

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 167 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2368.55810546875
Total Time: 1.1378729999996722
---------------------------------------------------------------------------
Text: further sad evidence that tom tykwer , director of the resonant and sense-spinning run lola run , has turned out to be a one-trick pony -- a maker of softheaded metaphysical claptrap .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2369.54541015625
Total Time: 1.1368104999419302
---------------------------------------------------------------------------
Text: you'll trudge out of the theater feeling as though you rode the zipper after eating a corn dog and an extra-large cotton candy .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2366.58349609375
Total Time: 1.1531462999992073
---------------------------------------------------------------------------
Text: the movie is a little tired ; maybe the original inspiration has run its course .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2364.77294921875
Total Time: 1.1083828000118956
---------------------------------------------------------------------------
Text: this will go on so long as there are moviegoers anxious to see strange young guys doing strange guy things .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2365.92529296875
Total Time: 1.129673899966292
---------------------------------------------------------------------------
Text: a full-frontal attack on audience patience .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2363.62158203125
Total Time: 1.1996768999379128
---------------------------------------------------------------------------
Text: any intellectual arguments being made about the nature of god are framed in a drama so clumsy , there is a real danger less sophisticated audiences will mistake it for an endorsement of the very things that bean abhors .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2369.05126953125
Total Time: 1.1630767000606284
---------------------------------------------------------------------------
Text: it's a big idea , but the film itself is small and shriveled .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2364.93798828125
Total Time: 1.1500188999343663
---------------------------------------------------------------------------
Text: debut effort by " project greenlight " winner is sappy and amateurish .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2364.77294921875
Total Time: 1.138254800112918
---------------------------------------------------------------------------
Text: one gets the impression the creators of don't ask don't tell laughed a hell of a lot at their own jokes . too bad none of it is funny .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2367.40576171875
Total Time: 1.1207516000140458
---------------------------------------------------------------------------
Text: the cast has a high time , but de broca has little enthusiasm for such antique pulp .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 147 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2365.26708984375
Total Time: 1.1749889999628067
---------------------------------------------------------------------------
Text: the film , like jimmy's routines , could use a few good laughs .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2364.77294921875
Total Time: 1.121353399939835
---------------------------------------------------------------------------
Text: the film has too many spots where it's on slippery footing , but is acceptable entertainment for the entire family and one that's especially fit for the kiddies .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2367.40576171875
Total Time: 1.1413197999354452
---------------------------------------------------------------------------
Text: purports to be a hollywood satire but winds up as the kind of film that should be the target of something deeper and more engaging . oh , and more entertaining , too .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2368.06396484375
Total Time: 1.169975099968724
---------------------------------------------------------------------------
Text: . . . in the pile of useless actioners from mtv schmucks who don't know how to tell a story for more than four minutes .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1272.01171875
Max VRAM Usage: 2367.24169921875
Total Time: 1.1638930999906734
---------------------------------------------------------------------------
Text: though it was made with careful attention to detail and is well-acted by james spader and maggie gyllenhaal , i felt disrespected .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 160 || Output tokens: 1
Peak memory Usage: 1272.01953125
Max VRAM Usage: 2367.40576171875
Total Time: 1.1305841000285
---------------------------------------------------------------------------
Text: well-made but mush-hearted .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1272.0234375
Max VRAM Usage: 2363.12744140625
Total Time: 1.127502000075765
---------------------------------------------------------------------------
Text: humor in i spy is so anemic .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1272.0234375
Max VRAM Usage: 2363.62158203125
Total Time: 1.1378661999478936
---------------------------------------------------------------------------
Text: the film is strictly routine .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1272.0234375
Max VRAM Usage: 2363.12744140625
Total Time: 1.139101899927482
---------------------------------------------------------------------------
Text: a real snooze .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 133 || Output tokens: 1
Peak memory Usage: 1272.0234375
Max VRAM Usage: 2362.96337890625
Total Time: 1.1563744000159204
---------------------------------------------------------------------------
Text: skillful as he is , mr . shyamalan is undone by his pretensions .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.0234375
Max VRAM Usage: 2365.10205078125
Total Time: 1.149102200055495
---------------------------------------------------------------------------
Text: while the new film is much more eye-catching than its blood-drenched stephen norrington-directed predecessor , the new script by the returning david s . goyer is much sillier .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1272.0234375
Max VRAM Usage: 2368.39306640625
Total Time: 1.1822135000256822
---------------------------------------------------------------------------
Text: in addition to sporting one of the worst titles in recent cinematic history , ballistic : ecks vs . sever also features terrible , banal dialogue ; convenient , hole-ridden plotting ; superficial characters and a rather dull , unimaginative car chase .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 176 || Output tokens: 1
Peak memory Usage: 1272.05078125
Max VRAM Usage: 2370.03857421875
Total Time: 1.1576912000309676
---------------------------------------------------------------------------
Text: it shares the first two films' loose-jointed structure , but laugh-out-loud bits are few and far between .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1272.05078125
Max VRAM Usage: 2366.08935546875
Total Time: 1.1338188999798149
---------------------------------------------------------------------------
Text: the santa clause 2 is a barely adequate babysitter for older kids , but i've got to give it thumbs down .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1272.05078125
Max VRAM Usage: 2366.25439453125
Total Time: 1.1344560000579804
---------------------------------------------------------------------------
Text: you cannot guess why the cast and crew didn't sign a pact to burn the negative and the script and pretend the whole thing never existed .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1272.05078125
Max VRAM Usage: 2366.74755859375
Total Time: 1.1334646999603137
---------------------------------------------------------------------------
Text: barney throws away the goodwill the first half of his movie generates by orchestrating a finale that is impenetrable and dull .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1272.11328125
Max VRAM Usage: 2366.58349609375
Total Time: 1.1485733001027256
---------------------------------------------------------------------------
Text: if you're really renting this you're not interested in discretion in your entertainment choices , you're interested in anne geddes , john grisham , and thomas kincaid .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1272.11328125
Max VRAM Usage: 2368.22900390625
Total Time: 1.1342658000066876
---------------------------------------------------------------------------
Text: we get the comedy we settle for .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1272.11328125
Max VRAM Usage: 2363.45654296875
Total Time: 1.1248379999306053
---------------------------------------------------------------------------
Text: the uneven movie does have its charms and its funny moments but not quite enough of them .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.11328125
Max VRAM Usage: 2365.10205078125
Total Time: 1.1291462000226602
---------------------------------------------------------------------------
Text: two hours of sepia-tinted heavy metal images and surround sound effects of people moaning .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1272.11328125
Max VRAM Usage: 2365.43115234375
Total Time: 1.1338878000387922
---------------------------------------------------------------------------
Text: a word of advice to the makers of the singles ward : celebrity cameos do not automatically equal laughs . and neither do cliches , no matter how 'inside' they are .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1272.09765625
Max VRAM Usage: 2368.06396484375
Total Time: 1.1168003000784665
---------------------------------------------------------------------------
Text: the campy results make mel brooks' borscht belt schtick look sophisticated .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.09765625
Max VRAM Usage: 2365.10205078125
Total Time: 1.1345537999877706
---------------------------------------------------------------------------
Text: its appeal will probably limited to lds church members and undemanding armchair tourists .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.09765625
Max VRAM Usage: 2365.10205078125
Total Time: 1.1322227999335155
---------------------------------------------------------------------------
Text: the hanukkah spirit seems fried in pork .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 138 || Output tokens: 1
Peak memory Usage: 1272.09765625
Max VRAM Usage: 2363.78564453125
Total Time: 1.122740599908866
---------------------------------------------------------------------------
Text: cherish would've worked a lot better had it been a short film .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 142 || Output tokens: 1
Peak memory Usage: 1272.1171875
Max VRAM Usage: 2364.44384765625
Total Time: 1.1467563000041991
---------------------------------------------------------------------------
Text: manipulative claptrap , a period-piece movie-of-the-week , plain old blarney . . . take your pick . all three descriptions suit evelyn , a besotted and obvious drama that tells us nothing new .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1272.13671875
Max VRAM Usage: 2369.54541015625
Total Time: 1.130354900029488
---------------------------------------------------------------------------
Text: hey arnold ! is now stretched to barely feature length , with a little more attention paid to the animation . still , the updated dickensian sensibility of writer craig bartlett's story is appealing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1272.13671875
Max VRAM Usage: 2369.21630859375
Total Time: 1.1295814999612048
---------------------------------------------------------------------------
Text: true to its title , it traps audiences in a series of relentlessly nasty situations that we would pay a considerable ransom not to be looking at .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 156 || Output tokens: 1
Peak memory Usage: 1272.13671875
Max VRAM Usage: 2366.74755859375
Total Time: 1.1331816000165418
---------------------------------------------------------------------------
Text: doesn't come close to justifying the hype that surrounded its debut at the sundance film festival two years ago .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 151 || Output tokens: 1
Peak memory Usage: 1272.13671875
Max VRAM Usage: 2365.92529296875
Total Time: 1.1238447000505403
---------------------------------------------------------------------------
Text: the plot is paper-thin and the characters aren't interesting enough to watch them go about their daily activities for two whole hours .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 154 || Output tokens: 1
Peak memory Usage: 1272.13671875
Max VRAM Usage: 2366.41845703125
Total Time: 1.214837500010617
---------------------------------------------------------------------------
Text: kaufman's script is never especially clever and often is rather pretentious .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 144 || Output tokens: 1
Peak memory Usage: 1272.13671875
Max VRAM Usage: 2364.77294921875
Total Time: 1.2295022000325844
---------------------------------------------------------------------------
Text: the film didn't move me one way or the other , but it was an honest effort and if you want to see a flick about telemarketers this one will due .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1272.140625
Max VRAM Usage: 2368.06396484375
Total Time: 1.1662336000008509
---------------------------------------------------------------------------
Text: queen of the damned is too long with too little going on .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1272.140625
Max VRAM Usage: 2364.27978515625
Total Time: 1.164641199982725
---------------------------------------------------------------------------
Text: it collapses when mr . taylor tries to shift the tone to a thriller's rush .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.14453125
Max VRAM Usage: 2365.10205078125
Total Time: 1.2105993001023307
---------------------------------------------------------------------------
Text: any film that doesn't even in passing mention political prisoners , poverty and the boat loads of people who try to escape the country is less a documentary and more propaganda by way of a valentine sealed with a kiss .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 171 || Output tokens: 1
Peak memory Usage: 1272.1484375
Max VRAM Usage: 2369.21630859375
Total Time: 1.2023707999614999
---------------------------------------------------------------------------
Text: . . . blade ii is still top-heavy with blazing guns , cheatfully filmed martial arts , disintegrating bloodsucker computer effects and jagged camera moves that serve no other purpose than to call attention to themselves .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 172 || Output tokens: 1
Peak memory Usage: 1272.1484375
Max VRAM Usage: 2369.38037109375
Total Time: 1.2181483999593183
---------------------------------------------------------------------------
Text: the rules of attraction gets us too drunk on the party favors to sober us up with the transparent attempts at moralizing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1272.1640625
Max VRAM Usage: 2366.08935546875
Total Time: 1.289641100098379
---------------------------------------------------------------------------
Text: though there are many tense scenes in trapped , they prove more distressing than suspenseful .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.1796875
Max VRAM Usage: 2365.10205078125
Total Time: 1.1944023000542074
---------------------------------------------------------------------------
Text: in this film we at least see a study in contrasts ; the wide range of one actor , and the limited range of a comedian .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1272.1796875
Max VRAM Usage: 2366.58349609375
Total Time: 1.141575300018303
---------------------------------------------------------------------------
Text: feels strangely hollow at its emotional core .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1272.1796875
Max VRAM Usage: 2363.45654296875
Total Time: 1.1495839999988675
---------------------------------------------------------------------------
Text: no surprises .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 131 || Output tokens: 1
Peak memory Usage: 1272.1796875
Max VRAM Usage: 2362.63427734375
Total Time: 1.1858412999426946
---------------------------------------------------------------------------
Text: you have once again entered the bizarre realm where director adrian lyne holds sway , where all relationships are simultaneously broadly metaphorical , oddly abstract , and excruciatingly literal .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 164 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2368.06396484375
Total Time: 1.1825712999561802
---------------------------------------------------------------------------
Text: the high-concept scenario soon proves preposterous , the acting is robotically italicized , and truth-in-advertising hounds take note : there's very little hustling on view .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 166 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2368.39306640625
Total Time: 1.1870665999595076
---------------------------------------------------------------------------
Text: this director's cut -- which adds 51 minutes -- takes a great film and turns it into a mundane soap opera .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 152 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2366.08935546875
Total Time: 1.18025720003061
---------------------------------------------------------------------------
Text: characterisation has been sacrificed for the sake of spectacle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.95068359375
Total Time: 1.1505379000445828
---------------------------------------------------------------------------
Text: the venezuelans say things like " si , pretty much " and " por favor , go home " when talking to americans . that's muy loco , but no more ridiculous than most of the rest of " dragonfly . "

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 176 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2370.03857421875
Total Time: 1.1382519999751821
---------------------------------------------------------------------------
Text: it's a movie that ends with truckzilla , for cryin' out loud . if that doesn't clue you in that something's horribly wrong , nothing will .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 161 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.57080078125
Total Time: 1.1402709999820217
---------------------------------------------------------------------------
Text: director tom shadyac and star kevin costner glumly mishandle the story's promising premise of a physician who needs to heal himself .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 157 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2366.91259765625
Total Time: 1.195964099955745
---------------------------------------------------------------------------
Text: it's difficult to imagine that a more confused , less interesting and more sloppily made film could possibly come down the road in 2002 .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.07666015625
Total Time: 1.1772510999580845
---------------------------------------------------------------------------
Text: like the tuck family themselves , this movie just goes on and on and on and on

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 146 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2365.10205078125
Total Time: 1.1352498000487685
---------------------------------------------------------------------------
Text: as pedestrian as they come .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 134 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.12744140625
Total Time: 1.1299472000682727
---------------------------------------------------------------------------
Text: a film that plays things so nice 'n safe as to often play like a milquetoast movie of the week blown up for the big screen .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 159 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.24169921875
Total Time: 1.1710094000445679
---------------------------------------------------------------------------
Text: it's a feel-bad ending for a depressing story that throws a bunch of hot-button items in the viewer's face and asks to be seen as hip , winking social commentary .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2368.22900390625
Total Time: 1.2352120999712497
---------------------------------------------------------------------------
Text: put it somewhere between sling blade and south of heaven , west of hell in the pantheon of billy bob's body of work .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2366.58349609375
Total Time: 1.2241811000276357
---------------------------------------------------------------------------
Text: more intellectually scary than dramatically involving .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.29248046875
Total Time: 1.1991522000171244
---------------------------------------------------------------------------
Text: an inconsequential , barely there bit of piffle .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2364.11474609375
Total Time: 1.1375119000440463
---------------------------------------------------------------------------
Text: the abiding impression , despite the mild hallucinogenic buzz , is of overwhelming waste -- the acres of haute couture can't quite conceal that there's nothing resembling a spine here .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2368.22900390625
Total Time: 1.1407501000212505
---------------------------------------------------------------------------
Text: as saccharine as it is disposable .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 137 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.62158203125
Total Time: 1.1397794999647886
---------------------------------------------------------------------------
Text: you come away thinking not only that kate isn't very bright , but that she hasn't been worth caring about and that maybe she , janine and molly -- an all-woman dysfunctional family -- deserve one another .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 173 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2369.54541015625
Total Time: 1.1337605000007898
---------------------------------------------------------------------------
Text: the metaphors are provocative , but too often , the viewer is left puzzled by the mechanics of the delivery .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 150 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2365.76025390625
Total Time: 1.125500899972394
---------------------------------------------------------------------------
Text: very much a home video , and so devoid of artifice and purpose that it appears not to have been edited at all .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2366.25439453125
Total Time: 1.1639729000162333
---------------------------------------------------------------------------
Text: too much power , not enough puff .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 136 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.45654296875
Total Time: 1.1377845999086276
---------------------------------------------------------------------------
Text: the attempt to build up a pressure cooker of horrified awe emerges from the simple fact that the movie has virtually nothing to show .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 153 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2366.25439453125
Total Time: 1.1230498000513762
---------------------------------------------------------------------------
Text: it's provocative stuff , but the speculative effort is hampered by taylor's cartoonish performance and the film's ill-considered notion that hitler's destiny was shaped by the most random of chances .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 170 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2369.05126953125
Total Time: 1.1325773000717163
---------------------------------------------------------------------------
Text: a cellophane-pop remake of the punk classic ladies and gentlemen , the fabulous stains . . . crossroads is never much worse than bland or better than inconsequential .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1367041999474168
---------------------------------------------------------------------------
Text: muddled , trashy and incompetent

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.29248046875
Total Time: 1.124557500006631
---------------------------------------------------------------------------
Text: for this sort of thing to work , we need agile performers , but the proficient , dull sorvino has no light touch , and rodan is out of his league .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1422407000791281
---------------------------------------------------------------------------
Text: narc is all menace and atmosphere .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 135 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.29248046875
Total Time: 1.1709344000555575
---------------------------------------------------------------------------
Text: though excessively tiresome , the uncertainty principle , as verbally pretentious as the title may be , has its handful of redeeming features , as long as you discount its ability to bore .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 165 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2368.22900390625
Total Time: 1.1149848999921232
---------------------------------------------------------------------------
Text: despite juliet stevenon's attempt to bring cohesion to pamela's emotional roller coaster life , it is not enough to give the film the substance it so desperately needs .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 163 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.89990234375
Total Time: 1.1897186000132933
---------------------------------------------------------------------------
Text: it's tough to be startled when you're almost dozing .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 141 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2364.27978515625
Total Time: 1.2149169000331312
---------------------------------------------------------------------------
Text: his [nelson's] screenplay needs some serious re-working to show more of the dilemma , rather than have his characters stage shouting matches about it .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

positive
Response: positive
Input tokens: 158 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2367.07666015625
Total Time: 1.2157373999943957
---------------------------------------------------------------------------
Text: it's so downbeat and nearly humorless that it becomes a chore to sit through -- despite some first-rate performances by its lead .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 155 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2366.58349609375
Total Time: 1.2512280999217182
---------------------------------------------------------------------------
Text: a terrible movie that some people will nevertheless find moving .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 139 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2363.95068359375
Total Time: 1.1995256000664085
---------------------------------------------------------------------------
Text: there are many definitions of 'time waster' but this movie must surely be one of them .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 148 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2365.43115234375
Total Time: 1.1433337000198662
---------------------------------------------------------------------------
Text: as it stands , crocodile hunter has the hurried , badly cobbled look of the 1959 godzilla , which combined scenes of a japanese monster flick with canned shots of raymond burr commenting on the monster's path of destruction .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 176 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2370.03857421875
Total Time: 1.1241005000192672
---------------------------------------------------------------------------
Text: the thing looks like a made-for-home-video quickie .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 140 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2364.11474609375
Total Time: 1.1481567999580875
---------------------------------------------------------------------------
Text: enigma is well-made , but it's just too dry and too placid .

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

negative
Response: negative
Input tokens: 145 || Output tokens: 1
Peak memory Usage: 1272.18359375
Max VRAM Usage: 2364.93798828125
Total Time: 1.1496895999880508
---------------------------------------------------------------------------

In [18]:
results.to_csv("results/results_llama_ZS_binary2.csv", index=False)
results

,text,true_label,predicted_label,peak_memory_usage,max_vram_usage,inference_time,num_input_tokens,num_output_tokens
0,lovingly photographed in the manner of a golde...,positive,positive,1464.617188,2366.418457,2.028370,154,1
1,consistently clever and suspenseful .,positive,positive,1472.929688,2363.127441,1.354463,134,1
2,"it's like a "" big chill "" reunion of the baade...",positive,positive,1473.054688,2367.076660,1.300386,158,1
3,the story gives ample opportunity for large-sc...,positive,positive,1473.097656,2366.089355,1.287321,152,1
4,"red dragon "" never cuts corners .",positive,positive,1473.125000,2363.292480,1.317719,135,1
...,...,...,...,...,...,...,...,...
1061,a terrible movie that some people will neverth...,negative,negative,1272.183594,2363.950684,1.199526,139,1
1062,there are many definitions of 'time waster' bu...,negative,negative,1272.183594,2365.431152,1.143334,148,1
1063,"as it stands , crocodile hunter has the hurrie...",negative,negative,1272.183594,2370.038574,1.124101,176,1
1064,the thing looks like a made-for-home-video qui...,negative,negative,1272.183594,2364.114746,1.148157,140,1
1065,"enigma is well-made , but it's just too dry an...",negative,negative,1272.183594,2364.937988,1.149690,145,1

In [19]:
print(results['predicted_label'].value_counts())
print(results['true_label'].value_counts())

predicted_label
positive    564
negative    494
none          8
Name: count, dtype: int64
true_label
positive    533
negative    533
Name: count, dtype: int64

In [27]:
y = results['true_label']
y_pred = results['predicted_label']

accuracy = accuracy_score(y, y_pred)
f1 = f1_score(y, y_pred, average='weighted')
recall = recall_score(y, y_pred, average='weighted')
precision = precision_score(y, y_pred, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
print(f"Recall: {recall}")
print(f"Precision: {precision}")

Accuracy: 0.8320825515947468
F1 Score: 0.8349752667050706
Recall: 0.8320825515947468
Precision: 0.8397364114049444

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))