# Importing libraries

In [1]:
# Basic libraries
import pandas as pd
import numpy as np
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.multioutput import MultiOutputClassifier

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, hamming_loss
from memory_profiler import memory_usage


# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [2]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [3]:
ds = load_dataset("Rami/multi-label-class-github-issues-text-classification")

train = ds['train'].to_pandas()
val = ds['valid'].to_pandas()
test = ds['test'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1556 non-null   object
 1   labels    1556 non-null   object
 2   bodyText  1556 non-null   object
dtypes: object(3)
memory usage: 36.6+ KB

# Dataset preprocessing

In [4]:
allowed_categories = ["bug", "feature", "question", "won't fix", "docs"]

def clean_element(lst):
    final = []
    for elem in lst:
        clean = elem.split('->')[-1]
        final.append(clean)
    return final

train['labels'] = train['labels'].apply(clean_element)
test['labels'] = test['labels'].apply(clean_element)
val['labels'] = val['labels'].apply(clean_element)

In [5]:
train = train[train['labels'].apply(lambda cats: all(c in allowed_categories for c in cats))]
test = test[test['labels'].apply(lambda cats: all(c in allowed_categories for c in cats))]
val = val[val['labels'].apply(lambda cats: all(c in allowed_categories for c in cats))]

train = train[train['labels'].apply(len) > 0]
test = test[test['labels'].apply(len) > 0]
val = val[val['labels'].apply(len) > 0]

In [6]:
train.rename(columns={'title': 'text'}, inplace=True)
test.rename(columns={'title': 'text'}, inplace=True)
val.rename(columns={'title': 'text'}, inplace=True)

train.drop(columns=['bodyText'], inplace=True)
test.drop(columns=['bodyText'], inplace=True)
val.drop(columns=['bodyText'], inplace=True)

train.reset_index(drop=True, inplace=True)
test.reset_index(drop=True, inplace=True)
val.reset_index(drop=True, inplace=True)

train

                                                  text                 labels
0                       Fix docs typo in starter files                 [docs]
1                            Fix typo in starter files                 [docs]
2     Load models give different results from original             [question]
3         Pickle error and OOM when upgrading to 1.2.0  [question, won't fix]
4    val_check_interval equivalent for training los...            [won't fix]
..                                                 ...                    ...
410                     How to implement pre-training?             [question]
411                  Logging the current learning rate             [question]
412  Example of gradient accumulation documentation...                 [docs]
413  Checkpooint Callback not called when training ...             [question]
414  Evaluation on subsampled training set during t...             [question]

[415 rows x 2 columns]

In [7]:
mlb = MultiLabelBinarizer()

train_labels_binarized = mlb.fit_transform(train['labels'])
val_labels_binarized = mlb.transform(val['labels'])
test_labels_binarized = mlb.transform(test['labels'])

train_labels_df = pd.DataFrame(train_labels_binarized, columns=mlb.classes_)
val_labels_df = pd.DataFrame(val_labels_binarized, columns=mlb.classes_)
test_labels_df = pd.DataFrame(test_labels_binarized, columns=mlb.classes_)

train = pd.concat([train, train_labels_df], axis=1)
val = pd.concat([val, val_labels_df], axis=1)
test = pd.concat([test, test_labels_df], axis=1)

train = train.drop(columns=['labels'])
val = val.drop(columns=['labels'])
test = test.drop(columns=['labels'])

train

,text,bug,docs,feature,question,won't fix
0,Fix docs typo in starter files,0,1,0,0,0
1,Fix typo in starter files,0,1,0,0,0
2,Load models give different results from original,0,0,0,1,0
3,Pickle error and OOM when upgrading to 1.2.0,0,0,0,1,1
4,val_check_interval equivalent for training los...,0,0,0,0,1
...,...,...,...,...,...,...
410,How to implement pre-training?,0,0,0,1,0
411,Logging the current learning rate,0,0,0,1,0
412,Example of gradient accumulation documentation...,0,1,0,0,0
413,Checkpooint Callback not called when training ...,0,0,0,1,0
414,Evaluation on subsampled training set during t...,0,0,0,1,0

In [8]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [9]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': MultiOutputClassifier(SVC()),
        'params': {
            'estimator__C': [0.1, 1, 10],
            'estimator__kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultiOutputClassifier(MultinomialNB()),
        'params': {
            'estimator__alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': MultiOutputClassifier(LogisticRegression(max_iter=1000)),
        'params': {
            'estimator__C': [0.1, 1, 10],
            'estimator__penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': MultiOutputClassifier(GradientBoostingClassifier()),
        'params': {
            'estimator__n_estimators': [100, 150, 200],
            'estimator__criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': MultiOutputClassifier(AdaBoostClassifier()),
        'params': {
            'estimator__n_estimators': [50, 100, 150],
            'estimator__learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': MultiOutputClassifier(SGDClassifier()),
        'params': {
            'estimator__alpha': [0.0001, 0.001, 0.01],
            'estimator__penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [10]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'hamming_loss', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = list(train.columns[1:])
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [11]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train[classes])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                val_classes = val.drop(columns=['text'])

                accuracy = accuracy_score(val_classes, y_pred)
                
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val_classes.to_numpy(), y_pred, average=None, zero_division=0)

                hamm_loss = hamming_loss(val_classes.to_numpy(), y_pred)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'hamming_loss': hamm_loss,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_multilabel2.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.3487792999949306
Peak memory usage during training: 369.73828125 MB
Prediction time: 1.9985945000080392
Peak memory usage during prediction: 369.296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_17488\2771957900.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 1.2528648999868892
Peak memory usage during training: 370.1875 MB
Prediction time: 1.8892155000357889
Peak memory usage during prediction: 369.734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.2059348999755457
Peak memory usage during training: 370.25 MB
Prediction time: 1.888440599956084
Peak memory usage during prediction: 369.828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.366499700001441
Peak memory usage during training: 372.86328125 MB
Prediction time: 1.8913718999829143
Peak memory usage during prediction: 372.36328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 0.7185840000165626
Peak memory usage during training: 373.0859375 MB
Prediction time: 1.856046300032176
Peak memory usage during prediction: 372.83984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 0.7157415999681689
Peak memory usage during training: 372.921875 MB
Prediction time: 1.8235077999997884
Peak memory usage during prediction: 372.5859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 0.7574724999722093
Peak memory usage during training: 375.05859375 MB
Prediction time: 1.8461234999704175
Peak memory usage during prediction: 375.0625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 0.8059014999889769
Peak memory usage during training: 375.390625 MB
Prediction time: 1.8513771999860182
Peak memory usage during prediction: 375.4453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 0.8066512999939732
Peak memory usage during training: 376.0 MB
Prediction time: 1.842130900011398
Peak memory usage during prediction: 375.24609375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.444668999989517
Peak memory usage during training: 376.51171875 MB
Prediction time: 1.8293230999843217
Peak memory usage during prediction: 375.921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9956217999570072
Peak memory usage during training: 376.58984375 MB
Prediction time: 1.8252702000318095
Peak memory usage during prediction: 376.29296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 0.9746585999964736
Peak memory usage during training: 376.6328125 MB
Prediction time: 1.8214419000432827
Peak memory usage during prediction: 376.078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.4508029999560677
Peak memory usage during training: 377.234375 MB
Prediction time: 1.8188032999751158
Peak memory usage during prediction: 376.3203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 0.9935961000155658
Peak memory usage during training: 377.21484375 MB
Prediction time: 1.8352809000061825
Peak memory usage during prediction: 376.48828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.42501650005579
Peak memory usage during training: 377.09765625 MB
Prediction time: 1.8145017999922857
Peak memory usage during prediction: 376.328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.4566466999822296
Peak memory usage during training: 377.57421875 MB
Prediction time: 1.8278292000177316
Peak memory usage during prediction: 376.65625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.4678098000003956
Peak memory usage during training: 377.4921875 MB
Prediction time: 1.828904900001362
Peak memory usage during prediction: 377.48828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.44994029996451
Peak memory usage during training: 377.9765625 MB
Prediction time: 1.814112699998077
Peak memory usage during prediction: 376.98046875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.805542299989611
Peak memory usage during training: 377.47265625 MB
Prediction time: 1.8006038999883458
Peak memory usage during prediction: 377.3203125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.8112381999962963
Peak memory usage during training: 377.36328125 MB
Prediction time: 1.7860044999979436
Peak memory usage during prediction: 376.9453125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.8145616000401787
Peak memory usage during training: 377.0546875 MB
Prediction time: 1.7910739000071771
Peak memory usage during prediction: 377.0625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.852740200003609
Peak memory usage during training: 377.53515625 MB
Prediction time: 1.7899565999978222
Peak memory usage during prediction: 377.109375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8538059000275098
Peak memory usage during training: 377.36328125 MB
Prediction time: 1.791283399972599
Peak memory usage during prediction: 377.36328125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.4155137000489049
Peak memory usage during training: 377.35546875 MB
Prediction time: 1.7947716999915428
Peak memory usage during prediction: 377.35546875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8209572999621741
Peak memory usage during training: 377.42578125 MB
Prediction time: 1.798165299987886
Peak memory usage during prediction: 378.40625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8058374000247568
Peak memory usage during training: 377.2109375 MB
Prediction time: 1.7998658999567851
Peak memory usage during prediction: 378.5078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.8205633999896236
Peak memory usage during training: 377.33984375 MB
Prediction time: 1.8122363000293262
Peak memory usage during prediction: 378.6328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.7997937999898568
Peak memory usage during training: 377.44140625 MB
Prediction time: 1.8242622999823652
Peak memory usage during prediction: 378.7578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8668209000024945
Peak memory usage during training: 377.60546875 MB
Prediction time: 1.803297299949918
Peak memory usage during prediction: 378.9453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.8066803000401706
Peak memory usage during training: 377.71484375 MB
Prediction time: 1.8020417999941856
Peak memory usage during prediction: 378.98828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.7966348999761976
Peak memory usage during training: 377.82421875 MB
Prediction time: 1.806522800005041
Peak memory usage during prediction: 379.140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8058714999933727
Peak memory usage during training: 377.87890625 MB
Prediction time: 1.826700699981302
Peak memory usage during prediction: 379.19921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.808269899978768
Peak memory usage during training: 377.97265625 MB
Prediction time: 1.810437300009653
Peak memory usage during prediction: 379.31640625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.8083432000130415
Peak memory usage during training: 378.3828125 MB
Prediction time: 1.7975229999865405
Peak memory usage during prediction: 378.38671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.807174900022801
Peak memory usage during training: 378.6328125 MB
Prediction time: 1.7921697999699973
Peak memory usage during prediction: 378.61328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9873239999869838
Peak memory usage during training: 378.61328125 MB
Prediction time: 1.7838210000190884
Peak memory usage during prediction: 378.63671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.8276429999968968
Peak memory usage during training: 378.8984375 MB
Prediction time: 1.8014728000271134
Peak memory usage during prediction: 378.609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.806134500016924
Peak memory usage during training: 378.81640625 MB
Prediction time: 1.7938772999914363
Peak memory usage during prediction: 378.828125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 0.9953468999592587
Peak memory usage during training: 378.85546875 MB
Prediction time: 1.7979698000126518
Peak memory usage during prediction: 378.85546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.8047124999575317
Peak memory usage during training: 378.9609375 MB
Prediction time: 1.7795625000144355
Peak memory usage during prediction: 378.9296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.8357248000102118
Peak memory usage during training: 379.21484375 MB
Prediction time: 1.7972715999931097
Peak memory usage during prediction: 379.26171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0054004000267014
Peak memory usage during training: 379.0390625 MB
Prediction time: 1.7860712999827228
Peak memory usage during prediction: 379.0625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.0132949000108056
Peak memory usage during training: 379.3203125 MB
Prediction time: 1.8024325000005774
Peak memory usage during prediction: 378.15234375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.0022053999709897
Peak memory usage during training: 378.39453125 MB
Prediction time: 1.8016989000025205
Peak memory usage during prediction: 378.22265625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.2559225000441074
Peak memory usage during training: 378.48046875 MB
Prediction time: 1.80912960000569
Peak memory usage during prediction: 378.4609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.2566740000038408
Peak memory usage during training: 378.59765625 MB
Prediction time: 1.8018105000373907
Peak memory usage during prediction: 378.48046875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.5164155999664217
Peak memory usage during training: 378.796875 MB
Prediction time: 1.7952361999778077
Peak memory usage during prediction: 378.80078125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.5091016999795102
Peak memory usage during training: 379.015625 MB
Prediction time: 1.8007004999672063
Peak memory usage during prediction: 378.94140625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.781747400003951
Peak memory usage during training: 379.23828125 MB
Prediction time: 1.4481041000108235
Peak memory usage during prediction: 379.2421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7744030000176281
Peak memory usage during training: 379.48046875 MB
Prediction time: 1.4376333999680355
Peak memory usage during prediction: 379.40234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.764532600005623
Peak memory usage during training: 379.58203125 MB
Prediction time: 0.9926357999793254
Peak memory usage during prediction: 379.58203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.071931599988602
Peak memory usage during training: 379.72265625 MB
Prediction time: 1.0367821999825537
Peak memory usage during prediction: 379.73046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.063180500001181
Peak memory usage during training: 380.0390625 MB
Prediction time: 1.0302953999489546
Peak memory usage during prediction: 380.0390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0702186999842525
Peak memory usage during training: 379.96484375 MB
Prediction time: 1.0300901000155136
Peak memory usage during prediction: 379.96484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3623379000346176
Peak memory usage during training: 380.23046875 MB
Prediction time: 1.0885280999937095
Peak memory usage during prediction: 380.23046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3725803999695927
Peak memory usage during training: 380.48828125 MB
Prediction time: 1.0869967000326142
Peak memory usage during prediction: 380.48828125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3708150000311434
Peak memory usage during training: 380.7109375 MB
Prediction time: 1.09000060003018
Peak memory usage during prediction: 380.7109375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8327124000061303
Peak memory usage during training: 380.55859375 MB
Prediction time: 1.795634699985385
Peak memory usage during prediction: 380.4765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.8233363999752328
Peak memory usage during training: 380.5546875 MB
Prediction time: 1.8114397999597713
Peak memory usage during prediction: 380.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.8393605000455864
Peak memory usage during training: 380.56640625 MB
Prediction time: 1.7953039000276476
Peak memory usage during prediction: 380.56640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.81433919997653
Peak memory usage during training: 380.56640625 MB
Prediction time: 1.7942290999926627
Peak memory usage during prediction: 380.56640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.8539343999582343
Peak memory usage during training: 380.57421875 MB
Prediction time: 1.7947216000175104
Peak memory usage during prediction: 380.57421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.8558065999532118
Peak memory usage during training: 380.57421875 MB
Prediction time: 1.7995420999941416
Peak memory usage during prediction: 380.57421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8246686000493355
Peak memory usage during training: 380.57421875 MB
Prediction time: 1.7927830999833532
Peak memory usage during prediction: 380.57421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.8205483999918215
Peak memory usage during training: 380.57421875 MB
Prediction time: 1.8018819999997504
Peak memory usage during prediction: 380.57421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.8367752999765798
Peak memory usage during training: 380.57421875 MB
Prediction time: 1.779768000007607
Peak memory usage during prediction: 380.57421875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.1306544999824837
Peak memory usage during training: 379.36328125 MB
Prediction time: 1.8132953000022098
Peak memory usage during prediction: 375.00390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.1577246999950148
Peak memory usage during training: 375.3828125 MB
Prediction time: 1.8144255999941379
Peak memory usage during prediction: 375.40234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.1454712999984622
Peak memory usage during training: 375.5234375 MB
Prediction time: 1.8023539000423625
Peak memory usage during prediction: 375.37890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.3170969999628142
Peak memory usage during training: 378.99609375 MB
Prediction time: 1.819276100024581
Peak memory usage during prediction: 377.82421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.3688277999754064
Peak memory usage during training: 378.421875 MB
Prediction time: 1.8119857999845408
Peak memory usage during prediction: 378.19921875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 0.6872365000308491
Peak memory usage during training: 378.57421875 MB
Prediction time: 1.8090665999916382
Peak memory usage during prediction: 378.24609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 0.758664199966006
Peak memory usage during training: 380.90625 MB
Prediction time: 1.8238729999866337
Peak memory usage during prediction: 380.90625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 0.789482299995143
Peak memory usage during training: 381.2265625 MB
Prediction time: 1.8336167999659665
Peak memory usage during prediction: 380.984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 0.7836130999494344
Peak memory usage during training: 381.15234375 MB
Prediction time: 1.8299871000344865
Peak memory usage during prediction: 381.15234375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.430041200015694
Peak memory usage during training: 381.66015625 MB
Prediction time: 1.8104040999896824
Peak memory usage during prediction: 381.16015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 0.9944362000096589
Peak memory usage during training: 382.0859375 MB
Prediction time: 1.8416057999711484
Peak memory usage during prediction: 381.41796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.420683200005442
Peak memory usage during training: 382.23828125 MB
Prediction time: 1.8113042999757454
Peak memory usage during prediction: 381.3125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.4529043000075035
Peak memory usage during training: 382.30859375 MB
Prediction time: 1.7985978999640793
Peak memory usage during prediction: 381.4375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.4645360999857076
Peak memory usage during training: 382.203125 MB
Prediction time: 1.8182267000083812
Peak memory usage during prediction: 381.9921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 0.9666125000221655
Peak memory usage during training: 382.00390625 MB
Prediction time: 1.8394636000157334
Peak memory usage during prediction: 381.25390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.1345216000336222
Peak memory usage during training: 382.35546875 MB
Prediction time: 2.0367694000015035
Peak memory usage during prediction: 381.515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.0771953000221401
Peak memory usage during training: 382.703125 MB
Prediction time: 1.8903479999862611
Peak memory usage during prediction: 381.83203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.466969600005541
Peak memory usage during training: 382.73046875 MB
Prediction time: 1.8234060000395402
Peak memory usage during prediction: 381.921875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.8062388999969698
Peak memory usage during training: 381.94140625 MB
Prediction time: 1.8568186000338756
Peak memory usage during prediction: 381.4609375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.882441999972798
Peak memory usage during training: 381.5234375 MB
Prediction time: 1.835570800001733
Peak memory usage during prediction: 381.3984375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.9432227000361308
Peak memory usage during training: 381.421875 MB
Prediction time: 1.8261947999708354
Peak memory usage during prediction: 381.2421875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.825722699984908
Peak memory usage during training: 381.421875 MB
Prediction time: 1.878406099975109
Peak memory usage during prediction: 381.2421875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9420577000128105
Peak memory usage during training: 381.421875 MB
Prediction time: 1.7920366000034846
Peak memory usage during prediction: 381.42578125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9005537999910302
Peak memory usage during training: 381.40625 MB
Prediction time: 1.8254686999716796
Peak memory usage during prediction: 381.40625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8409298000042327
Peak memory usage during training: 381.40625 MB
Prediction time: 1.9798764999723062
Peak memory usage during prediction: 382.50390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.941146299999673
Peak memory usage during training: 381.3125 MB
Prediction time: 1.4499408999690786
Peak memory usage during prediction: 382.60546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8168972000130452
Peak memory usage during training: 381.41015625 MB
Prediction time: 1.4352506000432186
Peak memory usage during prediction: 382.703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8837228000047617
Peak memory usage during training: 381.4765625 MB
Prediction time: 1.4354678000090644
Peak memory usage during prediction: 382.73046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8259065000456758
Peak memory usage during training: 381.578125 MB
Prediction time: 1.464056900003925
Peak memory usage during prediction: 382.83203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 2.2878690999932587
Peak memory usage during training: 381.6796875 MB
Prediction time: 1.987120000005234
Peak memory usage during prediction: 377.13671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8140379000105895
Peak memory usage during training: 375.5234375 MB
Prediction time: 1.4428426999947987
Peak memory usage during prediction: 376.72265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.819672100013122
Peak memory usage during training: 375.55078125 MB
Prediction time: 1.9081607999978587
Peak memory usage during prediction: 376.84375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8467153999954462
Peak memory usage during training: 375.57421875 MB
Prediction time: 1.4393084999755956
Peak memory usage during prediction: 376.8671875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.836493699986022
Peak memory usage during training: 376.03515625 MB
Prediction time: 1.9441634999820963
Peak memory usage during prediction: 376.03515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8007971000042744
Peak memory usage during training: 376.23046875 MB
Prediction time: 1.7956085000187159
Peak memory usage during prediction: 376.23046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.436663300031796
Peak memory usage during training: 376.23046875 MB
Prediction time: 1.7957942000357434
Peak memory usage during prediction: 375.95703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.813127200002782
Peak memory usage during training: 376.20703125 MB
Prediction time: 1.8077731000375934
Peak memory usage during prediction: 376.21484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.808747000002768
Peak memory usage during training: 376.4609375 MB
Prediction time: 1.7785204999963753
Peak memory usage during prediction: 376.4609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.4468632999924012
Peak memory usage during training: 376.515625 MB
Prediction time: 1.8105951999896206
Peak memory usage during prediction: 376.515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.8052384000038728
Peak memory usage during training: 376.8125 MB
Prediction time: 1.7957416000426747
Peak memory usage during prediction: 376.8203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8192574999993667
Peak memory usage during training: 376.796875 MB
Prediction time: 1.7826235999818891
Peak memory usage during prediction: 376.8125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 0.9748228000244126
Peak memory usage during training: 376.875 MB
Prediction time: 1.7694391999975778
Peak memory usage during prediction: 376.90234375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 0.9475322000216693
Peak memory usage during training: 376.91796875 MB
Prediction time: 1.8080752000096254
Peak memory usage during prediction: 376.0703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 0.9438318000175059
Peak memory usage during training: 376.09375 MB
Prediction time: 1.7821118999854662
Peak memory usage during prediction: 376.09375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.1776197000290267
Peak memory usage during training: 376.08203125 MB
Prediction time: 1.799094099958893
Peak memory usage during prediction: 375.9375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.1883900000248104
Peak memory usage during training: 376.0234375 MB
Prediction time: 2.042366400011815
Peak memory usage during prediction: 376.0234375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.540650699986145
Peak memory usage during training: 376.14453125 MB
Prediction time: 1.8432931999559514
Peak memory usage during prediction: 376.08984375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.469903199991677
Peak memory usage during training: 376.19921875 MB
Prediction time: 2.0239846000331454
Peak memory usage during prediction: 376.19140625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8754980000085197
Peak memory usage during training: 376.203125 MB
Prediction time: 1.577735299943015
Peak memory usage during prediction: 376.171875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8392303999862634
Peak memory usage during training: 376.2421875 MB
Prediction time: 1.0799639000324532
Peak memory usage during prediction: 376.2421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8171897999709472
Peak memory usage during training: 375.6484375 MB
Prediction time: 1.025089900009334
Peak memory usage during prediction: 375.6484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0678451999556273
Peak memory usage during training: 375.6875 MB
Prediction time: 1.0909887999878265
Peak memory usage during prediction: 375.69140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0643333999905735
Peak memory usage during training: 375.9453125 MB
Prediction time: 1.08792129997164
Peak memory usage during prediction: 375.9140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0824607000104152
Peak memory usage during training: 375.94921875 MB
Prediction time: 1.171717599965632
Peak memory usage during prediction: 375.94921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4438730000401847
Peak memory usage during training: 376.13671875 MB
Prediction time: 1.1375538999564014
Peak memory usage during prediction: 376.13671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4108633000287227
Peak memory usage during training: 376.35546875 MB
Prediction time: 1.1908642000053078
Peak memory usage during prediction: 376.36328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3960209999931976
Peak memory usage during training: 376.52734375 MB
Prediction time: 1.1426032000454143
Peak memory usage during prediction: 376.52734375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.8915012999786995
Peak memory usage during training: 376.54296875 MB
Prediction time: 1.8941203000140376
Peak memory usage during prediction: 376.484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 2.111121899972204
Peak memory usage during training: 376.50390625 MB
Prediction time: 2.1210914999828674
Peak memory usage during prediction: 376.50390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 2.0594718999927863
Peak memory usage during training: 376.5234375 MB
Prediction time: 1.9060214000055566
Peak memory usage during prediction: 376.5234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9409535999875516
Peak memory usage during training: 376.546875 MB
Prediction time: 1.8894411000073887
Peak memory usage during prediction: 376.546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.989036400045734
Peak memory usage during training: 376.546875 MB
Prediction time: 2.136432999977842
Peak memory usage during prediction: 376.546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.9233630999806337
Peak memory usage during training: 376.546875 MB
Prediction time: 1.867632000008598
Peak memory usage during prediction: 376.546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9102514000260271
Peak memory usage during training: 376.5546875 MB
Prediction time: 1.8698294999776408
Peak memory usage during prediction: 376.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.884008199966047
Peak memory usage during training: 376.5546875 MB
Prediction time: 1.884492399985902
Peak memory usage during prediction: 376.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.9083488000323996
Peak memory usage during training: 376.5546875 MB
Prediction time: 1.8698688999866135
Peak memory usage during prediction: 376.5546875 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.1754958999808878
Peak memory usage during training: 375.30078125 MB
Prediction time: 1.8728923000162467
Peak memory usage during prediction: 369.9140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.2004617999773473
Peak memory usage during training: 370.4140625 MB
Prediction time: 1.8797280000289902
Peak memory usage during prediction: 370.25390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.2048399999621324
Peak memory usage during training: 370.6640625 MB
Prediction time: 1.8718789999838918
Peak memory usage during prediction: 370.39453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.3839101999765262
Peak memory usage during training: 372.7265625 MB
Prediction time: 1.8811604999937117
Peak memory usage during prediction: 372.37109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 0.7177061000256799
Peak memory usage during training: 373.22265625 MB
Prediction time: 1.8977100999909453
Peak memory usage during prediction: 372.87109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 0.7211637999862432
Peak memory usage during training: 373.2421875 MB
Prediction time: 1.8965324999880977
Peak memory usage during prediction: 373.0 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 0.8029306000098586
Peak memory usage during training: 375.1171875 MB
Prediction time: 1.8986914999550208
Peak memory usage during prediction: 374.8984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 0.8379107000073418
Peak memory usage during training: 375.48046875 MB
Prediction time: 1.8923525999998674
Peak memory usage during prediction: 375.4921875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 0.8469906000536866
Peak memory usage during training: 375.59765625 MB
Prediction time: 1.8807559999986552
Peak memory usage during prediction: 375.65234375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.4913269000244327
Peak memory usage during training: 376.55859375 MB
Prediction time: 1.9511574999778531
Peak memory usage during prediction: 375.96875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.5239138000179082
Peak memory usage during training: 376.65625 MB
Prediction time: 1.922531800053548
Peak memory usage during prediction: 376.3984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.5848088000202551
Peak memory usage during training: 376.984375 MB
Prediction time: 1.8850429999874905
Peak memory usage during prediction: 376.22265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.5073589999810793
Peak memory usage during training: 377.07421875 MB
Prediction time: 1.897875800030306
Peak memory usage during prediction: 375.9375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.0293812000309117
Peak memory usage during training: 376.6875 MB
Prediction time: 1.903667900012806
Peak memory usage during prediction: 376.41015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.016139800020028
Peak memory usage during training: 376.7265625 MB
Prediction time: 1.8744462999748066
Peak memory usage during prediction: 376.1328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.5212434999994002
Peak memory usage during training: 376.80078125 MB
Prediction time: 1.8806151000317186
Peak memory usage during prediction: 376.22265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.0348777000326663
Peak memory usage during training: 377.0 MB
Prediction time: 1.9284869999974035
Peak memory usage during prediction: 376.109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.503046399971936
Peak memory usage during training: 376.8671875 MB
Prediction time: 1.9404689999646507
Peak memory usage during prediction: 376.296875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.8807054000208154
Peak memory usage during training: 376.4296875 MB
Prediction time: 1.8399245999753475
Peak memory usage during prediction: 376.27734375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.867608400003519
Peak memory usage during training: 376.30859375 MB
Prediction time: 1.854618199984543
Peak memory usage during prediction: 376.06640625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.8818397000432014
Peak memory usage during training: 376.08984375 MB
Prediction time: 1.852372599998489
Peak memory usage during prediction: 375.96484375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8986672000028193
Peak memory usage during training: 376.30859375 MB
Prediction time: 1.8396148000028916
Peak memory usage during prediction: 376.11328125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8781408999930136
Peak memory usage during training: 376.23828125 MB
Prediction time: 1.8515525999828242
Peak memory usage during prediction: 376.23828125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.927482900035102
Peak memory usage during training: 376.23828125 MB
Prediction time: 1.8349934000289068
Peak memory usage during prediction: 376.23828125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9235082999803126
Peak memory usage during training: 376.265625 MB
Prediction time: 1.881018799962476
Peak memory usage during prediction: 377.46875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9828751999884844
Peak memory usage during training: 376.1171875 MB
Prediction time: 1.8770147999748588
Peak memory usage during prediction: 377.4375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.8914721999899484
Peak memory usage during training: 376.2109375 MB
Prediction time: 1.8886888999841176
Peak memory usage during prediction: 377.546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8898360000457615
Peak memory usage during training: 376.28515625 MB
Prediction time: 1.869615200033877
Peak memory usage during prediction: 377.6015625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8748311000526883
Peak memory usage during training: 376.32421875 MB
Prediction time: 1.957751100009773
Peak memory usage during prediction: 377.6640625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.86754559999099
Peak memory usage during training: 376.47265625 MB
Prediction time: 1.8837763000046834
Peak memory usage during prediction: 377.82421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8680080999620259
Peak memory usage during training: 376.6015625 MB
Prediction time: 1.8682365999557078
Peak memory usage during prediction: 377.87109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8699389999965206
Peak memory usage during training: 376.70703125 MB
Prediction time: 1.870927700016182
Peak memory usage during prediction: 378.0234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.8799985000514425
Peak memory usage during training: 376.82421875 MB
Prediction time: 1.8552824999787845
Peak memory usage during prediction: 378.140625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.875742900010664
Peak memory usage during training: 377.1875 MB
Prediction time: 1.851110699994024
Peak memory usage during prediction: 377.1875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.8638570999610238
Peak memory usage during training: 377.41796875 MB
Prediction time: 1.9472432999755256
Peak memory usage during prediction: 377.42578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0736049999832176
Peak memory usage during training: 377.42578125 MB
Prediction time: 1.8652768000029027
Peak memory usage during prediction: 377.42578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.9099757999647409
Peak memory usage during training: 377.53125 MB
Prediction time: 1.8686155999894254
Peak memory usage during prediction: 377.53125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.8823449999908917
Peak memory usage during training: 377.8125 MB
Prediction time: 1.8515507000265643
Peak memory usage during prediction: 377.8125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0466593999881297
Peak memory usage during training: 377.85546875 MB
Prediction time: 1.8423661999986507
Peak memory usage during prediction: 377.8671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.896695200004615
Peak memory usage during training: 377.90234375 MB
Prediction time: 1.8709069999749772
Peak memory usage during prediction: 377.90234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.8808798999525607
Peak memory usage during training: 378.06640625 MB
Prediction time: 1.8662565000122413
Peak memory usage during prediction: 378.06640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0434231999679469
Peak memory usage during training: 378.078125 MB
Prediction time: 1.8662449999828823
Peak memory usage during prediction: 378.078125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.0366617999970913
Peak memory usage during training: 378.078125 MB
Prediction time: 1.872585800010711
Peak memory usage during prediction: 376.01171875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.029704499989748
Peak memory usage during training: 376.06640625 MB
Prediction time: 1.900460299977567
Peak memory usage during prediction: 375.8671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.2972740999539383
Peak memory usage during training: 375.95703125 MB
Prediction time: 1.8747450000373647
Peak memory usage during prediction: 375.84375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.3015828999923542
Peak memory usage during training: 375.96484375 MB
Prediction time: 1.8743385000270791
Peak memory usage during prediction: 375.875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.606496300024446
Peak memory usage during training: 376.02734375 MB
Prediction time: 1.9921603999682702
Peak memory usage during prediction: 376.03125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.5978844999917783
Peak memory usage during training: 376.125 MB
Prediction time: 1.9190006999997422
Peak memory usage during prediction: 376.0625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.799961099983193
Peak memory usage during training: 376.10546875 MB
Prediction time: 1.500635800010059
Peak memory usage during prediction: 375.27734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.801616600016132
Peak memory usage during training: 375.30078125 MB
Prediction time: 1.5245997000019997
Peak memory usage during prediction: 375.27734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.791839900019113
Peak memory usage during training: 375.27734375 MB
Prediction time: 2.000180300034117
Peak memory usage during prediction: 375.27734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.0982076999498531
Peak memory usage during training: 375.39453125 MB
Prediction time: 1.0689813999924809
Peak memory usage during prediction: 375.3984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1023500000010245
Peak memory usage during training: 375.5703125 MB
Prediction time: 1.0802955999970436
Peak memory usage during prediction: 375.5703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1198064999771304
Peak memory usage during training: 375.546875 MB
Prediction time: 1.065927899966482
Peak memory usage during prediction: 375.546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.3980255000060424
Peak memory usage during training: 375.734375 MB
Prediction time: 1.1252841000095941
Peak memory usage during prediction: 375.734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4700196999474429
Peak memory usage during training: 375.984375 MB
Prediction time: 1.1520966999814846
Peak memory usage during prediction: 375.984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4246559000457637
Peak memory usage during training: 376.15234375 MB
Prediction time: 1.1314561000326648
Peak memory usage during prediction: 376.15625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8922445999924093
Peak memory usage during training: 376.171875 MB
Prediction time: 1.9284609999740496
Peak memory usage during prediction: 376.09375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.8957024000119418
Peak memory usage during training: 376.14453125 MB
Prediction time: 1.8797674999805167
Peak memory usage during prediction: 376.14453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.9078944999491796
Peak memory usage during training: 376.15625 MB
Prediction time: 1.8800832999986596
Peak memory usage during prediction: 376.15625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.940213900001254
Peak memory usage during training: 376.15625 MB
Prediction time: 1.885757600015495
Peak memory usage during prediction: 376.15625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.9995000999770127
Peak memory usage during training: 376.15625 MB
Prediction time: 1.884137799963355
Peak memory usage during prediction: 376.15625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.9047849000198767
Peak memory usage during training: 376.17578125 MB
Prediction time: 1.865924499987159
Peak memory usage during prediction: 376.17578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.9723848000285216
Peak memory usage during training: 376.17578125 MB
Prediction time: 1.8988182000466622
Peak memory usage during prediction: 376.17578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.8947153000044636
Peak memory usage during training: 376.17578125 MB
Prediction time: 1.870086100010667
Peak memory usage during prediction: 376.17578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.8917422999511473
Peak memory usage during training: 376.17578125 MB
Prediction time: 1.8692834000103176
Peak memory usage during prediction: 376.09765625 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.1679402000154369
Peak memory usage during training: 375.05859375 MB
Prediction time: 1.9531386000453494
Peak memory usage during prediction: 370.234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.2446105999988504
Peak memory usage during training: 370.74609375 MB
Prediction time: 1.904632700025104
Peak memory usage during prediction: 370.40234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.1888384000048973
Peak memory usage during training: 370.62109375 MB
Prediction time: 1.8682871000492014
Peak memory usage during prediction: 370.62109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.3432332000229508
Peak memory usage during training: 373.59765625 MB
Prediction time: 1.8951392999733798
Peak memory usage during prediction: 372.9140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 0.697444399993401
Peak memory usage during training: 373.2734375 MB
Prediction time: 1.87386490002973
Peak memory usage during prediction: 373.28515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 0.6974385000066832
Peak memory usage during training: 373.54296875 MB
Prediction time: 1.8810562000144273
Peak memory usage during prediction: 373.2421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 0.7747838000068441
Peak memory usage during training: 375.9140625 MB
Prediction time: 1.9163638000027277
Peak memory usage during prediction: 375.9140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 0.8090231000096537
Peak memory usage during training: 376.0546875 MB
Prediction time: 1.9039531000307761
Peak memory usage during prediction: 376.0546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 0.8073820000281557
Peak memory usage during training: 376.36328125 MB
Prediction time: 1.9479191999998875
Peak memory usage during prediction: 375.95703125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 2.011149999976624
Peak memory usage during training: 376.69140625 MB
Prediction time: 1.9445973000256345
Peak memory usage during prediction: 375.94140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.084765499981586
Peak memory usage during training: 377.19140625 MB
Prediction time: 2.0045681999763474
Peak memory usage during prediction: 376.41015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.608255699975416
Peak memory usage during training: 377.265625 MB
Prediction time: 2.0795413999585435
Peak memory usage during prediction: 376.33203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.0841345000080764
Peak memory usage during training: 377.078125 MB
Prediction time: 1.9820388999651186
Peak memory usage during prediction: 376.5078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.1395180999534205
Peak memory usage during training: 377.26953125 MB
Prediction time: 1.9519516000291333
Peak memory usage during prediction: 376.77734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.036263499991037
Peak memory usage during training: 376.94140625 MB
Prediction time: 1.92135729995789
Peak memory usage during prediction: 376.46484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.0390195999643765
Peak memory usage during training: 377.26953125 MB
Prediction time: 1.8872845000005327
Peak memory usage during prediction: 376.5703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.0454868999659084
Peak memory usage during training: 377.7109375 MB
Prediction time: 1.931682200054638
Peak memory usage during prediction: 376.921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.5386258999933489
Peak memory usage during training: 377.6015625 MB
Prediction time: 1.9002347000059672
Peak memory usage during prediction: 376.8828125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 1.8781246999860741
Peak memory usage during training: 376.93359375 MB
Prediction time: 1.8740890999906696
Peak memory usage during prediction: 376.484375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 1.8972608000040054
Peak memory usage during training: 376.47265625 MB
Prediction time: 1.8792671999544837
Peak memory usage during prediction: 376.47265625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.8992455000407062
Peak memory usage during training: 376.125 MB
Prediction time: 1.8556210999959148
Peak memory usage during prediction: 376.125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.8968700999976136
Peak memory usage during training: 376.28515625 MB
Prediction time: 1.8563643000088632
Peak memory usage during prediction: 376.28515625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9493480999954045
Peak memory usage during training: 376.203125 MB
Prediction time: 1.8896712000132538
Peak memory usage during prediction: 376.203125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.926037599972915
Peak memory usage during training: 376.4375 MB
Prediction time: 1.8690252999658696
Peak memory usage during prediction: 376.20703125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.866011600010097
Peak memory usage during training: 376.234375 MB
Prediction time: 1.9758089000242762
Peak memory usage during prediction: 377.48828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.897159099986311
Peak memory usage during training: 376.2109375 MB
Prediction time: 1.4876867999555543
Peak memory usage during prediction: 377.51171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8953524000244215
Peak memory usage during training: 376.31640625 MB
Prediction time: 1.5095219999784604
Peak memory usage during prediction: 377.625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8789228000096045
Peak memory usage during training: 376.4375 MB
Prediction time: 1.4931061000097543
Peak memory usage during prediction: 377.7265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9319937000400387
Peak memory usage during training: 376.609375 MB
Prediction time: 1.4953006000141613
Peak memory usage during prediction: 377.91015625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8881837999797426
Peak memory usage during training: 376.75 MB
Prediction time: 1.497608300007414
Peak memory usage during prediction: 378.05859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8723867000080645
Peak memory usage during training: 376.2109375 MB
Prediction time: 1.482538799988106
Peak memory usage during prediction: 377.46484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8936234999564476
Peak memory usage during training: 376.21875 MB
Prediction time: 1.9909246999886818
Peak memory usage during prediction: 377.51171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8832916999817826
Peak memory usage during training: 376.34375 MB
Prediction time: 1.4964868999668397
Peak memory usage during prediction: 377.63671875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.8793929999810643
Peak memory usage during training: 376.67578125 MB
Prediction time: 1.8895101000089198
Peak memory usage during prediction: 376.67578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8798323000082746
Peak memory usage during training: 376.8515625 MB
Prediction time: 1.8638175000087358
Peak memory usage during prediction: 376.8515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.4910950000048615
Peak memory usage during training: 376.8515625 MB
Prediction time: 1.8818277000100352
Peak memory usage during prediction: 376.8515625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.8790905000059865
Peak memory usage during training: 377.0859375 MB
Prediction time: 1.8535350000020117
Peak memory usage during prediction: 376.9609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8740191000397317
Peak memory usage during training: 377.23046875 MB
Prediction time: 1.8511866999906488
Peak memory usage during prediction: 377.23046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.5038585000438616
Peak memory usage during training: 377.23046875 MB
Prediction time: 1.8647193999495357
Peak memory usage during prediction: 377.23046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.8803502999944612
Peak memory usage during training: 377.36328125 MB
Prediction time: 1.8810539999976754
Peak memory usage during prediction: 377.36328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8830729000037536
Peak memory usage during training: 377.44140625 MB
Prediction time: 1.861528699984774
Peak memory usage during prediction: 377.44140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.4885045999544673
Peak memory usage during training: 377.4453125 MB
Prediction time: 1.8564235999947414
Peak memory usage during prediction: 377.4453125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 0.9834110999945551
Peak memory usage during training: 377.45703125 MB
Prediction time: 1.8778785999747925
Peak memory usage during prediction: 376.375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.0514631999540143
Peak memory usage during training: 376.43359375 MB
Prediction time: 1.920863300038036
Peak memory usage during prediction: 375.96484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.222496600006707
Peak memory usage during training: 376.03125 MB
Prediction time: 1.871160000038799
Peak memory usage during prediction: 376.03515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.2226780999917537
Peak memory usage during training: 376.171875 MB
Prediction time: 1.9003049999591894
Peak memory usage during prediction: 376.1171875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.4612819000030868
Peak memory usage during training: 376.28515625 MB
Prediction time: 1.8659212000202388
Peak memory usage during prediction: 376.2890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.4709310000180267
Peak memory usage during training: 376.40625 MB
Prediction time: 1.8820535999839194
Peak memory usage during prediction: 376.39453125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7878514000331052
Peak memory usage during training: 376.5390625 MB
Prediction time: 1.0268292000400834
Peak memory usage during prediction: 376.5390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.78106360003585
Peak memory usage during training: 376.44921875 MB
Prediction time: 1.579839699959848
Peak memory usage during prediction: 375.875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8587145999772474
Peak memory usage during training: 375.875 MB
Prediction time: 1.0319258000236005
Peak memory usage during prediction: 375.875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1553838000399992
Peak memory usage during training: 375.9296875 MB
Prediction time: 1.1880628000362776
Peak memory usage during prediction: 375.94140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.185186899965629
Peak memory usage during training: 375.9765625 MB
Prediction time: 1.172989399987273
Peak memory usage during prediction: 375.9765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1589110000059009
Peak memory usage during training: 375.98046875 MB
Prediction time: 1.138624700019136
Peak memory usage during prediction: 375.98046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5034049000241794
Peak memory usage during training: 376.18359375 MB
Prediction time: 1.3374134000041522
Peak memory usage during prediction: 376.18359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4910027000005357
Peak memory usage during training: 376.4140625 MB
Prediction time: 1.2110410999739543
Peak memory usage during prediction: 376.4140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.5147300999960862
Peak memory usage during training: 376.5703125 MB
Prediction time: 1.2724543000222184
Peak memory usage during prediction: 376.5703125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 2.090749999973923
Peak memory usage during training: 376.57421875 MB
Prediction time: 2.079751600045711
Peak memory usage during prediction: 376.50390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 2.0885903000016697
Peak memory usage during training: 376.51171875 MB
Prediction time: 1.9865002000005916
Peak memory usage during prediction: 376.51171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 2.075792099989485
Peak memory usage during training: 376.51171875 MB
Prediction time: 1.971514000033494
Peak memory usage during prediction: 376.51171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9159838000196032
Peak memory usage during training: 376.5546875 MB
Prediction time: 1.9003740000189282
Peak memory usage during prediction: 376.5546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.9313060999847949
Peak memory usage during training: 376.59765625 MB
Prediction time: 1.9325313000008464
Peak memory usage during prediction: 376.59765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.9116276999702677
Peak memory usage during training: 376.64453125 MB
Prediction time: 1.8772783000022173
Peak memory usage during prediction: 376.64453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.892213899991475
Peak memory usage during training: 376.41796875 MB
Prediction time: 1.8833385000471026
Peak memory usage during prediction: 376.41796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.8986575999879278
Peak memory usage during training: 376.50390625 MB
Prediction time: 1.8750768000027165
Peak memory usage during prediction: 376.50390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.909621500002686
Peak memory usage during training: 376.51171875 MB
Prediction time: 1.898328000039328
Peak memory usage during prediction: 376.51171875 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 1.1947157999966294
Peak memory usage during training: 375.5703125 MB
Prediction time: 1.9365181000321172
Peak memory usage during prediction: 370.06640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 1.2287057000212371
Peak memory usage during training: 370.57421875 MB
Prediction time: 1.8824303000001237
Peak memory usage during prediction: 370.58203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 1.2158692999510095
Peak memory usage during training: 370.90625 MB
Prediction time: 1.8800478999619372
Peak memory usage during prediction: 370.546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 0.7086274999892339
Peak memory usage during training: 373.3046875 MB
Prediction time: 2.0448113000020385
Peak memory usage during prediction: 372.69140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 0.7367818000493571
Peak memory usage during training: 373.703125 MB
Prediction time: 1.931289599975571
Peak memory usage during prediction: 373.046875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 0.7571591000305489
Peak memory usage during training: 373.41796875 MB
Prediction time: 1.8807887000148185
Peak memory usage during prediction: 373.41796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 0.7915472000022419
Peak memory usage during training: 375.29296875 MB
Prediction time: 1.9086121000000276
Peak memory usage during prediction: 375.3203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 0.8593013999634422
Peak memory usage during training: 376.12109375 MB
Prediction time: 2.0661143999896012
Peak memory usage during prediction: 375.88671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 0.8570405999780633
Peak memory usage during training: 376.296875 MB
Prediction time: 1.9555182000040077
Peak memory usage during prediction: 375.80078125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.5895339000271633
Peak memory usage during training: 377.26171875 MB
Prediction time: 1.945357899996452
Peak memory usage during prediction: 376.2578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.0411959000048228
Peak memory usage during training: 376.984375 MB
Prediction time: 1.9752805000171065
Peak memory usage during prediction: 376.70703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.5015520000015385
Peak memory usage during training: 377.2734375 MB
Prediction time: 1.9283236999763176
Peak memory usage during prediction: 376.35546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.6302092999685556
Peak memory usage during training: 377.41015625 MB
Prediction time: 1.962704700010363
Peak memory usage during prediction: 376.2265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.0482037999900058
Peak memory usage during training: 377.421875 MB
Prediction time: 1.9038804000010714
Peak memory usage during prediction: 376.84375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.9212385000428185
Peak memory usage during training: 377.03125 MB
Prediction time: 1.9497819000389427
Peak memory usage during prediction: 376.515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1.5390885999659076
Peak memory usage during training: 377.4921875 MB
Prediction time: 1.9034697999595664
Peak memory usage during prediction: 376.45703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 1.0020918000373058
Peak memory usage during training: 377.34375 MB
Prediction time: 1.9656201000325382
Peak memory usage during prediction: 376.36328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1.014562600001227
Peak memory usage during training: 377.44921875 MB
Prediction time: 1.8851277999929152
Peak memory usage during prediction: 376.375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 1.884004699997604
Peak memory usage during training: 376.28125 MB
Prediction time: 1.8409221000038087
Peak memory usage during prediction: 376.28125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 1.8822151000495069
Peak memory usage during training: 376.13671875 MB
Prediction time: 1.8377481999923475
Peak memory usage during prediction: 376.13671875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 1.8204076999682002
Peak memory usage during training: 376.15625 MB
Prediction time: 1.8073609999846667
Peak memory usage during prediction: 376.15625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8511623999802396
Peak memory usage during training: 376.3828125 MB
Prediction time: 1.7976293999818154
Peak memory usage during prediction: 376.265625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.4485361999832094
Peak memory usage during training: 376.3359375 MB
Prediction time: 1.85219370003324
Peak memory usage during prediction: 376.3359375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.872302400006447
Peak memory usage during training: 376.265625 MB
Prediction time: 1.8030589999980293
Peak memory usage during prediction: 376.265625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8207296999753453
Peak memory usage during training: 376.3515625 MB
Prediction time: 1.8128005000180565
Peak memory usage during prediction: 377.33203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8258692999952473
Peak memory usage during training: 376.12890625 MB
Prediction time: 1.8226952999830246
Peak memory usage during prediction: 377.4140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.9156605000025593
Peak memory usage during training: 376.15625 MB
Prediction time: 2.1770233000279404
Peak memory usage during prediction: 19.625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.086249799991492
Peak memory usage during training: 33.578125 MB
Prediction time: 1.957297999993898
Peak memory usage during prediction: 35.09765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9516447999631055
Peak memory usage during training: 34.91796875 MB
Prediction time: 2.0032820999622345
Peak memory usage during prediction: 36.2734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.9621330000227317
Peak memory usage during training: 35.62890625 MB
Prediction time: 1.887339900014922
Peak memory usage during prediction: 36.94921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.9383109000045806
Peak memory usage during training: 36.41015625 MB
Prediction time: 1.8969173000077717
Peak memory usage during prediction: 37.7421875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 2.0037199000362307
Peak memory usage during training: 37.22265625 MB
Prediction time: 1.927488200017251
Peak memory usage during prediction: 38.58203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 1.9738148999749683
Peak memory usage during training: 38.0390625 MB
Prediction time: 1.9378926000208594
Peak memory usage during prediction: 39.33203125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.0139014999731444
Peak memory usage during training: 40.3828125 MB
Prediction time: 1.9222390000359155
Peak memory usage during prediction: 40.4453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.9037926999735646
Peak memory usage during training: 41.33203125 MB
Prediction time: 1.9310894000227563
Peak memory usage during prediction: 41.34375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0368043999769725
Peak memory usage during training: 41.6328125 MB
Prediction time: 1.920320899982471
Peak memory usage during prediction: 41.63671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.933548900007736
Peak memory usage during training: 42.22265625 MB
Prediction time: 1.9316953999805264
Peak memory usage during prediction: 42.234375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 2.0407672000001185
Peak memory usage during training: 43.0390625 MB
Prediction time: 2.0163530000136234
Peak memory usage during prediction: 43.0625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.1366191999986768
Peak memory usage during training: 43.4140625 MB
Prediction time: 1.984840399993118
Peak memory usage during prediction: 43.42578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 1.9379979000077583
Peak memory usage during training: 44.14453125 MB
Prediction time: 1.8623266000067815
Peak memory usage during prediction: 44.14453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 1.9202239000005648
Peak memory usage during training: 44.80078125 MB
Prediction time: 1.8278871000511572
Peak memory usage during prediction: 44.80859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 1.0741990000242367
Peak memory usage during training: 45.109375 MB
Prediction time: 1.8275977000012062
Peak memory usage during prediction: 45.11328125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.0763595000025816
Peak memory usage during training: 49.6796875 MB
Prediction time: 2.050721400009934
Peak memory usage during prediction: 48.26953125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.0602049000444822
Peak memory usage during training: 48.57421875 MB
Prediction time: 1.8683620999800041
Peak memory usage during prediction: 48.4765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.3265616999706253
Peak memory usage during training: 48.90234375 MB
Prediction time: 1.8870799000142142
Peak memory usage during prediction: 48.53515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.3313851000275463
Peak memory usage during training: 48.73828125 MB
Prediction time: 1.8453147999825887
Peak memory usage during prediction: 48.64453125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 1.623573699966073
Peak memory usage during training: 48.9296875 MB
Prediction time: 1.866641599975992
Peak memory usage during prediction: 48.90234375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 1.6210299999802373
Peak memory usage during training: 49.0234375 MB
Prediction time: 1.8726091000135057
Peak memory usage during prediction: 48.890625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.801789799996186
Peak memory usage during training: 49.87890625 MB
Prediction time: 1.5395055999979377
Peak memory usage during prediction: 49.546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7950105000054464
Peak memory usage during training: 49.828125 MB
Prediction time: 1.6003766999929212
Peak memory usage during prediction: 49.7890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8189746999996714
Peak memory usage during training: 49.859375 MB
Prediction time: 1.0697035000193864
Peak memory usage during prediction: 49.87890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1289584999904037
Peak memory usage during training: 50.07421875 MB
Prediction time: 1.0992201999761164
Peak memory usage during prediction: 50.05859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1296567000099458
Peak memory usage during training: 50.19921875 MB
Prediction time: 1.0873156000161543
Peak memory usage during prediction: 50.0703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.1394542999914847
Peak memory usage during training: 50.1328125 MB
Prediction time: 1.0732057999703102
Peak memory usage during prediction: 50.1328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.431540599965956
Peak memory usage during training: 50.36328125 MB
Prediction time: 1.136895099945832
Peak memory usage during prediction: 50.3671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4576021999819204
Peak memory usage during training: 50.62109375 MB
Prediction time: 1.1801066000480205
Peak memory usage during prediction: 50.6328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.4627434999565594
Peak memory usage during training: 50.765625 MB
Prediction time: 1.1749078000430018
Peak memory usage during prediction: 50.76953125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.8847357999766245
Peak memory usage during training: 51.58203125 MB
Prediction time: 1.8890828000148758
Peak memory usage during prediction: 51.62890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.8788022000226192
Peak memory usage during training: 51.6875 MB
Prediction time: 1.8839687000145204
Peak memory usage during prediction: 51.69140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.9036418999894522
Peak memory usage during training: 55.734375 MB
Prediction time: 1.8818874000571668
Peak memory usage during prediction: 55.74609375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.916366100020241
Peak memory usage during training: 55.76171875 MB
Prediction time: 1.9362128000357188
Peak memory usage during prediction: 55.76171875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.9359993999823928
Peak memory usage during training: 55.8046875 MB
Prediction time: 1.9392759000184014
Peak memory usage during prediction: 56.35546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.9793619999545626
Peak memory usage during training: 56.26953125 MB
Prediction time: 1.8906690000439994
Peak memory usage during prediction: 56.26953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.9361149000469595
Peak memory usage during training: 56.2734375 MB
Prediction time: 1.9270678000175394
Peak memory usage during prediction: 56.3125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.930629099952057
Peak memory usage during training: 56.32421875 MB
Prediction time: 1.8945323000079952
Peak memory usage during prediction: 56.33203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.9554884000099264
Peak memory usage during training: 56.34375 MB
Prediction time: 1.9169728999841027
Peak memory usage during prediction: 56.34375 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 1.2167937000049278
Peak memory usage during training: 60.24609375 MB
Prediction time: 1.9898847000440583
Peak memory usage during prediction: 59.06640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 1.2406620999681763
Peak memory usage during training: 59.97265625 MB
Prediction time: 1.990947199985385
Peak memory usage during prediction: 59.33203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 1.3055347999907099
Peak memory usage during training: 59.82421875 MB
Prediction time: 2.016346800024621
Peak memory usage during prediction: 59.5703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 0.739418699988164
Peak memory usage during training: 61.9453125 MB
Prediction time: 1.9927430000388995
Peak memory usage during prediction: 61.8984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 0.7158120999811217
Peak memory usage during training: 62.4296875 MB
Prediction time: 1.9799596999655478
Peak memory usage during prediction: 62.14453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 0.7196421999833547
Peak memory usage during training: 62.515625 MB
Prediction time: 1.943034500000067
Peak memory usage during prediction: 62.19921875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 0.8066983000026084
Peak memory usage during training: 64.80078125 MB
Prediction time: 1.9824042999534868
Peak memory usage during prediction: 64.84375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 0.8521284000016749
Peak memory usage during training: 64.97265625 MB
Prediction time: 1.975470100005623
Peak memory usage during prediction: 64.83203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 0.88692690001335
Peak memory usage during training: 65.58984375 MB
Prediction time: 2.0825781000312418
Peak memory usage during prediction: 65.1328125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.1527663999586366
Peak memory usage during training: 66.6328125 MB
Prediction time: 2.0573980000335723
Peak memory usage during prediction: 65.94921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.1303156000212766
Peak memory usage during training: 66.9140625 MB
Prediction time: 2.2199282000074163
Peak memory usage during prediction: 66.44921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 0.1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.5941667999722995
Peak memory usage during training: 67.2265625 MB
Prediction time: 2.0211339999805205
Peak memory usage during prediction: 66.69140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.1466445999685675
Peak memory usage during training: 67.8515625 MB
Prediction time: 2.0695351000176743
Peak memory usage during prediction: 67.05078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.1664264000137337
Peak memory usage during training: 68.03125 MB
Prediction time: 2.075586499995552
Peak memory usage during prediction: 67.54296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 1, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 1.1200570000219159
Peak memory usage during training: 67.5859375 MB
Prediction time: 2.021963900013361
Peak memory usage during prediction: 66.828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1.1118542999611236
Peak memory usage during training: 67.68359375 MB
Prediction time: 2.0548181000049226
Peak memory usage during prediction: 67.00390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 1.1202826999942772
Peak memory usage during training: 68.20703125 MB
Prediction time: 3.0514383999980055
Peak memory usage during prediction: 67.71484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'estimator__C': 10, 'estimator__kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 2.8233138999785297
Peak memory usage during training: 67.99609375 MB
Prediction time: 2.692109899944626
Peak memory usage during prediction: 67.75390625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'estimator__alpha': 0.01} and vectorizer CountVectorizer
Training time: 2.35125710000284
Peak memory usage during training: 68.140625 MB
Prediction time: 2.121575600001961
Peak memory usage during prediction: 67.9296875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 0.1} and vectorizer CountVectorizer
Training time: 2.0290572999510914
Peak memory usage during training: 68.0234375 MB
Prediction time: 1.9013301000231877
Peak memory usage during prediction: 67.8984375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'estimator__alpha': 1.0} and vectorizer CountVectorizer
Training time: 1.9298983000335284
Peak memory usage during training: 68.0234375 MB
Prediction time: 1.9259135000174865
Peak memory usage during prediction: 67.76171875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'estimator__C': 0.1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.9643093000049703
Peak memory usage during training: 69.14453125 MB
Prediction time: 1.8761961000273004
Peak memory usage during prediction: 69.015625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 1, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.4823211999610066
Peak memory usage during training: 69.07421875 MB
Prediction time: 1.872065199946519
Peak memory usage during prediction: 68.9375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'estimator__C': 10, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.4809990999638103
Peak memory usage during training: 69.0078125 MB
Prediction time: 1.8622009999817237
Peak memory usage during prediction: 69.01171875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8714489999692887
Peak memory usage during training: 68.8515625 MB
Prediction time: 1.491590299992822
Peak memory usage during prediction: 70.81640625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8552960000233725
Peak memory usage during training: 69.6640625 MB
Prediction time: 1.975578100013081
Peak memory usage during prediction: 70.95703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8606225000112318
Peak memory usage during training: 69.7734375 MB
Prediction time: 1.49169759999495
Peak memory usage during prediction: 71.02734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8604464000090957
Peak memory usage during training: 69.87109375 MB
Prediction time: 1.9814041000208817
Peak memory usage during prediction: 71.125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.88116849999642
Peak memory usage during training: 69.97265625 MB
Prediction time: 1.470536799984984
Peak memory usage during prediction: 71.234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.8579708999604918
Peak memory usage during training: 70.06640625 MB
Prediction time: 1.47285489999922
Peak memory usage during prediction: 71.328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8565518999821506
Peak memory usage during training: 70.17578125 MB
Prediction time: 1.002628599992022
Peak memory usage during prediction: 70.68359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.8568259999738075
Peak memory usage during training: 69.54296875 MB
Prediction time: 1.498469699989073
Peak memory usage during prediction: 70.8671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 1.844058100017719
Peak memory usage during training: 69.75390625 MB
Prediction time: 1.4684938000282273
Peak memory usage during prediction: 70.94140625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.8539400000008754
Peak memory usage during training: 70.015625 MB
Prediction time: 1.8062748000374995
Peak memory usage during prediction: 70.04296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8576384000480175
Peak memory usage during training: 70.1640625 MB
Prediction time: 1.8308924000011757
Peak memory usage during prediction: 70.1796875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.4820392000256106
Peak memory usage during training: 70.25 MB
Prediction time: 1.8248057999880984
Peak memory usage during prediction: 70.25 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.841174399945885
Peak memory usage during training: 70.4296875 MB
Prediction time: 1.8129355999990366
Peak memory usage during prediction: 70.4296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8216917000245303
Peak memory usage during training: 70.5625 MB
Prediction time: 1.7972059000167064
Peak memory usage during prediction: 70.5625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.4553786999895237
Peak memory usage during training: 70.69140625 MB
Prediction time: 1.8307035999605432
Peak memory usage during prediction: 70.70703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 1.8428898000274785
Peak memory usage during training: 70.7734375 MB
Prediction time: 1.7988431999692693
Peak memory usage during prediction: 70.78125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 1.8417553000035696
Peak memory usage during training: 70.953125 MB
Prediction time: 1.8052050999831408
Peak memory usage during prediction: 70.953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 1.7514821999939159
Peak memory usage during training: 70.94921875 MB
Prediction time: 5.115517000027467
Peak memory usage during prediction: 70.9453125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.778007399989292
Peak memory usage during training: 71.09765625 MB
Prediction time: 4.024365100020077
Peak memory usage during prediction: 70.12890625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 100, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.255527900008019
Peak memory usage during training: 70.171875 MB
Prediction time: 2.314670499996282
Peak memory usage during prediction: 69.98828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.369640499993693
Peak memory usage during training: 69.99609375 MB
Prediction time: 1.9806781000224873
Peak memory usage during prediction: 69.796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 150, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.2799409999861382
Peak memory usage during training: 69.921875 MB
Prediction time: 1.8944760999875143
Peak memory usage during prediction: 69.8359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 1.5117745000170544
Peak memory usage during training: 69.9140625 MB
Prediction time: 1.8601697999984026
Peak memory usage during prediction: 69.75 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'estimator__n_estimators': 200, 'estimator__criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 1.4825458999839611
Peak memory usage during training: 69.98046875 MB
Prediction time: 1.8566797000239603
Peak memory usage during prediction: 69.9921875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7828026000061072
Peak memory usage during training: 70.0859375 MB
Prediction time: 1.4844235999626108
Peak memory usage during prediction: 69.42578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.8160025000106543
Peak memory usage during training: 69.46875 MB
Prediction time: 1.4769953999784775
Peak memory usage during prediction: 69.33203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 50, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 0.7899655999499373
Peak memory usage during training: 69.33203125 MB
Prediction time: 0.9991376000107266
Peak memory usage during prediction: 69.33203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.081627000006847
Peak memory usage during training: 69.3828125 MB
Prediction time: 1.058305400016252
Peak memory usage during prediction: 69.36328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.0306507000350393
Peak memory usage during training: 69.421875 MB
Prediction time: 2.5637726000277326
Peak memory usage during prediction: 69.33984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 100, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.123289399954956
Peak memory usage during training: 69.44140625 MB
Prediction time: 2.4001358000095934
Peak memory usage during prediction: 69.41015625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.702402400027495
Peak memory usage during training: 69.64453125 MB
Prediction time: 1.9956818000064231
Peak memory usage during prediction: 69.6171875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.19060090003768
Peak memory usage during training: 69.80859375 MB
Prediction time: 1.188628299976699
Peak memory usage during prediction: 69.45703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'estimator__n_estimators': 150, 'estimator__learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 1.6048742000130005
Peak memory usage during training: 69.703125 MB
Prediction time: 2.7195778000168502
Peak memory usage during prediction: 69.67578125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 4.089170899998862
Peak memory usage during training: 69.6953125 MB
Prediction time: 4.187683500000276
Peak memory usage during prediction: 69.6953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 3.513048599998001
Peak memory usage during training: 69.703125 MB
Prediction time: 2.8447860999731347
Peak memory usage during prediction: 69.703125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.0001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 2.1559635999728926
Peak memory usage during training: 69.7265625 MB
Prediction time: 3.089403699967079
Peak memory usage during prediction: 69.7265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 4.155971500033047
Peak memory usage during training: 69.73828125 MB
Prediction time: 4.861567999992985
Peak memory usage during prediction: 69.73828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 3.766481600003317
Peak memory usage during training: 69.7421875 MB
Prediction time: 2.9503339999937452
Peak memory usage during prediction: 69.66015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.001, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.8716372000053525
Peak memory usage during training: 69.70703125 MB
Prediction time: 3.0481787000317127
Peak memory usage during prediction: 69.7109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l2'} and vectorizer CountVectorizer
Training time: 3.673053400008939
Peak memory usage during training: 69.73046875 MB
Prediction time: 3.728601799986791
Peak memory usage during prediction: 69.73046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'l1'} and vectorizer CountVectorizer
Training time: 3.649472400022205
Peak memory usage during training: 69.7734375 MB
Prediction time: 3.536330499977339
Peak memory usage during prediction: 69.7890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'estimator__alpha': 0.01, 'estimator__penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 2.2893119999789633
Peak memory usage during training: 69.7890625 MB
Prediction time: 4.059686099993996
Peak memory usage during prediction: 69.7890625 MB
----------------------------------------------------------------------------------------------------

# Process results

In [12]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   seed                       396 non-null    object
 1   vectorizer                 396 non-null    object
 2   model                      396 non-null    object
 3   params                     396 non-null    object
 4   accuracy                   396 non-null    float64
 5   hamming_loss               396 non-null    float64
 6   training_time              396 non-null    float64
 7   prediction_time            396 non-null    float64
 8   peak_memory_train          396 non-null    float64
 9   peak_memory_prediction     396 non-null    float64
 10  precision_class_bug        396 non-null    float64
 11  recall_class_bug           396 non-null    float64
 12  f1_class_bug               396 non-null    float64
 13  precision_class_docs       396 non-null    float64
 14  recall_class_docs          396 non-null    float64
 15  f1_class_docs              396 non-null    float64
 16  precision_class_feature    396 non-null    float64
 17  recall_class_feature       396 non-null    float64
 18  f1_class_feature           396 non-null    float64
 19  precision_class_question   396 non-null    float64
 20  recall_class_question      396 non-null    float64
 21  f1_class_question          396 non-null    float64
 22  precision_class_won't fix  396 non-null    float64
 23  recall_class_won't fix     396 non-null    float64
 24  f1_class_won't fix         396 non-null    float64
dtypes: float64(21), object(4)
memory usage: 77.5+ KB

In [13]:
results.head()

,seed,vectorizer,model,params,accuracy,hamming_loss,training_time,prediction_time,peak_memory_train,peak_memory_prediction,...,f1_class_docs,precision_class_feature,recall_class_feature,f1_class_feature,precision_class_question,recall_class_question,f1_class_question,precision_class_won't fix,recall_class_won't fix,f1_class_won't fix
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.481283,0.170053,1.348779,1.998595,369.738281,369.296875,...,0.411765,0.0,0.0,0.0,0.706250,0.933884,0.804270,0.333333,0.04878,0.085106
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.438503,0.181818,1.252865,1.889216,370.187500,369.734375,...,0.312500,0.0,0.0,0.0,0.691824,0.909091,0.785714,0.000000,0.00000,0.000000
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.438503,0.181818,1.205935,1.888441,370.250000,369.828125,...,0.312500,0.0,0.0,0.0,0.691824,0.909091,0.785714,0.000000,0.00000,0.000000
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.481283,0.171123,1.366500,1.891372,372.863281,372.363281,...,0.411765,0.0,0.0,0.0,0.710692,0.933884,0.807143,0.166667,0.02439,0.042553
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.454545,0.175401,0.718584,1.856046,373.085938,372.839844,...,0.411765,0.0,0.0,0.0,0.707006,0.917355,0.798561,0.000000,0.00000,0.000000

In [14]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,hamming_loss,training_time,prediction_time,peak_memory_train,peak_memory_prediction,...,precision_class_feature,recall_class_feature,f1_class_feature,precision_class_question,recall_class_question,f1_class_question,precision_class_won't fix,recall_class_won't fix,f1_class_won't fix,f1_avg
0,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.443850,0.180749,1.101619,1.112452,273.666667,273.665365,...,0.000000,0.0,0.000000,0.674157,0.991736,0.802676,0.250000,0.024390,0.044444,0.183710
1,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.429590,0.186096,1.426724,1.608228,273.781250,273.743490,...,0.000000,0.0,0.000000,0.710918,0.914601,0.799997,0.379545,0.089431,0.144386,0.282404
2,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 100, 'estimator__l...",3.333333,0.351159,0.212121,1.454887,1.570159,273.790365,273.779948,...,0.158730,0.1,0.122549,0.720898,0.818182,0.766450,0.238456,0.130081,0.168212,0.318776
3,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 150, 'estimator__l...",3.333333,0.459893,0.175401,1.883227,1.490216,273.988281,273.979167,...,0.000000,0.0,0.000000,0.674157,0.991736,0.802676,0.400000,0.048780,0.086957,0.240426
4,AdaBoost,CountVectorizer,"{'estimator__n_estimators': 150, 'estimator__l...",3.333333,0.397504,0.193226,1.697489,1.196845,274.192708,274.078125,...,0.000000,0.0,0.000000,0.715219,0.906336,0.799513,0.257576,0.081301,0.122981,0.277035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'estimator__C': 1, 'estimator__kernel': 'rbf'}",3.333333,0.454545,0.173262,1.023727,1.880943,377.108073,376.580729,...,0.000000,0.0,0.000000,0.698225,0.975207,0.813793,0.000000,0.000000,0.000000,0.177044
128,SVC,TfidfVectorizer,"{'estimator__C': 1, 'estimator__kernel': 'sigm...",3.333333,0.443850,0.170053,1.454132,1.879577,376.951823,376.325521,...,0.000000,0.0,0.000000,0.725490,0.917355,0.810219,0.250000,0.024390,0.044444,0.279756
129,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'lin...",3.333333,0.358289,0.216043,1.505660,1.870638,377.289062,376.445312,...,0.200000,0.1,0.133333,0.742188,0.785124,0.763052,0.238095,0.243902,0.240964,0.368608
130,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'rbf'}",3.333333,0.427807,0.188235,1.168260,1.907671,377.278646,376.653646,...,0.000000,0.0,0.000000,0.724832,0.892562,0.800000,0.090909,0.024390,0.038462,0.244084
131,SVC,TfidfVectorizer,"{'estimator__C': 10, 'estimator__kernel': 'sig...",3.333333,0.278075,0.250267,1.322516,1.879903,377.430990,376.550781,...,0.142857,0.1,0.117647,0.715596,0.644628,0.678261,0.229167,0.268293,0.247191,0.343165

In [15]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train[classes])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test[classes], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test[classes], y_pred, average=None, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: DecisionTree
Best model params: {'criterion': 'entropy', 'max_features': None}
Best vectorizer: TfidfVectorizer
Best accuracy: 0.315

Class bug
Precision: 0.36
Recall: 0.20930232558139536
F1: 0.2647058823529412
Support: 43

Class docs
Precision: 0.45454545454545453
Recall: 0.38461538461538464
F1: 0.4166666666666667
Support: 26

Class feature
Precision: 0.16666666666666666
Recall: 0.25
F1: 0.2
Support: 8

Class question
Precision: 0.6884057971014492
Recall: 0.7480314960629921
F1: 0.7169811320754716
Support: 127

Class won't fix
Precision: 0.21428571428571427
Recall: 0.27906976744186046
F1: 0.24242424242424243
Support: 43

In [16]:
with open('models/best_model_sklearn_multilabel2.pkl', 'wb') as f:
    pickle.dump(pipeline, f)